### ISSUE TITLE
Create several (3 or more) dashboard wireframe examples

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1]
Create multiple wireframe concepts to explore the design space for an API consumer dashboard interface.

User Stories
----------------
As a project manager,
I want to get an idea of the possibilities for an API consumer dashboard
so that I can have confidence we are considering among many possible solutions

As a software developer,
I want to see multiple dashboard wireframes
so that I can be part of the design process

As an end user
I want to see multiple dashboard layout and design possibilities
so I know that the design process explored multiple possible solutions

As a community member
I want to see the design process documents
so that I can participate in design decisions

As a designer
I want to produce multiple design possibilities
so that I explore the design space and can realize the multiple possibilities for this design

**Comment by brylie** [comment]
Related [API Umbrella issue](https://github.com/NREL/api-umbrella/issues/84).

**Comment by brylie** [comment]
Also, there is an [API Consumer Dashboard planning document](https://github.com/NREL/api-umbrella/wiki/API-Consumer-Dashboard). @kyyberi will you please help describe the API Consumer dashboard?

**Comment by imnzv** [comment]
Didn't got the last story. What are these multiple design possibilities?

**Comment by brylie** [comment]
In the design space, there are many possible decisions. The goal is to explore those possibilities and compare them. This contrasts with the tendency to pick the first design that comes to mind.

On 4 March 2015 16:20:29 EET, elijah <notifications@github.com> wrote:
>Didn't got the last story. What are these multiple design
>possibilities?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apinf/api-umbrella-dashboard/issues/1#issuecomment-77165225

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brylie** [comment]
@nizyev thanks for posting the wireframes for this task. A few notes:

* The red text detracts from the quality of the wireframes, and seems like an afterthought. I.e. it kind of looks like crayon, and is difficult to read.
* The diagrams lack annotations. Please provide annotation text to accompany each diagram, explaining what the red numbers indicate. Think of a person finding this image without any accompanying discussion thread. How would they know what the numbers represent?
* Consider how this design document would appear on a monochrome print-out (e.g. greyscale). What areas have high contrast? What areas have lower contrast? What aspects stand out? What are you trying to emphasize?

**Comment by brylie** [comment]
Also, please continue the design process by producing two more distinct sets of wireframes. This ensures that we are taking a wide view of design possibilities.

* How would the dashboard function without modal dialogues, drop-downs or fly-out menus?
* How would the UX be different without drag-and-drop?
* What are other possible arrangements of page elements?

Consider also how the design responds to smaller screen constraints.
