### ISSUE TITLE
Determine whether/how to create a unified index on Elasticsearch

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1]
By default, API Umbrella creates an Elasticsearch index every month:

![screenshot_20170524_141518](https://cloud.githubusercontent.com/assets/17307/26400824/930598ba-408b-11e7-9905-567c3b7f8baa.png)

# Anticipated difficulty
Having multiple indexes for analytics might make queries difficult, as described in the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_basic_concepts.html#_index):

> An index is identified by a name (that must be all lowercase) and this name is used to refer to the index when performing indexing, search, update, and delete operations against the documents in it.

# Goal
Determine whether/how to create a unified index for custom analytics queries/aggregations.

# Resources
- [Upstream issue with API Umbrella](https://github.com/NREL/api-umbrella/issues/369)
- Elasticsearch 2.0 Basic Concepts: [Index](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_basic_concepts.html#_index)

**Comment by bajiat** [comment]
@marla-singer @brylie Can this issue be closed?

**Comment by brylie** [comment]
Yep.
