### ISSUE TITLE
Show average response time per API

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1002]
Show the average response time per APIas milliseconds.

- Average response time per a selected API (related to #999)

# User story
> As an Apinf owner
I want to see average response time of API(s) 
so that I can quickly glance how my API(s) is/are performing

# Design
_Add link to wireframe here_
![apinf analytics charts2](https://cloud.githubusercontent.com/assets/17976243/16449706/a859cd68-3e01-11e6-8db0-1a76477cc17f.png)

# Definition of done
* [ ] When viewing a single API (owned by the user), user can see the average response time for that particular API
* [ ] The average response rate reacts to user actions (e.g. selecting a timeframe)
* [ ] Optionally, API owner can view average response time for all owned APIs (if such a view / option exists)
* [ ] Optionally, Apinf administrator can see average response time for all APIs

**Comment by Nazarah** [comment]
Suggesting a new layout/table for giving API information.  There should be option to select/ multiple APIs at a time, and that way, we can see average time for the selected ones in a new column on the table/place on the layout.

**Comment by Nazarah** [comment]
Wireframe added for average response tiem
