### ISSUE TITLE
Selecting analytics timeframe

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1009]
At the moment, Apinf users can select from hard coded months and years and interact with the overview chart, which contains the timeframe of a few days.
Apinf users viewing the dashboard page should be able to quickly see how they can select or determine the timeframe that is shown in analytics.  The UI can offer two different options to determine the timeframe, but it should contain the same options. 
The users should also be able to determine the granularity of the timeframe: year, month, week, day, hour. (Are minutes also needed?)

# User story
> As an Apinf user 
I want to easily select the timeframe for which I view analytics

# Design

* A single date picker when the chart can be rendered w.r.t. day, week, month, year using the view finder

![apinfanalytictimeframedatepickersingle](https://cloud.githubusercontent.com/assets/17976243/16521297/9a94b168-3f9e-11e6-9369-ae798a62df82.png)

* When There is option to view the chart in day, week, month or year basis by checking buttons

![apinfanalytictimeframedatepicker](https://cloud.githubusercontent.com/assets/17976243/16521324/c7dd80d2-3f9e-11e6-8e28-490eb091629e.png)

![apinfanalytictimeframedatepickermonth](https://cloud.githubusercontent.com/assets/17976243/16521331/d2731408-3f9e-11e6-968d-82f07b47670c.png)

![apinfanalytictimeframedatepickeryear](https://cloud.githubusercontent.com/assets/17976243/16521341/dbcb010a-3f9e-11e6-879b-e3ab8a32f7d5.png)

# Definition of done
* [ ] User can immediately see what is the method for determining the timeframe
* [ ] User can select the granularity of the time shown:  year, month, week, day, hour
* [ ] Optionally, either starting point or end point can be left blank: data from this point or data after this point
* [ ] Graphs are updated based on user selection
* [ ] User can reset the time selection with one action (clear the selection to return to default)

**Comment by Nazarah** [comment]
There should be both options for giving the date range as inputs (date selector) and focusing option to select particular date on charts.

**Comment by Nazarah** [comment]
Also should we consider a particular date? or date range? or both?

**Comment by Nazarah** [comment]
Good option for implementing this is:
https://dc-js.github.io/dc.js/

**Comment by Nazarah** [comment]
what about timing formats? Are we supporting this?
dd/mm/yyyy
mm/dd/yyyy
yyyy/mm/dd
24 Hr
12 Hr

**Comment by jykae** [comment]
Need findings and decision from #1066

**Comment by jykae** [comment]
@Nazarah let me know when you have wireframes ready for review.

**Comment by Nazarah** [comment]
@jykae: Added the wireframes

**Comment by jykae** [comment]
Wireframes reviewed, and merged: https://github.com/apinf/docs/tree/master/docs/Wireframes/Dashboard

**Comment by brylie** [comment]
@frenchbread would you like to work on this task? @nnn will be working with you on similar tasks.

**Comment by frenchbread** [comment]
Self-assigned.
