### ISSUE TITLE
Flag inappropriate or defunct APIs

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1013]
# User story
> As an Apinf administrator I want to flag inapproprite or defunct APIs so that it becomes possible to exclude or filter out these APIs

# Definition of done

## Collection
* [x] Collection exists for flags
  * [x] Contains flag reason: inappropriate, defunct
  * [x] Contains a text field for description or comment
  * [x] Contains reference field for user id (which admin flagged the API)
  * [x] foreign key to the API backend getting flagged
* [ ] if the api is unflagged by admin, the information gets updated to db

## UI component
* [x] UI component for flagging (opens dialog)
* [x] Modal dialog for adding the flag
* [ ] Modal dialog contains an option to unflag

## User permissions
 * [x] Only administrator can flag
* [x] Only administrator can view the UI component and the dialog
* [x] Only administrator can insert anything to the collection
* [ ] Only administrator can unflag

## Outcome
* [ ] Flagged API is not visible in catalog **(Update: decided to keep this open until the new version of api catalogue list is implemented)**

**Comment by brylie** [comment]
@frenchbread are you interested in taking this task?

**Comment by frenchbread** [comment]
Self-assigned

**Comment by philippeluickx** [comment]
Are there related tickets to this? There are a couple of interesting use cases:
- Optional description field (why does user flag this API)
- alert (email) the API owner when someone flags
- Use flags in scoring when ranking APIs
- Display flagged APIs in the dashboard for API owners

Also some concerns: let's say my server went down for 1h and some people flagged the API. Now I relaunched the server and made sure this won't happen anymore. But the flags still have an impact? It's a bit unforgiving...

**Comment by brylie** [comment]
@bajiat lets work on the definition of done for this task with @frenchbread

**Comment by bajiat** [comment]
@philippeluickx Good questions. We have another issue for crowdsourcing where these questions will come even more critical. I'll add the issue link later. This ticket is for the administrative usage only.

**Comment by philippeluickx** [comment]
Ok, thanks for the clarification. I got confused because the flagging showed up in some of the mockups.

**Comment by bajiat** [comment]
Your comments will be good enhancements for both this task and the crowdsourced flagging,

**Comment by bajiat** [comment]
@frenchbread Please check the definition of done. Is your estimate still valid?

**Comment by frenchbread** [comment]
@bajiat Yes.

**Comment by bajiat** [comment]
@philippeluickx Here is the link to the issue, where flagging could be done by community: #1014
