### ISSUE TITLE
Make APINF Setup fields Mandatory

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1025]
Referring from PR #925

Currently the fields to set up APINF are not mandatory by default.
So if Users leave them empty or give incorrect data, they still gets saved.
However in the analytics because of the empty/incorrect data, proper visualization does not appear. This may confuse users.

**Comment by Nazarah** [comment]
Requirements:
Add "*" sign beside field names to show them as mandatory.
On clicking save with leaving empty fields, update should not be possible.
Use CSS alert text under empty fields instructing users to provide correct data.

**Comment by bajiat** [comment]
This is not about API configuration but about Apinf setup. We need to first understand what are minimum required fields to make it work

**Comment by Nazarah** [comment]
Fixing up the title.
@frenchbread: would you like to look for the minimum details for setting up APINF?

**Comment by bajiat** [comment]
@nazarah I have added this to planning so that it would be included in the next sprint. So no need to assign it today. :)

**Comment by frenchbread** [comment]
@Nazarah This calls for separate PR and a list of minimum fields that are required for APINF to work correctly. Let's take this issue to the next sprint.

**Comment by brylie** [comment]
@frenchbread will you take this task?

**Comment by bajiat** [comment]
@nnn What's the status of the task?
