### ISSUE TITLE
Selection of API categories

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1026]
API needs to be filtered or sorted according to their functionality and purpose.
Need to have a set of categories selected.

**Comment by Nazarah** [comment]
@philippeluickx : would you like to co-pilot?

**Comment by philippeluickx** [comment]
Sure thing, next Tuesday?

**Comment by Nazarah** [comment]
:+1:

**Comment by kyyberi** [comment]
Categories do not work when amount of APIs is high. That can be seen for example in programmableweb.com. Exploring other options might be good.

**Comment by kyyberi** [comment]
Using multiple tags instead of distinct categories is brilliant. It serves the complex reality of APIs, where very few APIs belong in one category only. Putting APIs in multiple categories causes other UX issues.

**Comment by kyyberi** [comment]
Better yet, explore option to utilize AI to build maps (relations etc) of APIs. Watson understands English: input API meta data -> utilize results.

**Comment by philippeluickx** [comment]
+1 on Jarko's ideas. Generally pre-defined categories lead to bad design and experience. Free tags would be best, but I would add an autocomplete (at least) when adding tags. Maybe also have a suggest feature or display the most used ones.

**Comment by Nazarah** [comment]
I am listing API categories on  market mashup, IBM and programmable web.
Market mashup's sounds a reasonable list, although @kyyberi 's logic outweights this. 
Categories can be populated based on a given list as well as customized ones.
However I am also considering API filtering based on the protocols they use and lifestyle

**Comment by Nazarah** [comment]
Added the document listing  API protocols.
https://github.com/apinf/docs/blob/master/docs/research/API%20Protocols
@philippeluickx  , @kyyberi want to have a look and contribute? :)

**Comment by philippeluickx** [comment]
Didn't even know all of them... Good docs!
