### ISSUE TITLE
Install and configure Prometheus for internal service monitoring

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1028]
Install Prometheus monitoring service to a VM.
Configure the service to monitor apinf.io, api umbrella and other internal services as agreed with @ccsr. Make sure that email alerts are created when services are down.

**Comment by shaliko** [comment]
@bajiat, @ccsr Am I right understood that we need these metrics:

1) Shutdown with email alert.
2) CPU, disk I/O, network statistics.

For second requirement I plan use https://github.com/prometheus/node_exporter

**Comment by shaliko** [comment]
@bajiat @brylie I configured Prometheus + Graphana for collect server metrics, now Prometheus monitor sever where it installed. The next step is install node_exporters on other internal servers.

![grafana_-_prometheus_node_metrics_and_slack](https://cloud.githubusercontent.com/assets/36139/15921789/6ecd2692-2e2c-11e6-8d52-9fad96a0c6fb.jpg)

We have 2 options for install node_exporter:

1) From [source code](https://github.com/prometheus/node_exporter#building-and-running).
2) With [Docker image](https://github.com/prometheus/node_exporter#using-docker) based on [BusyBox](https://hub.docker.com/_/busybox/).

Installation with Docker looks simpler but require Docker on each monitoring server.

What way will be preferable for that task?

**Comment by brylie** [comment]
Is there an option for passive monitoring? E.g. ping check?

**Comment by shaliko** [comment]
I will try configure only alert about downtime (not tried). By default Prometheus want url where it can fetch metrics.

**Comment by brylie** [comment]
See related user story:

> As an Apinf user I want to see the percentage of failures/uptime (timeout, bad gateway, internal server error) for a given API so that I can determine the reliability of a given API backend

**Comment by brylie** [comment]
OK, here is the related user story:

> As an Apinf administrator I want to be notified if any of the Apinf platform services are down

**Comment by shaliko** [comment]
@brylie Hm, We splitted original story https://github.com/apinf/docs/pull/7#issuecomment-223569828

By this story we need observer internal services not API backends.

**Comment by brylie** [comment]
OK, cool. Do you have the access privileges you need on our Apinf services?

**Comment by brylie** [comment]
Ping @ccsr

**Comment by shaliko** [comment]
@brylie I have access to servers.

Before I will install node_exporter on these servers let's double check:

1) What metrics we need?

a) Shutdown with email alert.
b) CPU, disk I/O, network statistics.

I think both?

Is it OK install Docker for run "node_exporter" or will be better installation from source code?

**Comment by brylie** [comment]
Hm, it might depend on the server setup. E.g. apinf.io has an Apinf Docker deployment. Would the two services conflict in any way? Also, there is a Meteor package for Prometheus stats, that we might be able to include at some point.

**Comment by shaliko** [comment]
@brylie Will not have conflict, "node_export" can be runed on any port, usually on :9100.

Good point about "Meteor package for Prometheus".

**Comment by brylie** [comment]
OK, cool. @ccsr is double checking our server list, and will make sure you have the credentials you need.

**Comment by jykae** [comment]
@bajiat I tested and merged @shaliko 's work https://github.com/apinf/monitoring/pull/1

I suppose this could be closed or is there still something to do?

**Comment by shaliko** [comment]
@jykae I not started monitoring agent on 2 servers, because had issue with previous docker installation. Waiter @brylie for consultation (scare change old running soft), today will manage last 2 servers and then we can close that task.

**Comment by brylie** [comment]
@shaliko should we close this task?

**Comment by nnn** [comment]
@shaliko, should we close this task?

**Comment by shaliko** [comment]
@nnn Yes
