### ISSUE TITLE
Documentation viewer testing

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1033]
Perform explorative manual testing for the new Documentation Viewer, which is now included in the tabbed interface for API backend, on nightly.apinf.io.

#Definition of done
* [x] Get a hold of Swagger document for API backend.
 * [x] Log in to nightly.apinf.io with an account that has added an API backend. Upload a Swagger document for an API you own.
* [x] Check that it is not possible to add a Swagger document for an API you don't own.
* [x] Add a link to external API documentation.
* [x] Delete the Swagger document you have added and reload it.
* [x] Log into nightly.apinf.io as a regular user (owns no APIs)
  * [x] Check that you can see the document you have added in previous steps
  * [x] Check that Documentation tab does not show if user has not added either a link or a Swagger document.
* [x]  Report any issues labeling them appropriately (e.g. bug or enhancement)

**Comment by bajiat** [comment]
@sarala Documentation viewer is ready for testing and is available in nightly.apinf.io (Automatic nightly deployment is working again)

**Comment by saralavanip** [comment]
@bajiat , Thanks for the info.

**Comment by saralavanip** [comment]
Adding API backend as  new user fails. Same result with existing users as well. 

![add_api_fails](https://cloud.githubusercontent.com/assets/13309358/15895629/ed109946-2d94-11e6-99f8-65351d9e9846.png)

**Comment by saralavanip** [comment]
Reported issues
https://github.com/apinf/api-umbrella-dashboard/issues/1101  
https://github.com/apinf/api-umbrella-dashboard/issues/1102
