### ISSUE TITLE
Refactor dashboard code

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#1040]
> As an Apinf developer I want to easily reuse functions that are used there.

- Refactor code to be more easy to read and maintain.
- If the logic architecture allows it, try to make code more object oriented

Since this is not creating any new functionality, but rather improving existing one, do not spend more than 1 hour on this task.

# Definition of done
- [ ] Dashboard contains no functions with subfunctions
- [ ] If possible, dashboard functions are objects with methods
- [ ] Most or all of ElasticSearch variables are parametrized
- [x] Code is easy to read
- [x] Code contains comments

**Comment by brylie** [comment]
@frenchbread is this a work in progress or should we wait for the Dashboard sprint?

**Comment by frenchbread** [comment]
@brylie It's not in progress, so let's take this issue to the dashboard sprint.

**Comment by frenchbread** [comment]
Testing out refactored version of updated dashboard in [this](https://github.com/frenchbread/apinf-dashboard-example) repo.

Still having two issues: 
- Data fetch take too much time (even though it has been optimized)
- "Average response time" chart does not work

**Comment by brylie** [comment]
@frenchbread tried an approach where we stored analytics in the MongoDB instance, but the performance was slow when serving > 10,000 records:

![apinfdashboardbenchmark](https://cloud.githubusercontent.com/assets/17307/16482053/def4842a-3eb6-11e6-851a-12973d881895.jpg)

We decided to revert to using the Meteor server to relay the Elastic analytics data. This isn't 'perfect', but it seems to improve the situation we are trying to solve.
