### ISSUE TITLE
Create user roles

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#105]
Create user roles for API user, API administrator and system administrator and document their privileges

Definition of done
* [x] Create roles corresponding to our Personas' user roles
* [x] Create document describing roles and expected privileges
* [x] Define user roles in code, possibly on Startup
* [x] Decide how system administrators will manage user roles
* [x] Add roles collection and field to user administration interface

**Comment by brylie** [comment]
@JuusoV, check out the following learning resources demonstrating the alanning:roles package:

* [Adrian Lanning: Authorization with Meteor-Roles -- Devshop 5 Tech Talk ](https://www.youtube.com/watch?v=ooBEJIirNEo)
*

**Comment by brylie** [comment]
The alanning:roles API documentation indicates there is a `[createRole](http://alanning.github.io/meteor-roles/classes/Roles.html#method_createRole)` method. We may be able to create the roles on `Meteor.startup()` using `Roles.createRole('role-name')` one or more times.

**Comment by brylie** [comment]
It could also be possible to verify the roles before creating them, to avoid creating duplicates, by using the [Roles.getAllRoles()](http://alanning.github.io/meteor-roles/classes/Roles.html#method_getAllRoles) method and checking each returned role for a duplicate.

**Comment by brylie** [comment]
Also, refer to the [Best Practices section of the roles demonstration video](https://www.youtube.com/watch?feature=player_detailpage&v=ooBEJIirNEo#t=815), where Adrian Lanning explains conventions for creating roles. This may influence how we implement roles in our project.

**Comment by JuusoV** [comment]
Roles.createRole('role-name') works under Meteor.startup(). The created roles shown in the console with Roles.getAllRoles().find().fetch()

**Comment by brylie** [comment]
@JuusoV please review the similar pattern for [avoiding duplicates in the ApiUmbrellaAdmins collection](https://github.com/apinf/api-umbrella-dashboard/blob/feature/Synchronize-Admin-User/server/methods/apiUmbrellaAdmins.js#L9-L14). You will have to take the general pattern and modify it to work with your task.

**Comment by JuusoV** [comment]
I got the roles working but I think we should not impelement them in the startup because the roles are only created once. Do you agree?

**Comment by brylie** [comment]
Where should we implement them?

On 18 June 2015 17:02:00 EEST, Juuso Vallius <notifications@github.com> wrote:
>I got the roles working but I think we should not impelement them in
>the startup because the roles are only created once. Do you agree?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apinf/api-umbrella-dashboard/issues/105#issuecomment-113166154

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brylie** [comment]
@JuusoV consider the [Add Roles Collection to Admin Dashboard](https://github.com/yogiben/meteor-admin/issues/210). This is a simple and flexible recipe to add a 'Roles' button to the admin dashboard, where we can easily manage the Meteor.roles collection.

**Comment by JuusoV** [comment]
Thanks for the help and support @brylie. 
Task is now done and PR is created.
Estimate: 0
