### ISSUE TITLE
Add Travis CI build status to README

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1050]
As our project matures, and we introduce more automated tests, our Travic CI service will be a useful indicator of project stability. Lets add the Travis CI build status icon to our README, so that community members can see whether the latest build is passing.

**Comment by bajiat** [comment]
While we are updating the Readme, we could also remove the instruction to register with a particular user name (test@test.test) under the heading Nightly build

**Comment by bajiat** [comment]
@brylie I quess you have already added the build status. Should we close the issue?
