### ISSUE TITLE
Setup wizard form does not submit and save settings

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#1053]
When starting Apinf locally reset, setup wizard pops-up. When filling up all the fields and submitting the form nothing happens and it's not possible to proceed to the dashboard page.

## Steps to reproduce 

- Run `meteor reset` in terminal (in project root)
- Run app
- Navigate to home page in the browser & signup
- After signup setup wizard appears
- Fill all the form fields
- Click submit - > nothing happens

### Observed
- With all the fields provided correctly, setup wizard form does not submit. Also no error in both server/client consoles provided.

### Expected
- Form submit, and provided setting saved

### Browser
- Google Chrome Version 53.0.2760.0 canary (64-bit)
- Safari Version 9.1.1 (11601.6.17)

**Comment by elnzv** [comment]
Getting same using latest develop.
