### ISSUE TITLE
Select charting library and research available data types

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1066]
The main user for the dashboard is an API owner, who needs to be able to see analytics for the API(s) he/she owns.
Take the learnings related to visualizing analytics from service project follow-up dashboard and apply them to visualising analytics for API owner on the Apinf dashboard page.  

# Definition of done
- [x] Determine which charting library to use: NVD3 or DC
- [x] Research the available data structure and types for API backend data / queries from ElasticSearch

**Comment by Nazarah** [comment]
Need to know the purpose of the charts before start wireframing.
Also, should there be only these two charts? or additional ones are going to be added?

**Comment by bajiat** [comment]
- Number of calls (already in dashboard)
Charts and/or filters
- heat map or country map (see http://dc-js.github.io/dc.js/vc/)
- HTTP status code
- API key or IP address
- URL that is being accessed
- time range
- response time

Consider also giving ready made scenarios inside a menu for API managers:
- show all APIs that give 404
- show backends with slowest response time

**Comment by bajiat** [comment]
https://github.com/NREL/api-umbrella/issues/252

**Comment by frenchbread** [comment]
https://github.com/NREL/api-umbrella/issues/140

**Comment by frenchbread** [comment]
[Highcharts](http://www.highcharts.com/) library - worth checking out.

**Comment by frenchbread** [comment]
DC.js remains as a charting library for a dashboard.

**Comment by frenchbread** [comment]
#### List of fields that are available on each log entry inside ElasticSearch.
```js
const fieldsList = [
  'api_key',
  'backend_response_time',
  'internal_gatekeeper_time',
  'internal_response_time',
  'proxy_overhead',
  'request_accept',
  'request_accept_encoding',
  'request_at',
  'request_basic_auth_username',
  'request_connection',
  'request_content_type',
  'request_hierarchy',
  'request_host',
  'request_ip',
  'request_method',
  'request_origin',
  'request_path',
  'request_query',
  'request_referer',
  'request_scheme',
  'request_size',
  'request_url',
  'request_user_agent',
  'request_user_agent_family',
  'request_user_agent_type',
  'response_age',
  'response_content_type',
  'response_server',
  'response_size',
  'response_status',
  'response_time',
  'user_email',
  'user_id',
  'user_registration_source'
];
```

Link to [Gist](https://gist.github.com/frenchbread/052d043918987ace77cbe388f7df4ec7).
