### ISSUE TITLE
Create catalog table view

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1089]
# User story
> As an Apinf user I want to select between catalog views so that I can view either card catalog and table catalog.

# Design
Add wireframe here

# Definition of done
* [ ] Table view that is pre-populated with data from smart container exists
* [ ] Table row acts as a hotspot for the individual API backend detailed view
* [ ] Table row contains bookmarking widget and rating widget

**Comment by Nazarah** [comment]
@bajiat Should we show information about total no. of bookmarks, average star ratings, no. of raters, API condition and pricing in table view?

**Comment by Nazarah** [comment]
Suggested columns: Name, Bookmark, rating, column to show API info (total num of bookmarks, ratings, pricing, up time
back end name can be embedded as a tool tip which can appear on hovering over API name.

**Comment by jykae** [comment]
had session with @Nazarah about table view wireframes, let me know when you have wireframes for 2 options ready, I start with the initial templating as we now have idea what to show in the table.

**Comment by jykae** [comment]
Looks currently like this:

<img width="1018" alt="nayttokuva 2016-06-13 kello 10 52 33" src="https://cloud.githubusercontent.com/assets/293452/16000422/0d00edc8-3155-11e6-9efe-37bc3feb415e.png">
