### ISSUE TITLE
Required fields for API Umbrella user create

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#109]
So far, I was able to create an API Umbrella User on Apinf sign up. At the same time apiUmbrellaUser's ID is linked to apinf user's object as well as API Key field is now visible with real api key on profile settings page. Here is the branch I am working on - link.

There are two issues that do not affect functionality but still can be solved:

 When user is being created on Apinf the API Umbrella user object looks like:
apiUmbrellaUserObj = {
      "user":{
        "email": user.emails[0].address,
        "first_name": "First Name",
        "last_name": "Last Name",
        "terms_and_conditions":true
      }
    }
...meaning that there is no way to get real user's first name and last name because Apinf user object has just email after signing up without social services.

 Do we need create apiUmbrella User in Apinf database instantly after user is created on apiUmbrellaWeb or we can wait for daily sync update handled by cron tasks?

**Comment by frenchbread** [comment]
Single space option as " " did not work but "-" works. Example: 
```javascript
user":{
        "email": user.emails[0].address,
        "first_name": "-",
        "last_name": "-",
        "terms_and_conditions":true
      }
```

So, I guess we can go with it for now.
