### ISSUE TITLE
Add API backend as new user/ existing user fails

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1092]
Steps:    

1. Visit https://nightly.apinf.io   
2. Register by clicking on 'Sign Up'  
3. Go to 'Menu' and click on ' API Backend' 
4. Select 'Add API backend'  
5. Go to 'Base Information' and enter name of the API backend
6. Click on 'Next' 
7. Enter Backend details as follows:   
   - Select Protocol used by API from drop down menu (eg. http)  
   - Enter  'Host' name' of the API backend ( i.e Server where API is hosted)   
   - Enter 'Port' for the backend host (eg. 80)  
   - Click on 'Next'    
8. Enter 'Matching URL prefixes'   
    - Enter  'Frontend prefix'   
    - Enter 'Backend prefix'  

9. Click on 'Publish API Backend' button  

Findings: Adding API backend as a new user or existing user fails. Displays error "Cannot read property 'length' of null "  

Operating system: 
 Linux : Ubuntu 14.04.03 LTS (Trusty)

Web Browsers:
1. Mozilla Firefox 44.0
2. Google Chrome 48.0.2564.103   

Screenshot: 
![add_api_fails](https://cloud.githubusercontent.com/assets/13309358/15897897/de5bf620-2d9e-11e6-89f6-ce2a43d86b76.png)

**Comment by bajiat** [comment]
Resolved by #1087?
I verified this in nightly this morning. Added an API backend as an already registered and signed in user. Then I registered a new user and added another API backend. Both were successfully added.

**Comment by bajiat** [comment]
@saralavanip Can you verify this?

**Comment by saralavanip** [comment]
@bajiat , @brylie , I verified the resolved issue. Adding API backend in both cases was successful.

**Comment by brylie** [comment]
Closing as resolved.
