### ISSUE TITLE
Solve the problem with mixed http and https content

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1099]
After removing Force-SSL package due to dockerization, we are experiencing problems in deployment e.g. with Github authentication in nightly (see #1095), and in viewing Swagger files if in http (see #1101)

Propose the most optimal solution for this without causing too much pain on deployment configuration. May require changing dockerization.

**Comment by bajiat** [comment]
@shaliko Any comments / suggestions on this?

**Comment by shaliko** [comment]
@bajiat @brylie At lease first issue #1095 happen because nightly.apinf.io available by HTTPS and HTTP. Before I removed "Force-SSL" there was redirect from HTTP to HTTPS.

I think the right way for fix issue is update Nginx conf (mupx), handling SSL not app a responsibility

**Comment by brylie** [comment]
Alright, we will need to ensure our *mupx* and *Docker* deployments are HTTPS only.

**Comment by bajiat** [comment]
@shaliko The suggestion from Tampere team is to add Force-SSL back to the project, because removing it is causing multiple problems. What would the options for / changes needed to Docker? Is "one-command" installation still possible?

**Comment by shaliko** [comment]
@brylie I can don't know all details, but are we really need be HTTPS only? If application be agnostic to HTTP/HTTPS? The issue was because callback URL from github was configured only for HTTPS.

**Comment by shaliko** [comment]
@bajiat Even after Villie fix we still have issue?

**Comment by bajiat** [comment]
Agreed with @shaliko that only https to be allowed in dockerization,

**Comment by brylie** [comment]
What change(s) do we make in our codebase to reflect this issue? E.g. did we re-enable the force-https module?

**Comment by bajiat** [comment]
@brylie Should we re-open this? We discussed that Docker would only allow https. Nginx has been fixed in nightly. What is missing: what happens if someone deploys with mupx?

**Comment by brylie** [comment]
Sure, I am just wondering if we should add the force-ssl back to our project.

**Comment by bajiat** [comment]
@shaliko Would it be possible to add the Force SSL package back? Will that cause problems with Docker image(s)?

**Comment by shaliko** [comment]
@bajiat Yes, that will have effect on docker-compose configuration. Will be better keep out Force SSL from source code of api-umbrella-dashboard, that the not responsibility of app, preferable way handle  redirect and SSL by web server or load balancer in front of api-umbrella-dashboard.

**Comment by brylie** [comment]
Closing after discussion with @shaliko. We decided not to re-enable the force-ssl package, but to monitor the backlog for any issues related to mixed HTTP/HTTPS content.
