### ISSUE TITLE
Choose how to get analytics data from Elasticsearch

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#110]
Analytics data cannot be retrieved from the Elasticsearch http interface as it is currently disabled. Possible options for solving this:

* extend API Umbrella Admin API with REST calls
* enable remote REST calls on Elasticsearch service. Note: Potential security issue.

Research the options and then choose one.

**Comment by frenchbread** [comment]
Elasticsearch's http interface is not actually disabled and can be easily accessed for example using REST calls, [meteor package](https://atmospherejs.com/brishin/meteor-elasticsearch) suggested by @brylie. So far I have been able to fetch needed data for later use in a dashboard chart - issues [#80](https://github.com/apinf/api-umbrella-dashboard/issues/80) and [#120](https://github.com/apinf/api-umbrella-dashboard/issues/120). Here is the [working branch](https://github.com/apinf/api-umbrella-dashboard/tree/feature/testing-elasticsearch)
