### ISSUE TITLE
View documentation of API backend as a regular user fails

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1101]
Steps: 
  
1. Visit https://nightly.apinf.io 
2. Sign in as a owner   
3. Go to 'Menu' and click on 'Manage API backend' 
4. Go to Documentation
     - Upload  document
     - Enter Documentation link  
5. Click on 'Save' button  
6. Sign out  
7. Login as regular user (doesn't own API backend) 
8. Go to 'Menu' and select 'Catalog'
9. Select any one of the API backends and click on 'View Details'    
10. Click on 'Documentation' 
  
Findings: 

- Viewer: displays  error " Can't read from server. It may not have the appropriate access-control-origin settings." 
- No response when clicked on documentation link:  user not notified of any errors

Browsers:  
Operating system: 
Linux : Ubuntu 14.04.03 LTS (Trusty)

Web Browsers:
1. Mozilla Firefox 44.0
2. Google Chrome 48.0.2564.103

Screenshots:  
![viewer_error1](https://cloud.githubusercontent.com/assets/13309358/15925866/a0af0986-2e41-11e6-8334-404e5014f085.png)

![user_viewer_error2](https://cloud.githubusercontent.com/assets/13309358/15925819/75d38264-2e41-11e6-895a-d1fecfcd66cd.png)

**Comment by bajiat** [comment]
@brylie Could this bug also be related to #1099?

**Comment by brylie** [comment]
@bajiat yes. It looks like the Swagger UI is using `https`. @saralavanip can you submit a screenshot of this issue that also includes the browser URL bar?

**Comment by brylie** [comment]
It could also be related to our FileCollection permissions. I am getting a 403 error when trying to upload swagger files in the `develop` branch.

**Comment by saralavanip** [comment]
@brylie , please find the screenshot of this issue with browser URL bar. 

Screenshot: 

![swagger_viewer-regular_user](https://cloud.githubusercontent.com/assets/13309358/15958277/42de09e4-2efd-11e6-899b-5625f7c2f4d4.png)

**Comment by bajiat** [comment]
@saralavanip You are in http, so the error is caused by #1109. But when we tried to view the Swagger file in https, we got another error. Can you provide the Swagger file so that we can see if it is valid Swagger. Thanks!
