### ISSUE TITLE
Usability Testing of Documentation Viewer

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1108]
Conduct a small user testing to see how Swagger UI is functioning and if it is usable enough.

**Comment by Nazarah** [comment]
Need help from a Dev to show me the overall process of how it will work.

**Comment by bajiat** [comment]
@nazarah What are you planning to test - owners uploading documents or API consumers viewing documents? Or both?

**Comment by Nazarah** [comment]
It would be better if I can conduct both tests.
But right now I'd focus with API document owner persona. 
The document user persona can also be verified as soon as the bug related to swagger gets fixed.

**Comment by Nazarah** [comment]
Scenario:
1. API owner sets up API backend, updates swagger file and updates link
2, (Just a test)...uses may be 1 protocol from the loaded UI
3. API user views a document from another API not his own

https://nightly.apinf.io
