### ISSUE TITLE
403 Not Authorized when uploading swagger.json

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1111]
In the develop branch, uploading an API documentation file generates a 403 error.

# Screenshot
![screenshot from 2016-06-10 10-18-27](https://cloud.githubusercontent.com/assets/17307/15957008/da8edd44-2ef4-11e6-8485-d0e214819ee8.png)

# Steps to reproduce
1. checkout `develop` branch
2. run `meteor`
3. log in as admin user
4. navigate to any API backend
5. go to the **Documentation** tab
6. click **Manage**
7. click **Browse**
8. select the file
9. check browser console

**Comment by bajiat** [comment]
@elnzv Was going to ask you whether you can reproduce this, but you already assigned yourself. Thanks!
