### ISSUE TITLE
Increase the user context awareness in dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1116]
Based on discussion with two Apinf/Apika users, our users do not understand what they are seeing in the dashboard. One of the users had superuser privileges, one was an API owner. They were not sure 
* how to see analytics for one API
* whether they were seeing analytics for APIs they owned or analytics for their own API key usage
* open issue: retaining user settings across sessions - users are able to see the same view they have selected after logout and login

# User story
> As an Apinf user
I want to easily understand
what is the current analytics view about
so that I can switch to another view / select another option if that is not what I'm needing

# Design

* View for Admin
![apinfanalyticscadropdownadmin](https://cloud.githubusercontent.com/assets/17976243/16729600/2d77eae8-4776-11e6-8132-e8117ce61f61.png)

* View for Owner
![apinfanalyticscadropdownowner](https://cloud.githubusercontent.com/assets/17976243/16729615/42829c08-4776-11e6-9349-102a36549ec4.png)

* Multiple Selection and hovering when more than 3 APIs are selected
![apinfanalyticscadropdownmultipleselection](https://cloud.githubusercontent.com/assets/17976243/16729643/634736ce-4776-11e6-88c7-3e41bf4a0b20.png)
![apinfanalyticscadropdownmultipleselectionhover](https://cloud.githubusercontent.com/assets/17976243/16729648/6ce6a73c-4776-11e6-88f2-be2dd1a711a8.png)

* Additional: current date, time and timezone is included so user can easily compare API usage on different times.

# Definition of done
* [ ] User understands by just looking at the view what are the analytics they are viewing at the moment (examples: platform, owned API(s), own key)
* [ ] User understands without investigation how they can change to another option of viewing analytics

**Comment by Nazarah** [comment]
Wireframe Added.

**Comment by Nazarah** [comment]
When a user registers for the first time and has added no API backends, the charts should not appear in the analytics. Instead the following text should appear:
"You don't have any API Backend you manage. To add an API Backend, click here"
The "here" hyperlink would navigate the user to Add API Backend page.
