### ISSUE TITLE
Create UI element / bar for catalog view toggling and sorting

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1127]
The catalog card view and table view should have a common UI element (e.g. a bar) for toggling between catalog card and table view and for sorting the view according to popularity, owner, latest etc.

Related to #1089, #989, #988

# Definition of done
* [ ] User sees a bar that contains sorting menu and toggling icons
* [ ] User can press a toggling icon to toggle between the two catalog view
* [ ] User can use a drop-down menu or equivalent to sort the catalog view (view that is currently displayed)

**Comment by Nazarah** [comment]
Will be adding links to wireframe once the PR gets merged

**Comment by brylie** [comment]
This needs to be re-opened, as the sorting options were removed from the pull request.
