### ISSUE TITLE
Denormalize averageRating and bookmarksCount for API Backends

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1130]
In order to sort the API Catalogue by average rating and bookmarks count, we may need to store the corresponding values in the ApiBackends collection. Create helpers and methods to calculate the average rating and bookmarks count. Make sure the helpers are called when a user bookmarks or rates an API Backend.

**Comment by bajiat** [comment]
@brylie Should I close #1128 as duplicate?

**Comment by brylie** [comment]
Jep. I didn't notice that you had opened the issue.
