### ISSUE TITLE
API Analytics: When data for filtering (month/year) is changed back to default, alert appears saying table can't be reinitialized

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1144]
Chrome (latest), Windows 8

Reproduction Step:
1. Go to APINF Analytics and reload chart data.
2. Click Month dropdown and select a month.
3. Open the dropdown again and select default value
Result: the following alert appears

![image](https://cloud.githubusercontent.com/assets/17976243/16038263/e6bf6a6c-322c-11e6-89d8-3c81ab6c1ff3.png)

**Comment by bajiat** [comment]
@frenchbread Your PR #1245 will fix this bug, right? Should the issue be connected to your PR?

**Comment by frenchbread** [comment]
@bajiat Yes, it does. Updated description for #1245.
