### ISSUE TITLE
Incompatible jQuery version error from Bootstrap

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1149]
We recently added the `datatables` npm dependency to our project. Datatables requires jQuery > 1.x.x, and as a result, npm is installing jQuery latest (version 3.x). This causes a compatibility issue with Bootstrap.

Limit the maximum jQuery version to prior to 3.0.0.

# Output

```sh
$ npm install
...
datatables@1.10.12 node_modules/datatables
└── jquery@3.0.0
...
```

# Related error(s)

```
bootstrap.js:15 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
```

There is a second error related to jQuery, which may or may not be related to this issue:

```
settingsWizard.js:57 Uncaught TypeError: $(...).carousel is not a function
```

**Comment by jykae** [comment]
@brylie what is the actual error this fixes? I assigned to review #1150

**Comment by brylie** [comment]
@philippeluickx can you please help verify the error? I am having trouble reproducing on my laptop.

**Comment by brylie** [comment]
@jykae I have updated the issue with error message(s).

**Comment by brylie** [comment]
We just ran a second test on a fresh install. Switching the jQuery version to be < 3.0.0 resolves both errors in the task description.

**Comment by brylie** [comment]
Ping @bajiat.

**Comment by nnn** [comment]
Still getting this error in develop:

```
bootstrap.js:15 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3(anonymous function) @ bootstrap.js:15(anonymous function) @ bootstrap.js:17(anonymous function) @ twbs_bootstrap.js?hash=dc805bf…:2394(anonymous function) @ twbs_bootstrap.js?hash=dc805bf…:2401

app.js?hash=5ecf35e…:8050 Uncaught TypeError: $(...).carousel is not a functionclickNext @ app.js?hash=5ecf35e…:8050(anonymous function) @ template.js:496Template._withTemplateInstanceFunc @ template.js:465(anonymous function) @ template.js:495(anonymous function) @ view.js:884Blaze._withCurrentView @ view.js:538(anonymous function) @ view.js:883(anonymous function) @ events.js:47dispatch @ jquery.js:5087elemData.handle @ jquery.js:4895

**Comment by philippeluickx** [comment]
@nnn that's the error I was having.
Also, might be a good idea to comment any limits to version numbers, so we know that we need to keep an eye on this when we update to bootstrap v4 (that should support jquery 3)

**Comment by brylie** [comment]
@nnn you might need to re-run `npm install` after pulling changes from `develop`.

**Comment by jykae** [comment]
@nnn Can this be closed? Is it fixed for you?

**Comment by nnn** [comment]
Yes, it's fixed.
Tested in the latest develop.
No errors even after meteor reset.
