### ISSUE TITLE
Add inline help to API backend form fields

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#115]
The form fields should contain some information on what type of data can be entered or on the purpose of the fields.

Definition of done
---
* [x] Add markup to every field on form

**Comment by elnzv** [comment]
Related: https://github.com/aldeed/meteor-autoform/issues/402

**Comment by elnzv** [comment]
Related: 
https://github.com/aldeed/meteor-autoform/issues/257
https://github.com/aldeed/meteor-autoform/issues/336
https://github.com/aldeed/meteor-autoform/issues/868
https://github.com/aldeed/meteor-autoform/issues/555

**Comment by elnzv** [comment]
As a solution for now I propose to add 
```
<span id="helpBlock" class="help-block">A block of help text.</span>
```
after each quickForm field.
In future we can spent time writing a package which allows to define this field in schema.
