### ISSUE TITLE
Delay and error message when uploading swagger.json

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1151]
When uploading a swagger.json file, on the API Backend Documentation tab, there is a strange error message and delay before the Swagger file is rendered. After a few seconds, the page refreshes automatically and the swagger file is rendered.

# Screenshot
![animated screenshot](https://cloud.githubusercontent.com/assets/17307/16073757/2bbcb0c0-32f0-11e6-9444-0961753304e2.gif)

# Error text
```
Cannot read Swagger JSON from https://nightly.apinf.io/gridfs/fs/md5/...
```

**Comment by brylie** [comment]
I am re-opening until we are sure that PR #1155 resolved the issue.

**Comment by saralavanip** [comment]
@brylie , currently uploading swagger json file is delayed with another new error message:
'Failed to parse JSON/YAML response'

Screenshot:  
![upload_swagger_json_error](https://cloud.githubusercontent.com/assets/13309358/16114033/d3089970-33c7-11e6-99da-5dfc3d0fce49.png)

**Comment by bajiat** [comment]
@jykae will co-pilot

**Comment by jykae** [comment]
Oh, sorry, I have neglected my co-piloting.. @nnn do you have branch for this? I could take a look. Might have something to do with nginx proxying (HTTP->HTTPS) as well.. If this is only nightly issue.

**Comment by jykae** [comment]
@bajiat @nnn Just tested this on nightly. 

This delay and error message is because it takes a while to upload and serve file over that generated unique URL. So this is not bug in strict sense, Swagger is just hurrying a bit to trying parse the file before it exists on that URL. Do you think we should have some better information on this behaviour on UI for the user?

**Comment by jykae** [comment]
Other option is that we verify that file is uploaded and exists on that URL, and after that put the URL on Swagger UI to be sure not to get any error message on the process.

**Comment by jykae** [comment]
@nnn I'll take a look if that could be checked as suggested above.

**Comment by jykae** [comment]
@nnn Tried polling the URL solution until it exists, but didn't get it work on Thursday, returned always false for some reason. 
However, I would say this is quite small issue as it only shows error message a while when file uploading and serving it to unique URL is in progress.

**Comment by brylie** [comment]
> I would say this is quite small issue as it only shows error message a while when file uploading and serving it to unique URL is in progress.

@jykae good point. @bajiat should we put this in the icebox?

**Comment by bajiat** [comment]
@brylie @jykae Fair point. It is not a showstopper, since the file still gets uploaded.

**Comment by bajiat** [comment]
Unassigned and moved to icebox. @jykae @nnn I quess there are no associated PR's or branches?

**Comment by nnn** [comment]
@bajiat, the one @jykae did - https://github.com/apinf/api-umbrella-dashboard/tree/bugfix/apidocs-notdefined-when-deleting

**Comment by bajiat** [comment]
@nnn @jykae Isn't https://github.com/apinf/api-umbrella-dashboard/tree/bugfix/apidocs-notdefined-when-deleting actually related to issue #1199 ApiDocs is not defined when deleting API Backend

**Comment by nnn** [comment]
@saralavanip, please confirm.

**Comment by saralavanip** [comment]
@nnn, verified the resolved issue and it works as expected.
