### ISSUE TITLE
Upload swagger.yaml delayed with error message

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1156]
Steps:    
1.Visit https://nightly.apinf.io  
2.Login as API owner by clicking on 'Sign In'  
3.Go to 'Menu' and click on ' API Backend'  
4.Go to 'Manage API Backends '  
5.Go to API Backend and click on 'View' button     
6.Click on 'Documentation' tab  
7.Click on 'Manage' button  
8.Select file to upload by clicking on 'Choose file' (eg. swagger.yaml)  
9. Click on 'Save'  

Expected Result: Successful in uploading swagger document. Displays dialog 'Documentation has been successfully uploaded'. 

Actual: Uploading  swagger.yaml file is delayed and displays error message as shown in below screenshot: "Can't read swagger JSON from https://....."

Screenshot:  
![swagger_yaml_error3](https://cloud.githubusercontent.com/assets/13309358/16078376/4276b8b2-3307-11e6-9241-8080d5d8e324.png)

![swagger_yaml_successful1](https://cloud.githubusercontent.com/assets/13309358/16078381/4873a37e-3307-11e6-8d47-f64d1698ba1f.png)

**Comment by saralavanip** [comment]
Currently uploading swagger yaml  is delayed with another new error message:
'Failed to parse JSON/YAML response'

Screenshot:  
![upload_swagger_json_error](https://cloud.githubusercontent.com/assets/13309358/16114033/d3089970-33c7-11e6-99da-5dfc3d0fce49.png)

**Comment by jykae** [comment]
Most likely related to #1151

**Comment by jykae** [comment]
co-piloting @nnn

**Comment by nnn** [comment]
@saralavanip, please confirm.

**Comment by saralavanip** [comment]
@nnn, verified the resolved issue and it works as expected.
