### ISSUE TITLE
'View usage instructions' button not responding in API backend view

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1157]
Steps:    
1.Visit https://nightly.apinf.io
2.Login as a registered user by clicking on 'Sign In' 
3.Go to 'Menu' and click on 'Catalog' 
4.Select any one of the API backends and click on 'View Details' 
5.Click on 'View usage instructions' 

Expected Result: Shows information about API calls with example URL. 
Actual: Click on 'View usage instructions' button is not responding

**Comment by bajiat** [comment]
@saralavanip Can you verify this? Fix should be available on nightly.

**Comment by saralavanip** [comment]
Verification in progress.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on nightly.apinf.io and it is working as expected.
