### ISSUE TITLE
Design the dashboard analytics for API owners

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1158]
Separated from #1066. Work together with the assignee for #1066, because the chart library selection will affect which chart styles are available.

The main user for the dashboard is an API owner, who needs to be able to see analytics for the API(s) he/she owns.

Take the learnings related to visualizing analytics from service project follow-up dashboard and apply them to Apinf dashboard page. 

Another potential source of ideas: https://ethstats.net/
(Source code https://github.com/cubedro/eth-netstats)

Proposal for charts and/or filters
- Number of calls/requests (already in dashboard)
- heat map or country map (see http://dc-js.github.io/dc.js/vc/)
- HTTP status code
- API key or IP address
- URL that is being accessed
- time range
- response time

Consider also giving ready made scenarios inside a menu for API managers. Examples:
- show all APIs that give 404
- show backends with slowest response time

# Wireframes

![apinfanalyticsselectedapi-responsetime](https://cloud.githubusercontent.com/assets/17976243/16487277/67b44d02-3ed2-11e6-8f93-88ba83eb9403.png)

# Definition of done
- [ ] Identify the required charts
- [ ] Create lofi wireframe for showing a single API backend for an API owner

**Comment by Nazarah** [comment]
Proposed columns
1. Methods: (values: GET, POST, etc)
2. HTTP STATUSL 200, 404, etc.
 Alternatively, a column showing API names with a status indicator can be used to show its status( on mouse hover: HTTP Status)

**Comment by nnn** [comment]
@Nazarah, could you please link your design/wireframe to this issue?

**Comment by Nazarah** [comment]
@nnn added the designed wireframe.

**Comment by Nazarah** [comment]
@nnn what I saw from Damir'w work that they have a chart that shows time needed for responding to API request. That chart would be included in APINF Admin's dashboard, which is different from API owner.
So adding that one as well
![apinfanalyticsselectedapi-adminview](https://cloud.githubusercontent.com/assets/17976243/16486960/81e66c2a-3ed0-11e6-8488-b7913ab81378.png)
