### ISSUE TITLE
Published API backends are not rendered in 'Manage API Backend' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1164]
Findings: 
- Previously added API backends are not rendered in 'Manage API Backend view':shows a blank page. 
- Shows only APIs added on current day in 'Manage API backend' view and they get disappeared later. 

Screenshot: 
![selection_001](https://cloud.githubusercontent.com/assets/13309358/16256569/c3781538-385b-11e6-9340-82b176430f76.png)

**Comment by bajiat** [comment]
@sarala This is not a SW bug, but you could of course not know that. @jykae had to re-set the Apinf database for one particular deployment of nightly. This should not happen again (unless there is a very specific reason to re-set). We should remember to inform you, if this needs to be done again.

**Comment by saralavanip** [comment]
@bajiat, Thanks for the info.

**Comment by jykae** [comment]
@saralavanip @bajiat Verified yesterday locally and this morning on nightly. For some reason I am interested to find out, managerIds saving fails, causing that when Apinf is restarted information of user managed APIs is lost. This might be related with "description" field not saving on wizard (solved by removing the field in wizard), as these both are fields that doesn't exist on Umbrella.

Investigating the cause...

**Comment by jykae** [comment]
@saralavanip fix waiting PR review, https://github.com/apinf/api-umbrella-dashboard/pull/1202

**Comment by bajiat** [comment]
@saralavanip Please verify on nightly

**Comment by brylie** [comment]
@jykae what was the underlying issue here? I don't understand how removing the autovalue fixes this issue.

**Comment by saralavanip** [comment]
verified resolved issue on nightly.apinf.io
