### ISSUE TITLE
'Description' text not saved while adding API backend

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1188]
Steps:  
 1.Visit https://nightly.apinf.io  
2.Register by clicking on 'Sign Up'  
3.Go to 'Menu' and click on ' API Backend'  
4.Select 'Add API backend'   
5.Go to 'Base Information'  
    - Enter name of the API backend  
    - Enter description  
6.Click on 'Next'  
7.Enter Backend details  
8.Click on 'Next'  
9.Enter 'Matching URL prefixes'  
10.Click on 'Publish API Backend' button   
11.Go to 'Manage API backends' view  
12.Click on 'Edit'  

Expected Result: All the details given while adding the API are saved and shown in 'Edit' view.  
Actual: Description of the API is not saved while adding API  and shows empty description field in 'Edit API view'

**Comment by nnn** [comment]
@saralavanip, please confirm.

**Comment by saralavanip** [comment]
@nnn,  'Description' field is missing in Add API backend wizard and shown only in 'Edit' View. Is this as expected? 

Screenshot: 
![missing_description_field](https://cloud.githubusercontent.com/assets/13309358/16257880/bb1672a6-3863-11e6-9c06-dceba48659a1.png)  
![description_edit_view](https://cloud.githubusercontent.com/assets/13309358/16257888/c8fde480-3863-11e6-8cf4-00f3570ad3c7.png)
