### ISSUE TITLE
Add infinite scrolling or pagination to Catalog view

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1196]
Add functionality that only publishes (?) a performance-wise feasible number of API backends to API catalog container. More/Next backends are published when user takes an action. Most likely options for the user action are infinite scrolling or catalog pagination.

# User story
>  As an Apinf architect
I want catalog view to load only a reasonable amount of APIs when user goes into the view
so that the performance of the platform does not suffer from too many APIs being published to front-end

# Definition of done
* [x] Select either infinite scrolling or pagination as the solution
  * [x] Document the pros and cons of each option in the comments for this issue
* [x] Implement the solution so that UI does not get stuck even if the number of APIs stored in database would be high

# Wireframe

* Pagination for Catalog and Table View

![paginationcardentries](https://cloud.githubusercontent.com/assets/17976243/16611686/84a69d3c-436b-11e6-9fde-36608f68b13e.png)

![paginationtable entries](https://cloud.githubusercontent.com/assets/17976243/16611695/8f82a03e-436b-11e6-9b44-fe0b1d8a2599.png)

* Infinite Scrolling

![infinitescrollingcard](https://cloud.githubusercontent.com/assets/17976243/16613618/9c360654-4375-11e6-971e-7bc794de609d.png)

![infinitescrollingtable](https://cloud.githubusercontent.com/assets/17976243/16613624/a27ecb72-4375-11e6-8ba1-7c22f0f760c4.png)

**Comment by philippeluickx** [comment]
I'd prefer to go with pagination. Infinite scrolling is often not the best solution UX wise, pagination is a safer bet.
http://babich.biz/ux-infinite-scrolling-vs-pagination/

**Comment by Nazarah** [comment]
If using pagination and we have option to select number of entries to be shown in each page, then there can be another option"show all entries" in the dropdown. This somewhat implements the infinite scrolling option

**Comment by philippeluickx** [comment]
Let's keep it simple. Google does not have those options and is the most used website. I'm OK with having a sizeable amount of results (e.g. 25 or 50) and then just paginations.

**Comment by Nazarah** [comment]
Wireframes Added.
