### ISSUE TITLE
UI improvements to single API view (API profile)

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1203]
# User story
> As an API consumer
I want to be able to quickly determine whether the API is useful or interesting for me by looking at the default tab of API profile
so that I only need to go to other tab if I find the API interesting.

Potential improvements or additions
* Look and feel improvements, for example
  * buttons
  * tab alignment and design
  * usage instructions (placement & look and feel)
* API description to default tab: what is the API about, what user needs it does follow, who is it intended for
* average response time - if available for other users than owners
* option to bookmark (and rate?)
* Logo placeholder

# Design

* Usage instruction can be seen by hovering/clicking on Infor Icon
![apiprofilepage](https://cloud.githubusercontent.com/assets/17976243/16985189/9acd4e04-4e87-11e6-9d45-42ee5ea8ea6d.png)

* Usage Instruction appears in a pane in Details tab
![apiprofilepage2](https://cloud.githubusercontent.com/assets/17976243/16985199/a8f68dec-4e87-11e6-8582-c095333cd989.png)

**Comment by nnn** [comment]
interested in this task for API Backend Sprint.

**Comment by Nazarah** [comment]
changes in Button and tab style
information alignment in the main page.

**Comment by Nazarah** [comment]
Lo-Fi Wireframes

![profiledefaultmockup](https://cloud.githubusercontent.com/assets/17976243/16838756/9f77e878-49d3-11e6-8cb5-be8dd37bdcc3.png)
![profiledefaultmockup2-2](https://cloud.githubusercontent.com/assets/17976243/16838757/9f7efd7a-49d3-11e6-944c-358a24723274.png)

**Comment by Nazarah** [comment]
Wireframes Added
