### ISSUE TITLE
Separate API details editing from editing proxy settings

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1207]
Consider that all editing options that are related to API backend would happen in API profile (tabbed single API view) instead of the form that is used for controlling proxy settings.

For instance, allow owners to upload a logo, edit API description etc. in the API profile view

Note: this does not require inline editing.

See also related issues #1020, #1026

# User story
> As an API owner
I want edit my API backend details directly in API profile view
so that I do not have to go to a separate settings page

# Wireframe

![apiprofileproxytab](https://cloud.githubusercontent.com/assets/17976243/17802431/effb0550-65f8-11e6-8a63-089c030869fa.png)

**Comment by bajiat** [comment]
Partially already done, API settings in API tabbed view. Check that contains all necessary settings after API backend schema is ready.

**Comment by Nazarah** [comment]
@brylie : Wireframe added. Please review and give your feedback

**Comment by bajiat** [comment]
@nazarah This task should contain the wireframe for API settings (like logo etc.) not proxy backend settings for that API.

**Comment by bajiat** [comment]
Already completed in task #1091.
