### ISSUE TITLE
Create basic API grid for API user dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#121]
The API user dashboard needs a grid layout to display widgets. Check options available for Bootstrap dashboard grid layouts and implement one of them.

Definition of done
---
* [x] Document the available options or examples of Bootstrap dashboard grid.
* [x] Choose one and implement in API user dashboard.
* [ ] Remove unneeded API user dashboard elements (Posts).

**Comment by bajiat** [comment]
Related to #120 and #119.

**Comment by JuusoV** [comment]
Created basic grid. Looking to hear some feedback on it before moving further.

Im not seeing the documenting part on this task is neccessary as long as the implementation is self-explanatory in the code.
