### ISSUE TITLE
Enhance Apinf top bar

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1211]
Enhance the aesthetics and functionality of top bar

# Potential enhancements
- Optionally, Add API backend option to top menu
- Make sure Apinf logo is never collapsed
- Remove the hamburger icon related to collapsing side menu from top bar
- Include the language switch for all views (not just landing page)

Related issue: # 1209

**Comment by Nazarah** [comment]
Wireframes are attached at #1209
