### ISSUE TITLE
Catalog is not displayed in nightly

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1214]
[Catalog view](https://nightly.apinf.io/catalogue) in nightly displays only the top bar without any APIs

# Steps to reproduce

1. Log into https://nightly.apinf.io
2. Click Catalogue
3. (Optionally, try clicking any of the buttons in the top bar: My APIs, My Bookmarks or toggling the views)

# Observed behavior
The view does not contain any APIs, i.e. there is no catalog

# Expected behavior
The default API catalog view (card view) is displayed

# Environment

- Web browser: Chrome 51.0.2704.103
- Operating system: Windows 10

**Comment by bajiat** [comment]
![catalog screenshot](https://cloud.githubusercontent.com/assets/11626388/16374446/2f01ef20-3c5f-11e6-8085-07af7d3e58d5.png)

**Comment by bajiat** [comment]
@jykae @brylie Please inform @saralavanip when the fix is available so that she can start testing Catalog.

**Comment by saralavanip** [comment]
Verified resolved issue on nightly.apinf.io
