### ISSUE TITLE
Empty API key right after registration first user

### ISSUE THREAD

**Issue by shaliko** [apinf/api-umbrella-dashboard#1216]
First user get empty API key because API-Umbrella settings does not available when APInf try create user and get API key.

How to reproduce:

1) Make new installation of api-umbrella-dashboard without settings.json
2) Register first user and fill data in wizard.
3) Visit https://apiumbrellahost/profile

![https___apinf_usubov_com_profile](https://cloud.githubusercontent.com/assets/36139/16381263/599d9b38-3c84-11e6-8483-4f2908c2c934.jpg)

Possible fix move "create user and get API key after user have done setup wizard".

**Comment by brylie** [comment]
Ping @jykae. You mentioned interest in this issue.

**Comment by jykae** [comment]
@shaliko I'll take at look at this
