### ISSUE TITLE
Display the API backends catalog in base template

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#122]
Related to #67, create a catalog route to display API catalog table in the API consumer template.

Definition of done:
* [x] Connect table to the API backends collection.
* [x] Add route to display table template within our base template.
* [x] Add the catalog link to navigation.

**Comment by JuusoV** [comment]
@brylie isn't this already done by @elnzv?
Take a look of ApiBackends in the navigation of /admin.
Am I misunderstanding something?

**Comment by JuusoV** [comment]
Created created /catalogue to which calls the template already created by @elnzv. 
Waiting for the task # to finish in order to have a sidebar where to implement the link.

**Comment by JuusoV** [comment]
Changed estimation from 8 hours to 2.
