### ISSUE TITLE
Create instructions on deployment

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1222]
Create step-by-step instructions for making nightly deployment (and also temporary deployments to temporary server).

# Definition of done
* [x] Instructions for deploying nightly exist
* [x] Instructions for temporary deployment exist
* [ ] Instructions have been reviewed by another team member, preferably also tested
* [x] Instructions are available for the entire team

**Comment by jykae** [comment]
@bajiat Instructions done, and available for the team members. Please assign someone to check & test (tick the box when done). 

@nnn & @brylie should be also able to give rights to deployment instructions/config folders.

**Comment by jykae** [comment]
@frenchbread has also rights now.

**Comment by bajiat** [comment]
@jykae
Here are some comments...
What does run "anywhere" mean? In Meteor? 
What does one need to have installed before it is possible to run the script?

**Comment by jykae** [comment]
@bajiat Thank you for review, added further explanations to README.

**Comment by frenchbread** [comment]
@jykae Where can I find instructions for deployment.

**Comment by brylie** [comment]
@frenchbread they  are in owncloud.

Check under DevOps.

**Comment by frenchbread** [comment]
@brylie @jykae Ok.
