### ISSUE TITLE
Allow API consumer to download client code

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1225]
Use Swagger codegen API for creating a small UI for client code SDK download based on Swagger file. 

# User story
> As an API consumer
I want to download an SDK for my API in the language which I am using
so that I can start developing the client code based on the API design and don't have to start development from scratch

# Definition of done
* [ ] User can select a programming language for which they download the SDK for the Swagger file they have open on the UI (potential options: dropdown menu for all languages or buttons for most popular languages, rest in dropdown)
* [ ] User can take an action (e.g. press the button) to download
* [ ] After the user takes the action, a zip file is downloaded

# Wireframe

![documentationpage2](https://cloud.githubusercontent.com/assets/17976243/17807550/0c0f4ed4-6614-11e6-8921-b7fd314cecae.png)
![sdkgenerator](https://cloud.githubusercontent.com/assets/17976243/17807549/0c0cc178-6614-11e6-9b32-a8adaddce71d.png)

**Comment by marla-singer** [comment]
@bajiat I will work in this repository [https://github.com/2glab/sdk-generator](https://github.com/2glab/sdk-generator)

**Comment by marla-singer** [comment]
@bajiat The main task is ready. In progress: handling errors

**Comment by Nazarah** [comment]
@marla-singer : hey! lets discuss in rocket chat about integrating the test UI in the APINF. I need your opinion while designing the wireframe. :)
