### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by philippeluickx** [apinf/api-umbrella-dashboard#1235]
Console complains a favicon is missing. Should be a quick win. We can use a simple tool like http://realfavicongenerator.net/

**Comment by bajiat** [comment]
@brylie Do you have an idea what is missing? Is favicon something we are using or something we have used before?

**Comment by brylie** [comment]
@philippeluickx will you please paste the console error? We can figure out whether the file is missing, or if it is something else we need to change.

**Comment by philippeluickx** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) https://apinf.io/favicon.ico

Also couldn't find any file on the repo: https://github.com/apinf/api-umbrella-dashboard/search?utf8=%E2%9C%93&q=favicon

**Comment by brylie** [comment]
Cool, a simple fix would be to include the favicon.ico in `/public/`. We might also want to add favicon as an option on our branding page.

**Comment by bajiat** [comment]
@jykae Any update on the progress? Can the issue be moved to In progress column?
