### ISSUE TITLE
Catalog and settings wizard testing

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1236]
Continue explorative manual testing for catalog in [nightly deployment](nightly.apinf.io).  Test the settings wizard in local development environment. Document the test cases.

# Definition of done
* [x] Test dashboard 
* [x] Interact with the charts
* [x] Try sorting options in catalog (if not tested in sprint 25)
* [x] Test setting up a new Apinf instance in development environment (= test settings wizard)
* [x] Report any issues labeling them appropriately (e.g. bug or enhancement)
* [x] Document the test cases in Apinf test cases doc

**Comment by bajiat** [comment]
@brylie @nnn This is the testing task for @saralavanip for sprint 26.

**Comment by saralavanip** [comment]
Reported issues: 
https://github.com/apinf/api-umbrella-dashboard/issues/1283  
https://github.com/apinf/api-umbrella-dashboard/issues/1309     
https://github.com/apinf/api-umbrella-dashboard/issues/1310   
https://github.com/apinf/api-umbrella-dashboard/issues/1311

**Comment by nnn** [comment]
@saralavanip, are you going to continue dashboard and chart testing next sprint or should we close this issue?

**Comment by saralavanip** [comment]
@nnn , Please let me know if dashboard is ready for testing. I am available next week(18.07-22.07) and will continue with this testing task.

**Comment by nnn** [comment]
@saralavanip, yes, please, continue with dashboard testing.

**Comment by saralavanip** [comment]
Reported issue: 
https://github.com/apinf/api-umbrella-dashboard/issues/1337
