### ISSUE TITLE
Design and implement dashboard summary statistics panel(s)

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1241]
Related to feedback received while working on #1040, our UI mockups contain a 'summary statistics' panel. Design and implement the 'summary statistics' panel(s) on the dashboard, including:

- number of requests displayed / 
- total count of requests
- percentage of successful requests
- average response time (probably using **mode**, as opposed to mean)
- number of unique users who have called the API(s)

# Wireframe
![apinf analytics charts](https://cloud.githubusercontent.com/assets/17976243/16724510/b66da754-475b-11e6-9e96-dbf403eecca4.png)

# References
For the 'average response time' panel, the **mode** is suggested based on the observation that response time data is skewed, e.g. it 'leans to the left'. For skewed data, the **mode** will give a better estimation of the center than the *mean*, .

See: Wikipedia - [Skewness](https://en.wikipedia.org/wiki/Skewness)
![positive and negative skew](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Negative_and_positive_skew_diagrams_%28English%29.svg/500px-Negative_and_positive_skew_diagrams_%28English%29.svg.png)

![mean, median, and mode with relation to normal and skewed curves](https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Comparison_mean_median_mode.svg/500px-Comparison_mean_median_mode.svg.png)

**Comment by brylie** [comment]
@Nazarah would you like to take this task? It is mainly a task to coordinate several sub-tasks. E.g. 

- #1002
- #1003

**Comment by Nazarah** [comment]
I will take it

**Comment by Nazarah** [comment]
@brylie : do I need to provide the wireframe again? Cause the issue isn't showing one.

**Comment by brylie** [comment]
@Nazarah that would be helpful, yes :-)

**Comment by Nazarah** [comment]
Wireframe uploaded.
Added a simple tooltip and popup to notify users about average response time is calculated as Mode.
