### ISSUE TITLE
Select sorting order and toggle to 'bookmarks' view shows empty page

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1252]
Steps: 

1.Visit nightly.apinf.io   
2.Login as registered user  
3.Go to catalog view   
4.Select API and bookmark by clicking on 'flag' sign    
5.Select sorting order from drop down menu (eg. Name/Rating, ascending order)   
6.Click on 'My Bookmarks'   

Findings:    
- Select sorting order and toggle to 'bookmarks' view shows empty page   

Operating system:   
 Linux : Ubuntu 14.04.03 LTS (Trusty)

Web Browsers:
Google Chrome 48.0.2564.103      

Screenshot:  
![sort_bookmarks_empty_page1](https://cloud.githubusercontent.com/assets/13309358/16521599/a21b1f38-3fa0-11e6-8d70-d3010e19a730.png)  

![rating_bookmarks_emptypage](https://cloud.githubusercontent.com/assets/13309358/16521676/2418d02a-3fa1-11e6-93c2-21d29c7b7cee.png)

**Comment by nnn** [comment]
Working fine on nightly. @saralavanip, please confirm this.

**Comment by saralavanip** [comment]
@nnn , verified resolved issue and working fine as expected.
