### ISSUE TITLE
Choose unit and functional testing framework

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#126]
In order to automate project testing, we need a unit and functional testing framework. Possibly organise an internal workshop.

Definition of done
---
* [x] Review popular Meteor testing environments.
* [x] Decide on Apinf testing strategy.
* [x] Document the strategy.

**Comment by frenchbread** [comment]
This task is still in progress but so far I reviewed a couple of different approaches for testing the meteor application. The most suitable for us and popular in the development community are [Laika](http://arunoda.github.io/laika/features.html), [Casperjs](http://casperjs.org/) and [Jasmine](http://jasmine.github.io/2.1/introduction.html) ([meteor package])http://jasmine.github.io/2.1/introduction.html)).

There is a table that gives good overview around some of the most popular testing framework:
![untitled](https://cloud.githubusercontent.com/assets/2122679/8372205/967bf228-1be9-11e5-9d43-5bdd2ad7218b.png)

**Comment by brylie** [comment]
@frenchbread If I recall correctly, you recommend using the Mocha testing framework? Or did you lean towards Jasmine?

**Comment by frenchbread** [comment]
@brylie We agreed that we will use Jasmine for testing but as you may remember we kind of failed writing unit tests because of some problems with accessibility to `Meteor` object.
