### ISSUE TITLE
Finalize admin view for dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1260]
Give the last finishing touches to administrator dashboard.

Continuation for #1040
Related to #1158

# User story
> As an Apinf administrator
I want to be able to view the analytics for all calls made through the proxy

# Design
![apinfanalyticsselectedapi-adminview](https://cloud.githubusercontent.com/assets/11626388/16523300/64c8d49e-3fab-11e6-9383-c1ad63b270a9.png)

# Definition of done
* [ ] User is aware of context: entire dashboard analytics instead of single api
* [ ] info tips for charts
* [ ] Summary statistics panel

**Comment by bajiat** [comment]
@nazarah Can you add the wireframe for admin dashboard into Design

**Comment by nnn** [comment]
@Nazarah, any suggestions on icons help text?
For three charts and table.

**Comment by nnn** [comment]
@Nazarah, @brylie, @frenchbread, any suggestions on dashboard main title?

Current look:

![screencapture-localhost-3000-dashboard-1467629742642](https://cloud.githubusercontent.com/assets/7489044/16558549/1cccd564-41ef-11e6-83c8-1ab612f4b8d6.png)

**Comment by brylie** [comment]
Just 'Dashboard' is probably fine.

**Comment by Nazarah** [comment]
@nnn 
Help text for API request Timeline: "Click on the overview below to activate the View Finder. You can use it to select specific timeframe for which you wish to see API request patterns. HTTP Status Code and API Response Time charts will get rendered based on the selected timeframe."

HTTP Status code: "Click on any HTTP status bar to filter API Request Timeline and API Response Time chart for that specific response type."

API Response Time: "Click on any bar to filter  API Request Timeline and HTTP Status Code chart by requests that have the selected response time range."

Analytics Data: "Available data depends on how API Response Timeline, HTTP Status Code or API Response Time charts are rendered for viewing."

**Comment by Nazarah** [comment]
@nnn 
How about "glyphicon glyphicon-info-sign" for information icon.
http://www.w3schools.com/bootstrap/bootstrap_ref_comp_glyphs.asp
make sure the icon is mid aligned with the chart title.

I'd still go for API Dashboard as title, sounds more relevant.

**Comment by brylie** [comment]
@Nazarah see also FontAwesome:

http://fontawesome.io/icons/

We are using FontAwesome icons more often than Glyphicons.
