### ISSUE TITLE
Dashboard view to be selected based on user role

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1262]
Implement the rules for which dashboard the user should see
- admin for dashboard administrators
- owner for dashboard owners

# Definition of done
* [ ] List or wireframe of dashboard elements exists (see #1158)
  * [ ] List or wireframe indicates user role visibility for each dashboard element
* [ ] Template helper exists for checking user role (returing true / false to toggle elements)
* [ ] Dashboard elements are only visible for users with the appropriate role

**Comment by Nazarah** [comment]
@nnn : do we have separate lists of what to display in separate admin and owner views? If so please list them here. Might need to rework on the wireframes.
