### ISSUE TITLE
Create a mission statement for Apinf

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#130]
Related to #104, write a mission statement describing the Apinf project and product.

Definition of done
---
* [ ] Hackpad document containing mission statement.
* [ ] Updated descriptions in Facebook and Twitter accounts.

**Comment by Laura-Sampo** [comment]
We decided to create two separate statements. One short one, more like slogan. The other one with two sentences, more like description.

Proposals:

- Building a bridge between API developers and API owners.

-Bringing API owners and developers under the same roof.

-Connecting API owners and developers.

-We want to enable easy discovery and use of API's.

-We help organizations open, manage and monitor their APIs. We enable developers to discover and use APIs easily.

-We help organizations and individual developers to open, manage, discover and use  API's easily.

**Comment by kyyberi** [comment]
+1
