### ISSUE TITLE
Create Social media strategy document

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#131]
Create a social media strategy for the Apinf project, based on existing social media strategy template(s).

Definition of done
* [x] Hackpad document, or extend existing document describing social media strategy
* [ ] List of two or more social media strategy templates, used as resources/references for our document
* [x] List of social media channels relevant to Apinf project (Twitter, Facebook, Linkedin, etc)
* [ ] Specific recommendations for each social media channel regarding frequency, content, keywords, etc

**Comment by Laura-Sampo** [comment]
Template:
http://blog.hootsuite.com/wp-content/uploads/2014/12/Social-Media-Strategy-Template-Sheet1.pdf
