### ISSUE TITLE
Edit API backend as owner displays message 'Not Authorized'

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1310]
Steps:  
1.Visit https://nightly.apinf.io  
2.Sign up  
3.Add API backend   
4.Go to 'Manage API Backends'    
5.Click on 'Edit'   

Findings:  
- Displays message 'Not Authorized' cannot access this page and ensure to be logged in.  

Screenshot:  
![edit_api_unauthorized_error](https://cloud.githubusercontent.com/assets/13309358/16795327/7432587c-48e5-11e6-8909-b2b30080c27e.png)

**Comment by nnn** [comment]
@saralavanip, please confirm.

**Comment by saralavanip** [comment]
@nnn , verified the resolved issue and works as expected.
