### ISSUE TITLE
Being owner of API backend unable to add metadata,documentation and backlog in 'API backend view' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1311]
Steps:  
1.Visit https://nightly.apinf.io  
2.Sign up  
3.Add API backend   
4.Go to 'Manage API Backends'    
5.Click on 'View' 

Findings:  
- Being owner of API, unable to add metadata, documentation and backlog

**Comment by nnn** [comment]
@saralavanip, please confirm.

**Comment by saralavanip** [comment]
@nnn , verified the resolved issue and works as expected.
