### ISSUE TITLE
Unable to edit or/and delete API backlog item

### ISSUE THREAD

**Issue by nnn** [apinf/api-umbrella-dashboard#1314]
When trying to edit or delete API backlog item getting this:

![](https://cloud.githubusercontent.com/assets/2034879/15279584/c6037ab6-1ada-11e6-95b2-9aa7bdd37aff.png)

![](https://cloud.githubusercontent.com/assets/2034879/15279589/d3ec100c-1ada-11e6-8784-874b885f2a22.png)

**Comment by bajiat** [comment]
@nnn Did 1464 fix this issue?
