### ISSUE TITLE
Make logo appear in API profile and catalog pages s.t. the logo retains its original shape

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1316]
Right now logo of any shape uploaded appears as circle in API profile and catalog pages. Uploaded logo should retain its original shape in the place holder.

# Definition of Done
* [ ] Original shape (square, rectanlge, triangle, circular) of the logo is retained within the place holder.
* [ ] Logo is clearly identified within placeholder irrespective of the shape.
* [ ] Logo images bigger than placeholder is rendered to retain its original shape.

**Comment by nnn** [comment]
Already implemented in develop.
