### ISSUE TITLE
Swagger UI-viewer handled over http

### ISSUE THREAD

**Issue by philippeluickx** [apinf/api-umbrella-dashboard#1369]
UI viewer is done through calling a http URL and gives this warning:

Mixed Content: The page at 'https://nightly2.apinf.io/api/pGZPrqpS4i3jduC2C' was loaded over HTTPS, but requested an insecure image 'http://online.swagger.io/validator?url=https://nightly2.apinf.io/gridfs/fs/id/88d7b90bb0547157b848752f'. This content should also be served over HTTPS.

**Comment by shaliko** [comment]
@bajiat Should be fixed by update swagger-ui.js https://github.com/apinf/api-umbrella-dashboard/issues/1371#issuecomment-239176879
