### ISSUE TITLE
Clicking on VALID button in swagger UI-viewer makes page blank

### ISSUE THREAD

**Issue by philippeluickx** [apinf/api-umbrella-dashboard#1371]
![image](https://cloud.githubusercontent.com/assets/836866/17508744/24299378-5e1f-11e6-92f7-fa9b9969e120.png)

When you click on the lower right button, the Swagger UI-viewer section becomes completely blank. Only page refresh gets docs back.

**Comment by bajiat** [comment]
@shaliko Here is one of the cases where we run into trouble with http. If I press "Valid" in Swagger UI in nightly2, I get a blank page (as described above) and the following error in console:

Mixed Content: The page at ... was loaded over HTTPS, but requested an insecure resource 'http://online.swagger.io/validator/debug?url=https://nightly2.apinf.io/gridfs/fs/id/0ea6886fd4a9dfbbc2a6b163'. This request has been blocked; the content must be served over HTTPS.

Is there a possibility to fix this on server side for Swagger validator? (See also #1369 for Swagger viewer itself)

**Comment by shaliko** [comment]
@bajiat The issue in swagger-ui.js file https://nightly2.apinf.io/swagger/swagger-ui.js.

```
      // Default validator
      if(window.location.protocol === 'https') {
        this.model.validatorUrl = 'https://online.swagger.io/validator';
      }
      else {
        this.model.validatorUrl = 'http://online.swagger.io/validator';
      }
```

window.location.protocol will return "https:" instead of "https". https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/protocol

As I can see swagger-ui have that issue in version version v2.1.0, that currently on nightly2.apinf.io. And we already updated swagger-ui in main repo of https://raw.githubusercontent.com/apinf/api-umbrella-dashboard/develop/public/swagger/swagger-ui.js on version v2.1.5 that dose not have that issue.

**Comment by shaliko** [comment]
@bajiat Please create new release with that commit https://github.com/apinf/api-umbrella-dashboard/commit/580df6599b9ef94f1a42c0770991d66ac1924afc and I will create new docker image for nightly2.

**Comment by bajiat** [comment]
@shaliko we will create a new release on Tuesday, we will ping you then

**Comment by shaliko** [comment]
@bajiat How should works "Clicking on VALID button"? Now after fix issue with mixed content and click on VALID button, browser open tab and show me just empty JSON response

![https___online_swagger_io_validator_debug_url_https___nightly2_apinf_io_gridfs_documentationfiles_id_ffd6e2260163999d5f5f45a6](https://cloud.githubusercontent.com/assets/36139/17703403/409b9342-63da-11e6-819d-ba29e3b3235c.jpg)

**Comment by bajiat** [comment]
@shaliko Tested this by adding a new Swagger and I get the same response. Should be ok. Closing the issue.
