### ISSUE TITLE
Integrate SDK download to Documentation tab

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1376]
Integrate the SDK generator UI created in #1225 into the Documentation tab as a section of its own, thus allowing API consumers to download an SDK in the selected programming language, if a valid Swagger file has been updated for an API

# Definition of done
* [ ] SDK UI is only available in Documentation tab, if a valid Swagger file has been uploaded for an API. 
* [ ] The SDK UI passes the Swagger file to the Codegen API without the user having to select the file (In other words, the particular Swagger file on this tab gets passed to the Codegen API)

# Wireframe

![sdkgenerator](https://cloud.githubusercontent.com/assets/17976243/17765626/a7d5fc4a-652f-11e6-9e02-b2ef9a156e0b.png)
![documentationpage2](https://cloud.githubusercontent.com/assets/17976243/17765638/badea5d0-652f-11e6-9743-b69846e71df9.png)

**Comment by Nazarah** [comment]
Wireframes Added

**Comment by Nazarah** [comment]
On hovering the SDK Generator button, tooltip should show the following message:
"With a valid swagger file, you can download an SDK of your preferred language using this wizard."
alternatively, this can be shown inside the dialogue with an info icon

**Comment by shaliko** [comment]
@bajiat "if a valid Swagger file has been updated for an API" can you clarify that part of task.

1) Should we show "SDK generator" button ONLY if file was uploaded.
2) Or we need send uploaded file to "https://online.swagger.io/validator/debug?url=https://nightly2.apinf.io/gridfs/DocumentationFiles/...." and allow generate SDK only if file valid.

It looks like we need go with option #1, but add validation on upload swagger file, currently we just check extensions (.json, .yml, etc).

**Comment by marla-singer** [comment]
@bajiat The task is almost ready, I have some questions:

1. **Localization**: Now form **Generate SDK form JSON file** has few english phrases like title of buttons, title of form and message of tooltip. Can you write translate to Finnish language for this:

- "With a valid swagger file, you can download an SDK of your preferred language using this wizard"
- "Select language"
- "Download"
- "Generate SDK file"
- "SDK Generator"

**Comment by marla-singer** [comment]
@bajiat 
2. **List of languages.** Swagger editor has two section: Generate Server and Generate Client. I took languages form Generate Сlient. I think it doesn't need server languages, right?

**Comment by brylie** [comment]
It seems like Generate Client is our current focus. We can look at Generate Server as a separate task.

**Comment by bajiat** [comment]
@shaliko Option 1: if a Swagger file was uploaded

@marla-singer 
* You do not need the Finnish translations for UI texts. Instead you should use an i18n token for each UI text in your code, which makes it possible for us to extract all UI texts to a localisation environment.
* Confirming what @brylie said: Generate Client is the correct one, since the SDK generator task is about creating SDK's for developers using APIs (i.e. API consumers) and not for API developers.

**Comment by brylie** [comment]
The i18n token should take the form of:

```js
{{_ "templateName_elementName" }}
```
