### ISSUE TITLE
Design Proxies collection and schema

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1378]
Create a collection that will store configuration details like base URL for API proxies, for example API Umbrella. This is distinct the from the Proxy Backends collections which contains settings for a specific API backend (e.g. rate limiting).

# Definition of done
* [ ] Proxies component exists
* [ ] Proxies component follows folder structure of other components
* [ ] Proxies collection exists
* [ ] Proxies schema exists
  * [ ] Schema contains field contains fields to distinguish proxies (name)
  * [ ] Schema contains Api Umbrella configuration fields
  * [ ] Schema contains Type field with one allowed value (Api Umbrella for the time being)
  * [ ] Schema has conditional validation when type field is Api Umbrella

**Comment by frenchbread** [comment]
@brylie Could you post the initial Proxies schema?

**Comment by bajiat** [comment]
@frenchbread 

# Proxies
- _id
- name
- description ?
- type (allowed values: 'api-umbrella', 'kong', 'tyk')
- settings
  - url
  - apiKey
  - authToken
    - custom validation: required if `type` === 'api-umbrella'
  - elastic
    - custom validation: required if `type` === 'api-umbrella'
