### ISSUE TITLE
Update Add API wizard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1379]
Update Add API wizard to add an API without proxy settings. (Proxy should be added - or in the future selected - in separate UI.) This UI will add an API with basic details to Catalog.

# Definition of done
* [x] User can enter all details related purely to  API backend such as name, description, base URL with Add API wizard 
  * [x] Add API wizard does not contain any details or settings related to proxy or selecting proxy
* [x] When user presses Publish API backend, the API will be added to API backends collection
  * [x] User get redirected to single API view for the newly created API

**Comment by Nazarah** [comment]
@bajiat : need wireframe for this?

**Comment by jykae** [comment]
Discussed with @brylie about deprecating wizard and using simple form approach.

Base for the form will be new API Backend schema.
Fields for API backend schema:
- name
- description
- base URL for API
- isPublic checkbox

**Comment by brylie** [comment]
We decided to deprecate the Add API Wizard, since we are simplifying the basic API fields.

@jykae would you be interested in improving the Add API form after we have merged these initial changes?
