### ISSUE TITLE
Update single API view / proxy settings

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1380]
Add either a Proxy tab or a partial view in Settings tab to add a proxy to an API backend.
The page should have a possibility to select an existing API proxy and define the backend configuration. The essential settings should be prominently available. Use the opportunity to explain frontend and backend prefix in a more user friendly manner, possibly selecting new terminology.
The tab/view should be only available if platform administrator has created a proxy.

# Definition of done
* [ ] Proxy tab or partial view for selecting proxy exists
* [ ] User can select an existing proxy
  * [ ] After selecting the proxy, user is required to fill in the mandatory backend configuration details
  * [ ] Ensure inline help text clarifies the meaning of each field
  * [ ] Optionally, come up with easier terms for frontend and backend prefix
* [ ] When the settings are saved, a relational link is made between API backend document and Proxy API backend document

# Wireframe

![apiproxysetting](https://cloud.githubusercontent.com/assets/17976243/17807402/f1636242-6612-11e6-8898-641948c9003a.png)

**Comment by Nazarah** [comment]
Wireframes are part of issue #1383

**Comment by bajiat** [comment]
@Nazarah The wireframe above is for Proxy settings (= setting for entire platform). You will need to create a wireframe for proxy backend settings for API profile view. It is possible that this task will be combined with #1233. Note that you should start with he mandatory settings only.

**Comment by bajiat** [comment]
Combining the UI work with #1233 and closing this issue.
