### ISSUE TITLE
Update dashboard analytics URL and user notifications

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1382]
Update dashboard so that it gets the proxy analytics URL (e.g. ElasticSearch) from Proxies collection.
Ensure also that administrators can see all analytics, if possible also to filter API Umbrella Admin API. Other than that keep the current functionality, changing only the analytics URL.

 Also, make sure that users get a notification, if there are no analytics
* regular user: keep current notification about adding an API to see analytics
* API owner: if user has added and API and become an owner, but has not selected a proxy for any of the APIs, use a notification to say that API needs to be connected to a Proxy for the analytics to be available (with a link?)
 * Open issue: What if user is an owner of several APIs and only some of them are connected to a proxy? Proposal: The list of APIs in dashboard only shows the APIs that are connected to a proxy

Note the related task #1394 (If no proxy has been added, dashboard should not be available to users.)

# Definition of done
* [x] Dashboard gets proxy analytics URL from Proxies collection
* [x] If there are no analytics to show, user is notified about the reason (see above)

# Wireframe

![dashboarnodata](https://cloud.githubusercontent.com/assets/17976243/18127547/bf15bba2-6f89-11e6-80e0-33effa4c6279.png)

**Comment by frenchbread** [comment]
Interested

**Comment by frenchbread** [comment]
When there is no data found, message is shown to the user:

Looks like: 

![screen shot 2016-08-30 at 13 36 15](https://cloud.githubusercontent.com/assets/2122679/18086155/27d749c2-6eb7-11e6-9010-c5d93483d7ad.png)

**Comment by Nazarah** [comment]
as per the discussion with @frenchbread, when the charts and table have no data to show, they will be faded in the background. 
A single notification message will appear in the foreground:
"No Data is found. Please try changing the filter options to populate analytics data."
