### ISSUE TITLE
UI for adding or editing API proxy

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1383]
For the Settings view, add a form for adding and editing proxy. (In first phase, only API Umbrella) . The code should be reusable for the Settings wizard, if possible.

# Definition of done
* [ ] Settings page contains form for adding and editing proxy
* [ ] The form is autopopulated from the Proxies schema
* [ ] The form contains show/hide fields based on proxy type

# Wireframe

![apiproxysetting](https://cloud.githubusercontent.com/assets/17976243/17807129/612a8530-6611-11e6-9b48-40a41550497f.png)

![apiproxysetting2](https://cloud.githubusercontent.com/assets/17976243/17807130/612b9024-6611-11e6-8c4f-89f12179659f.png)

**Comment by Nazarah** [comment]
Need to learn what is already included before I start wireframing this.

**Comment by frenchbread** [comment]
@Nazarah we had an idea to place the `add proxy` modal window on the `/settings` page.

**Comment by Nazarah** [comment]
Wireframes added. 
Added a message notifying users about the consequence of adding/not adding an API proxy.
Please review and give feedback

**Comment by bajiat** [comment]
@Nazarah The message is a good idea, but since it is administrators who adds the proxy settings to the platform (while API owners only select a proxy for their own API in API profile), I would like to suggest some changes to the wording:
"With no proxy defined, you will only have access to the Catalog feature. Defining a proxy will give you access to proxy features for APIs and to Analytics."

**Comment by bajiat** [comment]
Closed by PR #1399
