### ISSUE TITLE
Get API key button to API profile page

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1384]
Create a collection and schema for API key.
Add get API key button and copy API key buttons to API profile. See the conditions in Definition of done for what should be available in which situation.
After a proxy has been configured, display Get API key button on API profile (once / for APIs that are connected to a proxy) for any user for without an API key. 

Definition of done
* [x] Collection and schema
  * [x] API key collection exists
  * [x] API key schema exists
  * [x] Remove API key from user.profile schema
* [x] UI
  * [x] Remove API key from user profile template
  * [x] Get API key should have a prominent location (i.e. should not hidden in one of the tabs)
  * [ ] Get API key is only available if a proxy has been defined/added for a platform.
  * [x] When user presses the Get API key, it is stored in (collection to be added)
  * [x] Once Get API key has been pressed (for that proxy) in any API, all API profile pages for APIs connected to that proxy should 
    * [x] display the API key and a Copy button
    * [x] should not contain Get API key button again

Open issue: what should happen if API proxy is changed for the platform?

# Wireframes

1. When the API is connected to a proxy, API users can see "Get API Key" button in the API profile page.
![apikey1](https://cloud.githubusercontent.com/assets/17976243/18146118/bbe449c4-6fd6-11e6-9823-9d687bdd3828.png)

2. When API users presses Get API Key button, the API key appears in a non-editable text field with Copy API Key button. Clicking on the button copies the generated key.
![apikey2](https://cloud.githubusercontent.com/assets/17976243/18146129/c7e20734-6fd6-11e6-8e26-47fd02b8279f.png)

3. When API owner has not attached the API to any proxy, a pane appears in the details tab of API Profile. It contains an informative message and a link to page for connecting the API to a proxy.
![apikey4](https://cloud.githubusercontent.com/assets/17976243/18146162/e9b38dba-6fd6-11e6-9d4c-cf72e24be128.png)

**Comment by Nazarah** [comment]
@jykae added the wireframes for the discussed for issues. Please review them with @bajiat .
Will add the fifth scenario, (consumer POV, when s/he sees no Get API Key) later.

**Comment by jykae** [comment]
@Nazarah Where I can find the wireframes?

**Comment by Nazarah** [comment]
@jykae : for some reasons, the pictures didn't get attached in the 1st place. Now they are available with this issue. Sorry for the inconvenience.

**Comment by Nazarah** [comment]
Added the 5th scenario.

**Comment by bajiat** [comment]
Scenarios 3 and 4 are describing the same thing in my opinion. API owner has not selected a proxy for his/her API / attached his/her API to a proxy. I prefer the 4th wireframe.
Scenario 5 should not be implemented: owner can add an API and just want it to appear in catalog. If I'm wrong about this, it would be implemented as an enhancement.

**Comment by Nazarah** [comment]
Changed Wireframe descriptions.

Scenario 3:
Pane title: Connect API to a Proxy.
Message: The API is not connected to a proxy. To enable API Keys for API users and to get API Management features, click here to connect to a proxy.

(click here is clickable link)

**Comment by bajiat** [comment]
Created an enhancement task #1483. This task will add the Get API keys and Copy API key buttons for all API profiles, while the enhancement task will limit the button only to APIs that have been connected to the available proxy. (At this stage only one proxy.)
