### ISSUE TITLE
Wireframe for Separating API details editing from editing proxy settings

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1390]
#1207

**Comment by brylie** [comment]
@Nazarah here are the API Umbrella proxy settings, which we are removing for the time being and will add them back under the Proxy tab of the Single API view:

![screen shot 2016-08-18 at 12 53 08](https://cloud.githubusercontent.com/assets/17307/17769785/0686ab46-6543-11e6-8a21-6bc328d7edc5.png)
