### ISSUE TITLE
wireframe for Updating single API view / proxy settings

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1391]
#1380

**Comment by philippeluickx** [comment]
Based on a discussion we just had with @brylie and @frenchbread 
When selecting a proxy in the wizard, we need to inform the user of the impact of the choice.
E.g. if selecting "None" (so no proxy), there will be only catalog functionality, not analytics, security,...
If selecting "API Umbrella" we have more functionality.
If selecting "Tyk" it might be something else again.

Obviously we do not have enough information now, as we only know functionality from API Umbrella. But user can at least already choose between API Umbrella and no-proxy.

**Comment by brylie** [comment]
One clarification, we are removing the Proxy settings from the *Add API* form. This wireframe task is related to the 'Proxy' tab on the *Single API* view.

**Comment by brylie** [comment]
Here is the current Proxy Settings modal and page, for reference:

![screen shot 2016-08-18 at 13 01 10](https://cloud.githubusercontent.com/assets/17307/17769959/ebcffff4-6543-11e6-8517-8048289a2aad.png)


![screen shot 2016-08-18 at 13 00 04](https://cloud.githubusercontent.com/assets/17307/17769932/cfa814f6-6543-11e6-9109-301d6e9a4d62.png)

**Comment by Nazarah** [comment]
added as part of the task #1391

**Comment by Nazarah** [comment]
added as part of the task #1393
