### ISSUE TITLE
If no proxy selected for platform, dashboard should not be available

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1394]
If the admin does not add/define any proxy to the platform, the link to the dashboard should not be available as it would be confusing to the users, since it is not possible to have meaningful content in dashboard without the proxy. So the entire page (route) and link should be made conditionally available.

# Definition of done
* [x] User can see link to dashboard only if there is at least one proxy defined for database
* [x] User can access dashboard route/page only  if there is at least one proxy defined for database
* [x] User sees the catalog as their default page when they sign into platform, if there is no proxy defined for platform

**Comment by bajiat** [comment]
@frenchbread Did you already work on this? Do we need any further work on the issue?

**Comment by frenchbread** [comment]
@bajiat No, I did not. I think in this task it could be either placeholder on dashboard page, saying 'no source analytics found' or just redirect to catalog page (or settings page)

**Comment by frenchbread** [comment]
Interested
