### ISSUE TITLE
Manual testing: single API backend view

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1396]
Continue explorative manual testing particularly for the single API view. Document the test cases, if not already documented. (Update if necessary.) Report any findings as issues giving steps to reproduce, expected outcome and actual outcome and stating the testing environment like OS, browser and the browser version.

# Definition of done
* [x] Bookmark an API from single API view
* [x] Add and API and make API key optional from the API settings.
  * [x] Test that you are still able to make a call through proxy (without using your API key)
* [x] Add a logo for an API
  * [x] Check that the logo is available both in single API view and in catalog
* [x] Add an API and make it private from the single API view
  * [x] Test that you as the owner can still view it in the catalog
  * [x] Log in as another user and check that you cannot see the hidden/private API

If possible, check also Catalog pagination.

**Comment by saralavanip** [comment]
Reported and updated issues: 
https://github.com/apinf/api-umbrella-dashboard/issues/1428  
https://github.com/apinf/api-umbrella-dashboard/issues/622
