### ISSUE TITLE
Replace all bar chart to line chart

### ISSUE THREAD

**Issue by marla-singer** [apinf/api-umbrella-dashboard#14]
Replace all bar chart to line chart
- Request over time
- Average response time

**Comment by brylie** [comment]
Based on a discussion with @preriasusi, I was reminded that line chart might be confusing. 

The line chart takes at least two values, and interpolates a line between them. When the line chart has only one value, it cannot draw a line. The line drawn between two points implies that the values are present between the two points. 

We need to consider how to show the user when **zero values** are present, such as using a **bar chart** which **naturally handles binned data**.

**Comment by marla-singer** [comment]
@brylie I have wireframe with line chart. Open the following issue in the main repo

**Comment by brylie** [comment]
@marla-singer we need to look a bit deeper into this dashboard project than the wireframes.

**Comment by brylie** [comment]
The following information might help us better compare bar and line charts, to make an informed decision here.

> Line graphs are useful for encoding values along an interval scale, but there are occasions when it is preferable to use a bar graph to display such measures. For example, when we wish to enable close comparisons of values that are located next to one another, a bar graph is a better choice. ... [A] bar graph emphasizes the individual values in each interval and makes it easy to compare those values to one another whereas the line graph does a much better job of revealing the overall shape of the distribution.
>
> Few, Stephen. *Information Dashboard Design*. Burlingame, CA: Analytics Press, 2013. Print.
