### ISSUE TITLE
Test database migration with percolate:migrations

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1406]
Test the percolate:migrations npm package by migrating Apinf database to add the isPublic field to all the documents where it does not exists with default value true.

# Definition of done
* [x] Migration code exists.
* [x] Migration package has been added to project.
* [x] Migration has been tested locally.
* [ ] Migration has been tested with nightly or nightly2 (This step will be discussed after testing locally.)

**Comment by jykae** [comment]
Migration code for percolate:migration, https://github.com/apinf/api-umbrella-dashboard/pull/1411
Adds & sets field "isPublic" to true for all apiBackends  where it is undefined.

**Comment by jykae** [comment]
@bajiat I propose we close this + PR as it's basically going to change place anyway schemas change. It's was just showcase with simple example.

**Comment by bajiat** [comment]
Ok to close.
