### ISSUE TITLE
Click on 'Copy API Key' in 'Profile' view displays successful dialog twice

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1428]
Steps:  

1.Visit https://nightly2.apinf.io  
2.Sign in as API owner  
3.Go to Profile view  
4.Click on 'Copy API Key' button  

Expected Result: API Key is copied to clipboard and displays a successful dialog   
Actual Result: Successful in copying API key to clipboard and displays successful dialog twice   

Operating system: Ubuntu 16.04 LTS 
Browser: Mozilla Firefox 48.0  

Screenshot:  
![copy_api_key_succesful_dialogs](https://cloud.githubusercontent.com/assets/13309358/17845518/2c377018-684b-11e6-97a1-1a2418caac46.png)

**Comment by jykae** [comment]
API key functionality is moving to single API view, checking this while working on it.
