### ISSUE TITLE
Add a setting for SDK generator

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1433]
Add a setting for SDK generator in platform settings (Settings view, settings collection).

# User story
> As an Apinf administrator I want to be able to add a Codegen instance location to Apinf
so that I can allow API consumers to download SDK's 
whenever APIs added to Apinf have a Swagger file.

# Definition of done
* [ ] Settings collection contains a setting for SDK generator.
* [ ] Settings view contains a setting for SDK generator.
* [ ] An Apinf administrator can give the location of the SDK generator (= Codegen).
* [ ] The SDK generator UI in Documentation tab passes the Swagger to the Codegen instance defined in Settings.
* [ ]  SDK generator is available in Documentation tab only if there is a setting for SDK generator

**Comment by bajiat** [comment]
@marla-singer @shaliko Here is the next task for Dasha. I will still check the Definition of done and description with @brylie.

**Comment by shaliko** [comment]
@bajiat Thanks!

**Comment by marla-singer** [comment]
@bajiat 
1) How can give the location of the SDK generator: Apinf Administrator (global admin, who has auth token) or API owner (user, who add this API)? 
2) Which page have to contains a setting for SDK? 
**API settings page**
![joxi_screenshot_1472213462998](https://cloud.githubusercontent.com/assets/20643403/18005022/111f3cf4-6ba0-11e6-9dfa-e382c844bb03.png)

**Edit API page**
![joxi_screenshot_1472213574731](https://cloud.githubusercontent.com/assets/20643403/18005035/21772184-6ba0-11e6-8ea7-ef52bcd39db2.png)

**Comment by bajiat** [comment]
@marla-singer: SDK generator setting is not a setting for an individual API but for the entire platform/deployment.

So it should not be in API settings tab, but in the platform Settings. You can find the Settings UI by pressing the small triangle next to your user name.  Implement it similarly to the other settings: it needs to be enabled and once enabled you can give the host.

Only admins should be able enable SDK generator and give the host.

**Comment by marla-singer** [comment]
@bajiat I found the platform Settings. This feature should looks like "API Documentation Editor", right?
Click to checkbox "Enabled" -> Show input with label "Host"
