### ISSUE TITLE
Refactor project files for consistency

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1444]
Audit all project router.js files so they follow the same pattern:

- each router file is located in a component
- each component router file contains routes only for the component
- component router files are in the `/component/client/lib/router.js` file
- router onBefore or other hooks are either in core, or in the specific router file where they are used

Additionally, refactor the `Settings` component into several separate components. Based on discussion with @brylie and @frenchbread.

**Comment by brylie** [comment]
@jykae thanks for going beyond the definition of done here. As per our discussion, and approval from @bajiat, please refactor the `settings` component into separate components, with the following structure:

 - /branding
  - /logo
- /settings
  - /client
    - /menu
- /proxies
- /users
  - /account
  - /profile

@frenchbread and @nnn, please be aware that @jykae will be moving these files around, so that you have as few conflicts as possible.

**Comment by brylie** [comment]
Also note, this should not affect the user interface. It is just a code-level refactor. We want to keep the great work on the settings page, including the navigation menu.

**Comment by jykae** [comment]
@brylie Ok, did not notice to check out this issue, was following PR. I make further changes based on your comments & our discussion.
