### ISSUE TITLE
Clarify project terminology 'module' and 'component'

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1469]
We are modularizing our code. In the spirit of other projects, our terminology should align with common use. To that end, we can adopt the term 'module' to mean 'high level project feature' (i.e. epic level feature) and 'component' to mean something similar to a UI/WebComponent.

Update the CONTRIBUTING.md to include these clarifications.

**Comment by bajiat** [comment]
@brylie I agree with this change. Modules could be potentially something administrators could select to include or exclude in deployment / setup.
