### ISSUE TITLE
Username is not shown header dropdown menu on the "home" page

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#1471]
Observed:
- No username is shown

Expected:
- Username of current user is show

![screen shot 2016-08-31 at 12 14 19](https://cloud.githubusercontent.com/assets/2122679/18122974/7b338bae-6f74-11e6-98ca-3a1248d11ae3.png)

**Comment by saralavanip** [comment]
Verified this resolved issue in local develop environment.
