### ISSUE TITLE
Missing text letters in 'Search results' view 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#1473]
Steps:  
1.Visit https://nightly2.apinf.io    
2.Click on API Catalog   
3.Click on Search icon    
4.Enter search text (eg.maps)  
5.Click on 'Search'   

Findings: Missing text letters in user help text and Header text (letter 'S' in words 'Start' and 'Search')

Expected Result: Text should be shown completely without any missing letters  

Operating system: Ubuntu 16.0 LTS    
Browsers:     
1. Mozilla Firefox 48.0   
(Mozilla Firefox for Ubuntu Canonical – 1.0 )     
2. Google Chrome 52.0.2743.116    

Screenshots:      

Mozilla Firefox:
![search_result_view_missingtext_firefox](https://cloud.githubusercontent.com/assets/13309358/18126633/c0f64ffe-6f84-11e6-803e-9c8786e75eba.png)    

Google Chrome:   
![search_result_view_chrome](https://cloud.githubusercontent.com/assets/13309358/18126922/18176272-6f86-11e6-8337-91304881ca6e.png)

**Comment by brylie** [comment]
@saralavanip please provide a screenshot of your entire screen. This may be an issue where your browser windows are being covered up by the Ubuntu menu.

**Comment by brylie** [comment]
Also, try taking the window out of full-size mode by clicking the middle icon in the upper left hand corner. This should make the window smaller, so that it does not appear near the Ubuntu application menu.

**Comment by saralavanip** [comment]
@brylie , please find the screenshots below: Entire screens: both min and maximized window in chrome and Firefox browsers. 

Screenshots:  
Firefox: 
![minimised_screen_firefox](https://cloud.githubusercontent.com/assets/13309358/18308435/402da420-74fd-11e6-8bd4-26bcff3b0040.png)  

![max_screen_firefox](https://cloud.githubusercontent.com/assets/13309358/18308456/4dc2f770-74fd-11e6-919e-be2dd9246140.png)  

Chrome:  
![minimised_screen_chrome](https://cloud.githubusercontent.com/assets/13309358/18308479/5f1df27c-74fd-11e6-8593-206afe346fd0.png)  

![max_screen_chrome](https://cloud.githubusercontent.com/assets/13309358/18308485/65738196-74fd-11e6-9860-ca48ad87c580.png)

**Comment by brylie** [comment]
OK, it looks like this issue will be resolved with an open PR.

**Comment by saralavanip** [comment]
Verified this resolved issue on local develop environment.
