### ISSUE TITLE
Implement Swagger viewer as npm module

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1476]
Swagger Viewer is currently displayed in iFrame. The solution is very brittle and for example inserting base URL and user's API for making calls through apinf would require a hacky implementation.

The iFrame solution should be replaced by implementing Swagger viewer as npm module.

# Definition of done
* [ ] Suitable, actively maintained npm package for Swagger UI has been selected
* [ ] Package has been integrated into Apinf
* [ ] Swagger viewer module is displayed in the same place as the current iFrame solution
* [ ] Swagger viewer is only displayed in documentation tab, if a Swagger file has been uploaded for that particular API
* [ ] Swagger viewer displays the Swagger file that has been uploaded for the particular API

# Candidate npm packages
- [swagger-ui](https://www.npmjs.com/package/swagger-ui)
- [swagger-ui-lite](https://www.npmjs.com/package/swagger-ui-lite)
- [Swagger UI Browserify](https://www.npmjs.com/package/swagger-ui-browserify)
- [Swagger UI Headless](https://www.npmjs.com/package/swagger-ui-headless)

## Example of integrating Swagger UI into templating languages
- [Ember Swagger UI](https://www.npmjs.com/package/ember-swagger-ui)

**Comment by bajiat** [comment]
@brylie Add links to potential npm packages

**Comment by brylie** [comment]
@bajiat @marla-singer Please see the **Candidate npm packages** section in the issue description.

@marla-singer feel free to do any research and offer alternative proposals to how we can integrate Swagger UI into our templates without using iframe.

**Comment by bajiat** [comment]
@brylie Thanks!

**Comment by marla-singer** [comment]
@brylie Thank you! Has this task any deadline?

**Comment by bajiat** [comment]
@marla-singer Can you give us your estimate on how long it would take? How many days?

**Comment by marla-singer** [comment]
@bajiat Today I'm going to study the task more detail and I'll be able give my estimate tomorrow.

**Comment by bajiat** [comment]
@marla-singer Sounds good to me.

**Comment by bajiat** [comment]
@marla-singer I removed part of the definition of done. (I thought I had removed it before, but that change didn't actually get updated to Github). The removed part will be in another continuation task. Without removing, your task would be partially blocked by another developer's task. Also, it is best to approach this incrementally.

**Comment by marla-singer** [comment]
@bajiat Yesterday and today I learnt npm packages and tryed to implement swagger-ui packages in empty meteor project. So I think it needs about 2 days to integrate and setting swagger library to our project plus a day for test and review. My estimate is three days.

**Comment by bajiat** [comment]
@marla-singer Thanks for the estimate! What is the current status of the task?

**Comment by marla-singer** [comment]
@bajiat Current status is setting of css and fix to show button 'Authorize'

**Comment by preriasusi** [comment]
#1490 @marla-singer Is it possible to control Swagger UI launch settings while starting?

**Comment by brylie** [comment]
@preriasusi we can invoke Swagger UI with [several parameters](https://github.com/swagger-api/swagger-ui#parametershttps://github.com/swagger-api/swagger-ui#parameters).  Which settings do we need to control?

**Comment by marla-singer** [comment]
@preriasusi Yea, I think it's possible.

**Comment by brylie** [comment]
For clarification, this task takes us in the direction of being able to use Swagger UI parameters, rather than the iframe, by using an npm module. 

We can follow-up with enhancements based on the [Swagger UI configuration parameters](https://github.com/swagger-api/swagger-ui#parameters), etc.
