### ISSUE TITLE
Access denied when saving API Proxy

### ISSUE THREAD

**Issue by nnn** [apinf/api-umbrella-dashboard#1520]
When trying to edit API Proxy

Steps:
1. Add new API
2. Go to Proxy tab
3. Fill the form
4. Save

 Getting this:

![error](https://cloud.githubusercontent.com/assets/7489044/18378514/20b77e16-7676-11e6-9bbc-089a2f89a12f.png)

**Comment by bajiat** [comment]
@brylie Was this resolved already?

**Comment by brylie** [comment]
@nnn pull changes from `develop`.

**Comment by brylie** [comment]
@bajiat we fixed this issue as part of @jykae's PR #1458

**Comment by bajiat** [comment]
Closing this. @nnn If you still have this issue after pulling from develop, pls reopen.
