### ISSUE TITLE
Design initial APIs for APInf

### ISSUE THREAD

**Issue by ccsr** [apinf/api-umbrella-dashboard#159]
We need to add the APIs for APInf service to give some status update. Chandra suggested 2 API endpoints:
1. Just returns if the service is running or not
2. Gives the status of the service concerned to user

Defintion of done
---
* [x] Determine possible API structure.
* [x] Determine API endpoints useful for MVP.
* [x] Determine how to implement REST APIs in Meteor.
* [ ] Implement an example REST endpoint in Apinf.
* [x] Create basic design file (Swagger, RAML or similar) for the Apinf API.

**Comment by brylie** [comment]
We can implement REST endpoints, in Meteor, using the [Restivus package](https://github.com/kahmali/meteor-restivus/).
