### ISSUE TITLE
Specify recruitment needs

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#16]
Identify technologies to be used and gaps in skills/resources. Make a suggestio to management regarding resource allocation.

**Comment by bajiat** [comment]
We organised a meeting on the recruitment needs for the project 21 April.
 Meeting minutes can be found from here https://apinf.hackpad.com/2015-04-21-Needs-assessment-meeting-minutes-6XTZXzoVcKt (The minutes include specs for a developer who should be recruited for the summer period).
