### ISSUE TITLE
Automatically generate labels (for dates, etc) on dashboard charts

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#162]
Dashboard charts currently are hard-wired with labels. Determine how to auto-generate chart labels to make our code more reusable.

Definition of done
---
* [x] Remove hard coded labels from chart
* [x] Choose how to allow dynamic labels in analytics charts
* [x] Refactor chart logic to allow dynamic labels

**Comment by brylie** [comment]
@frenchbread please link to your pull request in this issue.

**Comment by frenchbread** [comment]
Here is a pull request #198 for that issue.
