### ISSUE TITLE
Make dashboard chart functions more object oriented

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#165]
The chart data function is currently rather long and procedural. Consider how to make the code more re-usable, for example by creating a ChartData class with several methods/parameters.

Definition of done
---
* [x] Create chart class  for reuse throughout the system
* [x] Refactor chart logic to accept parameters for filtering data.
* [x] Remove hard coded analytics query.
* [x] Add [documentation comments](http://usejsdoc.org/about-getting-started.html#adding-documentation-comments-to-your-code) to your code

**Comment by frenchbread** [comment]
I've created a class for elastic search called ```es``` with two methods: 
1. ```doSearch``` - that basically returns the total search result
2. ```getMonthAnalytics``` - returns an array of values that are later used within chart on a dashboard.

The task is still in progress but this far, @apinf/developers, please review this OOP approach, probably suggest something, so I could move further with it. Here is the [code comparison](https://github.com/apinf/api-umbrella-dashboard/compare/develop...feature/chart-code-refactoring?expand=1)

**Comment by brylie** [comment]
So, it looks like you have the following structure:

* es - top-level object
  * doSearch -- REST query
  * getMonthAnalytics -- parse the result and return an array of values

The getMonthAnalytics may still be doing more than one thing, i.e. it is parsing all results and creating an array based on an input.

What are your function arguments? What other verbs will your object know how to do (e.g. parse, filter, ...)?

**Comment by brylie** [comment]
Addy Osmani wrote an article called [Patterns For Large-Scale JavaScript Application Architecture](http://addyosmani.com/largescalejavascript/). Of particular relevance to this task, is the article section [The Module Pattern](http://addyosmani.com/largescalejavascript/#modpattern)

**Comment by brylie** [comment]
Ben Fry has outlined a general process for designing data visualizations, mentioned in [Dashing D3.js - The Data Visualization Process](https://www.dashingd3js.com/the-data-visualization-process) chapter. Your object may have similar verbs, such as `query`, `parse`, and `filter`.
