### ISSUE TITLE
Choose project versioning scheme

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#172]
Choose a scheme for project versions. Include alpha and beta releases in scheme.

Definition of done
---
* [x] Determine whether semantic versioning is suitable for this project.
* [x] Determine the version for the pre-release.
* [x] Choose how to indicate alpha, beta and release candidate in the release tag.
* [x] If it is, make a semantically versioned pre-release.
* [ ] Determine the difference between pre-releases and full releases in terms of branching.

**Comment by bajiat** [comment]
[Semantic versioning specification](http://semver.org/)

**Comment by brylie** [comment]
## Additional resources
### Meteor.js specific
* Meteor docs - [writing packages](http://docs.meteor.com/#/full/writingpackages) - "Meteor packages uses extended semver".
* Meteor docs - [package.js](http://docs.meteor.com/#/full/packagejs) - demonstrates semantic versioning in Meteor.js packages
* [Meteor packaging system: understanding versioning](https://meteorhacks.com/meteor-packaging-system-understanding-versioning) - describes using semver for meteor projects/packages
* [Meteor Cookbook: semver convention](https://books.google.fi/books?id=lOeuCQAAQBAJ&pg=PA54&lpg=PA54&dq=meteor+package+semantic+version+semver&source=bl&ots=NR0j2Lys7R&sig=_KDuK31xXUQj7bg15O0G_6-jVAE&hl=en&sa=X&ei=IV6SVYT2B8ehsgGAoIiACQ&ved=0CDoQ6AEwBA#v=onepage&q=meteor%20package%20semantic%20version%20semver&f=false)

### Node.js specific
* [semantic versioning and npm](https://docs.npmjs.com/getting-started/semantic-versioning)
* [NPM packages often use semver](https://www.npmjs.com/)

### General guidelines
* [Semantic Versioning: Why You Should Be Using it](http://www.sitepoint.com/semantic-versioning-why-you-should-using/)

**Comment by bajiat** [comment]
*	Determine whether semantic versioning is suitable for this project.
 o	Semantic versioning is the standard way.
o	Major.Minor.Patch
o	1.0.0-alpha – alpha and beta spelled out for clarity (Note: used for the quality)
o	Rc should also be used: 1.0.0-rc1
•	First release should be 0.1.0
•	For any milestone, we’ll need to make a stable release
•	At least one pre-release for every sprint
o	To be made on Mondays prior to new sprint planning
o	Rotating release task responsibility, working with project owner
•	Nightly builds made from development branch and not tight to official releases
•	0.1.0 to be made from master, requires pulling from the dev branch
•	Each time we release, need to decide whether it’s a minor version or a patch

**Comment by bajiat** [comment]
Made the [initial alpha](https://github.com/apinf/api-umbrella-dashboard/releases/tag/0.1.0-alpha) release!

**Comment by bajiat** [comment]
Task almost complete
- "Determine the difference between pre-releases and full releases in terms of branching" > to be defined after we get some more understanding.
- Need to document the versioning scheme in GitHub.

**Comment by bajiat** [comment]
Versioning scheme documented in docs/developers/release-versioning.md
