### ISSUE TITLE
Deploy the pre-release code to a sub-domain of apinf.com

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#174]
In order to allow users to test our pre-release code, deploy the latest pre-release to a sub-domain of apinf.com. This allows for instance demonstrating the product without needing to install it locally.

User story:
As a business/product owner or a product evangelist,  I want to easily demonstrate a relatively recent version of the product to potential customers and users.

Definition of done
---
* [x] Choose and create a subdomain for demonstration purposes.
* [x] Provision a virtual machine for deployment purposes.
* [x] Update subdomain.dns setting to point to virtual machine.
* [x] Configure "meteor up" for project deployment purposes.
* [x] Using "meteor up" deploy project release.
* [x] Create a testing user on the deployment.
* [x] Add demo details to project readme.

**Comment by brylie** [comment]
Please focus on setting up one VM for this task and manually deploying the `develop` branch to this VM from your local computer. While the Automated deployment is related, this task is asking for you to manually deploy for starters. This way, we have two things:
* a demonstration of the recent development work, for stakeholders to review
* experience manually deploying the app, so that we understand what to script in the automated deployment

**Comment by JuusoV** [comment]
While installing Meteor Up locally I ran into a problem where I couldn't initialize the project because I was using latest version of Node.  After research the fix was to use node-legacy (sudo apt-get install nodejs-legacy).

Currently waiting for the server to be deployed so I can finish up the set up and close the task.

A good tutorial worth checking out: https://www.youtube.com/watch?v=WLGdXtZMmiI

**Comment by JuusoV** [comment]
Pretty much done, need to do couple finishing touches to the server and configure it to use apinf.com as its query server.

Quick TODO list

*[] Create user in apinf.com for nightly site
*[] Configure nightly.apinf.com to use the user provided from apinf.com
*[] Reinforce the server security with firewall and fail2ban

**Comment by JuusoV** [comment]
Moved to done since we decided to use existing account.
