### ISSUE TITLE
Add bookmark API functionality  to API Catalog view

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#176]
Users need to be able to see both available APIs and the APIs they have subscribed to on the user dashboard. They also need to have method for subscribing to or bookmarking APIs.
User story: As Minh (API consumer), I want to find Apinf hosted APIs.

Definition of done
----------
* [x] Add API catalog to user dashboard view
* [x] Create button  for bookmarking  APIs.
  * [x] Create a [template](http://meteortips.com/first-meteor-tutorial/templates/) containing a 'bookmark' button ([bootstrap button](http://getbootstrap.com/css/#buttons))
  * [x] Create a [template event](https://www.meteor.com/tutorials/blaze/forms-and-events) to `console.log` on the button click
* [x] Add 'bookmark' button(s) to API Catalog table
  * [x] Create additional **column** in API Catalog **table** (tabular)
  * [x] Add the 'bookmark' template as a [template cell](https://github.com/aldeed/meteor-tabular#template-cells) in **each row** newly of created column
  * [x] Alert, or log, 'hello world' when 'boookmark' button is **clicked**
  * [x] Console.log document ID when 'bookmark' button is **clicked**
  * [x] Console.log user ID when 'bookmark' button is **clicked**
* [x] Associate users with API backends via a `foreign key relationship`
  * [x] Decide how to associate users with backends, via a relationship (foreign key) field
* [x] Display bookmarks list in HTML template
  * [x] Generate list of API bookmarks
  * [x] Show API ID for each bookmark in template
  * [x] Inside template helper, create array of API IDs (from bookmarks)
  * [x] Return API Backends query (using API IDs array)
* [x] Display API bookmark titles in template, {{#each apiBackends }}

**Comment by brylie** [comment]
There are two basic approaches to storing the bookmarks:
* bookmarkedApiIdsfield in user profile - containing an array of API IDs the user has bookmarked
* bookmarkedByIds field in ApiBackend collection - containing an array of User IDs who have bookmarked the API

**Comment by brylie** [comment]
@JuusoV, I have rewritten this task to include some specific, and sequential, steps you can take to make progress. I will also link to relevant documentation and sourcecode files ASAP.

**Comment by JuusoV** [comment]
Still needed to add some styles.
Thanks for help @brylie and @frenchbread

**Comment by JuusoV** [comment]
TODO: PR
