### ISSUE TITLE
Configure project SMTP

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#179]
Various actions, such as password reset, generate emails. Configure functional SMTP  server in our project deployment.

Related issue #174

Definition of done
---
* [x] Check for existing email configuration file in the project.
* [x] Choose mailing provider (e.g. SMTP).
* [x] Configure email settings in project based on the chosen provider.
* [x] Test configuration by sending email.
* [ ] Write automated test around email functionality.

**Comment by JuusoV** [comment]
Way to do with Meteor.js:
http://docs.meteor.com/#/full/email_send
https://gentlenode.com/journal/meteor-3-smtp-configuration/5

**Comment by brylie** [comment]
@elnzv, will you please offer your perspective on the Meteor Forums discussion "[Best Email API / Service to use with Meteor"](https://forums.meteor.com/t/best-email-api-service-to-use-with-meteor/3664/3)? Having your perspective, and possibly linking to our sourcecode as an example, would be helpful for the community.

**Comment by JuusoV** [comment]
Pretty much done. PR created.
Not sure about automated test, since we dont even have test environment running right now?
