### ISSUE TITLE
Define email as a mandatory field on user registration

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#180]
We are using email as a unique identifier for users. Ensure that all users of Apinf must register and validate their email at signup. This includes Github authentication.

Definition of done
---
* [x] Make sure email is a mandatory field in user profile schema.
* [x] Ensure that user email is collected when users authenticate by any method.
* [x] Send confirmation email to ensure accuracy of user emails.
* [x] To ensure the validity of email address.

**Comment by frenchbread** [comment]
Related branch - [`email-is-mandatory`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/email-is-mandatory)

**Comment by brylie** [comment]
E.g. when a user signs in, check if they have an email address stored in their profile. If no email address is available, prompt for email.

**Comment by frenchbread** [comment]
Useful info regarding email when [authenticating](https://github.com/meteor/meteor/issues/4545) using github
