### ISSUE TITLE
Create VM for automated deployment

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#189]
Related to #173

**Comment by bajiat** [comment]
For Aseem

**Comment by JuusoV** [comment]
According to the  diagram we need one more server from our original plan.
Mail sent to request the server.

The diagram is available at: 
https://owncloud.samposoftware.com/public.php?service=files&t=35be464504d9c4

**Comment by JuusoV** [comment]
Closed this since the VM is now deployed and configured.
