### ISSUE TITLE
Bug: STDERR when running application

### ISSUE THREAD

**Issue by JuusoV** [apinf/api-umbrella-dashboard#192]
W20150701-12:27:15.122(3)? (STDERR) 
W20150701-12:27:15.123(3)? (STDERR) /home/sampo/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150701-12:27:15.124(3)? (STDERR) 						throw(ex);
W20150701-12:27:15.124(3)? (STDERR) 						      ^
W20150701-12:27:15.218(3)? (STDERR) TypeError: Cannot read property 'data' of undefined
W20150701-12:27:15.218(3)? (STDERR)     at [object Object].Meteor.methods.syncApiUmbrellaUsers (app/server/methods/apiUmbrellaWeb.js:8:35)
W20150701-12:27:15.219(3)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
W20150701-12:27:15.219(3)? (STDERR)     at packages/ddp/livedata_server.js:1530:1
W20150701-12:27:15.219(3)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150701-12:27:15.219(3)? (STDERR)     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
W20150701-12:27:15.220(3)? (STDERR)     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
W20150701-12:27:15.221(3)? (STDERR)     at app/server/startup.js:15:10
W20150701-12:27:15.222(3)? (STDERR)     at /home/sampo/Code/api-umbrella-dashboard/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8

**Comment by ashakunt** [comment]
Thats precisely the error I was getting while I was there.

**Comment by brylie** [comment]
This was related to our VM being offline. We have created a new testing VM on DigitalOcean. @frenchbread, please inform the team how to access this new VM, so that we can all update our config files.

**Comment by frenchbread** [comment]
This issue is related to #194 and should be fixed for now. Check out [this comment](https://github.com/apinf/api-umbrella-dashboard/issues/194#issuecomment-119575680) for instructions.
