### ISSUE TITLE
Add missing configuration instructions for dashboard chart ElasticSearch code

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#194]
We are missing details about how to configure our project to access the ElasticSearch engine for dashboard analytics. @frenchbread, please update the team as to how we can configure our development environments to support remote ElasticSearch queries.

**Comment by frenchbread** [comment]
Here is a [pull request](https://github.com/apinf/api-umbrella-dashboard/pull/193) that has been already merged.

**Comment by frenchbread** [comment]
Summing up all latest changes and configs:
For having everything up to date and working,
1. Pull the lastest commit from [develop](https://github.com/apinf/api-umbrella-dashboard/tree/develop) branch
2. Create `settings.json` file (if it does not already exist)
Here is its contents (host address is the usual one):
 ```
 {
   "api_umbrella": {
     "api_key": "...",
     "auth_token": "...",
     "base_url": "https://.../api-umbrella/"
   },
   "elasticsearch": {
     "host": "http://...:14002"
   }
 }
 ```
When running meteor app, do it like this:
`meteor --settings /absolute/path/to/settings.json`
