### ISSUE TITLE
Resolve materialize issues after meteor-admin update

### ISSUE THREAD

**Issue by elnzv** [apinf/api-umbrella-dashboard#199]
There are some conflicts, especially with styles which needed to be resolved.

**Comment by elnzv** [comment]
Already done:
- removed materializecss
- cleaned all admin dashboard styling
- moved sidebar navigation  to topbar navigation

Left:
* [ ] Add .active class to routes
* [ ] Code cleanup

**Comment by brylie** [comment]
I have created a [support request on yogiben:meteor-admin](https://github.com/yogiben/meteor-admin/issues/225). Please explain some of your difficulties in that context, so that we can learn how to blend with and extend the Admin LTE styles.

**Comment by brylie** [comment]
@elnzv please respond to the [support request on meteor-admin](https://github.com/yogiben/meteor-admin/issues/225#issuecomment-118380663) and describe your difficulties.
