### ISSUE TITLE
Test documentation browser with different Swagger files

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#207]
Find Swagger files to test the documentation browser implementation.

Definition of done
---
* [x] Locate one or more Swagger files for testing purposes.
 * [ ] Optionally, upload the Swagger files in our project to the public directory.
* [x] Load the Swagger route using URL parameter with URL of Swagger file.

**Comment by bajiat** [comment]
One potential Swagger file: 
[Oppijan verkkopalvelukokonaisuus](https://virkailija.opintopolku.fi/eperusteet-service/#!/perusteet/getAll).

[Raw file](https://virkailija.opintopolku.fi/eperusteet-service/api/api-docs/public/arviointiasteikot)

**Comment by JuusoV** [comment]
https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-simple.json

Works perfectly. Will confirm with someone before to done.
