### ISSUE TITLE
Create user dashboard with Admin LTE framework

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#211]
Admin LTE framework has been separated from Yogiben Meteor Admin. Start writing our dashboard using Admin LTE components. Add the Admin LTE components without extending them.

Definition of done
---
* [x] Include Admin LTE Meteor package in our project.
* [x] Add Admin LTE template helper to dashboard template.
* [x] Write basic structure of Admin LTE dashboard (layout, menus, etc.)
* [x] Add menu links to navigation sidebar.
* [x] Add chart widget as dashboard component.
* [x] Add APIs list as dashboard component.

**Comment by brylie** [comment]
An [Admin LTE package](https://atmospherejs.com/mfactory) was just released.

**Comment by elnzv** [comment]
Included  Admin LTE Meteor package in our project https://github.com/apinf/api-umbrella-dashboard/commit/8ffb4dab763a8e95d45102095a65652b3df7fee5

Added Admin LTE template helper to dashboard template.

Wrote basic structure of Admin LTE dashboard (layout, menus, etc.).

Added menu links to navigation sidebar https://github.com/apinf/api-umbrella-dashboard/commit/36b105a163dc115280cf638a9c3ba255d5e9d25f

**Comment by elnzv** [comment]
Added chart widget as dashboard component https://github.com/apinf/api-umbrella-dashboard/commit/c8757fc32a738a2a803bbc07b3490c237c41ac8e

Added APIs list as dashboard component https://github.com/apinf/api-umbrella-dashboard/commit/09af4763cfce7c3776140281d981aa8ce6390ab2

**Comment by JuusoV** [comment]
@elnzv this can be moved to done
