### ISSUE TITLE
Add filtering to analytics charts and tables

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#212]
Ensure that analytics charts and tables can be filtered based on individual fields, such as users, date, time, location. Related to #183 

Definition of done
---
* [x] Determine how to add faceted filtering to analytics data.
* [x] Add UI widgets for faceting data.
* [x] Determine how to connect UI widgets with analytics data query.
* [ ] Update data table according to faceted data.
* [x] Update chart according to faceted data.
* [ ] Optionally, update URL to include data faceting parameters.
* [ ] Document how to write functional tests for faceted filtering.

**Comment by brylie** [comment]
See the tutorial [Interactive Data Visualization using D3.js, DC.js, Nodejs and MongoDB](https://anmolkoul.wordpress.com/2015/06/05/interactive-data-visualization-using-d3-js-dc-js-nodejs-and-mongodb/) for a great example of how to implement this feature.

**Comment by frenchbread** [comment]
@brylie Do you think it is better to use D3.js charting library rather than Chart.js?

**Comment by brylie** [comment]
Yeppers, or even DC.js, as in the tutorial.

**Comment by frenchbread** [comment]
[DC.js](https://atmospherejs.com/charts/dc) package for meteor.

**Comment by frenchbread** [comment]
[Crossfiler.js](https://atmospherejs.com/pfafman/crossfilter)

**Comment by frenchbread** [comment]
[D3.js](https://atmospherejs.com/d3js/d3)(official) or [DC.js](https://atmospherejs.com/meteor/d3)(unofficial)

**Comment by bajiat** [comment]
Perhaps you can use this documentation as an inspiration?
[https://tyk.io/dashboard-v0-9/analytics/](https://tyk.io/dashboard-v0-9/analytics/)

**Comment by frenchbread** [comment]
@bajiat Thanks! Filtering approach is useful on that resource.

**Comment by frenchbread** [comment]
Here is related branch - [`feature/dc-d3-dynamic-charting`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/dc-d3-dynamic-charting).

So far, having:
1. Added package `charts:dc`. It includes d3.js + dc.js + crossfilter.js.
2. Line chart with real data rendered within a package mentioned above.
3. Dynamically filtering data by month and year.
