### ISSUE TITLE
Determine required fields for API configuration form

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#216]
Currently, all fields are treated as optional in the API backend configuration form. Some of them must be mandatory for API Umbrella to accept the API configuration.

Definition of done
---
* [x] Determine which fields are mandatory and which fields are optional based on API Umbrella (possibly by testing against API Umbrella Postman).
* [x] Make the necessary fields required in the schema.

**Comment by brylie** [comment]
I have opened a [documentation request on API Umbrella Web](https://github.com/NREL/api-umbrella/issues/164) that would inform this task.

**Comment by brylie** [comment]
I get a 500 error when sending a POST request via Postman.

**Comment by brylie** [comment]
It is not documented how to structure the request, so any experimentation is simply guesswork.

**Comment by frenchbread** [comment]
Fields required by apiUmbrella.
'''
{ "api": { "name": "Example ", "backend_protocol": "https", "frontend_host": "<umbrella-url>", "backend_host": "<backend-host-url>", "balance_algorithm": "least_conn", "url_matches": [ { "frontend_prefix": "/<some-prefix1>/", "backend_prefix": "/<some-prefix2/" } ], "servers": [ { "host": "<i-used-same-as-backend-host-url>", "port": 443 } ] } }
'''

**Comment by frenchbread** [comment]
Related discussion - [link](https://github.com/NREL/api-umbrella/issues/165)
