### ISSUE TITLE
Define and implement most important privileges

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#217]
Define potential database privileges for Apinf user roles. Prioritize them and implement the most significant ones for MVP.

Definition of done
----
* [x] Make a list of user privileges per user role
  * [x] apiBackends collection
  * [x] apiBookmarks collection
  * [x] ElasticSearch analytics data
* [ ] Implement 3-5 most important database privileges.
  * [x] user bookmarks publication
  * [x ] all analytics data query

**Comment by brylie** [comment]
I have created a document describing our [system permissions](https://apinf.hackpad.com/Permissions-o6FqN3TtxIz).

**Comment by brylie** [comment]
I am working on this issue, starting with user bookmarks. I would like to work with a pair programming partner on the Elastic analytics query (filtering to a given UserID or API ID). There is also a proposed schema change to the `apiBackends` collection, which is modified in a pending pull-request.
