### ISSUE TITLE
Testing workshop

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#241]
Organize, plan and facilitate a testing workshop

# Workshop Outline
* Why test?
  * Align code with business goals and needs
  * Code documentation
  * Prevent regression
  * Confidence when refactoring
  * Make sure our assumptions are correct
  * Project and team scaling
* [Behavior Driven Design](https://en.wikipedia.org/wiki/Behavior-driven_development)
  * User Stories - interactive (bakery)
    * As a ... [role]
    * I want ... [feature or activity]
    * So that ... [outcome]
  * Scenarios - interactive (bakery)
    * Given ... [initial setup]
    * When ... [event or action]
    * then ... [expected outcome]
* Types of Tests - system diagram
  * Unit
  * Integration
  * Functional (Browser)
* Tests are functions
* Test Doubles
* Testing sequence
  * Setup
  * Execute
  * Verify
  * Teardown
* [Jasmine](http://jasmine.github.io)
  * beforeAll()
  * describe()
    * it()
  * afterAll()
* Browser Testing
  * [Casper](http://casperjs.org/) & [Slimer](http://slimerjs.org/)

# Resources
* [End-to-end testing with Meteor](http://vstark.net/2014/10/10/end-to-end-testing-meteor/)
* [Introducing BDD by Dan North](http://dannorth.net/introducing-bdd/)
* [JavaScript testing with Jasmine](https://www.youtube.com/playlist?list=PLOxOmO43E6Jt0SruKGxtZs-W3PJN90G_a) - video series

**Comment by brylie** [comment]
Bakery examples:

spec.js
```describe('Bakery', function () {
  it('should bake bread', function () {
    expect(bakeBread()).toEqual('Fresh baked bread!');
  })

  it ('should bake customer favorite bread', function () {
    expect(bakeCustomerFavoriteBread('rye')).toEqual('Fresh baked rye bread!');
  })
})
```

source.js
```
var bakeBread = function (breadType) {
  if (breadType) {
    return 'Fresh baked ' + breadType + ' bread!'
  } else {
    return 'Fresh baked bread!';
  }
};

var bakeCustomerFavoriteBread = function (favoriteBread) {
  var bakedBread = bakeBread(favoriteBread);

  return bakedBread;
}

```
