### ISSUE TITLE
nightly.apinf.com down because of failed depoloyment

### ISSUE THREAD

**Issue by JuusoV** [apinf/api-umbrella-dashboard#243]
Mup server is down because of failed deployment.
Blocking:  #188 and a step of #201

**Comment by JuusoV** [comment]
Im not the only one having this issue. Im following the discussion on the mup Github.

**Comment by elnzv** [comment]
Have you checked [this](https://github.com/arunoda/meteor-up/tree/mupx) out?

**Comment by JuusoV** [comment]
Yes, trying with the older stable version of MUP first since it worked well the last time.
Installing mupx would need migration work or either whole reset on the server.
