### ISSUE TITLE
'getChartData' Error: No Living connections

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#251]
Damir,
When I load the dashboard based on your `getChartData`function, I get the following error:
```
Exception while invoking method 'getChartData' Error: No Living connections
     at Object.search (packages/meteorhacks:async/async.js:71:1)
     at [object Object].doSearch (packages/frenchbread:elastic-rest/server/elastic-rest.js:31:1)
```

**Comment by brylie** [comment]
This boiled down to using `https` when the server expected `http`. See inline notes in the pull request.

**Comment by frenchbread** [comment]
@brylie This error pops up every time when the elasticsearch cannot find data within provided query. Error handling and parsing values are not implemented in [`feature/dc-d3-dynamic-charting`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/dc-d3-dynamic-charting)

**Comment by bajiat** [comment]
Resolved.
