### ISSUE TITLE
Ensure mup.json configuration file is no longer in commit history

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#257]
The mup.json was accidentally published to Github, and may still be in our project commit history (i.e. the feature branch). Ensure the mup.json is no longer published, and is cleaned from the repository commit history.

**Comment by brylie** [comment]
I am not sure that deleting the branch was sufficient, as the file may still be visible in the pull request.

**Comment by bajiat** [comment]
Done.
