### ISSUE TITLE
Automatically generate lists of years and months in select filed (filter template)

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#258]
Now, when filtering analytics data, values in `select` box are hard coded to the `filterData` template. The goal is to have this fields generated automatically using javascript.

Def of done:
- [ ] Explore possibilities for date range selection on dashboard.
- [ ] Generate a list of months
- [ ] Generate a list of years
- [ ] Research, if it possible to generate year/month values dynamically based on data available in database

**Comment by frenchbread** [comment]
#254 related

**Comment by bajiat** [comment]
@frenchbread Can you please describe this task?

**Comment by frenchbread** [comment]
@bajiat Done. Updated the task title as well, so it is more specific.

**Comment by bajiat** [comment]
Obsolete.
