### ISSUE TITLE
Create data table pagination on /dashboard

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#259]
#183 - Related issue.

`/dashboard` page contains data table that displays usage logs. The data in the table is dynamic so when user does some filtering, or selects specific area on a chart, data in the table instantly updates.

Since data table is built using `dc.js` library, there is no pagination attached to the table "out of the box".

Definition of done
---
* [x] Determine if DC uses DataTables.js
* [x] Review, if it possible to attach pagination to `dc` data table
   * [x] If not, review other solutions how data table can have pagination.
* [x] Demonstrate working data table with pagination

**Comment by bajiat** [comment]
@frenchbread Can you please describe this task?

**Comment by JuusoV** [comment]
This can be done with Tabular Tables easily. Only issue is that we lose the dynamic functionality of DC.js. The table will show all the available data at the same time.

**Comment by frenchbread** [comment]
@JuusoV Here is the working branch where we did some refactoring. Now it can be a bit easier to attach pagination to data table.

**Comment by brylie** [comment]
I opened a feature [request on the DC.js repository for integration with DataTables.js](https://github.com/dc-js/dc.js/issues/966)

**Comment by JuusoV** [comment]
Awesome. Great stuff guys!

**Comment by brylie** [comment]
@frenchbread please get some sample data to work with. This way we won't have to wait for a round-trip from the Elastic server. The sample data can be passed in to the `parseData` function now that the code is refactored.

**Comment by frenchbread** [comment]
@brylie Here is the sample data example at [gist](https://gist.github.com/frenchbread/4f7d0af3386869c13322)

**Comment by JuusoV** [comment]
@frenchbread doing what he knows the best here. Really amazing job! The task is pretty much done and I will create PR asap after some cleanup.

**Comment by frenchbread** [comment]
@JuusoV Ok, no problem. Create a PR whenever it's ready. Probably will need to do some more code refactoring but it is fine for now.

**Comment by bajiat** [comment]
Thumbs up for you, guys! Thanks!
