### ISSUE TITLE
Set up Github account for Apinf

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#265]
In order to authenticate users via Github, we need a Github account and corresponding client id and client secret. Related to #264.

* [x] Set up the account
* [x] Create Github application
* [x] Get the client id and client secret.
* [x] Find a safe place to store the information so that it's included in automated deployment.

**Comment by ashakunt** [comment]
Wishlist: use the username as apinf (or apiops) what ever is the umbrella brand.  In this way, we can also host the website directly on github like: apinf.github.io OR apiops.github.io

**Comment by ashakunt** [comment]
(or at least, these available domains can be used by our system to re-direct to original apinf / apiops websites. (cc: @chandra)

**Comment by bajiat** [comment]
After briefly looking at this, I quess this is what we need to do: Since we need this for getting OAuth tokens for the purpose of using Github API for user registration, we need to register an application for our current Apinf organization through Settings > Applications > Register an application.

**Comment by bajiat** [comment]
Does anyone know what is an "Authorization callback URL"? It is required for the app registration.
This is the information I found on the Github instructions for OAuth: 
The redirect_uri parameter is optional. If left out, GitHub will redirect users to the callback URL configured in the OAuth Application settings. If provided, the redirect URL’s host and port must exactly match the callback URL. The redirect URL’s path must reference a subdirectory of the callback URL.

And here are examples of goof callback URL's:
CALLBACK: http://example.com/path

GOOD: http://example.com/path
GOOD: http://example.com/path/subdir/other

**Comment by elnzv** [comment]
Homepage URL:
http://nightly.apinf.com/_oauth/github

Authorization callback URL:
http://nightly.apinf.com/_oauth/github

**Comment by bajiat** [comment]
I registered two applications
* Apinf
* Apinf nightly
