### ISSUE TITLE
Add open data APIs to Apinf catalog (for hackathon and MindTrek)

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#268]
Once Apinf has been deployed on Apinf.io, configure several example open data APIs to catalog. 

Definition of done
---
* [x] Select 3-5 interesting or useful open APIs.
* [ ] Add/configure API backends via *Add API Backend form*.
  * [ ] Finnkino
  * [ ] TKL
  * [x] Google Maps Geocoding
* [ ] *[optional]* Add API documentation, if an existing Swagger file is available.

# Resources
The following sources may prove beneficial when selecting Open Data APIs for this tack.

* [Tampere Kaupunki Avoin Data](http://www.tampere.fi/tampereinfo/avoindata.html) has around 30 Open Data APIs
* [ITS Factory Wiki](http://wiki.itsfactory.fi/index.php/Main_Page) contains links to many Open Data APIs.
* [AvoinData.fi](https://www.avoindata.fi/) has links to over 1,500 Open APIs

**Comment by bajiat** [comment]
@ashakunt Can you consider taking this task? You could additionally add some Codemenders APIs, if you want.

**Comment by ashakunt** [comment]
@bajiat I can take a look at this. I cannot estimate the hours right now since I would first need to pick the apis I would like to have here. 

PS: We can add Codemenders APIs too. I will keep this bug posted.

**Comment by bajiat** [comment]
@ashakunt Thanks for taking this. I think the rest of the team could also provide some suggestions on interesting APIs to add.

**Comment by ashakunt** [comment]
I was looking at the Helsinki city transport APIs briefly today. It was not very clear as to where and how should be use it (esp. documenting all its methods). 

One quick example that comes to my mind is: Pet Store; the one on which all the swagger examples are based. I will still spend time on this tomorrow to find more apis which can be used. One interesting thing during the hackathon could also be the role of an apitalist. He creates an API, relevant documentation and then, uploads its methods to API umbrella. We can showcase how easy it is to be an apitalist. If no body signs up for this purpose, I will be happy doing it.

@ccsr what do you think?

**Comment by ashakunt** [comment]
Setting time limit as 20 since we need to look into existing APIs (and find their documentation). Its possible that the work might be quite smaller.

**Comment by ashakunt** [comment]
@bajiat what do you think about: 

----8<----
One interesting thing during the hackathon could also be the role of an apitalist. He creates an API, relevant documentation and then, uploads its methods to API umbrella. We can showcase how easy it is to be an apitalist. If no body signs up for this purpose, I will be happy doing it.
----->8-----

**Comment by bajiat** [comment]
@ashakunt I think it would be a good idea for the kick off. We probably need to showcase adding APIs to Apinf anyway, since we won't be able to add all APIs the participants might need in the hackathon.

Could we at least have the most typical ones like Google maps? Juuso was earlier commenting that some students have created apps based on Finnkino movie schedules, so I quess Finnkino has APIs too.

**Comment by bajiat** [comment]
@ashakunt Are there any useful open APIs that could be added on the API Suomi page?

**Comment by brylie** [comment]
@ashakunt this task does not include creating a Swagger file, if it does not exist. You only need to select existing API Backends, and add them via the Add API Backend form. Swagger documentation is optional and 'extra credit'.

**Comment by brylie** [comment]
@bajiat and @ashakunt I have updated the task description and added a resources section.

**Comment by ashakunt** [comment]
@bajiat: 

Finnkino is a good example. It has an XML based service. See this: http://www.finnkino.fi/XML; so this is a good match. 

Another one is tkl, see examples here: http://developer.publictransport.tampere.fi/pages/en/siri.php

**Comment by ashakunt** [comment]
IMHO, we should also add the following: 

https://developers.google.com/maps/documentation/geocoding/intro

**Comment by brylie** [comment]
@ashakunt, I have updated the Definition of Done to include the three APIs specified in recent comments. Please proceed with configuring Google Maps Geocoding, Finnkino, and TKL on the nightly.apinf.io platform.

**Comment by ashakunt** [comment]
@brylie, @bajiat: 

I have added Google Geocoding APis but the access seems to be down. 

https://nightly.apinf.com/google/maps/api/geocode/json?latlng=63.1,23.4&api_key=<my api key> 

OR 

https://nightly.apinf.com/google1/maps/api/geocode/json?latlng=63.1,23.4&api_key=<my api key> 

(both added by me) return a connection refused.

**Comment by ashakunt** [comment]
Is this known?

**Comment by ashakunt** [comment]
(precisely: Google Chrome's connection attempt to nightly.apinf.com was rejected. The website may be down, or your network may not be properly configured.)

**Comment by bajiat** [comment]
@ashakunt @brylie will take a look at this

**Comment by bajiat** [comment]
First *guess* was SSL certificate not being in place on Apinf,io yet.

**Comment by brylie** [comment]
@ashakunt our APi Umbrella instance is currently running on its own sub-domain. Try the requests using **https://umbrella.apinf.io**.

**Comment by ashakunt** [comment]
@brylie with umbrella.apinf.io: I get a 404 error when I try to use the APIs.

Further, it turns out that not all the backends that I added from nightly.apinf.io landed up to umbrella.apinf.io. I could find only one API available at umbrella.apinf.io. I think that the nightly is handling the URL in a wrong way. See below (backend host -> frontend host): 

![selection_010](https://cloud.githubusercontent.com/assets/5460151/9733531/ac4d0008-5634-11e5-9e31-ef4cd8ff9911.png)

While, originally, in the umbrella, its like (frontend host -> backend host): 
![selection_011](https://cloud.githubusercontent.com/assets/5460151/9733543/cbefaf32-5634-11e5-9751-1e561982a830.png)

**Comment by ashakunt** [comment]
Some other comments: 

* I found out that not all the APIs backends were published on umbrella.apinf.io. 
* Accessing the apis directly from umbrealla.apinf.io shows a 404.

@brylie @bajiat Your comments?

**Comment by brylie** [comment]
The inconsistency may arise from how we are deploying API Umbrella. Our Apinf deployment may have pointed to a different API Umbrella deployment at some point (e.g. apinf.com), and is only configured to pull API Backends from API Umbrella.

**Comment by brylie** [comment]
I have opened issue #446 to describe the API Backend data inconsistency.

**Comment by ashakunt** [comment]
and what about the 404 problem?

**Comment by brylie** [comment]
Checking now. Are you using an API key?

**Comment by ashakunt** [comment]
Yes sir.. :)

**Comment by ashakunt** [comment]
e.g.

**Comment by ashakunt** [comment]
The above API is added in accordance with: http://apiumbrella.io/docs/getting-started/

**Comment by brylie** [comment]
I see the following entry for Google:

```
Name | Host | prefix
Google Geocoding APIs	| localhost	| /google/
```

**Comment by ashakunt** [comment]
Yes. That's correct.

**Comment by brylie** [comment]
OK, so it seems like the API Backend exists. How can we troubleshoot the 404?

**Comment by brylie** [comment]
Perhaps the *'localhost'* needs to change to *umbrella.apinf.io*

**Comment by ashakunt** [comment]
Tried with that already. Does not work. (see the testing entry for google geocoding apis)

**Comment by brylie** [comment]
Alright, please open a support request on API Umbrella issue tracker. We may need help in troubleshooting this issue.

**Comment by ashakunt** [comment]
can you or anyone in team who has access to umbrella.apinf.io provide the versoin of the umbrella?

**Comment by ashakunt** [comment]
I opened: https://github.com/NREL/api-umbrella/issues/168

**Comment by brylie** [comment]
You can also log in to the admin interface with "aseem at samposoftware ... "

**Comment by ashakunt** [comment]
@brylie I am already using that.

**Comment by brylie** [comment]
Alright, cool. Well the UI doesn't display the version of API Umbrella, so we need to check on the server-side.

**Comment by ashakunt** [comment]
I actually meant the same, so can you ask @elnzv  or someone else who has access?

**Comment by brylie** [comment]
@elnzv will you please check the version number of API Umbrella that is running on *umbrella.apinf.io*?

**Comment by elnzv** [comment]
@ashakunt it is 0.8.0

**Comment by ashakunt** [comment]
Thanks, @elnzv

**Comment by ashakunt** [comment]
@elnzv / @ccsr can you please provide the following information from umbrella.apinf.io 

1. contents of ```/opt/api-umbrella/etc/nginx/backends.conf```
1. restart api-umbrella ```sudo /etc/init.d/api-umbrella restart```

OR provide me a sudo access to the machine so that I can check them myself?

(refer: https://github.com/NREL/api-umbrella/issues/168#issuecomment-138809483)

**Comment by bajiat** [comment]
@elnzv Will you take a look at Aseem's request above?

**Comment by elnzv** [comment]
@ashakunt I think the best way is to have a sudo access.
I can provide you my credentials via email or you can ask Chandra for your's.

**Comment by ccsr** [comment]
@ashakunt You have sudo access to umbrella.apinf.io
Let me know if you are not able log in

**Comment by ashakunt** [comment]
@ccsr able to login with sudo access now. Providing the relevant information to @GUI now. :)

**Comment by ccsr** [comment]
@ashakunt @elnzv Illya is changing the certificate and lets check that option also

**Comment by ashakunt** [comment]
@ccsr, I fixed the original issue. So, now every thing is OK.

**Comment by ashakunt** [comment]
@bajiat @brylie @elnzv @ccsr @apinf/developers @apinf/owners Please do not do any changes to umbrella.apinf.io since it might break the installation again. This is for your info.

**Comment by ashakunt** [comment]
@apinf/developers @apinf/owners A learning from this issue and its consequences: We should have tests which not only validate the dashboard but also run an end-to-end check 

An MVP of testing would be (in addition to what we have right now?): 

1. Able to add an API to the backend
1. Able to add documentation to API
1. Able to get data from the backend

Further these stories can be broken into smaller parts.

**Comment by brylie** [comment]
@ashakunt what is the status of this task?

**Comment by jykae** [comment]
I am facing the same issue, fix seems to exist https://github.com/NREL/api-umbrella-router/pull/9
@ashakunt Can you tell how you fixed the issue on umbrella.apinf.io ?
