### ISSUE TITLE
Implement contact form for landing page

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#277]
The Apinf landing page will contain a "Contact us" form. The task is to implement the form.

Related to #275.
* [x] Schema using SimpleSchema 
* [x] Show it with AutoForm 
* [x] Send mail logic
* [x] Visual feedback on form submit
* [x] Move 'To Email' to config file

**Comment by elnzv** [comment]
Schema - https://github.com/apinf/api-umbrella-dashboard/commit/6593913c78bb807bb17bfa7dc4eac0da6cea9190

Template with AutoForm - https://github.com/apinf/api-umbrella-dashboard/commit/6a20a260d391f8acf9079ea3f6130f692fa08d57

Send mail logic - https://github.com/apinf/api-umbrella-dashboard/commit/205fefa62d23a272d262c969277402e71a17cfda

**Comment by elnzv** [comment]
"To Email" field now is defined in settings.json:

```json
"contactForm": {
    "toEmail": "email@address.com"
  }
```
