### ISSUE TITLE
Document dashboard integration decision

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#278]
We need to understand how the dashboard components will share data and state. Technical discussion and decision required. Document describing the where the data will live and how dashboard will read and modify the data set. 

Definition of done
---
* [ ] Organise a workshop to discuss the desired the data views.
* [ ] Identify data views needing attention.
* [ ] Add any identified tasks to the project backlog.
* [ ] Determine if any added tasks will affect the current sprint.
* [ ] Make a diagram or wireframe showing that we have one unified dashboard to show which parts are for privileged user and which parts are for restricted users.

**Comment by brylie** [comment]
I have created a [dashboard integration design document](https://github.com/apinf/api-umbrella-dashboard/blob/feature/dashboard-integration-diagram/docs/developers/dashboard-integration.svg).
