### ISSUE TITLE
Autopopulate API backend configuration form

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#279]
When  uploading an API configuration file, autopopulate the API configuration backend form using data from the configuration file.
Related to #215.

Defition of done
---
* [x] Check the parsing code created in #215.
  * [ ] Make sure API configuration files are parsed, when uploaded via the API configuration form.
 * [x]  If in original code, file is parsed directly to database, re-factor code to move parsing function.
* [x] Populate the form with the parsed data.

**Comment by elnzv** [comment]
Maybe [this](https://github.com/gwendall/meteor-autoform-i18n/) can help.
