### ISSUE TITLE
Integrate heatmap to dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#284]
Based on #278, determine how to integrate a geographic heatmap on dashboard with shared state.

Definition of done
----
* [ ] Place the heatmap on unified dashboard.
  * [ ] Choose the desired place.
  * [ ] Add template inclusion.
* [ ] Make sure its using the shared data with DC charts, if possible.

**Comment by JuusoV** [comment]
@elnzv managed to get the map working on clean install, whereas it doesnt work for me when I do exactly the same steps. 
This still needs investigation or even the decision to move to a completely different mapping library. 
The big problem with all the libraries is that we are probably the first ones trying to implement them on meteor production environment. This means that its hard to find anyone else with a solution to exactly the issue we might have.

**Comment by JuusoV** [comment]
The branch needs to be updated and then PR can be created.
