### ISSUE TITLE
Allow only text files on API config and Swagger upload

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#285]
For security reasons, we need to disallow any other file types than text files on file upload.

Definition of done
---
* [x] Figure out what options for enforcing file types.
  * [ ] HTML form allow
  * [x] Check also on server-side.
* [x] Implement file type checks
* [ ] Visual feedback on validation

**Comment by elnzv** [comment]
Now filtering swagger upload by .json & .yaml file only https://github.com/apinf/api-umbrella-dashboard/commit/f573e8ca078532e2ce708b8ef6fee162b554e976
