### ISSUE TITLE
Add overview chart to dashboard layout

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#288]
In order for the user to navigate the dashboard chart data, it may prove useful to have an overview chart. 

Definition of done
* [ ] Add overview chart to dashboard layout
* [ ] Populate overview chart with aggregate data
   * [ ] Number of hits in a given timeframe

Note: the overview chart may not need all fields or records, but rather may suffice to have aggregate statistics. This will speed up the time to load on the client.

**Comment by frenchbread** [comment]
Created a PR #297 with added overview chart to dashboard. So now basically you can select specific range on an overview chart and see zoomed in line chart for more exact reference.

**Comment by frenchbread** [comment]
Hotfix #301 and related discussion there.
