### ISSUE TITLE
Documentation browser

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#30]
Create an interface or frame for displaying Swagger files.

User story: As Minh (API consumer), I want to access API documentation.

Definition of done:
---
* [ ] Add Swagger source files to project  in location determined in #160(?)
* [ ]  Create "Upload Swagger file" functionality.
  * [ ] Create basic template for Swagger file upload.
  * [ ] Add Bootstrap button to Swagger file upload template.
  * [ ] Create file system collection to store Swagger files.
  * [ ] Create template logic e.g. helper and event to upload file, when button is clicked.
  * [ ] Create foreign key relationship between API backend and Swagger file.
  * [ ] Create collection helper to retrieve Swagger file from API backend.

**Comment by brylie** [comment]
This documentation browser can be used to display Swagger and/or RAML files, such as described in issue #99.

**Comment by JuusoV** [comment]
Very relevant(?):

https://github.com/swagger-api/swagger-ui
http://petstore.swagger.io/

**Comment by brylie** [comment]
There is a [Meteor Swagger client](https://atmospherejs.com/warehouseman/meteor-swagger-client) package for [creating sandbox interfaces to remote APIs based on a Swagger file](https://forums.meteor.com/t/instant-rest-client-from-a-swagger-specification/6259).
