### ISSUE TITLE
Get data for selected API

### ISSUE THREAD

**Issue by marla-singer** [apinf/api-umbrella-dashboard#31]
## Goal
Create a query request to ElasticSearch Data Storage to get data for early selected API which will be displayed on the API Analytics View page
- [ ] Get data for small charts: Number of requests, Average response time, Unique API users. These data must be general for specified proxy backend path (endpoint)
- [ ] Get data for a current week and previous week for comparing: Number of requests, Average response time, Unique API users. These data must be general for specified proxy backend path (endpoint)
- [ ] Get data about status and count of calls: 2xx, 3xx, 4xx, 5xx. These data must be general for specified proxy backend path (endpoint)
- [ ] Get data for big charts: API Request timeline and API response time chart. These data depends on called endpoint (Endpoint 1, Endpoint 2, Endpoint 3 ... ).
- [ ] Get summary count of requests number and response time for called endpoint (Endpoint 1, Endpoint 2, Endpoint 3 ... ).
- [ ] Get data for table Problems
- [ ] Get data for table Most frequent Users

![28869600-f13e579c-7785-11e7-8d15-2c01cf4b9d73](https://user-images.githubusercontent.com/20643403/29043131-7a41877c-7bc2-11e7-9594-3827466f6986.png)

**Comment by bajiat** [comment]
@marla-singer Could you add a basic description for this issue? It would make it easier to follow the status and progress of dashboard, if the issues have even as brief description of purpose/goal.
