### ISSUE TITLE
Organize Hackathon brainstorming session

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#317]
Brainstorming is needed for 2 Apinf hackathons. Organise a session, where the following issues are discussed:
* Where? 
* When?
* Who? How many developers?
* How to recruit / Where to promote? 
* Tasks?
* Prize?
* Refreshments?
* Swag? (T-shirts etc.)

Definition of done
---
* [ ] Book a brainstorming session.
* [ ] Document the ideas from the session.
* [ ] Create the relevant tasks for social media marketing, user recruitment etc.

**Comment by JuusoV** [comment]
Depending on the target group of the hackathon I would be interested to market this in TAMK and TTY

**Comment by bajiat** [comment]
Brainstorming with Laura started. Initial ideas in [Mini hackathon](https://apinf.hackpad.com/Mini-hackathon-R2zjsiNqVG7) document
