### ISSUE TITLE
Create an export functionality for single API backend configuration

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#323]
To be able to import single  API backend configurations to Apinf, the configurations need to be first exported from an existing API backend. The exporting solutions should adhere to API Umbrella configuration format.

Definition of done
---
* [x] Document fields and structure of API Umbrella configuration format to API Umbrella project repository.
* [x] Create function to export a single API backend to API Umbrella format.
* [ ] Create Export API button to catalogue UI.

**Comment by bajiat** [comment]
Keep Nick informed on the design plans.

**Comment by frenchbread** [comment]
Basically, apiUmbrella allows to export all the APIs created at once and to one file. Here is the [example of fresh API configurations export](https://gist.github.com/frenchbread/f755ca7f0fee2c7590fd). I also modified config file export for easier understanding of API configuration structure at apiUmbrella site. Here is [single API config example](https://gist.github.com/frenchbread/0f44925f051b6700be09). (This config file can also be used for testing #344)
The approach is to generate JSON document on a client-side, the document will contain API backend configurations. Once document is generated, using [FileSaver.js](https://atmospherejs.com/pfafman/filesaver) meteor package, user will be able to download it after clicking on `Export Configurations` button.

There is also possibility for "bonus" functionality - to allow user to choose apiConfig file format/extension of file to be exported (for example `YAML` or `JSON`)
