### ISSUE TITLE
Create functionality to import single API backend configuration

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#324]
Based on task #323, create functionality to import single API backend configuration. 

### Definition of done
* [x] Create user interface button to upload single API backend configuration.
* [x] Create function to parse uploaded to configuration to JSON object.
* [x] Create function to insert configuration into API backends collection in the database.
* [ ]  Make sure API backend is validated against API backend schema.
* [ ] After upload, re-direct user to the API configuration form for the uploaded API.

**Comment by frenchbread** [comment]
Related PR - #344. Mainly the task is done. Still need to figure out how to get dynamic `path` value in `both/collections/backendConfigurations.js` file so that we are not providing hard-coded path which probably won't work on other PC's. @brylie, Any ideas?

**Comment by brylie** [comment]
@frenchbread, try using [GridFS](https://github.com/CollectionFS/DEPRECATING-cfs-gridfs/tree/master/packages/gridfs), which stores the files in a collection.

**Comment by frenchbread** [comment]
Wireframe:

![img_20150820_104121](https://cloud.githubusercontent.com/assets/2122679/9378200/3c57274e-4728-11e5-8493-4bc2413ff188.jpg)

**Comment by frenchbread** [comment]
PR #344 created. Please review. 

Followed wire-frame that is provided above, kind of rewrote api config file import approach. 
Changes:
- most of the checks and parsing is done on client-side (so it is much faster)
- 2-panel view (file upload drop box and file preview (with syntax highlights))
- only YAML and JSON config files are allowed for now
- once submit button is clicked - form contents are sent to server where final schema verification takes place
- error handling provided almost everywhere where possible - so pretty secure 
- added custom parsing of `required fields` 
- couple of tips on "How to import configs" are provided.

**Comment by brylie** [comment]
Looks good. Also keep in mind the redirect after success, as this will help orient the user to the result of their action.

**Comment by frenchbread** [comment]
@brylie Ok. Once `api backend view` page is ready & merged, I will add functionality to redirect after import.

**Comment by brylie** [comment]
@frenchbread cool. The [pull request](https://github.com/apinf/api-umbrella-dashboard/pull/390) has been submitted and updated.

**Comment by frenchbread** [comment]
@brylie Updated PR #344 with redirect to view page.  It shows 404 for now because #390 is not in develop yet. 

I've made a small suggestion in #390 to use simpler path for api backend view in url. If it will be accepted I will need to change the redirect path in this PR as well.
