### ISSUE TITLE
Add view for user management

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#326]
Apinf administrators need to be able to view and manage users. Additionally, they need to assign users as Apinf administrators.

Definition of done
---
* [x] Salvage package for displaying/editing users
* [x] Divide package into sub-packages for commonly useful functionality
* [x] Add package to our platform
* [x] Create route, view, and link for user management

**Comment by brylie** [comment]
[Pull request open](https://github.com/apinf/api-umbrella-dashboard/pull/410)
