### ISSUE TITLE
Add service monitoring endpoint to Apinf infrastructure

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#329]
All Apinf users (API consumers, API managers and Apinf administrators) need to be able to check Apinf service availability.

Definition of done
---
* [x] Create REST endpoint for returning confimation, if service is up.
   * [x] If desired, design a user interface to display the status information.

**Comment by JuusoV** [comment]
More than interested!

**Comment by frenchbread** [comment]
PR #358 created. Pls review, test and merge it.
