### ISSUE TITLE
Add API design UI that generates Swagger to Apinf infrastructure

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#330]
As an API owner I need a tool that allows me to generate API documentation for my API in Swagger format.

Definition of done
---
* [x] Choose an UI to generate Swagger documentation
* [x] Implement the chosen tool in Apinf infrastructure.
* [x] Integrate the tool to Apinf UI as simply as possible.

**Comment by ashakunt** [comment]
Trying to put the pieces together: 

1. Allow an option for the API owner to generate the Swagger file
    1. Restlet Studio
    1. Swagger Generator (use Swagger UI or Implement own UI)
1. Upload OR obtain the file at the dashboard from above step
1. Show the documentation using the in-built swagger ui implementation

**Comment by ashakunt** [comment]
RestLet studio: 

1. Pros
    1. Allows to create a file in design view so a person without any know-how of swagger syntax can create a documentation
    1. Simple to use UI
1. Cons
    1. No API to access studio
    1. No way to start from an existing swagger file (if that needs to be updated)
    1. For designing, if forces the design to be done from scratch

**Comment by ashakunt** [comment]
Swagger UI (internal: swagger-editor)

1. Pros:
    1. Install on our own server
    1. Can get tightly integrated to the dashboard
    1. Allows to import an existing file
 1. Cons:
     1. A design view for editor must be developed. Cannot find a solution (other than RestLet) where a design can be done

**Comment by ashakunt** [comment]
Based on discussions with @ccsr, @JuusoV and @ashakunt, we agreed to use Swagger UI. Reasons: 

1. Can be tightly coupled with our current system
1. Easier to implement 
1. It is also possible to integrate this product to upstream (umbrella ui) if required in future, considering that the whole apiumbreall* product is tightly coupled with Swagger.

IMHO, this is a standard approach. 

What should be done next:
* Implementation / integration of swagger editor in the dashboard 
* Implement toolbar, something like: [Upload your own | Edit default]
    * Upload your own (upload your existing swagger file)
    * Edit default (swagger-editor opens with a default swagger file which can be edited by the geek)

**Comment by JuusoV** [comment]
According to the research I did, we cannot implement Swagger editor inside our project as is. The reason being that the editor is written in Node and we cannot run Node inside Meteor.js project. 
Luckily there is a workaround: We can install the Swagger editor as a separate instance on a different server and implement it to our UI with an iFrame.

**Comment by ashakunt** [comment]
I think this still is a decent approach, keeping in mind, that any API owner can already create a documentation for their APIs right before they actually decide to add it under the umbrella (even if they are not logged in to APINF or registered).

**Comment by JuusoV** [comment]
Yeah, agreed. This is just taking more time than I originally expected. Looking to close this today since the server is up right now.
