### ISSUE TITLE
Choose API mock testing solution

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#331]
Definition of done
---
* [x] Create functionality to check API type and how input parameters are accepted.
* [x] Form to provide the input parameters.
* [x] Button to try it out.

**Comment by ashakunt** [comment]
IMHO, 331 and 76 are related, just that 331 is a smaller version of 76.

**Comment by ashakunt** [comment]
While using the swagger ui, it already has a way to mock the APIs (using the Send Request OR Try it out functionalities). It alerts the user about Cross Origin Reference; so, the dashboard should be white-listed in the umbrella for access.

**Comment by bajiat** [comment]
@ashakunt Could you take this task?

**Comment by ashakunt** [comment]
Mocking can be done in two ways: 

1. Dummy data = where we just validate the input and return some dummy data to developer that "Hey, it should work"
2. Real Data = where we create a REAL "Try it out" request and then return the REAL status to the user.

While mocking the GET apis is easy in both the modes, mocking of PUT/DELETE APIs is going to be tricky because in CASE 2, we are actually going to delete the data.

**Comment by ashakunt** [comment]
Based on discussions with @ccsr, @JuusoV and @ashakunt, we decided to use REAL DATA for mocking. So, native swagger implementation should already support the mocking by the "Try it out" or "Send Request" button. We just need to put the CORS (Cross Origin Resource Sharing) policies in place between API Umbrella and Dashboard. 

One nice way to do this would be (for example in PHP): 

```
 84 function enableCORS() {
 85     // Allow from any origin
 86     if (isset($_SERVER['HTTP_ORIGIN'])) {
 87         header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
 88         header("Access-Control-Allow-Methods: GET, POST");
 89         header("Access-Control-Allow-Headers: X-Requested-With");
 90     } else {
 91         error_log("CORS WAS NOT ENABLED (script: {$_SERVER['PHP_SELF']}, requested by: {$_SERVER['REMOTE_ADDR']})");
 92     }
 93 }
```

Of course, this means that all the requests from Dashboard should have HTTP_ORIGIN set to its own ORIGIN. Alternatively, one could also create a whitelist of HTTP_ORIGIN which have access to the Umbrella.

**Comment by ashakunt** [comment]
Next crucial items are: When the API has WRITE methods like POST, PUT, DELETE, then a user should be alerted before mocking that "this is going to actually change the data on the server".

**Comment by ashakunt** [comment]
Swagger UI already has an authentication/access control mechanism in-built. There are multiple authentication mechanisms in place, like oauth2, plain http, ftp etc. This can be found by clicking on the slider under the header in the right corner  (under the description of the method)

**Comment by ashakunt** [comment]
Did we already have CORS enabled? It would be good to cross check that Swagger's internal mocking actually works.

**Comment by brylie** [comment]
@JuusoV can we please have a status update here, based on your recent work/discussions?

**Comment by brylie** [comment]
@ashakunt, please follow up on the following CORS related issues in the API Umbrella tracker:
* [Cross-Origin Resource Sharing (CORS) support](https://github.com/NREL/api-umbrella/issues/81)
* [CORS error when making requests through API umbrella](https://github.com/NREL/api-umbrella/issues/116)

**Comment by bajiat** [comment]
@ashakunt, can you give me a status update?

**Comment by ashakunt** [comment]
@bajiat I need to check a few things and I will provide an update by EOD today.

**Comment by ashakunt** [comment]
I have tested the latest HEAD for mocking of API from the existing documentation (example JSON). It seems to work just fine.

**Comment by ashakunt** [comment]
All the above items are already a part of swagger-ui. Current installed version of api-umbrella is 0.8.0-1 and as per https://github.com/NREL/api-umbrella-gatekeeper/commit/9c275d79c8c1d1f82f37f9207a6e0b04c6eaae99, it is a part of https://github.com/NREL/api-umbrella-gatekeeper/releases/tag/v0.8.16 .

Hence, after the update is applied to umbrella, this should be solved.

**Comment by ashakunt** [comment]
I also realize that there is a workaround: https://github.com/NREL/api-umbrella-web/commit/e47d6d1b4f9c025583ed855d0c6635e0cb0e43cf and which is part of release already. So, imho, we are good to go.
