### ISSUE TITLE
Decide how to inform end-users of remote API status

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#332]
As Jukka (API consumer), I want to know, whether the API I'm using or interested in is alive or down.

### Definition of done
* [x] Determine how we can inform users about API status.
* [x] Determine what "alive" and "down" means and how to check the aliveness.
* [x] Create a Hackpad document describing the solution.
* [x]  Create a wireframe or diagram to show user is informed about the status.
* [x] Write example/pseudo code on checking the status.

**Comment by ashakunt** [comment]
@bajiat @brylie : I have added some notes and proposal to: https://apinf.hackpad.com/API-Status-notification-to-user-esXppZr8Dbe

Please take a look. I will do some more feasibility study to reach upto a level where we can focus on one single solution to move forward.

**Comment by ashakunt** [comment]
Hi, so basically, we can use a code-sample like this: 

```
 41     function returnStatus(req, status) {
 42         //console.log(req);
 43         if(status == 200) {
 44             console.log("The url is available");
 45             // send an event that all is OK: use GREEN BALL
 46         }
 47         else {
 48             console.log("The url returned status code " + status);
 49             // send a different event that looks like its not OK: YELLOW OR RED Ball based on status
 50         }
 51     }
 52 
 53     function fetchStatus(address) {
 54         var client = new XMLHttpRequest();
 55         console.log(client);
 56         client.onreadystatechange = function() {
 57             // in case of network errors this might not give reliable results
 58             if(this.readyState == 4)
 59                 returnStatus(this, this.status);
 60         }
 61         client.open("HEAD", address);
 62         client.send();
 63        }
```

when earlier: 

```
 12 $(document).ready(function() {
 13     console.log("Loaded");
 14 
 15     $('#isUp').click(function() {
 16         var url = $('#url').val();
 17         fetchStatus(url);
 18     });
 19});
```

and the UI is something like: 
``````
 9  <input type='text' id=url>
 10 <button id=isUp>IsUp</button>
``````

But this violates the Same Origin Policy since we want to make the Status call directly to the server hosting the API. Hence, CORS becomes our victim because not all APIs will have allowed CORS. Keeping this in mind, I suggest that we use a proxy on our own server which checks the API status and returns us the response as it is (see: Technic # 2 here: https://css-tricks.com/snippets/php/check-if-website-is-available/)

Relevant urls for this study and handson :

1. http://www.leggetter.co.uk/2010/03/12/making-cross-domain-javascript-requests-using-xmlhttprequest-or-xdomainrequest.html
1. https://css-tricks.com/snippets/php/check-if-website-is-available/
1. https://jvaneyck.wordpress.com/2014/01/07/cross-domain-requests-in-javascript/

**Comment by ashakunt** [comment]
I think now its a matter of decision as to how we should proceed. I propose to have a proxy php script that will take care of checking the API status. This script should be placed and accessible from our server hosting the dashboard, preferably on the same document_root.

**Comment by ashakunt** [comment]
@brylie, @bajiat any thoughts?

**Comment by brylie** [comment]
Lets keep our development efforts relegated to JavaScript. NPM has a [ping utility](https://www.npmjs.com/package/ping), which can be called from the servera or client without violating same origin.

**Comment by brylie** [comment]
Here is the example from NPM Ping:

```
var ping = require('ping');

var hosts = ['192.168.1.1', 'google.com', 'yahoo.com'];
hosts.forEach(function(host){
    ping.sys.probe(host, function(isAlive){
        var msg = isAlive ? 'host ' + host + ' is alive' : 'host ' + host + ' is dead';
        console.log(msg);
    });
});
```

From within the probe callback, we can set the status indicator for each API.

**Comment by ashakunt** [comment]
IMHO, ping would only define if the host is up or not. This does not guarantee if the API is working or not.  Hence, using npm-ping does not really solve the original question.

**Comment by brylie** [comment]
As pointed out in your [Hackpad document](https://apinf.hackpad.com/API-Status-notification-to-user-esXppZr8Dbe), PING may be an adequate indicator of backend 'aliveness'. Lets start there, as it is a simple tool to begin with.

**Comment by brylie** [comment]
Anoother tool we can use is the [HTTP status code](https://nodejs.org/api/http.html#http_message_statuscode) of response object from the remote backend. Since we are building on Node.js, we can write a function similar to the following ([source](http://stackoverflow.com/a/23712487/1191545)):

```javascript
https.get(options, function (response) {
  // Do something based on status code/message
  console.log(response.statusCode);
  console.log(response.statusMessage);
};
```

**Comment by ashakunt** [comment]
Looking at the hackpad document, my idea of ping was to show only the response timeout (performance) to access the API. But I definitely agree that it can be a  basic starting point, which MUST be improved further. As for http status code is concerned, the example that I put in my previous comments uses the same technique (just in JavaScript). If nodejs can handle that without any CORS complexity, IMHO, we should use that as the solution. :) What say?

**Comment by brylie** [comment]
Yep, lets go forward with ping/http response via NPM packages.

**Comment by ashakunt** [comment]
Great.

**Comment by bajiat** [comment]
@ashakunt @brylie Is it possible to proceed with implementing the functionality for the ping? I think the UI part (how to show the response on the UI) can be another task.

**Comment by brylie** [comment]
@bajiat it is possible to proceed. Who will proceed with this task?

**Comment by frenchbread** [comment]
@brylie @bajiat Can I take this one?

**Comment by brylie** [comment]
@bajiat and @frenchbread, I have added an issue (#395) to track the implementation of this feature.

**Comment by bajiat** [comment]
@frenchbread @brylie Thanks!
