### ISSUE TITLE
Implement privileges for all apiBackends publication

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#334]
For the catalog view, we need to publish a list of API backends.

 Definition of done
---
* [x] Create all apiBackends publication
* [ ] Subscribe to apiBackends publication in the catalog view.

**Comment by brylie** [comment]
PR #451 is open.

**Comment by brylie** [comment]
The second step is unnecessary, as we are using a Reactive Table in the catalogue view.
