### ISSUE TITLE
Choose code snippet generator

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#336]
As a developer I would like code snippets of APIs to be automatically generated in my preferred language.

Definition of done
---
* [x] Choose SDK generator for generating code examples based on API structure.
* [x] Implement the SDK generator in the Apinf infrastructure.
* [x]  Integrate the SDK generator to the Apinf UI.

**Comment by bajiat** [comment]
Related to 
RESTLET studio or Codebank

**Comment by bajiat** [comment]
@kyyberi What would you suggest for a code snippet generator?

**Comment by ashakunt** [comment]
Some options: 

1. We can use swagger-codegen which will generate snippets for most of the programming languages.
1. Similar support is also available in swagger-ui
1. We should consider other tools like: 
    1. Restlet
    1. CodeBank
    1. GitLab
    1. GitHub
Only when we think that the API manager is going to create the snippet (at least, for Codebank, GitLab and GitHub).

**Comment by ashakunt** [comment]
using swagger will kill many birds with one stone. (documentation, mocking and code snippet)

**Comment by JuusoV** [comment]
According to my understanding the current Swagger editor does produce snippets when you click generate server or generate client and download the code package. 
Can someone please confirm this so we can close the task?

You can review the editor here: http://editor.apinf.io:49160/#/

@ashakunt, @brylie @frenchbread

**Comment by ashakunt** [comment]
@bajiat yes. The current swagger editor does generate the snippets (as in, the whole SDK)
