### ISSUE TITLE
Research API umbrella web features

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#34]
Get to know more about API Umbrella web. Take notes and share them on the API Umbrella Github wiki, so the community benefits. Also, note the structure of the API Umbrella AII.

**Comment by bajiat** [comment]
Research and possibly document, in which cases the existing API Umbrella functionality can be utilized and enhanced through API's they are providing and in which cases it is necessary to build support e.g. with Ruby on Rails

**Comment by JuusoV** [comment]
Unfortunately there isn't much to document about the API Umbrella web. The features and everything else can be found here: http://apiumbrella.io/docs/getting-started/
