### ISSUE TITLE
Design UI for managing API backend managers

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#343]
Create an UI for adding or deleting managers for a given API backend based on user email.

# Wireframe
![API Managers UI wireframe](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23343_tab-view%26manager-view.png)

# Definition of done

## Display manager emails
* [x] Create `apiBackends` collection helper to retrieve Meteor users based on the `managerIds` field
* [ ] Create user interface to show of API managers for a given API.
  * [ ] Show name if available in user profile
  * [ ] Otherwise, show email (`user.emails[0].address` for example)
* [ ] User interface should be in Bootstrap component
  * [ ] Each manager in list will have 'delete' or similar button (see below)

## Add managers by email
* [ ] Create user interface  (text input with button) to enter new email address
  * [ ] When user inputs email address and clicks button, start invitation flow for new manager
* [ ] For adding managers, implement invitation user flow.
 * [ ]  Manager enters user email.
  * [ ] System emails user an invitation.
  * [ ] User clicks invitation link.
  * [ ] Registration step if user is not registered
  * [ ]  System adds user ID to array.

## Manage existing managers
* [ ] Add delete button or trash can or equivalent for deleting managers.
  * [ ] Add confirmation for the action.
* [ ] Check whether existing managers have update permission on the API backends collection.

# Related documentation
* [Meteor Users collection (Accounts)](http://docs.meteor.com/#/full/meteor_user)
* [Collection Helpers](https://github.com/dburles/meteor-collection-helpers)
* [MongoDB $in](http://docs.mongodb.org/manual/reference/operator/query/in/)
* [Bootstrap components](http://getbootstrap.com/components/)

**Comment by bajiat** [comment]
@ccsr FYI: We needed to remove this task from sprint 9. This means that in MVP any given API endpoint can only have a single API manager. This is not ideal, but the priority of the other tasks was so much higher and we could not fit this in.

**Comment by brylie** [comment]
You can use dburles:collection helpers to return all Manager  users for a given API Backend. We have the collection helpers package installed in our project. Collection helpers take the form of :

```
CollectionName.helpers({
  "helperName": function () {
    ... do something
   ... return something
  }
});
```

**Comment by mauriciovieira** [comment]
Branch ```feature/manage-apibackend-managers```

**Comment by mauriciovieira** [comment]
I am interested in taking this task.

**Comment by bajiat** [comment]
@mauriciovieira The task is yours to take. :) I believe you had already planned this task with Brylie. Please estimate the size.

**Comment by mauriciovieira** [comment]
@bajiat As soon as I finish #357 I will start this one.

**Comment by bajiat** [comment]
@mauriciovieira Can you inform me of the status of this task?

**Comment by mauriciovieira** [comment]
It is 30% done. I will move it back to 'ready' column

**Comment by brylie** [comment]
Sprint 15 co-pilot: @brylie

**Comment by bajiat** [comment]
@mauriciovieira Can you please add the estimate for size (remaining hours)? 13?

**Comment by mauriciovieira** [comment]
@bajiat 13 :-)

**Comment by mauriciovieira** [comment]
Work being performed on _feature/343-manage-apibackend-managers_

**Comment by brylie** [comment]
@mauriciovieira, what is the status of this issue?

**Comment by brylie** [comment]
@mauriciovieira, status update?

**Comment by mauriciovieira** [comment]
@brylie sorry. I did not work on that again. I am still working on https://github.com/brylie/meteor-api-umbrella/issues/1

**Comment by bajiat** [comment]
@mauriciovieira Would you be interested in taking this again?

**Comment by bajiat** [comment]
@mauriciovieira We decided to assign it to @frenchbread.

**Comment by frenchbread** [comment]
Created a first wireframe for API managers View, a simplified addition to API Backed View page. Api backend manage's template locates on a right side of the page. Bootstrap grid system can be used for it. 
At the same time, api manager's view can be either side menu that slides from the edge of the template or a static block. 

Main functionality (Adding/Inviting new user to be a manager, removing manager privilege) is provided.

![Image](https://raw.githubusercontent.com/apinf/docs/5adb2e55b261519a83df7a65d97836ea6a1b1834/docs/design/%23343%20api-anagers.png)

Second wireframe I am currently working on includes complete redesign of the API Backend View template. It includes tabs - "API Info", "Status", "Export", "Settings" and "Managers". In this case, manager view will be represented as a separate tab.

**Comment by frenchbread** [comment]
Here is Second wireframe for `Manager View`. As said, it includes some redesign with focus on tabs.
![Image](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23343_tab-view%26manager-view.png)

**Comment by brylie** [comment]
@kyyberi and @apinf/design , any feedback on the wireframes?

**Comment by kyyberi** [comment]
Looks good to me.

**Comment by elnzv** [comment]
Manager rights options are missing. (not sure if it is needed)
Otherwise looks good.
