### ISSUE TITLE
Exception "Sync API Umbrella Users and API Backends" Error: Server is required

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#346]
When starting Meteor on the *develop* branch, I am getting an error:
```
Error: Server is required
     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
     at app/server/methods/apiBackends.js:15:23
     at Array.forEach (native)
     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at [object Object].Meteor.methods.syncApiBackends (app/server/methods/apiBackends.js:9:9)
     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
     at packages/ddp/livedata_server.js:1530:1
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```
The error seems to be related to the **[server/methods/apiBackends.js:15:23](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/methods/apiBackends.js#L15)**, which is the [`syncApiBackends`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/methods/apiBackends.js#L2) method.

SyncedCron produces the same error, when I comment out the initial `Meteor.call("syncApiBackends")` in **[startup.js:16](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/startup.js#L16)**:

```
Exception "Sync API Umbrella Users and API Backends" Error: Server is required
```

**Comment by brylie** [comment]
@frenchbread, can you please look into this error? I am not sure what has changed recently to regress the `syncApiBackends` method.

**Comment by frenchbread** [comment]
@brylie Had the same error. In `develop` branch it somehow fixed itself after couple of server launches, but in `featire/api-config-import`, in [apiBackend Schema](https://github.com/apinf/api-umbrella-dashboard/pull/344/files#diff-32619b5d8051a66dc2ec81c4b012e59eL52) file I updated `server` and `matching` fields as optional. This could actually fix `develop` branch as well. Seems like hotfix needed.

**Comment by brylie** [comment]
Ah, this seems like a bug with API Umbrella then. Or at least, the REST API may not be returning all fields perhaps?

**Comment by brylie** [comment]
@frenchbread the keys `server` and `matching` may be invalid. API Umbrella uses `servers` and `url_matches` for those fields.

**Comment by frenchbread** [comment]
@brylie Agree, this could be an error on API Umbrella side. Since everything worked before and suddenly started to crash.

**Comment by brylie** [comment]
Well, it seems to be on our side, since we recently changed the schema required fields while our schema does not match the [API Umbrella Backend model](https://github.com/NREL/api-umbrella-web/blob/master/app/models/api.rb).

**Comment by brylie** [comment]
I updated the schema in my open pull request #345. Merging this pull request should hopefully resolve this problem.
