### ISSUE TITLE
Create route and view to display an existing API Backend

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#349]
Create a view for displaying API backend. Related to #324.

Definition of done
---
* [x] Create template to display fields of the API schema, with HTML markup.
  * [x] display at least the required fields for the API, as they should be present in any given API
* [x] Create route to display a given API (e.g. /api/{id})
* [x] Populate template with data taken from the API Id passed in from the route

**Comment by JuusoV** [comment]
Todo: Styling. 
Required fields (Optional: false) are in place and rendered in template in url: /api/API_ID_HERE/view
