### ISSUE TITLE
Add a method for selecting relevant Swagger file to Documentation browser

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#351]
In the documentation browser / Swagger viewer, there should be a method for selecting the relevant Swagger file / relevant API from the Swagger files that are available in the database. This could for instance be a drop-down list of the  APIs that have a related Swagger file.

Definition of done
---
* [x] Create select widget on View Documentation page
* [x] Autopopulate select widget filenames and URLs of all upladed API Documentation files
* [x] Render selected API Documentation in Swagger UI

**Comment by bajiat** [comment]
@elnzv Could you consider taking this task?

**Comment by bajiat** [comment]
There should be a way to access API documentation (Swagger) from the API backends catalog. This could for instance be a button or a link. Should be available only if there is a related file.

**Comment by elnzv** [comment]
Related branch: https://github.com/apinf/api-umbrella-dashboard/tree/feature/swagger-link

**Comment by brylie** [comment]
Opened PR #509

**Comment by bajiat** [comment]
@elnzv Can I close the issue? Didn't you review the PR and merge?
