### ISSUE TITLE
Inform user of API Umbrella errors when submitting API Backends form

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#357]
When a user submits the API Backend form, API Umbrella sometimes returns errors to the server. When the server receives an error, the user needs to be informed, as their API Backend may not be properly submitted to API Umbrella. One specific example is that API Umbrella will not accept a backend submission when filling in the `backend_host` field with a domain that does not exist.

# Task

* [x] Use the sAlert package or similar to display errors to the end user. 
* [x] Ensure that the API Backend is not inserted into the apiBackends collection, if there are API Umbrella errors in the response object.

**Comment by elnzv** [comment]
Error form server console:
```console
Exception while invoking method 'createApiBackendOnApiUmbrella' Error: failed [422] {"errors":{"servers[0].host":["Could not resolve host: no address for scdsc"]}}
```

**Comment by brylie** [comment]
We may need to update our schema to strictly align with the API Umbrella validation, as well as pass response errors to the end-user.

**Comment by mauriciovieira** [comment]
Another error: 
```
Exception while invoking method 'createApiBackendOnApiUmbrella' Error: failed [422] {"errors":{"frontend_host":["must be in the format of \"example.com\""],"backend_host":["must be in the format of \"example.com\""],"base":["must have at least one url_matches"],"servers[0].host":["must be in the format of \"example.com\"","Could not resolve host: no address for http://api.example.com"],"servers[0].port":["can't be blank","is not included in the list"]}}
```

and the fix should be placed at https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/methods/apiBackends.js#L33

**Comment by brylie** [comment]
We can use the sAlert package or similar to display errors to the end user. Also, the API Backend should not be inserted into the apiBackends collection if there are API Umbrella errors in the response object.

**Comment by mauriciovieira** [comment]
I think the solution might lie on changing https://github.com/brylie/meteor-api-umbrella/blob/master/server/admin-api/v1/apiBackends.js#L40 error handling.  After reading https://www.joyent.com/developers/node/design/errors#4-augment-the--code-error--code--object-with-properties-that-explain-details, I believe that _apiUmbrellaWeb.adminApi.v1.apiBackends.createApiBackend_ should throw an ApiUmbrellaError with details of the error, because I do not think that this error handling  is client's responsibility (in case, the client is api-umbrella-dashboard code).

**Comment by mauriciovieira** [comment]
See fc422662e05e10e3fdb98bc12b5cd0972df6780f

**Comment by brylie** [comment]
Thanks for the research. I would like to improve the package, but may need some pair-programming help.

**Comment by mauriciovieira** [comment]
PR #527 waits for code review.

**Comment by bajiat** [comment]
@mauriciovieira Something probably no-one has remembered to tell you. While a PR is under review, we have agreed to keep the size estimate for the original issue as 1.

**Comment by mauriciovieira** [comment]
@bajiat :+1:
