### ISSUE TITLE
Create minihackathon portal with registration form

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#360]
Create an information page on hackathon, which should contain a link to registration form (modal or new view). Information from the registration form should be stored automatically and a confirmation email should be sent.

Definition of done
---
* [x] Select portal platform.
* [x] Create subdomain.
* [x] Create pages defined in task #361.
* [x] Create registration form with mandatory and optional fields.
* [x] Ensure data submission can be exported to csv.
* [x] Send a notice of the form submission to an admin email (to be agreed).

**Comment by bajiat** [comment]
Refer e.g. to this: (http://hackathon.affecto.fi/)[http://hackathon.affecto.fi/]

**Comment by bajiat** [comment]
@elnzv Could you take this task?

**Comment by elnzv** [comment]
I suggest to use [https://www.google.com/forms](Google Forms) for registration. It's easier and faster.

**Comment by elnzv** [comment]
Suggested page sections (common for all hackathon web-sites): 
- About
- Register
- Schedule
- Sponsors
- Contact

**Comment by elnzv** [comment]
Related repo: https://github.com/apinf/hackathon
