### ISSUE TITLE
Organise brainstorming about hackathon challenge

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#364]
We need to come up with an idea for the minihackathon task. The developers will have 7 hours (minus lunch) to complete the challenge.

Definition of done
---
* [x] Organise a brainstorming session about the hackathon task
* [x] Make sure there are 3 well-defined challenges at the end of the brainstorming.
* [x] Document the ideas from the brainstorming

**Comment by Laura-Sampo** [comment]
Challenge: Create an application or integrate your existing application using Apinf.

More ideas: https://apinf.hackpad.com/Mini-hackathon-R2zjsiNqVG7
