### ISSUE TITLE
Rename swaggerConfiguration collection to apiDocumentation

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#366]
Rename Swagger configuration collection to apiDocumentation. Track down any other places where it is used in the code and in the UI and update. The term "Documentation" is more human-friendly and it allows us to later use other documentation approaches than Swagger.

Definition of done
---
* [x] Find out the current name of the collection.
* [x] Find all the places where the collection name or the name Swagger is used (both in code and on UI).
* [x] Update code and UI to use the more general term Documentation.

**Comment by bajiat** [comment]
@JuusoV Could you take this one?
