### ISSUE TITLE
Inform users that Documentation Browser makes calls directly to the remote APIs

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#367]
Swagger UI  'try it out' makes requests directly to the remote API. This means that operations such as PUT, POST, or DELETE will have the relevant effect on the remote server. To prevent accidental data loss or unexpected results, let users know that our documentation browser makes calls directly to the specific API.

# User story
As an Apinf administrator I want to warn Apinf users that API calls from Swagger are real calls

**Comment by bajiat** [comment]
@elnzv Would this be for you as well? It's connected to documentation tab (viewing documentation)

**Comment by elnzv** [comment]
@Nazarah, could you please help with text here?
