### ISSUE TITLE
Re-direct user to View API after uploading API configuration file

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#371]
After successfully an API backend configuration, re-direct the user to the single API view for the uploaded API.

**Comment by bajiat** [comment]
@frenchbread Did you already handle this functionality as a part of a different task/PR?

**Comment by frenchbread** [comment]
@bajiat Yes. The functionality has been already implemented and merged to develop. (Closed PR #344). Closing this issue.

**Comment by bajiat** [comment]
@frenchbread Thanks!
