### ISSUE TITLE
Check whether it is possible to autogenerate code snippets via API docs

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#373]
For generating code snippets directly into browser view and / or directly saving Swagger files to Apinf, determine if Swagger Editor has REST endpoint or other relevant approach.

Definition of done
---
* [x] Check the Swagger Editor documentation for any options to generate code snippets programmatically.
  * [x] E.g. check if Swagger Editor or CodeGen has REST interface
* [x] Communicate your findings to the team in written format.

**Comment by bajiat** [comment]
@JuusoV Would this task fit into your schedule?

**Comment by JuusoV** [comment]
Couldn't find available REST interface to interact with editor or Codegen.
[This] (http://swagger.io/specification/)  document only describes and documents the Swagger format itself.
@ashakunt may doublecheck if im mistaken

**Comment by ashakunt** [comment]
@JuusoV I could not find anything meaningful either. :(

**Comment by JuusoV** [comment]
thanks @ashakunt. 
Closing.
