### ISSUE TITLE
Re-organise project documentation

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#374]
Export Hackpad documents in markdown format and archive them in our docs folder in our Github repository.

Definition of done
---
* [x] Export Hackpad documents in markdown format.
* [x] Create documentation repository in the Apinf organization.
* [ ] Publish the exported documentation in the repository.
* [ ] Move any documentation from the api-umbrella-dashboard repository into documentation repository.
* [ ] Publish the documentation in the ReadTheDocs.org.

**Comment by brylie** [comment]
@kyyberi, we have exported all [Apinf Hackpad](http://apinf.hackpad.com) documents, and will be adding them to a new [documentation repository](https://github.com/apinf/docs). The content license for the Apinf Documentation repository is [CreativeCommons Zero](https://creativecommons.org/about/cc0). Is it alright that we include your APIOps contributions to our Hackpad in the new documentation repository?

**Comment by kyyberi** [comment]
I'm cool with that
