### ISSUE TITLE
Install community platform

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#375]
We have agreed to combine the Apinf and API Umbrella communities under API Umbrella. To this end, we need a community portal.  Please refer to the [community platform discusison](https://github.com/NREL/api-umbrella/issues/122) on the API Umbrella issue queue.

Definition of done
---
* [x] Choose the community platform.
* [x] Create VM or Docker instance.
* [ ] Create subdomain.
* [ ] Point subdomain to VM.
* [x] Install community platform on VM or Docker instance.
* [x] Perform initial configuration on community platform.
 * [ ] [Reverse proxy](http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/)
  * [ ] Mailgun
  * [ ] Initial admins
  * [ ] Initial categories (e.g. Apinf, API Umbrella, Finland, ...)
  * [ ] Branding text (such as welcome message)

**Comment by ashakunt** [comment]
Please provide the details of the VM (with access to me) so that I can go ahead and install a discussion platform, e.g. discourse.

**Comment by brylie** [comment]
@ashakunt please follow up directly with Chandra on this task, as he will be creating the VM.

**Comment by ccsr** [comment]
@ashakunt & @brylie I am trying to get one IP free from our pool so that we can create the VM. Are we still using Discourse?

**Comment by ashakunt** [comment]
@ccsr  discourse seems to be a pretty nice option. So, for now yes. Although, one could also fall back to google-groups or other similar offerings. But I am not sure if we want to go there using apinf?

**Comment by ccsr** [comment]
@ashakunt No Google stuff in this project please. thanks

**Comment by ashakunt** [comment]
On the lighter note, @ccsr ; what will be do without google ... (search)

**Comment by ccsr** [comment]
@ashakunt I recommend https://duckduckgo.com/

**Comment by ccsr** [comment]
Assigning to @ccsr

**Comment by ashakunt** [comment]
@ccsr : quack! please let me know when the VM is done (with relevant credentials)

**Comment by ccsr** [comment]
@ashakunt you should have all the details now

**Comment by ashakunt** [comment]
@ccsr can you please first create a domain and point that to the VM (hack.apinf.io)?

**Comment by ashakunt** [comment]
@ccsr It would also be required to create a mailgun credential for this website. So, please get the following items  done: 

 [  ] Create a new VM (since hack.apinf is already running docker, we cannot run discourse, which also requires docker)
 [  ] Create a subdomain (e.g. discourse.apinf.io)
 [  ] Point this subdomain to VM 
 [  ] Create mailgun account for discourse.apinf.io 
 [  ] Share the credentials for mailgun with me

**Comment by ashakunt** [comment]
Other alternatives are to run other forum software, e.g. phpBB or bbPress (by wordpress, installs as a plugin to wordpress); but they will be running on NON DEFAULT ports which is not what we want. So, a new VM + IP is required.

**Comment by brylie** [comment]
If Discourse is dockerized, it should run fine on the [same VM with another dockerized application](https://docs.docker.com/introduction/understanding-docker/#what-is-docker-s-architecture). As far as I understand, that is one of the benefits of containerization.

**Comment by ashakunt** [comment]
@brylie, thanks, I guess I would have been misguided. I will check that as soon as I am in office and close it. 

--
Excuse typos, sent from mobile device!

-----Original Message-----

**Comment by ashakunt** [comment]
@ccsr @brylie 

Please still provide a mailgun account, which is required during installation + subdomain mapped to the VM.

**Comment by ashakunt** [comment]
@ccsr discourse has been installed at the VM. I have use sandbox mailgun credentials that might or might not work. So, please provide a valid mailgun credential for this purpose. Also, after the subdomain is available and mapped to the VM, we have to fix the url. Currently, the installation is accessible at: hack.apinf.io:8080

**Comment by ccsr** [comment]
@ashakunt This is community portal for apiumbrella.io and not for apinf.io
We need to wait till it happens from apiumbrella.io

**Comment by ashakunt** [comment]
@ccsr  in that case, should I shut down the app right now and we turn it on only where there are actual credentials available?

**Comment by ccsr** [comment]
@ashakunt this is depending on the issue https://github.com/NREL/api-umbrella/issues/122#issuecomment-135655971

**Comment by ccsr** [comment]
@ashakunt So you can safely shutdown

**Comment by ashakunt** [comment]
Ok. So, discourse has been installed already and seems to work (on port 8080). Once we have the proper credentials, we need to fill them up here:

```
  DISCOURSE_SMTP_PORT: 465                      # (optional)
  #DISCOURSE_SMTP_USER_NAME: "mailgun smtp username"      # (optional)
  #DISCOURSE_SMTP_PASSWORD: "mailgun smtp password"              # (optional)
  DISCOURSE_SMTP_ENABLE_START_TLS: true           # (optional, default true)
```

After this: sudo ./launcher rebuild app

**Comment by ashakunt** [comment]
(as of now, the docker has been stopped)

**Comment by brylie** [comment]
I am getting errors when trying to load *hack.apinf.io:8080*. Is the Discourse platform still running? Also, we will need to set up a reverse proxy, so that end-users do not have to enter a port number when visiting the community site.

**Comment by ashakunt** [comment]
@brylie based on the comments from @ccsr (and myself), the docker is currently turned OFF. My understanding is that it will be turned on once we have the correct mailgun credentials for api-umbrella.

**Comment by ccsr** [comment]
@brylie  I am able to get in with out using 8080

**Comment by ashakunt** [comment]
@ccsr you must be getting into hack.apinf.io. Not the discourse installation.

**Comment by ashakunt** [comment]
@brylie , Yes, when I have the information about what domain to use, we will setup a reverse proxy.
