### ISSUE TITLE
Implement feature that informs user about API status via ping and HTTP status code

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#395]
End-users want to see API status at-a-glance. Design a UI feature and server-side method(s) to check remote API 'aliveness' and inform user.

* [x] Implement function to check aliveness of API backend and how to show it on the UI.
  * [x] Ping
  * [x] HTTP Status Code
* [x] Create UI mockup(s) for showing API status to end-user(s)
* [x] Create Template to display status information for a given API
* [x] Include the API Status Template in relevant templates
  * [ ] My Managed APIs
  * [x] Single API view

**Comment by brylie** [comment]
Here is the example from [NPM Ping](https://www.npmjs.com/package/ping):

```javascript
var ping = require('ping');

var hosts = ['192.168.1.1', 'google.com', 'yahoo.com'];
hosts.forEach(function(host){
    ping.sys.probe(host, function(isAlive){
        var msg = isAlive ? 'host ' + host + ' is alive' : 'host ' + host + ' is dead';
        console.log(msg);
    });
});
```

From within the Method callback, we can set the status indicator for each API.

**Comment by brylie** [comment]
For additional detail, we can possibly use is the [Node.js HTTP status code](https://nodejs.org/api/http.html#http_message_statuscode) of a response object from the remote backend. Since we are building on Node.js, we can write a function similar to the following ([source](http://stackoverflow.com/a/23712487/1191545)):

```javascript
https.get(options, function (response) {
  // Do something based on status code/message
  console.log(response.statusCode);
  console.log(response.statusMessage);
};
```

**Comment by ashakunt** [comment]
+1

**Comment by frenchbread** [comment]
I've been using `HTTP.call()` in previous tasks - works out nicely, so I think we can run with this one.

**Comment by frenchbread** [comment]
PR #396 created. Please review.
