### ISSUE TITLE
Deploy beta version

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#409]
Deploy the beta release of Apinf on Apinf.io.

Definition of done
---
* [x] Re-purpose apinf.io VM for Apinf (Meteor).
* [x] Deploy Apinf to re-purposed VM.
* [x] Configure Apinf deployment to use umbrella.apinf.io as backend.
* [x] Make other configurations
  * [x] admins
  * [x] Github
  * [x] Mailgun
  * [x] Elastic
* [x] Create re-direct from Apinf.com to Apinf.io.

**Comment by bajiat** [comment]
@ccsr Beta release is now available.
@elnzv Please assist @ccsr by providing credentials and configuration information for beta deployment.

**Comment by elnzv** [comment]
@bajiat I can easily do it myself. @ccsr, couple things: VM address (with root access) and domain name.

**Comment by bajiat** [comment]
@elnzv What's the status? Have you registered as the first admin in the deployment? Did you install the SSL certificate?
