### ISSUE TITLE
Research how the team can promote Apinf in social media as a team

### ISSUE THREAD

**Issue by ccsr** [apinf/api-umbrella-dashboard#417]
Can we use http://www.smarpshare.com/ for getting team involved in social media reach out.

**Comment by elnzv** [comment]
http://www.postplanner.com/
Post Planner makes it easy for people to find and share amazing content consistently - to get predictable, measurable, and remarkable results with their social media posts on Facebook and Twitter.

https://buffer.com/
Buffer is the easiest way to publish on social media. It has analytic, schedule and other cool features.
