### ISSUE TITLE
Study social networks for developers

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#418]
Study social media / networks used by developers and give recommendations for Apinf project on which social networks to use for promotion in addition to the current social media.

**Comment by bajiat** [comment]
@ccsr Do you want to keep working on this task in Sprint 12?

**Comment by frenchbread** [comment]
I am personally interested in this task since I have been spending a lot of time roaming at such services for developers so can suggest some popular ones. Saying it just for the record. But it is up to you, guys, to decide who gonna take this one.

**Comment by bajiat** [comment]
@ccsr or @frencbread Either of you interested in this task and have the time for it?

**Comment by frenchbread** [comment]
@bajiat I'll take this one.

**Comment by frenchbread** [comment]
I've added a new document to [hackpad](https://apinf.hackpad.com/Social-networks-for-developers-bR4Cm7P9jBh) which lists and describes most of popular social networks for developers that know about so far. Please feel free to add more.
