### ISSUE TITLE
Add user-confirmation on success when submitting Add API Backend form

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#426]
When a user successfully submits the Add API Backend form, display a confirmation message.

Definition of done
---
* [x] Add autoform `onSuccess` hook to Add API backend form.
* [ ] Using `onSuccess` hook  display success message on UI.
* [x] Redirect to API view.

**Comment by elnzv** [comment]
onSuccess message added.

**Comment by brylie** [comment]
I am assigning Mauricio (@mauriciovieira) to this task.

**Comment by mauriciovieira** [comment]
"Redirect to API view." is done.

**Comment by brylie** [comment]
We determined the UI message was not necessary, so removed it from the onSuccess callback.
