### ISSUE TITLE
Add or edit help text for the fields of Add API Backend form

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#427]
The Add API Backend form is poorly documented. Add descriptive notes to all fields on the form, so that users can understand their purpose.

Definition of done
---
* [x] Create the [Add API Backend Form help text document](https://github.com/apinf/api-umbrella-dashboard/wiki/Add-API-Backend-form-help-text) to create draft copy for help text
* [ ] Update [Add API Backend Form help text document](https://github.com/apinf/api-umbrella-dashboard/wiki/Add-API-Backend-form-help-text) with relevant help text for each field
* [ ] Update the helps texts on the HTML form.

**Comment by brylie** [comment]
@elnzv has already created some inline help example code that can be used for this task.

**Comment by elnzv** [comment]
Here is the branch with inline help block:
https://github.com/apinf/api-umbrella-dashboard/tree/feature/help-block-charts

**Comment by elnzv** [comment]
Added hint block to API Backends Form. Continue adding the rest of them.
Will take basic hints and examples from original API Unbrella Add API Form.

**Comment by elnzv** [comment]
Here is new working branch - https://github.com/apinf/api-umbrella-dashboard/tree/feature/apibackend-form-hints

**Comment by bajiat** [comment]
@elnzv As suggested last week, it might be best to list the fields and the current/proposed texts in a Hackpad document or similar so that @brylie and maybe even I could review and comments those even if we don't have a chance to sit down and work on those together.

**Comment by brylie** [comment]
@elnzv please see the [Add API Backend Form help text document](https://github.com/apinf/api-umbrella-dashboard/wiki/Add-API-Backend-form-help-text).
