### ISSUE TITLE
Add general description of key terms and form elements on Add API Backend form

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#429]
Some of the concepts on the Add API Backend form, such as prefix and hosts, can confuse new users. Make sure we are providing adequate explanation of all relevant concepts, so that users can easily submit the Add API Backend form.

**Comment by brylie** [comment]
It might also be advisable to relate the specific technical terms to general concepts.

**Comment by elnzv** [comment]
Interested

**Comment by bajiat** [comment]
Duplicate.
