### ISSUE TITLE
Add inline help to documentation link and documentation upload fields on Add API Backend form

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#431]
The documentation fields are proving quite confusing for new users. Add descriptive text with examples on both the Documentation link and documentation upload fields, so that users can determine what the fields expect.

Related #425, #427 

Definition of done
---
* [ ] Update the [Add API Backend Form help text document](https://github.com/apinf/api-umbrella-dashboard/wiki/Add-API-Backend-form-help-text)
* [ ] Determine how to explain the purpose of the fields as briefly as possible.
* [ ] Add inline help texts.
* [ ] Optionally, also modify the field labels.

**Comment by brylie** [comment]
@elnzv please update the [Add API Backend Form help text document](https://github.com/apinf/api-umbrella-dashboard/wiki/Add-API-Backend-form-help-text).

**Comment by elnzv** [comment]
Closed in #534 PR.
