### ISSUE TITLE
Clean up API catalog

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#457]
Api backends catalog contains testing and duplicate APIs. These need to be removed before demonstrating Apinf at MindTrek.

Definition of done
---
* [x] Remove unnecessary API backends from API Umbrella.
* [ ] Re-set the database for Apinf.io.
* [ ] Check that Apinf has synchronised backends from API Umbrella and all the unnecessary API backends have been removed.

**Comment by brylie** [comment]
@elnzv, would you please reset the database on the apinf.io deployment?

**Comment by elnzv** [comment]
@brylie, yes, I will do it later today.
