### ISSUE TITLE
Troubleshoot API Umbrella 404 error when using APIs

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#459]
Related issue https://github.com/NREL/api-umbrella/issues/168

Definition of done
---
* [x] Make a successful request to a remote API backend configured through Apinf.

**Comment by ashakunt** [comment]
This was done and api umbrella installation is now fixed. The problem was in underlying nginx package and actual fix should go to NREL. For now, the error is fixed and all is good.
