### ISSUE TITLE
Plan workshop outline and topics

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#460]
Definition of done
---
* [x] Type the [basic outline](https://github.com/apinf/docs/blob/master/docs/organization/outreach/Mindtrek-Apinf-Launch-Workshop.md#outline) from brainstorming notes.
* [ ] Add brief details about each topics into outline.
* [ ] Determine ways to encourage and reward participation.
* [ ] Figure out how to divide the audience into working groups.
* [ ] Figure out how working groups will present their main findings.

**Comment by brylie** [comment]
[Outline work in progress](https://github.com/apinf/docs/blob/master/docs/organization/outreach/Mindtrek-Apinf-Launch-Workshop.md#outline).
