### ISSUE TITLE
Show the API call url after api has been added

### ISSUE THREAD

**Issue by ashakunt** [apinf/api-umbrella-dashboard#469]
Based on feedback from hackathon: Once the API has been successfully added, a feedback should be shown that it was done (issue#426). At the same time, the api access URL must be shown to the user. Currently, the user has no idea where to make an api call after having added it in the dashboard.

## Definition of Done
* [ ] After a confirmation is made ```onsuccess``` of adding api, show the URL to the user which is like: ```https://umbrella.apinf.io/[frontend-prefix]/?api_key=[api_key]&key1=val1...```
* [ ] The same information as shown above should be shown at manage api section

**Comment by ashakunt** [comment]
@bajiat please review above. We missed to add it in hackathon notes.

**Comment by bajiat** [comment]
@ashakunt This is a good idea for an enhancement.
