### ISSUE TITLE
Design API Rating field and widget

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#471]
Design functionality for consumers to be able to rate API Backends on a numeric scale via a simple widget.

Definition of done
---
* [x] Brainstorm ideas for rating.
  * [x] Look for and document existing examples of rating applications etc.
* [x] Create design document for the rating functionality. (This may include user flow, schema etc.)
* [x] Create wireframes for rating UI.

**Comment by bajiat** [comment]
@elnzv Can you provide a status provide and commit any work in progress, even design pictures, to Github?

**Comment by elnzv** [comment]
added wireframes to docs repo:
https://github.com/apinf/docs/blob/master/docs/design/%23471_rating_field_widget.png

**Comment by elnzv** [comment]
@bajiat please review, if you have any comments, let me know.

**Comment by bajiat** [comment]
@elnzv I would suggest that you would indicate your own preference for the three options and also explain the pros and cons of each. Also, please indicate how a user can  rate the APIs or vote for them in each.

**Comment by elnzv** [comment]
@bajiat, added suggested information

**Comment by bajiat** [comment]
@elnzv Excellent additions! You can perhaps still say explicitly which one do you recommend (I quess it's the one with stars) and then close the issue.

**Comment by elnzv** [comment]
@bajiat, already done this - next to Stars' title my comment.

**Comment by bajiat** [comment]
@elnzv Ok, I managed to somehow ignore that and noticed only the visual feedback and the pros and cons. Then everything's just fine, go ahead and close the issue.
