### ISSUE TITLE
Add API Metadata form, schema, and template

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#472]
Create a form to collect API metadata. Also make sure end-users can view metadata when browsing API Backends.

See picture for Palveluväylä metadata model:
![metadata model from Palveluväylä](https://cloud.githubusercontent.com/assets/1927158/11168086/e1ca8e9c-8b88-11e5-92cc-9e0e2c1352f0.png)

Check also NREL's standard for data.gov.

Definition of done
---
* [x] API metadata schema exists.
  * [ ] API metadata schema contains a selection of attributes from Palveluväylä metadata model.
* [x] API metadata schema is attached to API metadata collection.
* [x] API metadata view for showing metadata is accessible for all users from View API backend page.
* [x] API metadata input and edit form is accessible by managers from My managed APIs.
* [ ] Api managers and system administrators can **insert** API metadata for their managed APIs.
* [ ] Api managers  and system administrators  can **update** API metadata for their managed APIs.
* [ ] Api managers  and system administrators can **delete** API metadata for their managed APIs.

**Comment by bajiat** [comment]
![metadata model from Palveluväylä](https://cloud.githubusercontent.com/assets/1927158/11168086/e1ca8e9c-8b88-11e5-92cc-9e0e2c1352f0.png)

**Comment by brylie** [comment]
Current work in progress:
![screen shot 2016-01-12 at 15 31 41](https://cloud.githubusercontent.com/assets/17307/12264779/a2c56a64-b941-11e5-9444-16d6f25c719c.png)

**Comment by brylie** [comment]
Current status:
![screen shot 2016-01-13 at 13 47 46](https://cloud.githubusercontent.com/assets/17307/12293448/4f47d334-b9fc-11e5-8fbb-374d9bb2789e.png)

**Comment by brylie** [comment]
Note, in Firefox, the date input renders as a plain text box. Other browsers, such as Chromium, render a date select widget. We can add a [polyfill](http://afarkas.github.io/webshim/demos/index.html#Forms-forms-ext) to our project that will [display a user-friendly date selection widget on date inputs](http://jsfiddle.net/trixta/BMEc9/).

**Comment by brylie** [comment]
As part of the metadata task, I am adding a metadata section to the "view API Backend" page. On the way to this goal, I re-architected the `viewApiBackend` template to follow the component model described in the Meteor Guide and added a tabbed navigation along top:

![screen shot 2016-01-15 at 16 03 16](https://cloud.githubusercontent.com/assets/17307/12354907/da067b28-bba1-11e5-87e8-92f14fa33611.png)

![screen shot 2016-01-15 at 16 06 10](https://cloud.githubusercontent.com/assets/17307/12354926/ef243b26-bba1-11e5-98c2-0a138d8e1300.png)

![screen shot 2016-01-15 at 16 06 07](https://cloud.githubusercontent.com/assets/17307/12354921/ec98d57e-bba1-11e5-97d4-2aeb30903d53.png)

This task will continue next sprint.

**Comment by brylie** [comment]
@frenchbread please be aware of the tabbed navigation interface while working on your API Backlog feature. You can see my working code in the feature/api-metadata branch.

**Comment by frenchbread** [comment]
@brylie Looks good. 

Should not affect "backlog feature" functionality since its current navigation is an additional button before "View Usage Instructions" button .

:bulb:  Or I can remove it and you add tab "Backlog" with link to `api/:id/backlog` with empty content for now?

Also I think that each of this tabs should have its own route.

**Comment by brylie** [comment]
@frenchbread for consistency, the Backlog will be another tab on the navigation menu. E.g. 

* [Details]
* [Metadata]
* [Feedback]
* [Backlog]
* [Export]

**Comment by frenchbread** [comment]
@brylie Yeah, that's what I meant. What about tabs having its own routes? (this could be different issue)

**Comment by brylie** [comment]
Bootstrap Tabs use hash routes (e.g. /api/:id#backlog) by default. At least how I chose to add them.

**Comment by brylie** [comment]
Metadata UI and forms for insert/update are working. Fields and metadata panels conditionally display on metadata tab.

**Comment by brylie** [comment]
I would like to add the access control checks as an enhancement feature, so that we can merge this PR.
