### ISSUE TITLE
Test adding and using a SOAP API

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#480]
In order to support legacy APIs, we need to test a SOAP-based API through our proxy. This task is to test API Umbrella for SOAP support, so does not involve the Apika frontend as such.

Definition of done
---
* [x] Find at least one open SOAP API.
* [x] Add the SOAP API to **umbrella.apinf.io**.
* [x] Test the SOAP API through **umbrella.apinf.io**.
  * [x] If additional support is required, document any additional implementation needs as Github issues.

**Comment by preriasusi** [comment]
Planning to test Soap weather api:  http://www.webservicex.com/New/Home/ServiceDetail/56

**Comment by preriasusi** [comment]
Doesn't look it it works. 
The respond I get is:


---------------------8<------------------------------
<!DOCTYPE html>
<html>
    <head>
        <title>The page you were looking for doesn't exist (404)</title>
        <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
    </head>
    <body>
        
        <div class="dialog">
            <h1>The page you were looking for doesn't exist.</h1>
            <p>You may have mistyped the address or the page may have moved.</p>
        </div>
    </body>
</html>
----------------------------->8----------------------

Rechecking tomorrow.

**Comment by brylie** [comment]
@jykae, this issue description now indicates to test the SOAP API on **umbrella.apinf.io**. Please log in directly to API Umbrella and configure the SOAP API there.

**Comment by jykae** [comment]
@brylie umbrella.apinf.io is not working at the moment, I can't test it there.

**Comment by brylie** [comment]
OK, what is the error with umbrella.apinf.io?

**Comment by jykae** [comment]
Tested with Postman, works. Must understand the usage of the API first. With SOAP API the parameters are sent within XML data in request body. SOAPAction and Content-Type must be defined in the request header.

Example call using Umbrella: https://umbrella.apinf.io/getWeather/globalweather.asmx?api_key=xxx&op=GetWeather
```
POST /globalweather.asmx HTTP/1.1
Host: www.webservicex.com
Content-Type: text/xml; charset=utf-8
Content-Length: length
SOAPAction: "http://www.webserviceX.NET/GetWeather"

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetWeather xmlns="http://www.webserviceX.NET">
      <CityName>string</CityName>
      <CountryName>string</CountryName>
    </GetWeather>
  </soap:Body>
</soap:Envelope>
```
Successful Result when using CityName: "Tampere" and CountryName: "Finland"

<img width="939" alt="nayttokuva 2015-12-17 kello 16 26 30" src="https://cloud.githubusercontent.com/assets/293452/11871990/a2de55b2-a4db-11e5-9da7-0a0c96279c2c.png">

**Comment by jykae** [comment]
Umbrella is proxy and whatever type of API should work if it's configured correctly in Umbrella as long as we are calling over HTTP, using headers correctly and passing JSON or XML data. Umbrella forwards headers, params & data as is if we are not defining anything advanced mechanisms.

Understanding usage of the API is of course crucial, before user can use it with proxy.

**Comment by jykae** [comment]
@bajiat @brylie @preriasusi Should I demonstrate this or is this enough information?

**Comment by preriasusi** [comment]
Sounds like done to me. Enough.

**Comment by brylie** [comment]
Great work @jykae :-)

**Comment by bajiat** [comment]
Thanks for the research @jykae. Do you think it's possible to add the SOAP API using Apinf UI?

**Comment by bajiat** [comment]
Let's try adding a SOAP API using the Apinf UI and take screen captures of the process.

**Comment by jykae** [comment]
This seems to work from Apinf as well. Maybe I could take screenshots by using the latest simple Wizard form. Those fields are enough to add this. 
Or using couple of header fields: "Content-Type" and "SOAPAction" with Advanced form could simplify the API call.

**Comment by jykae** [comment]
I had to remove one API backend from umbrella.apinf.io that caused everything to proxy to google.com. If user puts just "/" to frontend prefix, Umbrella seems to proxy everything to the defined API backend. This should be somehow prevented.

**Comment by jykae** [comment]
Step 1:
![soap1](https://cloud.githubusercontent.com/assets/293452/12063667/4eb315f0-afbb-11e5-9edd-2b03bc00d60c.png)
Step 2:
![soap2](https://cloud.githubusercontent.com/assets/293452/12063666/4eb2ca1e-afbb-11e5-96ae-13b55a11a4ea.png)
Step 3:
![soap3](https://cloud.githubusercontent.com/assets/293452/12063665/4eb2ae94-afbb-11e5-80ec-49ba6dba31e6.png)
Step 4:
![soap4](https://cloud.githubusercontent.com/assets/293452/12063664/4eb2a66a-afbb-11e5-9e3a-ad3924a86af4.png)

Making call with Postman to URL: https://umbrella.apinf.io/soapweather/globalweather.asmx?api_key=xxx&op=GetWeather

where xxx = the API key in loggedin user's profile page.

![soap5](https://cloud.githubusercontent.com/assets/293452/12063668/4eb524b2-afbb-11e5-9d3a-71a5a6b7cc05.png)

Headers for the request:
![soapheaders](https://cloud.githubusercontent.com/assets/293452/12063669/4eb6e716-afbb-11e5-8cd6-cfe0db2f2323.png)

**Comment by jykae** [comment]
I used the latest develop version nightly.apinf.io.

**Comment by bajiat** [comment]
Add the steps and screenshots for adding API and calling it here: https://github.com/apinf/docs/blob/master/docs/support/Adding-SOAP-API.md

**Comment by jykae** [comment]
Updated the support doc above. Closing.
