### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#481]
In order to be able to present the user interface to people in their native languages, we need to internationalize our project.

Definition of done
---
* [x] Choose i18n framework.
* [x] Add basic i18n markup in UI templates for text strings.
* [ ] Document the logic for creating the string id's.

**Comment by elnzv** [comment]
Chose [tap-i18n](https://github.com/TAPevents/tap-i18n)

**Comment by elnzv** [comment]
For autoform [Meteor Autoform i18n](https://github.com/gwendall/meteor-autoform-i18n/)

**Comment by elnzv** [comment]
Added  i18n markup in  for all text strings except form elements.

**Comment by brylie** [comment]
We might also need to add i18n support to our collections via [tap:i18n-db](https://github.com/TAPevents/tap-i18n-db). See [demonstration video](https://www.youtube.com/watch?v=cu_dsoIc_0E).

**Comment by brylie** [comment]
There appear to be user interface helpers for language selection, etc. as part of the [tap:i18n-ui](https://github.com/TAPevents/tap-i18n-ui) package.

**Comment by bajiat** [comment]
@elnzv We moved some of the work for this task to a new task: #508. You could open a PR already for this task. Brylie has promised to review it, if it is open before Friday.
