### ISSUE TITLE
Design API backlog

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#482]
Design API backlog or roadmap functionality and user flow.

Definition of done
---
* [x] Brainstorm ideas for API backlog.
  * [x] Look for and document existing examples of backlog / feature planning etc.
* [x] Create design document for the API backlog. (This may include user flow, schema etc.)
* [x] Create wireframes for API backlog UI.

**Comment by bajiat** [comment]
@elnzv Can you provide a status provide and commit any work in progress, even design pictures, to Github?

**Comment by bajiat** [comment]
@elnzv I'm moving this task to pre-planning for next sprint and unassigning it.

**Comment by elnzv** [comment]
Have almost done this task. Need to move wireframes, ideas and design document from my notepad to the digital form.

**Comment by brylie** [comment]
@elnzv please keep us updated more regularly with design artefacts.

**Comment by elnzv** [comment]
added wireframes to docs repo:
https://github.com/apinf/docs/blob/master/docs/design/%23482_api_backlog_apinf.png

@apinf/design, please review.

**Comment by kyyberi** [comment]
Looks like a good start from my perspective
