### ISSUE TITLE
Create Getting started package for developers

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#485]
At the moment, we only have basic installation instructions. Developers need more help getting started.

Definition of done
---
* [x] Create a [contributor guide](https://github.com/apinf/docs/blob/master/docs/develop/contributing.md) for new community members
* [x] Create outline of how to setup local development environment.
* [x] Add outline to Readme and documentation repository.
* [ ] Decide whether a development link should be added to Apinf.io and where it should lead (issue queue?)

**Comment by brylie** [comment]
Added the [Apinf contributer guide](https://github.com/apinf/docs/blob/master/docs/develop/contributing.md) file to contain an overview of how to get involved.

**Comment by brylie** [comment]
I have updated the installation documentation on the Master branch. It now includes more detail about Mailgun and a link to the API Umbrella developer setup instructions.
