### ISSUE TITLE
Document standards for API metadata

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#488]
In order to be able to design API metadata form, it is necessary to research and document the metadata requirements / standards.
Related to #472.

Definition of done
---
* [ ] Find out the contact point for metadata for National data exchange layer in Finland (Palveluväylä).
* [ ] Check also metadata standard for data.gov.
* [ ] Locate and document additional governmental or international API metadata standards

**Comment by brylie** [comment]
I have started a [API Metadata Standards](https://github.com/apinf/docs/blob/master/docs/research/API%20Metadata%20Standards.md) document.

**Comment by brylie** [comment]
@bajiat do you have the contact information for the Palveluväylä organization?

**Comment by bajiat** [comment]
@brylie I might be able to discuss this tomorrow, since I will be in Helsinki in a meeting that is related to Palveluväylä.
BTW, have you seen this: [API section in Government Service Design Manual](https://www.gov.uk/service-manual/making-software/apis.html)? Not about metadata as such, but related to API standards. Largely compatible with [White House API standards](https://github.com/WhiteHouse/api-standards)
