### ISSUE TITLE
Create presentation materials for visiting lecture

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#490]
There is visiting lecture on 29 September at TUT about Real-time open web technologies. Design a presentation about the given topic.

Definition of done
---
* [x] Create topic outline for presentation.
* [x] Organize topic outline for flow.
* [x] Create slides for each topic.
  * [x] If possible, ask for peer review on slides.
* [x] Rehearse slides for flow.
* [x] Deliver lecture.

**Comment by bajiat** [comment]
@brylie Could you provide a link to your material?

**Comment by brylie** [comment]
The slides are available on [Github](https://github.com/brylie/realtime-open-web/blob/master/README.md) and can be viewed in online presentation mode](https://gnab.github.io/remark/remarkise?url=https%3A%2F%2Fraw.githubusercontent.com%2Fbrylie%2Frealtime-open-web%2Fmaster%2FREADME.md#1).
