### ISSUE TITLE
Move all schema definitions under the global Schemas object

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#497]
We are currently defining our schemas as global variables. This causes unnecessary clutter of our global namespace. Move all schema definitions to attributes of the global Schemas object.

Task
---
* [x] Make list of all project schema definitions
* [x] Move each schema definition to an attribute of the Schemas object
* [x] Update the collection-schema attachment lines to use the global Schemas object/attribute

**Comment by mauriciovieira** [comment]
Schema definitions list: 
- **both/collections/apiUmbrellaUsers.js**: _ApiUmbrellaUsersSchema_
- **both/collections/apiUmbrellaAdmins.js**: _ApiUmbrellaAdminsSchema_
- **both/collections/rateLimit.js** - _RateLimitSchema_
- **both/collections/roles.js** - _RolesSchema_
- **both/collections/users.js** - _Schemas.UserProfile_ and _Schemas.User_
- **both/contactForm.js** - _Schemas.contact_
- **lib/NCSchemas.js** - _NCSchemas.updatePassword_

**Comment by mauriciovieira** [comment]
@brylie please :mag:  #516
