### ISSUE TITLE
Create installation package(s)

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#500]
Create installation package(s) for Apinf. Specifically, a Docker file and Debian packaging might be desirable.

See e.g. [Kong Installation](https://getkong.org/install/)

**Comment by brylie** [comment]
@jykae, please consider contributing towards this task.

**Comment by bajiat** [comment]
Related to #511

**Comment by bajiat** [comment]
@shaliko Is this already completed?

**Comment by bajiat** [comment]
Closing as duplicate.
