### ISSUE TITLE
Upgrade packages, including Meteor 1.2

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#506]
Upgrade all project packages including meteor core, which is now at 1.2)

**Comment by bajiat** [comment]
PR is open.

**Comment by bajiat** [comment]
@frenchbread Can I close this issue? Wasn't the PR #509 you reviewed and merged related to this task?

**Comment by frenchbread** [comment]
@bajiat PR #514 was related. Closing this issue.
