### ISSUE TITLE
Implement API backlog

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#518]
Related to #482

![wireframe](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23482_api_backlog_apinf.png)

Note: even though the wireframe contains labels / tags for backlog items, they are not in the scope of this task. That will be a continuation task.

Definition of done
---
* [x] API backlog items are stored in collection.
* [x] API backlog collection has a schema.
  * [x] Schema contains 'foreign key' field 'apiBackendId`
  * [x] `apiBackendId` field contains unique ID of any given API Backend
  * [x] `apiBackendId` field uses `regEx: SimpleSchema.RegEx.Id` for validation 
* [x] API backlog schema contains all relevant fields included in UI wireframe.
* [x] API backlog input form exists.
* [x] API Backlog is associated with each API Backend
  * [x] Backlog has defined route (e.g. `/api/{{ _id }}/backlog` 
* [x] API managers can submit backlog items for their managed API Backends.
* [x] API managers can update backlog items for their managed API Backends.
* [x] API managers can delete backlog items for their managed API Backends.

**Comment by brylie** [comment]
@baijat, should we move this issue back to Backlog?

**Comment by bajiat** [comment]
@frenchbread Would you be interested in this task? Brylie's rough estimate was 5-8 hours.

**Comment by frenchbread** [comment]
Self-assigned.

**Comment by bajiat** [comment]
@frenchbread Can you also estimate? Or are you happy with the current estimate?

**Comment by frenchbread** [comment]
@bajiat Current estimate is fine.

**Comment by bajiat** [comment]
@frenchbread Any update on this task?

**Comment by frenchbread** [comment]
@bajiat Have not started this task yet. Taking it to the next sprint.

**Comment by bajiat** [comment]
@frenchbread Thanks for the update! This is the highest priority task (mandatory) for next sprint.

**Comment by frenchbread** [comment]
Did some good progress so far:

- Created layout for backlog items
- Added form for adding new backlog items
- Priority label for each backlog item
- Remove backlog item functionality
- Sorting by priority & date added

Screenshot of backlog items list:
<img width="1433" alt="screen shot 2016-01-08 at 00 54 55" src="https://cloud.githubusercontent.com/assets/2122679/12185344/19fa496c-b5a3-11e5-89db-c0e528be1e58.png">

Screenshot of backlog form (stays in modal window):
<img width="1049" alt="screen shot 2016-01-08 at 00 55 10" src="https://cloud.githubusercontent.com/assets/2122679/12185355/2b5ab8f4-b5a3-11e5-8ed7-1acaa2dc7ec5.png">

ToDo:
- Deal with AutoForm with FlashMessages integration (was not able to set it up on go..). Would be cool to have some help from @elnzv since he worked with in when coding `API Feedback` feature.
- Replace privileges (insert, update, remove) from admin to managers.

Working branch: [`feature/api-backlog`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/api-backlog).

Also, if i'm misunderstanding, @brylie, should each backlog item be attached to specific API Backend?

**Comment by bajiat** [comment]
@frenchbread The entire backlog should be for one API backend. And consequently each item in that backlog for that particular API backend.

The purpose is to communicate what changes are planned to that particular API and the backlog is managed by the API manager. 

(Did this answer your question?)

**Comment by brylie** [comment]
@frenchbread yes, each API Backend has its own backlog. I have updated the definition of done do include specific details about how to link the API Backlog and API Backend, as well as details about routing. My apologies for the omissions.

**Comment by brylie** [comment]
Also note, the API Managers can only manage (add, update, delete) items in API Backlogs for their own API Backends. This can be done by comparing the apiBackend.managersId array to make sure it contains the API Manager user ID.

**Comment by brylie** [comment]
Here is an example helper function you can use:

```
// Get user ID
    var userId = Meteor.user()._id;

    // Get API Backend ID
    var backendId = this.params._id

    // Get API Backend (only managerIds field is necessary)
    var backend = ApiBackends.findOne(backendId, {fields: {managerIds: 1}});

    // Get the backend manager IDs
    var managerIds = backend.managerIds;

    // Check if user ID is in manager IDs
    var userCanEdit = _.contains(managerIds, userId);
```

**Comment by frenchbread** [comment]
@brylie @bajiat Thanks for info & updated def. of done. Now it's more clear.

**Comment by bajiat** [comment]
@frenchbread Any updates on this task?

**Comment by frenchbread** [comment]
@bajiat Almost finished this one. Just need to add inline comments describing the code.

**Comment by frenchbread** [comment]
Created PR #757. This is quite heavy one so I would suggest that couple of @apinf/developers review it. 

For testing & playing with it, navigate to `view-api-backend` page.

Design implementation was not a part of this issue, so probably would need to create another one which is going to relate to #643.

**Comment by bajiat** [comment]
@frenchbread Hi, have you had a chance to look at Brylie's feedback on the PR?

**Comment by frenchbread** [comment]
@bajiat I am on it. After some refactoring & renaming was not able to run a project. Figuring out why stuff does not work..

**Comment by brylie** [comment]
@frenchbread are you getting any errors?

**Comment by brylie** [comment]
Try the basic stuff first, start with the foundation and work up to higher level things:

* reset Meteor
* rename the collection
* refactor the template
* try the collection helper

**Comment by frenchbread** [comment]
@brylie Did not get any errors, backlog items were not able to load. Seems to be an issue with subscription/publication namings.

**Comment by brylie** [comment]
OK, what are you naming the publication?

**Comment by frenchbread** [comment]
@brylie It's `ApiBacklogItems`.

**Comment by brylie** [comment]
@frenchbread is the branch working now? I can present at the review meeting.

**Comment by frenchbread** [comment]
@brylie yes, it works.

**Comment by brylie** [comment]
@frenchbread please focus on finalizing this branch today. The testing task is lower priority.
