### ISSUE TITLE
Implement API Rating field and widget

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#519]
# Feature
Create a rating feature for API Backends. Users can select a rating, and aggregate ratings are displayed on the API Backend page and API Backends catalog.

# Design
![Rating design](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23471_rating_field_widget.png)

# Resources
* [jQuery Rate It package](https://atmospherejs.com/dandv/jquery-rateit)

# Related
Related to #471

**Comment by brylie** [comment]
Co-pilot: @elnzv

**Comment by elnzv** [comment]
Related design file - https://github.com/apinf/docs/blob/master/docs/design/%23471_rating_field_widget.png

**Comment by kyyberi** [comment]
Somehow add the amount of ratings to option one. Could it be number in parenthesis after the stars? This is vital since its different level of credibility if there is just two ratings or 200 ratings.

**Comment by brylie** [comment]
This design/issue is focused on the basic, single-user rating widget. I have created a follow up design task to show the aggregate ratings (including number of ratings and average result).

**Comment by kyyberi** [comment]
Ah, ok.

**Comment by brylie** [comment]
I am able to get the individual rating in a column of the API Catalog. Also, users who are anonymous or who have not rated the API Backend will see an average of existing ratings. 

One problem I am getting is that we can not sort by the rating column, so users may not be able to 'show highest rated' by clicking the column title.

**Comment by brylie** [comment]
I have gone with a four star max rating, as opposed to five. This is to encourage users to lean one way or the other, rather than going with a three star rating.

**Comment by brylie** [comment]
I am not sure how to show both the aggregate rating and individual rating in the same table cell, but could create an additional column for 'average rating' or similar. This may not be the best in terms of space usage, but would differentiate the user rating from the aggregate.

**Comment by brylie** [comment]
I am implementing the rating widget in a similar fashion to Netflix movie rating functionality. 

When a user has not rated an API backnd, they are shown the aggregate rating, e.g. red stars. When the user has rated an API backend, they are shown their individual rating, e.g. in yellow stars to differentiate.

**Comment by bajiat** [comment]
@brylie I like the approach on separating the user ratings and aggregated ratings with different color.

**Comment by brylie** [comment]
PR Open: #572

**Comment by kyyberi** [comment]
+1 for the idea

**Comment by brylie** [comment]
Below is a screenshot of the current API Catalogue table, showing yellow rating for user rating and red rating for aggregate:

![screenshot](https://cloud.githubusercontent.com/assets/17307/10903815/87740700-8216-11e5-8b59-d6d3c6f98133.png)

**Comment by brylie** [comment]
I have added the user count to aggregate rating display:
![screenshot-1](https://cloud.githubusercontent.com/assets/17307/10904840/d644f4a4-821e-11e5-8977-94d1e39a512b.png)

A grey 'badge' appears next to the rating showing the aggregate count and a 'user' icon. The use of the icon avoids string translation and saves space.

**Comment by kyyberi** [comment]
See also Kin Lane's thoughts on this https://www.linkedin.com/pulse/how-we-going-create-standard-poors-moodys-api-economy-kin-lane

**Comment by brylie** [comment]
A lot of the ideas in that article seem also related to our API Metadata entry form task (#472). E.g. we can build an 'API Metadata' form that conforms to existing standards (including possibly Swagger specification), and provides fields such as outlined in the previous article.
