### ISSUE TITLE
Validate Swagger files when they are uploaded

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#523]
Definition of done
---
* [x] Choose package for Swagger validation.
* [x] Integrate the package to the project.
* [x] Create a function to run the validation.
* [ ] Work with the developer working with issue to make sure the validation is run when a Swagger document is being uploaded.

**Comment by kyyberi** [comment]
https://www.npmjs.com/package/swagger-validate

**Comment by kyyberi** [comment]
https://github.com/BigstickCarpet/swagger-parser

**Comment by bajiat** [comment]
@frenchbread Are you already working on this? Did you have any PR's related to this?

**Comment by frenchbread** [comment]
@bajiat swagger file validation is not included in PR #517. Just host url modifications are done there.
