### ISSUE TITLE
Improve API Umbrella error handling 

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/api-umbrella-dashboard#531]
This task is related to task #357. An [issue](https://github.com/brylie/meteor-api-umbrella/issues/1) was created on brylie:meteor-api-umbrella to enhance the error handling. After this issue is finished some work must be performed according to instructions left in the commit: 229a7dec66f7c2f0becc8ba2218649e8e328dd29

**Comment by mauriciovieira** [comment]
Maybe it is a duplicate of #604

**Comment by bajiat** [comment]
@mauriciovieira You commented that you would be interested in #638. This is a related task. Could you take this one as well?

**Comment by bajiat** [comment]
One function remains that does not have proper error handling: https://github.com/apinf/meteor-api-umbrella/blob/master/server/apiUmbrellaWeb.js#L264

**Comment by bajiat** [comment]
@frenchbread This is another smallish task. Would you be interested in taking this?

**Comment by frenchbread** [comment]
Yup.

**Comment by frenchbread** [comment]
PR [#9](https://github.com/apinf/meteor-api-umbrella/pull/9).

**Comment by frenchbread** [comment]
Moving to done since related PR has been merged.
