### ISSUE TITLE
Functional testing: Familiarize yourself with Apinf platform

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#538]

**Comment by brylie** [comment]
@ashakunt, what is the status of this issue?

**Comment by ashakunt** [comment]
@brylie @bajiat: @saralavanip has been familiarizing with APINF already and has an understanding of basics in APINF.

**Comment by ashakunt** [comment]
Marking this as done and basic familiarization was done already.

**Comment by ashakunt** [comment]
@bajiat: can you please move this to done? Size of this task was: 5hrs.

**Comment by bajiat** [comment]
@ashakunt Moved to Done.
