### ISSUE TITLE
Functional testing: Test user registration

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#539]

**Comment by brylie** [comment]
@ashakunt, what is the status of this issue?

**Comment by ashakunt** [comment]
@brylie, @saralavanip has already been creating issues and testing them. You might want to check those items in issues section already.

**Comment by ashakunt** [comment]
The  bugs mentioned at: https://github.com/apinf/api-umbrella-dashboard/issues/created_by/saralavanip were created by @saralavanip. 

The bugs are focused around: 

1. User registration
2. Normal play-around usecase of APINF.IO

**Comment by bajiat** [comment]
@ashakunt Can you also request Sarala to add the label bug when she is creating issues in Github?

**Comment by bajiat** [comment]
@ashakunt I moved this issue to "in progress" since there are already bug reports based on this testing task.

**Comment by bajiat** [comment]
@ashakunt Shall we close this issue? Is it completed?

**Comment by bajiat** [comment]
@ashakunt We are closing this issue.
