### ISSUE TITLE
Create social media accounts for project outreach

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#54]
Once we have our project name (task #53), we will need to create social media accounts. This will help us build community.

Deliverables
---------
* [ ] List of relevant social networks for our project
* [ ] Decide on reasonable number of networks to use
* [ ]  Create two or more accounts on desirable networks

**Comment by Laura-Sampo** [comment]
Facebook account created. 
Networks decided; Facebook, Twitter, LinkedIn and blog.
