### ISSUE TITLE
Make all the team members in GitHub public

### ISSUE THREAD

**Issue by ccsr** [apinf/api-umbrella-dashboard#540]
APInf team needs to be visible to public in GitHub. Right now only Illya & Brylie are visible.

**Comment by bajiat** [comment]
Membership can only be changed to Public by each individual. I have sent a request on mail to all team members that are still Private.

**Comment by mauriciovieira** [comment]
:+1:

**Comment by kyyberi** [comment]
Only three private, huge improvement in transparency :)

**Comment by ccsr** [comment]
done

**Comment by elnzv** [comment]
@JuusoV & @Laura-Sampo need to make them public.
This can be done on this page - https://github.com/orgs/apinf/people

**Comment by JuusoV** [comment]
@elnzv
Fix'd

**Comment by bajiat** [comment]
Thanks everyone! All team members have now public membership. Closing the issue.

**Comment by kyyberi** [comment]
Excellent
