### ISSUE TITLE
Design reply functionality to communication channel

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#541]
First version of communication channel between consumers and managers allows consumers to send feedback, request etc. about APIs and managers to view the feedback.

# User Interface
The discussions will appear within the feedback container, as a flat list at the bottom (threaded replies may be added later). The discussion will be date sorted. 

## Comment input
There will be an text input for adding a reply, which can later be refactored to show a modal dialogue or similar.

## Comment display
Once comments are submitted, they will be displayed in a card-like frame, with the comment, user name, user photo, and timestamp (in time-ago format):

![Feedback Comments UI](https://raw.githubusercontent.com/apinf/docs/master/docs/design/Feedback-CommentListUI.png)

# Design example(s)
The following designs may be freely adapted for our purposes:

* [User comment example](http://bootsnipp.com/snippets/featured/user-comment-example)
* [Comments list](http://bootsnipp.com/snippets/featured/comments-list)
* [Recent comments admin panel](http://bootsnipp.com/snippets/featured/recent-comments-admin-panel) - additional buttons to manage comments (e.g. may be shown for managers and comment authors)

# Collection
The feedback discussion will be stored in a separate collection, called `FeedbackDiscussion`.

# Schema
The `FeedbackDiscussion` collection will have the following schema:

* `feedbackId` - String - containing the ID of the related feedback document
* `authorId` - String - containing the ID of the discussion item Meteor User ID
* `message` - String - containing the message
* `createdAt` - Date - the Datetime when the discussion document was created

# Publication(s)
The following publication(s) will be useful:

* `relatedFeedbackDiscussion (feedbackId)` - returns a collection pointer to feedback discussion documents that match the feedbackId parameter:

```
FeedbackDiscussion.find({feedbackId: feedbackId});
```

# Subscription(s)
The publications will be used as template subscriptions:

* `relatedFeedbackDiscussion` - will be used on the Feedback template to populate the discussion thread

Co-pilot: @frenchbread

**Comment by brylie** [comment]
Co-pilot: @elnzv

**Comment by brylie** [comment]
Work ongoing in [feature/feedback-discussion](https://github.com/apinf/api-umbrella-dashboard/tree/feature/feedback-discussion) branch.

**Comment by brylie** [comment]
@apinf/design @apinf/developers please review the issue summary. @kyyberi please also review. I will begin work on this feature soon.

**Comment by bajiat** [comment]
@brylie Would it be possible to have a wireframe sketch to show how you are planning to combine / reuse the available designs you have found?
