### ISSUE TITLE
Design public API feedback voting

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#542]
First version of communication channel between consumers and managers allows consumers to send feedback, request etc. about APIs and managers to view the feedback.

# Wireframe
![mockup](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23149_communication_channel_apinf.png)

# FeedbackVotes collection
This feature may use a new collection called `FeedbackVotes`. Each Feedback Vote document will contain the following fields:

* feedbackId - string - the ID of the Feedback document
* userId - string - the ID of the user
* vote - integer - the numeric vote for the user (allowed values: 1 and -1)

# Collection helper(s)
The following collection helper will be attached to the Feedback collection:
* `sumOfVotes()` - adds all vote integers together, returns the sum of all votes as an integer

# Server method(s)
The following method(s) will be defined on the server:

* `submitVote(vote)` - takes an integer as an argument, checks whether user has already voted, either updates existing or adds new user vote

# Publication(s)
The following publication(s) will be useful:

* getAllVotesForSingleFeedback (feedbackId) - returns a database cursor for the following query:

```JavaScript
FeedbackVotes.find({feedbackId: feedbackId});
```

# Template-level subscription(s)
Each feedback template will subscribe to the `getAllVotesForSingleFeedback` publication. This will ensure that only votes for displayed feedback are returned.

# Sorting by top voted?
* [ ] Determine how to sort by top voted. I.e. is it possible to sort by a collection helper? Will it be necessary to store the computed sum of ratings as a field in the Feedback document, rather than using a collection helper?

**Comment by brylie** [comment]
@apinf/developers do you have any ideas how to sort the top voted Feedback submissions? Please review the implementation notes to get an idea of my thinking.

**Comment by bajiat** [comment]
@brylie I think it is more important to have the voting in place than to be able to sort according to votes, if sorting is blocking the implementation. Besides, we have quite a number of UI improvements in backlog that in my opinion have a higher priority than sorting the votes, for example enhancements for user profile. 
@kyyberi, what would you say, is it possible to implement this feature without sorting by the votes?

**Comment by brylie** [comment]
@bajiat and @kyyberi, if there is not any further feedback, I will proceed with implementing this feature as described in the issue text.

**Comment by kyyberi** [comment]
Without sorting is fine for now.

**Comment by brylie** [comment]
@frenchbread for future reference, will you please provide a link to the article you mentioned about MongoDB math operations?

**Comment by frenchbread** [comment]
I was talking about an online course [MongoDB for developers](https://university.mongodb.com/courses/schedule). Course is free but requires you to be registered for it to view its materials.

I found a similar [article](http://www.tutorialspoint.com/mongodb/mongodb_aggregation.htm) that covers main idea of aggregation principles in mongodb described in this course.
