### ISSUE TITLE
Link to help forum from apinf.io

### ISSUE THREAD

**Issue by preriasusi** [apinf/api-umbrella-dashboard#543]
I'm adding new API to apinf.io. I got it added, even though I was searching for help while doing it.

Now I'm trying to call it with Postman, and I get error "API_KEY_MISSING". I would like to go to read discussions, support forum to get help for this one, but there's no link on apinf.io. I can't find any kind of help text or link anywhere where I could get help.

**Comment by nnn** [comment]
Checked apinf.io. Now there is a link to http://community.apinf.io/.
