### ISSUE TITLE
Measure API Proxy latency

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#551]
Determine how to report API Proxy latency, as a separate value from network or remote API Backend latency. (Test the latency for making calls through Api Umbrella vs making calls directly)

# User story
```
As a system administrator
I would like to know how much latency is introduced at the proxy layer
so that I understand how a proxy affects our request/response cycle
```

# Details
Since the API Proxy layer is currently provided by API Umbrella, the reporting functionality may need to be provided by the API Umbrella platform. See the [upstream support ticket](https://github.com/NREL/api-umbrella/issues/184) for status update.

# Definition of done
* [ ] Developers should be able to read about results of benchmarking - e.g. in project documentation
* [ ] Administrators should be able to re-run the benchmark in order to verify the results
* [ ] DevOps repository should be updated to contain benchmarking script(s)

**Comment by kyyberi** [comment]
This is most likely one question coming from APIKA api owners. It is a question that was asked already in the spring by Aleksi Rossi from YLE.

**Comment by jykae** [comment]
Steps for simple benchmarking: https://github.com/NREL/api-umbrella/issues/184

**Comment by jykae** [comment]
I think I am going first to query *proxy_overhead* from Analytics DB, as it is sounds good metric for this.

"*proxy_overhead* attempts to measure the difference between how fast the backend sent its response and how fast API Umbrella responded, so this should be the best metric of the complete overhead (taking into account the hops through our local caching server, for example)."

**Comment by jykae** [comment]
The analysis results was showed to the customers on Wednesday.
Shared also to NREL: https://github.com/NREL/api-umbrella/issues/184

**Comment by kyyberi** [comment]
You should write a blog post about the results. If you don't I'm willing to. @jykae
