### ISSUE TITLE
Please remove footer in https://apinf.io/

### ISSUE THREAD

**Issue by ccsr** [apinf/api-umbrella-dashboard#555]
APInf is Sampo Software Product which is fully open source and it is free. The statement "collaboration between Sampo Software & API-Umbrella" is totally irrelevant here. Please remove it immediately. It is confusing lot of people.

Please add the text "APInf is brought to you by Sampo Software.© 2015 APInf. All rights reserved."

**Comment by bajiat** [comment]
@elnzv Could you handle this?

**Comment by elnzv** [comment]
Closing.
Will deploy changes directly to apinf.io

**Comment by elnzv** [comment]
Have problems with deployment.
Will close this issue, when have code deployed.

**Comment by elnzv** [comment]
opened an issue on mup project - https://github.com/arunoda/meteor-up/issues/730

**Comment by elnzv** [comment]
Deployed, bug fixed, thanks to @jykae

**Comment by jykae** [comment]
@elnzv Your welcome :+1:
