### ISSUE TITLE
Invalid redirects to Privacy policy  and Terms of use

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#578]
Steps:  

1.Visit https://apinf.io
2. Click on sign up button
3. Enter email address
4. Enter  the password
5. Open the links given for Privacy policy and terms of use

Expected: Valid redirects to the documents related to privacy policy and terms of use
Actual: Clicking on the links redirects to meteorfactory.io   
              - No specific documentation available related to privacy policy and terms of use.

**Comment by bajiat** [comment]
We don't have Privacy policy and Terms of use yet.

**Comment by bajiat** [comment]
Check Mozilla and Wikimedia Foundation for reference.

**Comment by Laura-Sampo** [comment]
https://www.rallydev.com/privacy-statement

**Comment by Laura-Sampo** [comment]
https://waffle.io/apinf/api-umbrella-dashboard/cards/5638e941b0e91303004b7e6c

-> draft about items privacy policy should include.

**Comment by Laura-Sampo** [comment]
http://samposoftware.com/privacy-policy/

Sampo's privacy policy.  BTW impossible to find from the web pages without search-tool.

**Comment by elnzv** [comment]
@Laura-Sampo, will fix it, thanks for finding this out.

**Comment by bajiat** [comment]
Closing, since links have been removed.
