### ISSUE TITLE
Empty  profile updating doesn't notify errors 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#580]
Steps:    

1.Visit https://apinf.io
2.Sign in
2.Go to Profile section
3.Click on update button

Expected: Not successful in update profile and notify users to fill empty fields
Actual:  shows notification dialog 'profile updated' while text fields are empty
              - Update button is active all the time.  

Screenshot:  

![update_empty_profile_error](https://cloud.githubusercontent.com/assets/13309358/10915335/fe0ef300-825e-11e5-9253-ecf6880d6cd2.png)  

![profile_updated_dialog_repeated_error](https://cloud.githubusercontent.com/assets/13309358/10915342/041ced9c-825f-11e5-9942-3e35d799c7a4.png)

**Comment by bajiat** [comment]
Fields are optional, so there are no errors when submitting empty values. They will have to remain optional, because we don't require all users to provide that information.
