### ISSUE TITLE
Sign up with github account demands user to make their github email public 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#581]
Steps:  

1.Visit https://apinf.io
2.Click on 'sign up' button
3.Select 'sign in with github account'
4.Enter username /  email address
5.Enter password
6.Click on 'authorize application' button 

- Application notifies the user to make their github email public in order to login  

Screenshot:  

![sign_in_with_github_email_public](https://cloud.githubusercontent.com/assets/13309358/10915451/8fbe09b2-825f-11e5-9b0c-f74711b70674.png)

**Comment by bajiat** [comment]
Email is used as primary identifier for a user. Github does not allow retrieving private emails. Hence, we are aware of the issue, but cannot fix at this time.
