### ISSUE TITLE
'Data not found' error after sign out

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#582]
Steps:

1.Visit https://apinf.io
2.Go to sign in page
3.Enter email address
4.Enter  the password
5.Click on 'sign in ' button
6. Go to Menu and click on  'Catalogue'
7.Sign out

Expected: Successful sign out
Actual: Successful sign out with error message 'data not found'  

Screenshot:  
![signin_open_menu_page_signout_data_not_found_error](https://cloud.githubusercontent.com/assets/13309358/10915564/0c112152-8260-11e5-9e6a-a67a1887ac07.png)

**Comment by bajiat** [comment]
Co-pilot: @elnzv

**Comment by frenchbread** [comment]
PR - #608
