### ISSUE TITLE
Sign out from profile page shows error 'Data not found'

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#583]
Steps:   

1.Visit https://apinf.io
2.Sign in
3.Go to Profile section 
4.Sign out

- Successful sign out with error: Data not found

Screenshot:  

![signin_goto_profile_signout_data_not_found](https://cloud.githubusercontent.com/assets/13309358/10915655/5a2b449e-8260-11e5-8ede-ab9b1b643f01.png)

**Comment by bajiat** [comment]
Related to  #585

**Comment by bajiat** [comment]
Co-pilot: @elnzv

**Comment by frenchbread** [comment]
PR - #608
