### ISSUE TITLE
'Delete Account' header text not visible in Account details settings 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#584]
Steps:   
 
1.Visit https://apinf.io 
2.Sign in
3.Go to Account section

-  'Delete Account ' header text not visible

Screenshot:  

![account_page__delete_account_header_not_visible](https://cloud.githubusercontent.com/assets/13309358/10915743/c3db65b8-8260-11e5-950b-84fcf37210a6.png)

**Comment by elnzv** [comment]
@saralavanip, just checked apinf.io, title is visible now.
I think, it was fixed during style files refactoring. 
Please, confirm.

**Comment by saralavanip** [comment]
@elnzv , Yes, I verified at apinf.io and the title is visible now.
