### ISSUE TITLE
Sign out from Accounts page shows error 'Data not found'

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#585]
# Steps to reproduce

1. Visit https://apinf.io
1. Login
1. Go to Account section
1. Sign out 

## Result
- Successful sign out with error: 'Data not found'  

## Screenshot

![signin_goto_profile_signout_data_not_found](https://cloud.githubusercontent.com/assets/13309358/10915847/40af4c44-8261-11e5-80a2-3a20c52177f3.png)

# Server console
Additionally, there is a traceback in the server console:

```
Exception while invoking method 'getChartData' TypeError: Cannot read property 'profile' of null
at [object Object].Meteor.methods.getChartData (server/methods/elasticSearch.js:26:1)
...
```

This suggests the user is being redirected to the dashboard page, so check the Router.onBeforeAction declarations. Also, the `getChartData` function needs to be refactored to handle exceptions (try ... catch).

# Related
There is a [related issue](https://github.com/apinf/api-umbrella-dashboard/issues/617) regarding exception handling.

**Comment by bajiat** [comment]
Related to  #583.

**Comment by bajiat** [comment]
Co-pilot: @elnzv

**Comment by frenchbread** [comment]
PR - #608

**Comment by brylie** [comment]
@frenchbread I have updated this issue description with console messages. Also note, the methods may need to handle exceptions.

**Comment by saralavanip** [comment]
Hi,

Could you please let me know if the latest changes been deployed.


Regards
Sarala

**Comment by brylie** [comment]
We will deploy changes next Monday or Tuesday, after we make an alpha release.

@bajiat please confirm.
