### ISSUE TITLE
Create ecosystem/architecture diagram

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#59]

**Comment by bajiat** [comment]
Architecture diagram can be found from https://github.com/apinf/api-umbrella-dashboard/blob/b546a96532afe5f00052cee79b95101558b007a2/docs/APINF_MVP_architecture.svg

**Comment by bajiat** [comment]
Ecosystem diagram can be found from: https://github.com/apinf/api-umbrella-dashboard/blob/b546a96532afe5f00052cee79b95101558b007a2/docs/APINF_MVP_ecosystem.svg
