### ISSUE TITLE
Refactor project to use updated Meteor apiUmbrellaWeb package

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#591]
Brylie and Mauricio have been refactoring the Meteor API Umbrella Web package. This will require some changes in our project code. 
Determine what needs to be changed, make changes and test.

If not updated, will block other issues.

**Comment by brylie** [comment]
I have completed most of the [brylie:api-umbrella](https://github.com/brylie/meteor-api-umbrella/issues/3) refactoring. I may re-design the module API to be more flat, with a [unified function for each endpoint](https://github.com/brylie/meteor-api-umbrella/issues/3#unified-functions) that accepts arguments for request type, etc.
