### ISSUE TITLE
Benchmark open source project websites

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#592]
For the purpose of creating an open source project website for Apinf (separated from product page), it would be good to look at other open source project websites.

Definition of done
---
* [x] Choose 3-5 existing open source project websites.
* [ ] Identify common characteristics and desirable content. 
* [ ] Document findings in Wiki so that we can plan our project website.

https://apinf.hackpad.com/Benchmark-open-source-project-websites-AvN1sPp13Rc

**Comment by brylie** [comment]
Just a note, it would be nice to have a chat on our project page, so community members can quickly get in contact. E.g. [Gitter Sidecar](https://sidecar.gitter.im/)
