### ISSUE TITLE
Ensure user name exists for all users

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#595]
We need enhancements to user profile in connection to API feedback / communication channel, etc. Improve the user profile to collect more detail, such as user name.

# Definition of done

* [ ]  Username  should be obligatory. This is related to for instance showing names in communication channel, selecting API managers.
* [ ] Sign up form should contain mandatory field for username.
* [ ] If username is not given in third-party sign up (currently only Github), re-direct users to profile page.
  * [ ] Modify the [existing router hook to ensure that users have usernames](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/router.js#L60-L62).
* [ ] Also, remove the Config.username check, as we do not use the global Config object.
* [ ] Allow only unique usernames. If the username already exists, prompt for another username.

**Comment by sbe** [comment]
"Username (either nick or a real user's name) should be obligatory."
Is this about the field "name" in the Schema UserProfile and the "username" field in the User Collection? 

I would like to use the package: https://github.com/meteor-utilities/avatar/ to implement the avatar features, there is an inbuild featue for default profile pictures. the image path could then be added as a field in the UserProfile Schema.

**Comment by brylie** [comment]
@sbe, may we assign you to this task? I am available for pair programming.

At the very least we need to collect a username, but it is up to you whether to make the `name` field mandatory.

**Comment by sbe** [comment]
I am happy to take this task. When are you available for pair programming?

2015-11-27 12:13 GMT+01:00 Brylie Christopher Oxley <
notifications@github.com>:

**Comment by brylie** [comment]
Also, the Avatar package looks great! I am available for pair programming today, and can be found in IRC.

@baijat, may we add @sbe to the Apinf organization (development team), so that he can be assigned this task?

**Comment by bajiat** [comment]
@sbe invited to Apinf organisation and developers team.

**Comment by bajiat** [comment]
@sbe Hi, we are checking sprint 17 task statuses in order to start sprint 18 planning. Can you tell me the status of this task?

**Comment by sbe** [comment]
in progress

**Comment by bajiat** [comment]
@sbe Let us know what the branch is so that we can check progress. Thanks!

**Comment by sbe** [comment]
This is the branch: https://github.com/apinf/api-umbrella-dashboard/tree/feature/595-userprofile-enhancement
I will continue development on wednesday

**Comment by brylie** [comment]
Sandstorm.io has a simple user profile, which is shown to new users automatically when signing up:

![screenshot-1_001](https://cloud.githubusercontent.com/assets/17307/11917585/6a927e80-a716-11e5-93fa-a64f31a1222c.png)

These fields, labels, and help texts would also be well suited tor our profile feature.

**Comment by sbe** [comment]
Thanks for the suggestion. I am in the process of getting rid of the
quickfields and setting fine grained forms to implement the user profile.

**Comment by brylie** [comment]
We have no visibility into the progress of this task without code or comments on this task. Please keep your work in progress in a branch on Github.

**Comment by sbe** [comment]
I have added the Meteor Avatar package but questions arise about how we will handle avatar uploads.

**Comment by brylie** [comment]
Lets not focus on the Avatar functionality yet, it is optional. 

The important part is the username. Without a username field, or at least 'full name' field, we cannot implement other features.

**Comment by brylie** [comment]
@sebbel, can you take this task to require username for all users?

**Comment by sebbel** [comment]
Would this also require setting a username on registration?

**Comment by brylie** [comment]
Yes, or at least having the user set their username shortly after registering. E.g. some of our users are registering via Github, so we may not get a username when they register.

**Comment by brylie** [comment]
One proposed idea was to check whether a user has set a username before rendering a route. If they don't have a username set, then redirect to their profile page or prompt them to set a username.

**Comment by bajiat** [comment]
@sebbel Hi Sebastian, just wanted to ask you whether you are willing to complete the task with the new definition of done? This is a high priority task for us, because it is blocking another task. It is ok not to do it, but if you want to complete it, it would be needed to be completed by next sprint (4 - 15 January). If you are not interested, we can also assign it to another team member. Thanks and a happy new year!

**Comment by sebbel** [comment]
I'd love to!
Just had a chat with @brylie:
- I will remove the avatar package
- I will focus on the user profile feature

I want to prompt users who do not have a username yet to enter a username
upon entering the profile site. maybe it would be better to include the
username in the registration.

**Comment by brylie** [comment]
I have updated the task definition with a link to the router hook. Please also make sure to use the proper route of your choice.

**Comment by bajiat** [comment]
@sebbel Any updates on this task?

**Comment by sebbel** [comment]
I've learned that I am supposed to use the username field inside the User Collection. Currently trying to find a way on how to link the updates of both Schemas.

**Comment by brylie** [comment]
@sebbel, pull in the recent changes from `develop`, as they greatly simplify the [code in the onCreateUser callback](https://github.com/apinf/api-umbrella-dashboard/blob/24742d02a4c8a7b7ff4b8cc1561a0eadb94b1d8d/server/accounts.js#L1-L49).

We may not need to work with any schemas for this task. The AccountsTemplates documentation has [instructions for adding a username field to the sign-up form](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#special-fields-ids).

The username field is attached directly to the Meteor user at the top level. as opposed to the profile.

**Comment by brylie** [comment]
@sebbel push your working branch to Github, open a pull request, and label it as **WIP**. We can review your code in process to offer advice.

**Comment by sebbel** [comment]
I have pushed my working branch to github.
I managed to get this to work:
- Users without a username are redirected to /profile and prompted to Enter a username
- You can now also change your username on the profile page.

Current bugs:

- If chosing an already existant username, the usernameExists function is overridden and a "Mongo db duplicate key error" is shown to the user.
- had to remove the rules in Meteor.user.allow in order to make it work for now. Will re-implement the rules when I know what's going on.

Looking forward to your suggestions&comments @apinf/developers

**Comment by sebbel** [comment]
I am considering to branch from the current develop and go the accounts
template route.

I don't think that we want users to be able to change their username
anytime. so forcing users to choose a username at registration seems
sufficient for solving this task.

**Comment by brylie** [comment]
Good idea :-)

**Comment by brylie** [comment]
Closed by PR #752
