### ISSUE TITLE
Presentation material for Apika info session

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#597]
The Apika info session will take place 25 November. There will be a 15 - 30 non-technical presentation about
* What is API management (This may be covered by a presenter from YLE, Finnish National Broadcasting company, but we have to be prepared in case the person from YLE is not available)
* What is Apika
* Introduction of the support channel

Target group: public sector clerks and managers

Definition of done
-----
* [ ] Create presentation outline. Indicate which slides would be left out, if API management does not need to be covered.
* [ ] Get feedback on the outline.
* [ ] Create presentation texts and images.

**Comment by kyyberi** [comment]
Target group is public sector clerks and managers. Not too much tech details.

**Comment by bajiat** [comment]
Presentation topics:

APIKA lyhyesti (Apika in short)
Rajapintojen hallinta (API management)
APIKA-palvelun ominaisuudet (Features of APIKA)
Kehitettävät ominaisuudet (Features to be developed)
Avoin kehitysprosessi (Open development process)
Mistä lisätietoa ja tukea? (More information and support)

**Comment by kyyberi** [comment]
Looks good
