### ISSUE TITLE
Functional testing: Test adding an API backend

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#598]
Test adding an API backend through the Add API backend form. Report any unexpected issues or errors as Github issues providing steps to reproduce the error. Add the label "bug" to the issues.

**Comment by bajiat** [comment]
@ashakunt I added the functional testing task for sprint 16 and assigned it to you. Reword this if necessary.

**Comment by saralavanip** [comment]
Reported the issues below, related  to 'Adding API backend' through 'Add API backend form' on Github: 
1.https://github.com/apinf/api-umbrella-dashboard/issues/602
2.https://github.com/apinf/api-umbrella-dashboard/issues/603
3.https://github.com/apinf/api-umbrella-dashboard/issues/604
4.https://github.com/apinf/api-umbrella-dashboard/issues/605
5.https://github.com/apinf/api-umbrella-dashboard/issues/599

**Comment by bajiat** [comment]
@saralavanip @ashakunt Can we close this issue, since it has already been tested?
