### ISSUE TITLE
Name of the labels 'Backend host' and 'Frontend host' are misplaced

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#602]
Steps:  
1.Visit https://apinf.io    
2.Sign in     
3.Select 'API Backends' from menu  
4.Click on 'Add API Backend'  
5.Enter API name  
6.Select the backend protocol from drop down menu  
7.Enter the details of servers: Host and Port  
8.Enter Frontend host and Backend  host  

- Names of the labels 'Backend host' and 'Frontend host' are misplaced

Screenshot:  

![misplaced_namelabels](https://cloud.githubusercontent.com/assets/13309358/11058257/426b5404-879a-11e5-981f-f90e182d132e.png)    

![autofill_api_umbrella](https://cloud.githubusercontent.com/assets/13309358/11058303/9828c9e4-879a-11e5-8c94-b5a5e7e71f86.png)

**Comment by kyyberi** [comment]
Confirmed. I stumbled upon this today. When adding API and when editing API, front and backend change order.

**Comment by kyyberi** [comment]
![screenshot from 2015-11-11 18 51 55](https://cloud.githubusercontent.com/assets/1927158/11096953/4cbc3318-88a5-11e5-86b3-a05789f2bfdf.png)
![screenshot from 2015-11-11 18 51 31](https://cloud.githubusercontent.com/assets/1927158/11096952/4cb95760-88a5-11e5-919c-25e51cadb235.png)

**Comment by bajiat** [comment]
Possibly resolved with combining Add API backend and Edit API backend forms. To be checked.

**Comment by bajiat** [comment]
Fix the following lines in the relevant file: https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/views/api_backends/api_backend_form/api_backend_form.html#L18-L31

**Comment by saralavanip** [comment]
Verified this resolved issue on develop version.
