### ISSUE TITLE
API Umbrella host value must be autofilled.

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#603]
Steps:  

1.Visit https://apinf.io  
2.Sign in   
3.Select 'API Backends' from menu  
4.Click on 'Add API Backend'  
5.Enter API name  
6.Select the backend protocol from drop down menu  
7.Enter the details of servers: Host and Port  
8.Enter Frontend host and Backend host   
    
- Enduser doesn't know where the API Umbrella is used and must be defined in settings and autofilled.

**Comment by bajiat** [comment]
Closing, because Add API backend wizard does not ask for the host value.

**Comment by saralavanip** [comment]
Verified on latest develop version.
