### ISSUE TITLE
'API _key_missing' error while calling API 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#606]
Steps:  

1.Visit https://apinf.io    
2.Sign in   
3.Select 'API Backends' from menu    
4.Click on 'Add API Backend'  
5.Enter API name  
6.Select the Backend protocol from drop down menu  
7.Enter the details of servers: Host and Port  
8.Enter Frontend host and Backend host  
9.Enter URL matches: Frontend prefix and Backend prefix  
10.Click on 'Submit'  button  
11.Click on 'View usage instructions'  
12.Click on the link for 'profile page'  and copy the API key  
13.Click on the link given for making API call  
14. Add the Frontend prefix and API key  

 
-  It shows 'API-Key missing' while calling API  though added the API key.   

Screenshot:  

![key_missing_whencalled](https://cloud.githubusercontent.com/assets/13309358/11059086/2a7600f0-87a0-11e5-829e-f0e5160d804e.png)

**Comment by saralavanip** [comment]
Investigating more about this issue.

**Comment by tuukka** [comment]
Based on the screenshot, this issue seems to be caused by using `key` instead of `api_key`.

**Comment by saralavanip** [comment]
I have added APIs and Call API successfully with the URL including API key:

 https://umbrella.apinf.io/ [frontend-prefix] /?api_key=MY_API_KEY)

eg: https//https://umbrella.apinf.io/test_weather_forecast/api_key=olOxVkeksNFUX8wgtwharNkS1rYS75zhO9Dtbpxs
