### ISSUE TITLE
Deploy the 0.2.0 alpha 1 release

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#607]
Deploy the 0.2.0 alpha 1 release, i.e. release made based on sprint 15 development, on apinf.io

**Comment by elnzv** [comment]
Deployed.

**Comment by brylie** [comment]
@elnzv did you have any errors? We have had a bit of trouble with NPM packages. How did the deployment go for you?

**Comment by elnzv** [comment]
Smoothly, no errors.

On Thu, 12 Nov 2015, 15:12 Brylie Christopher Oxley <
notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> did you have any errors? We have had a
> bit of trouble with NPM packages. How did the deployment go for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apinf/api-umbrella-dashboard/issues/607#issuecomment-156099317>
> .
>
-- 

Illya Nizyev | www.nzv.nz
