### ISSUE TITLE
Building NPM packages inside npm-container doesn't work in production deployment

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#609]
Please stick to Meteor packages as much as you can. NPM packages must be installed manually after production build. I am automating the building process with Meteor Up, which reduces the amount of work a LOT. (Nginx, Node.js, MongoDB + all the configuration are done automatically).

Good thing is that currently we have only "elasticsearch" NPM package required.

**Comment by bajiat** [comment]
To be checked whether the problem still persists with 0.2.0 alpha 1 release.

**Comment by jykae** [comment]
Solved. Complete re-installation of NPM on my own machine fixed the problem.
