### ISSUE TITLE
Allow managers to delete API Backends that they manage

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#616]
# User story
```
As a manager
I would like to delete an API Backend that I manage
so that I can keep my API Backends list up to date
```

# Feature
Add a method for API Managers to delete API Backends they manage. The deletion should also remove the API Backend from API Umbrella.

# Wireframes
## User Managed APIs
![My Managed APIs wireframe](https://raw.githubusercontent.com/apinf/docs/master/docs/design/MyManagedAPIs-deleteButton.png)

## View API Backend 
![View API Backend wireframe](https://raw.githubusercontent.com/apinf/docs/master/docs/design/APIBackend-deleteButton.png)
Definition of done
---

* [x] Delete button exists in My managed APIs.
* [x] Delete button exists in View Api backend, if the user has the privilege to delete the API (is the owner/manager of that API or is an Apinf administrator).
* [x] When clicking delete, user is prompted for confirmation, i.e. making sure that they have not accidentally pushed that button. 
  * [x] Confirmation includes the name of the API backend to be removed.
* [x] After confirming, the API backend is deleted from Apinf API backends collection.
* [x] The related documents are also removed from respective collections:
  * [x] API backlog
  * [x] API feedback
  * [x] API metadata
  * [x] API documentation
* [x] API backend is deleted from API Umbrella via REST call to Admin API.
* [x] Only authorized users. i.e. API owners and Apinf administrators, can delete API backends.

**Comment by kyyberi** [comment]
Highly needed :) Should have safe mechanism. Perhaps something like when deleting repository from Github.

**Comment by brylie** [comment]
Right, like the '**Danger Zone**' box. 

[![highway to the danger zone](http://img.youtube.com/vi/ZzQ3eBerHfM/default.jpg)](https://www.youtube.com/watch?v=ZzQ3eBerHfM)

**Comment by bajiat** [comment]
@ashakunt and @alapan Definition of done has been added. Wireframe to be added later today. Assigning task to Alapan.

**Comment by jykae** [comment]
Great, long waited feature for admin also :) :+1:

**Comment by brylie** [comment]
@Alapan, we may already have code related to API Backend administrator permissions that would be useful here. Do you want to do some pair programming, or have a brief chat?

**Comment by bajiat** [comment]
@Alapan Can you comment whether this is in progress and what would be the estimation for completion? This week?

**Comment by Alapan** [comment]
@bajiat Yes, this issue is in progress and I have implemented most of the front-end. It should be completed by this week.

**Comment by Alapan** [comment]
@brylie I wanted to know if the REST endpoint for API backend deletion has been implemented? I was looking through https://github.com/apinf/meteor-api-umbrella/blob/master/server/apiUmbrellaWeb.js, where it seems the REST interfaces are defined, and couldn't find anything related to deletion.

**Comment by brylie** [comment]
Right, as indicated via chat discussion, go ahead and add the `deleteApiBackend` method.

**Comment by Alapan** [comment]
The deleteApiBackend method  was implemented. Despite this, I am currently getting an error "Object [object Object] has no method 'deleteApiBackend'" when making the REST call apiUmbrellaWeb.adminApi.v1.apiBackends.deleteApiBackend(backendId)  in apiBackends.js.

**Comment by brylie** [comment]
Make sure to update the package version and publish it to Atmosphere. Then, run `meteor update` in our project, so that the latest version of the package will be available. We may need to figure out how to publish a Meteor package as an organization, rather than an individual.

**Comment by sebbel** [comment]
http://info.meteor.com/blog/meteor-091-organizations-blaze-apis

1. Create apinf Account on meteor
2. Create Organization on apinf account
3. add members to organization

Am Mittwoch, 9. März 2016 schrieb Brylie Christopher Oxley :

**Comment by brylie** [comment]
@sebbel what is your Meteor.com username?

**Comment by Alapan** [comment]
@brylie I had to make another small change to the deleteApiBackend method in API umbrella - I had written HTTP.delete instead of HTTP.del - like PUT, POST and GET, I thought the function name is the same as the action. I fixed it and created a pull request (https://github.com/apinf/meteor-api-umbrella/pull/17).

**Comment by Alapan** [comment]
First working version created. Created a pull request.

**Comment by sebbel** [comment]
@brylie my meteor account is sebbel

**Comment by Alapan** [comment]
@brylie I resolved the conflicts in the Issue#616 branch and pushed it.

**Comment by brylie** [comment]
@Alapan see my line comment for `client/views/api_backends/delete/deleteApiBackendConfirmation.js
` on line 54. The sAlert call is not in the `if`, `else if`, or `else` block. It looks like it is a logical error.

**Comment by saralavanip** [comment]
I have tested  'delete' feature on my local machine. 
Findings:  
- As a manager select API backend from 'Catalogue' and delete API backend returns to 'Catalogue' view. 
- If user has only one API backend added and delete it from 'Manage API backend' view, it stays on same page 'My Managed APIs' view.

**Comment by ashakunt** [comment]
thanks, @saralavanip

**Comment by ashakunt** [comment]
@Alapan did you check @brylie 's latest comment.

**Comment by saralavanip** [comment]
Findings:  
 - Add API backend and delete the same, returns to catalog view.

**Comment by saralavanip** [comment]
Findings:  
- As a manager select API backend from 'Catalogue' and delete API backend returns to 'Catalogue' view
 and user dialog not shown after successful delete API backend.
.

**Comment by brylie** [comment]
@saralavanip will you please verify with @Alapan that your previous observation is resolved?

**Comment by jykae** [comment]
Noticed on review: 
API Umbrella changes are made to the proxy configurations only after the changes have been published. This includes adding, updating, deleting. @brylie can probably point out what has to done to publish the changes for removal, as he fixed the publishing issue on adding API.

**Comment by saralavanip** [comment]
@brylie , verified the resolved issue: 'confirmation dialog is shown after successful delete API backend from Catalog view'.

**Comment by saralavanip** [comment]
@brylie , @bajiat , Deleting an API backend when it is down for some reason is unsuccessful. Could you please confirm if this is the expected result?

**Comment by brylie** [comment]
I am not sure about the cause of that error, but it should still be possible to delete the API Backend. Please file a bug report, so that we can troubleshoot.

**Comment by saralavanip** [comment]
@brylie , please find issue reported https://github.com/apinf/api-umbrella-dashboard/issues/919.

**Comment by brylie** [comment]
@Alapan, I have tested this feature. It seems ready for merging, and we can work on enhancements/bugs in upcoming sprints.
