### ISSUE TITLE
Exception while invoking method 'getChartData' Error: IndexMissingException[[api-umbrella-logs-v1-2015-01] missing]

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#617]
On the dashboard when interacting with the filter, the following exception is logged when only the month has been selected:

```
Exception while invoking method 'getChartData' Error:  IndexMissingException[[api-umbrella-logs-v1-2015-01] missing]
at Object.search (packages/meteorhacks_async/packages/meteorhacks_async.js:79:1)
at [object Object].doSearch (packages/frenchbread_elastic-rest/packages/frenchbread_elastic-rest.js:59:1)
at [object Object].Meteor.methods.getChartData (server/methods/elasticSearch.js:45:1)
```
Additionally, the 'Data Not Found' dialogue appears, suggesting the dashboard filter is **missing exception handling** when retrieving data from Elastic.

# Steps to reproduce
1. log in to the system as an admin user (to ensure you can access analytics data)
1. go to the dashboard
1. click a month from the dropdown (e.g. January)
1. check the server console

**Comment by brylie** [comment]
@frenchbread can you please take a look at this? Check if you can reproduce the error.

**Comment by brylie** [comment]
Related issue #585

**Comment by frenchbread** [comment]
@brylie This error appears every time when specified query does not match document in ES data store. I guess we can get rid of it by using `try-carch` approach when requesting for data.

**Comment by frenchbread** [comment]
I was thinking of this approach when solving #582, #583, #585.

**Comment by frenchbread** [comment]
As I mentioned in a comment, as far as I understand there is either search results or an error returned from ES. So we don't have much context at this point. Meaning that we can return a single error if fails, e.g. :
```
try{
    newSearch.doSeach(query)
}catch(err){
    return "Data not found...".
}
```

**Comment by brylie** [comment]
OK, cool. Be sure to add i18n tags on any user-facing text.

**Comment by frenchbread** [comment]
@brylie How to access `i18n` file to be able to fetch its tags in js file?

**Comment by brylie** [comment]
Check the tap:i18n docs. It has a JS function to get a translation string.

**Comment by frenchbread** [comment]
Added changes to PR #608. Please take a look.

**Comment by bajiat** [comment]
@frenchbread Did this get solved? Or does it need more work?

**Comment by frenchbread** [comment]
The related branch has been merged. Closing this issue.
