### ISSUE TITLE
Design link to API documentation

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#624]
## User story
As a API owner and API consumer I want to access API documentation which can a link to external site or build-in swagger. 

## additional info
I added Lentodiilit API and link to documentation but it's not visible anywhere. 
 
Definition of done
---
* [x] View API backend should display a link to documentation whether it is external documentation or a Swagger file in Apinf. 
* [x] If both are provided, it should display both.

**Comment by bajiat** [comment]
@elnzv This should be a fairly small design task. Could you take this one along with the bigger implementation task (settings)?

**Comment by elnzv** [comment]
Okay, taking this task.

**Comment by elnzv** [comment]
![doc_links](https://cloud.githubusercontent.com/assets/7489044/11553598/e00b4010-9998-11e5-8aee-85ff85f05bbe.gif)

Also uploaded to docs repo.

**Comment by kyyberi** [comment]
I would try tabbed content here too. I have a gut feeling the content will expand and with current design people are forced to scroll and most hate it nowadays.

**Comment by kyyberi** [comment]
Related to #664
