### ISSUE TITLE
Allow administrators to re-brand platform through UI

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#625]
Allow administrators to configure browser bar title text. Related to #74 (whitelabeling).
(Original description: When you open the APIKA service, in browser title is apinf, should be apika)

Definition of done
---
* [x] Key branding elements are  defined.
* [x] Administrators can change at least the following elements through the branding form.
  * [x] site title
  * [x] site slogan
  * [x] footer text
  * [x] logo image

### cover photo

* [x] cover photo field allows image upload
  * [x] image is to be used as full-width 'cover photo' in site header
  * [x] cover photo image is displayed via inline CSS style `background-image`
#### Schema
* [x] social media accounts field schema exists
* [x] Social media field allows users to select a network name (e.g. Facebook) and enter a url
* [x] `socialMedia` field allows multiple social media network/links to be entered
* [x] `socialMedia` field *does not* use sub-fields specific to any social media network
* [ ] `socialMedia` field can easily be extended to include additional networks (e.g. an "Other" option)
* [x] `socialMedia` field is optional

#### Example schema
The following details demonstrate one possible way to implement the `socialMedia` field, so that it is simple in structure and easy to extend:

* [x] socialMedia field type is `[Object]` (array of objects)
* [x] `socialMedia` sub fields include `network` and `url`
* [x] `socialMedia.$.network` is a string field
* [x] `socialMedia.$.network` `allowedValues includes "Facebook" and "Twitter"
* [x] `socialMedia.$.url` is a string field
* [x] `socialMedia.$.url` uses `regEx: SimpleSchema.RegEx.Url` for validation

```javascript
// in branding.js schema
socialMedia: {
  type: [Object]
  optional: true
},
"socialMedia.$.name": {
  type: String,
  allowedValues: ["Facebook", "Twitter", ...]
},
"socialMedia.$.url": {
  type: String,
  regEx: SimpleSchema.RegEx.Url
}
// ... other schema fields
```

#### UI
* [x] Social media links are displayed on front page
* [ ] (bonus points) Each social media link has corresponding social media icon from Font Awesome library
* [x] Only configured social media accounts are displayed

#### UI Example
The following example demnstrates one possible way to add the social media links to the UI. Feel free to deviate from this example, but please consider trying it to save time and effort.

```js
<!-- in home.html template (footer) -->
<ul>
{{# each network in socialMedia }}
  <li>
    <a href="network.url">{{ network.name }}</a>
  </li>
{{/ each }}
</ul>
```
## Additional UI elements

* [x] language switching bar (black) (issue #653)
* [x] primary navigation bar (grey)
* [x] search field in cover photo area
* [ ] HTML class names are semantic.

**Comment by jykae** [comment]
This was decided with @brylie that we put a field to the new Branding tab, that is available for administrators.

**Comment by jykae** [comment]
We took this a bit further with @brylie by pair programming and keeping sync with @elnzv  #756 :) We identified all needed branding elements, and added them to branding settings. We are making the generic structural changes, while @elnzv makes the styling just for APIKA. Continuing tomorrow.

**Comment by bajiat** [comment]
@kyyberi Browser title bar can be only be changed through a config file for the time being. This is related to SEO package we are using. Needs to be investigated. Solution for APIKA: needs to be changed manually at deployment.

**Comment by brylie** [comment]
@elnzv statud update? In what branch is your work-in-progress?

**Comment by brylie** [comment]
Note, the language switching bar is related to task #653. Essentially, we need links on the language bar to trigger a tap:i18n method when clicked. E.g. clicking on "Finnish" will trigger the tap:i18n method `TAPi18n.setLanguage("fi");`

**Comment by jykae** [comment]
@elnzv I will continue on this one, please let me know if there's anything that would clash on development.

**Comment by brylie** [comment]
@jykae will you please work on the cover photo and social media input?

**Comment by brylie** [comment]
@jykae , I have added more ideas in the definition of done (regarding the social media and cover photo fields). Feel free to deviate from that definition of done, but please at least consider trying it to save yourself some time and trouble.

**Comment by jykae** [comment]
@brylie yep, working on social media accounts and cover photo first. My progress is in branch "feature/625-site-title-branding" as the name of this task was different at first.

**Comment by brylie** [comment]
You rock! Also, I am adding some example code for you to consider in the "definition of done" section. Right now, there is an example of the following:

* schema definition
* UI social media list

**Comment by jykae** [comment]
Thanks, noticed :+1:
