### ISSUE TITLE
Re-design adding new API UI

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#628]
Implement adding new API backend based on the workflow and design described in the wireframes below.

>I was totally lost with the UI when I was adding new API to service. I'm no UI designer nor graphics designer, but I decided to give it a shot and sketch new UI. The idea is to force API owner give information is smaller patches. This is highly simplified model and does not contain all the flavours which should be added if this path is selected. 

Definition of done
---
* [x] Create wireframes for the user flow.
* [x] Create flow diagram combining the wireframes.
* [x] Choose how to implement tabbed flow UI.
* [x] Determine how to track the state (current tab/step).
* [x] Pre-populate fields based on user feedback from user input.
* [x] Allow users to go back to previous steps by choosing the step.
* [x] When a user completes a step, toggle active state to subsequent step.
* [x] Validate each field.
* [x] Ensure that the submission to API Umbrella is successful.

# Stages
## Add Base information 
When API owner clicks add new API backend, the following will be shown. 
In the view API owner can see sections, which are expected to be filled. In the below phase "Base" is active, rest are links too but in purpose a little in the background. Owner gives 
* API name, long format
* API slug, short one word. It will be used as "prefix" in umbrella to differentiate it from rest of the APIS
* Description of the API, around 500 chars, not the whole documentation. 

Perhaps there should be a button "next" or something below the last field and from there API owner is taken to next phase. The owner can always switch the phase from top bar. 

![apinf-add-api-suggetion-1](https://cloud.githubusercontent.com/assets/1927158/11164789/0be185cc-8b03-11e5-8aa1-96dea8336b38.png)

## Add servers (host)
In the second phase, owner adds host and servers. The text "Servers" in top bar might be better as "hosts" or something. In that part, owner adds:
* Host name
* Host port
* selects protocol
![apinf-add-api-suggetion-2](https://cloud.githubusercontent.com/assets/1927158/11164808/102776f4-8b04-11e5-8990-d91e345d9a85.png)

## Add documentation
In the third phase, owner defines documentation. It can be either link to external site or Swagger file. Here should be also information how and where the documentation will be shown eg what is means if external is selected or if swagger is used. 
![apinf-add-api-suggetion-3](https://cloud.githubusercontent.com/assets/1927158/11164832/9ab3ce8a-8b04-11e5-896f-39436b236624.png)

## Method mapping
In this phase API owner defines the mapping between OWN API methods and APIKA methods. The owner does not define the umbrella.xxx.xx url, it is as text/given. Note that the slug given in phase 1 is used in umbrella url. Also the OWN API hostname is taken from previously given field (phase 2), in here it is apisuomi.fi.  

What the owner gives is the url path to given method in OWN API and then adds from what url it should be responding from umbrella. Owner can add multiple mappings from below "+" icon. 
![apinf-add-api-suggetion-4](https://cloud.githubusercontent.com/assets/1927158/11164852/4d12e598-8b05-11e5-9f2f-fab7f204381b.png)

## Ready to proceed
The last view which is now lacking should be something that verifies that all needed is now given and we are ready to save and publish API. In other words the last view should include "Save" and "Save and Publish" buttons. 

### Additional notes
This could be also used in editing existing APIs. I have no idea how well this behaves and does it make sense in all cases, but to me this kind of approach would be make it easier to add new APIs.

# Resources
The following Meteor package will enable a the described workflow:
* [Meteor Wizard](https://github.com/forwarder/meteor-wizard/)

**Comment by kyyberi** [comment]
Related to #368

**Comment by kyyberi** [comment]
In the protocol selection, there is no reason to use dropdown since we have two options. Make it buttons "http" and "https", which can click to be selected. Another option is to make it switch 
![button-on-off](https://cloud.githubusercontent.com/assets/1927158/11165159/1d059b7e-8b10-11e5-9f30-ab8481dd4bbf.png)

**Comment by kyyberi** [comment]
In the last still missing phase there should also be "Unpublish" and "Remove" buttons. In the latter there should be safe pattern perhaps like what is in Github when removing repository to avoid accidental removals.

**Comment by kyyberi** [comment]
Another option is to use accordion approach which works for Mobile as well. http://blogs.sitepointstatic.com/examples/tech/css3-target/accordionvert.html

**Comment by bajiat** [comment]
@kyyberi Really good suggestion for UI flow. Being able to add APIs is a key success factor for APIKA and Apinf, so this task must be prioritized.

**Comment by elnzv** [comment]
@kyyberi good idea and nice wireframes! Yes, totally we need to redesign and improve Add New API UI flow. 
Originally, we have just mirrored UI from API Umbrella project

**Comment by bajiat** [comment]
@elnzv You were interested in this task. It is mainly implementation and only some design (flow). Do you still want to take the task?

**Comment by bajiat** [comment]
@elnzv Actually, we decided to propose two other tasks for you from your list. There should not be more than 1-2 big implementation tasks per developer.

**Comment by brylie** [comment]
I will begin work on this feature next Monday. Have a great weekend all!

**Comment by brylie** [comment]
I started re-writing this form as a Wizard, using autoform-wizard. However, I was blocked by an [autoform-wizard bug](https://github.com/forwarder/meteor-wizard/issues/62).

I will review the Meteor Chef article [Form States with ReactiveVar](https://themeteorchef.com/snippets/form-states-with-reactivevar/) for a possible way forward next sprint.

**Comment by brylie** [comment]
Working branch from Sprint 17: https://github.com/apinf/api-umbrella-dashboard/tree/feature/628-add-backend-wizard

**Comment by bajiat** [comment]
Assigning to Brylie for completing the submission of API.
