### ISSUE TITLE
Re-design front page (was: API listing UX)

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#629]
Suggestion for layout in API listing / catalogue 
![listing2](https://cloud.githubusercontent.com/assets/1927158/11168041/953b3e0c-8b86-11e5-858f-aab941fc1801.png)

**Comment by kyyberi** [comment]
This is actualyl what the front page should look like and in that case change the topic to something like "APIKA - avoimien rajapintojen hallinta"

**Comment by brylie** [comment]
This UI seems to imply several features, which may not yet be in our backlog. Specifically, I notice the following features that need planning:

* API Search
* API Categorization
* API Metadata
  * Description
* API Sandbox
  * We agreed to use Swagger UI for sandboxing
  * We will need to continue work on the Swagger UI documentation upload feature

@baijat, lets create this as a 'meta' feature, so that we can track the progress of all related components.

**Comment by bajiat** [comment]
@brylie I agree with you that is not a trivial task. It has quite a lot of items that are either captured in the backlog, but not yet implemented, or are not even planned.

**Comment by brylie** [comment]
Also, it looks like the [Liityntakatalogi](http://liityntakatalogi.suomi.fi/fi/) is powered by CKAN. Since CKAN is open-source, we can either borrow code or provide an integration via its API.

**Comment by ccsr** [comment]
@kyyberi @brylie @bajiat @preriasusi This is a significant change to UI. Can we split to different milestones like APIKA1, APIKA2...based on the realistic estimation?

**Comment by brylie** [comment]
@elnzv will you please also help us understand the design changes? E.g. how the new design elements could be added or factored in to the existing front-end design.

**Comment by kyyberi** [comment]
Btw, with sandbox at this point I refer to live swagger documentation.

**Comment by bajiat** [comment]
@kyyberi "This is actualyl what the front page" Can you clarify front page? Is the proposed view available when user is logged in or not logged in? If not logged in, then sandboxing has to happen without API key. Also, as far as I have understood testing in Swagger always makes a real request so it not sandboxing in the true sense.

@ccsr (@kyyberi @brylie @preriasusi) What are the milestones you had in mind? Splitting current APIKA project into milestones?

**Comment by brylie** [comment]
Relatedly, CKAN are [testing packaging for Ubuntu 14.04 LTS](https://github.com/ckan/ckan/pull/2726). May we spin up a VM and help test the packaging?

**Comment by kyyberi** [comment]
Perhaps th term sandbox is not the right one. Anything with what you can fool around with the api, it can use dummy data or whatever.

**Comment by kyyberi** [comment]
For you to know I met swagger people at apistrat and I'm organizing webinar for the Finnish developer community about the latest tools around swagger. It might interest you too.

**Comment by elnzv** [comment]
@brylie, need more details on this page. Let's plan this and discuss it and then I will provide my ideas and thoughts.

**Comment by bajiat** [comment]
@kyyberi Currently we are only using Swagger for testing APIs and the API calls Swagger makes are real calls direct to the API. And we are working on rerouting them to our proxy. Other than that, we don't have any sandboxing functionality and have no such plans in APIKA timeframe.

**Comment by kyyberi** [comment]
Well, replace the word "sandbox" to "live docs" or something :) I would not use "swagger" as other options should occur in the future.

**Comment by brylie** [comment]
Ah, nice. OK, we will use generic language. Swagger UI is a good API UI for the time being, but we are definitely open to new options. :+1:

**Comment by kyyberi** [comment]
I was browsing the web and it lead to thought or requirement that when we have listing of APIs in the frontpage, we need to offer clear sing of APIs which do not require auth or API-key. Those so called free APIs can be utilized without registering to APIKA. That user registration to get API-key is a barrier for some open data enthusiasts. https://opendata.stackexchange.com/questions/774/should-data-apis-require-registration-and-api-keys

**Comment by brylie** [comment]
Great suggestion. Lets create a new enhancement request based on this idea. That way we can discuss and track its implementation.

On 29 November 2015 20:38:58 EET, Jarkko Moilanen <notifications@github.com> wrote:
>I was browsing the web and it lead to thought or requirement that when
>we have listing of APIs in the frontpage, we need to offer clear sing
>of APIs which do not require auth or API-key. Those so called free APIs
>can be utilized without registering to APIKA. That user registration to
>get API-key is a barrier for some open data enthusiasts.
>https://opendata.stackexchange.com/questions/774/should-data-apis-require-registration-and-api-keys
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apinf/api-umbrella-dashboard/issues/629#issuecomment-160446434

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kyyberi** [comment]
Stumbled upon this pretty good idea of providing for ways to get started. This could be under the title of frontpage 
![screenshot from 2015-12-24 08 31 10](https://cloud.githubusercontent.com/assets/1927158/11990702/2a8498c6-aa1a-11e5-9431-5c4b39756ae8.png)

**Comment by kyyberi** [comment]
Added also featured apps, which refers to application profile containing information of used APIs, description, links to shared Swagger specs etc, creator name and contact. IT's s show window for developers. 

![listing-12-2015](https://cloud.githubusercontent.com/assets/1927158/11993322/26813c66-aa38-11e5-9611-225895b28f28.png)

**Comment by bajiat** [comment]
Closing, the most relevant front page modifications were implemented in #756 and have been deployed to Apika.
