### ISSUE TITLE
API metadata model

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#630]
X-Road API catalogue in Finland has following data structure
![datamodel](https://cloud.githubusercontent.com/assets/1927158/11168086/e1ca8e9c-8b88-11e5-92cc-9e0e2c1352f0.png)

**Comment by kyyberi** [comment]
https://github.com/vrk-kpa/api-catalog

**Comment by kyyberi** [comment]
Related to #472

**Comment by bajiat** [comment]
@kyyberi Thanks for providing the information!

**Comment by kyyberi** [comment]
More info in Digipalvelutehdas Slack

**Comment by kyyberi** [comment]
Perhaps the model should also include API repository information. What I'm after is linking "backlog" to Github Issue list of open issues. That would be great for admin and for API consumers too. It might encourage to contribute. 

The process would need: 
* repo url in API profile (given by admin)
* authorized connection to read and write to Github via API (connection management by API owner)
* ability to close above connection
* ability to change repo
* admin could choose which tags to show. 

At first we would support just Github. Other code management services would follow. I'll make a separate issue about this and label it as design.

**Comment by brylie** [comment]
Closing, since basic API Metadata feature is implemented and we have an open issue for linking Github issues to backlog.
