### ISSUE TITLE
Invalid redirects for Backend host and Frontend host

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#633]
Steps:    

1.Open Internet explorer and visit https://apinf.io    
2.Sign in   
3.Select 'API Backends' from menu    
4.Add API Backend   
5.Go to 'Manage API backends'  
6.Click on Backendhost / Frontend host   

- It redirects to dashboard  instead of showing details of server and URL matches respectively.

Screenshot:  

In Firefox and Chrome:

![links_server_urlmatchers_firefox](https://cloud.githubusercontent.com/assets/13309358/11211297/1c822a90-8d37-11e5-9028-e59760c6188f.png)

**Comment by brylie** [comment]
I am unable to verify this on Firefox/Ubuntu. I will follow up with @baijat to test on IE.

Basically, clicking the 'backend / frontend host' should only open the collapsed section (not link to any other page), whereas clicking 'view/edit' buttons should show the corresponding page.

**Comment by brylie** [comment]
@saralavanip, what version of IE are you using? What version of Windows?

**Comment by saralavanip** [comment]
@brylie ,  IE version 11  and Windows 10.

**Comment by brylie** [comment]
@elnzv suggested using prevent default on click event.

**Comment by brylie** [comment]
@elnzv has duplicated this bug. He has also agreed to fix the issue.
