### ISSUE TITLE
Protocol labels not visible

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#635]
Steps:   

1.Open the Internet explorer and visit https://apinf.io  
2.Sign in   
3.Select 'API Backends' from menu  
4.Add API Backend  
5.Go to 'Manage API backends'  
6.Click on 'View' button

- Protocol labels (http / https)  are not visible.  

Screenshot:  

In Internet Explorer:  

![protocol_label_invisible_ie](https://cloud.githubusercontent.com/assets/13309358/11211678/d207451a-8d39-11e5-867b-80f41d83f9a9.png)

In Mozilla Firefox and Chrome:

![backend_protocol_visible_chrome](https://cloud.githubusercontent.com/assets/13309358/11211696/f582d1da-8d39-11e5-9159-47a1875650fa.png)

**Comment by brylie** [comment]
I have an open PR (#662) with a re-design of the Servers section. 

I changed page elements to use Bootstrap `input-group` with `input-group-addon` for the labels and protocol. The design is a bit cleaner and includes a template helper with CSS classes to colour the protocol (yellow or green based on HTTP/HTTPS) and label elements:

![screenshot-1](https://cloud.githubusercontent.com/assets/17307/11442050/8f22341a-951a-11e5-9aad-285848b5cc5a.png)

![screenshot-2](https://cloud.githubusercontent.com/assets/17307/11442086/f7f8bc84-951a-11e5-9231-86653e5b47ed.png)

**Comment by bajiat** [comment]
Re-opening and assigning to Sarala for verification.

**Comment by bajiat** [comment]
@saralavanip Can you please verify and close the issue, if the bug has been fixed?

**Comment by saralavanip** [comment]
Verified the issue.
