### ISSUE TITLE
Add error handling inside of syncApiBackends method

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#636]
The [`syncApiBakends`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/methods/apiBackends.js#L15) method has been reported to crash Apinf when invalid API backends are returned from API Umbrella. This is partially due to differing validation requirements between Apinf and API Umbrella. In the short-term, we need to at least catch the error within the sync method.

# Related
@mauriciovieira reported the issue when reviewing PR #619

**Comment by mauriciovieira** [comment]
@brylie, @frenchbread, @elnzv  I am working on a hotfix for this one.
