### ISSUE TITLE
Implement public API feedback voting

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#641]
Refer to #542 for discussion

First version of communication channel between consumers and managers allows consumers to send feedback, request etc. about APIs and managers to view the feedback.

# Wireframe
![mockup](https://raw.githubusercontent.com/apinf/docs/master/docs/design/%23149_communication_channel_apinf.png)

# FeedbackVotes collection
This feature may use a new collection called `FeedbackVotes`. Each Feedback Vote document will contain the following fields:

* feedbackId - string - the ID of the Feedback document
* userId - string - the ID of the user
* vote - integer - the numeric vote for the user (allowed values: 1 and -1)

# Collection helper(s)
The following collection helper will be attached to the Feedback collection:
* `sumOfVotes()` - adds all vote integers together, returns the sum of all votes as an integer

# Server method(s)
The following method(s) will be defined on the server:

* `submitVote(vote)` - takes an integer as an argument, checks whether user has already voted, either updates existing or adds new user vote

# Publication(s)
The following publication(s) will be useful:

* getAllVotesForSingleFeedback (feedbackId) - returns a database cursor for the following query:

```JavaScript
FeedbackVotes.find({feedbackId: feedbackId});
```

# Template-level subscription(s)
Each feedback template will subscribe to the `getAllVotesForSingleFeedback` publication. This will ensure that only votes for displayed feedback are returned.

# Definition of done
* [x] Up and downvote arrows appear on each feedback item
* [x] The sum of all up/downvotes displays between up and down arrows
  * [x] Display of sum of votes is visually prominent
* [x] Display of voting arrows is visually prominent
  * [x] Arrows are large enough for easy interaction in touch device
* [x] Up/down arrows change visual appearance to indicate existing user vote
  * [x] Color change
* [x] Mouse cursor changes to 'hand pointer' when hovering over vote arrow, to indicate the user can interact with arrow
* [x] Clicking on a vote a second time deletes user vote.
  * E.g. clicking up and up again 'resets' the user vote
* [x] Any given user can vote only once for a given feedback item
* [x] Anonymous votes are not allowed

## Optional
* [ ]  Sum of votes displays to anonymous visitors
* [ ] When anonymous visitor clicks vote arrow, an alert (`sAlert`) displays instructing the user to 'log in to vote'

**Comment by bajiat** [comment]
@frenchbread Would you be interested in this task?

**Comment by frenchbread** [comment]
@bajiat Self-assigned.

**Comment by bajiat** [comment]
@frenchbread Can you estimate this task?

**Comment by frenchbread** [comment]
@bajiat Done

**Comment by elnzv** [comment]
We keep issue open until PR is merged.

**Comment by brylie** [comment]
@jykae I updated this task with a 'Definition of done', so that the feature requirements are described better. @bajiat please review the definition of done.

**Comment by brylie** [comment]
Most of the unfinished tasks in the Definition of done are related to css classes and declarations. There are some important usability improvements as well, such as the visual indication of user vote. Additionally, users need to be able to 'unvote' or cancel their vote.

**Comment by jykae** [comment]
@brylie Ok,  now I think everything in Definition of Done is done, as well as comments are improved. PR: https://github.com/apinf/api-umbrella-dashboard/pull/703
