### ISSUE TITLE
Functional testing: Test analytics dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#647]
Analytics dashboard is a high priority feature in Apinf. As such, we need manual functional and usability testing for this view.

Definition of done
----
* [x] Use your own API key to create API requests to several APIs. (Add APIs, if necessary)
* [x] Check the analytics dashboard and interact with the graphs. 
* [x] Report any issues labeling them appropriately (e.g. bug or enhancement)

**Comment by saralavanip** [comment]
@Taija , I have added APIs and tried to call APIs with API Key. I am
getting error 'API_Key_Missing' though added  API key. Please refer to the
similar issue filed :
https://github.com/apinf/api-umbrella-dashboard/issues/606. Could you
please let me know, if it is the right procedure to call an API using API
key.

**Comment by ashakunt** [comment]
@bajiat @brylie I find that making calls to umbrella as per the usage instructions given in APINF.com is broken. The instructions say: 

Make API calls to: 
https://umbrella.apinf.io/api-umbrella/[Frontend prefix]
Note: you may need to use your API Key, found on your profile page.

Although, the actual call happens at: https://umbrella.apinf.io/[frontend prefix]

Is there a specific reason for this?

**Comment by saralavanip** [comment]
I just added an API from my login and following are the results : 

* The API was not published immediately. @ashakunt had to that from umbrella.apinf.io website. If there is a delay in publishing the API to the underlying umbrella server; as an END USER, I would like to be informed.
* After the API was published, I still cannot access my API from the umbrella.

(I am using https://umbrella.apinf.io/ [frontend-prefix] / api / url ?api_key=MY_API_KEY) 

As pointed out by @ashakunt earlier, the link given in Usage instructions does not work.

**Comment by saralavanip** [comment]
Issues related to 'Manage API backend' and 'Analytics dashboard' : 

1.https://github.com/apinf/api-umbrella-dashboard/issues/671
2. https://github.com/apinf/api-umbrella-dashboard/issues/672  
3. https://github.com/apinf/api-umbrella-dashboard/issues/673
4. https://github.com/apinf/api-umbrella-dashboard/issues/674  
5.  https://github.com/apinf/api-umbrella-dashboard/issues/675

**Comment by brylie** [comment]
It is a UI bug. We will open a hotfix ASAP.

On 1 December 2015 14:56:46 EET, Aseem Shakuntal <notifications@github.com> wrote:
>@bajiat @brylie I find that making calls to umbrella as per the usage
>instructions given in APINF.com is broken. The instructions say: 
>
>Make API calls to: 
>https://umbrella.apinf.io/api-umbrella/[Frontend prefix]
>Note: you may need to use your API Key, found on your profile page.
>
>Although, the actual call happens at:
>https://umbrella.apinf.io/[frontend prefix]
>
>Is there a specific reason for this? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apinf/api-umbrella-dashboard/issues/647#issuecomment-160962007

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bajiat** [comment]
@saralavanip We had sprint 17 review today and are cleaning the board for sprint 18 planning. I quess you have already tested the dashboard and reported the errors? Can we close the issue? Or is there something that should still be checked?

**Comment by saralavanip** [comment]
@bajiat , Yes, we can close the issue for this Sprint 17.
