### ISSUE TITLE
Implement displaying API name in Swagger Viewer doc select

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#649]
At the moment, the drop down box for selecting Swagger file in Swagger viewer shows file name.  The user might not be able to recognise the file name. Hence, the select box should show API backend name instead.

Definition of done
---
* [x] Drop down box should not display empty rows.
* [x] Drop down box should display API backend names.
* [x] Documentation file should be linked to API Backend (by foreign key?)
* [ ] Optionally, drop down box can be combined with type-ahead feature.

**Comment by frenchbread** [comment]
I would like to take this one since I am working on similar issue about Swagger.

**Comment by bajiat** [comment]
@frenchbread Can you estimate this task?

**Comment by frenchbread** [comment]
@bajiat Done

**Comment by frenchbread** [comment]
This issue is partly implemented in  #517 (PR - #590).

**Comment by brylie** [comment]
I opened a PR (#677) for this issue. @apinf/developers please review.

**Comment by brylie** [comment]
Lets move the type-ahead feature request to its own issue.
