### ISSUE TITLE
Create docker installation file

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#650]
As part of our packaging process, we would like to support Docker. Create a basic Dockerfile for the Apinf installer.

# Definition of done
* [ ] System administrators can deploy an Apinf + API Umbrella stack in one command, via Docker
* [ ] Developers can set up a local development environment in one command, using Docker, sh, or something similar
* [ ] **Bonus**: System administrators can deploy Apinf + API Umbrella using [Rancher](http://rancher.com/rancher/) UI

# Related
- There is an open [pull request](https://github.com/apinf/api-umbrella-dashboard/pull/900) with initial work on an Apinf Docker image
- We opened an [upstream issue](https://github.com/NREL/api-umbrella/issues/228) requesting that NREL provide an up-to-date Docker image for API Umbrella.

**Comment by brylie** [comment]
@bajiat and @ccsr, @shaliko has agreed to begin work on this task. I have updated the definition of done to include some general goals of the task.

**Comment by bajiat** [comment]
@shaliko What is the status of this task? (I closed the other one I asked about as duplicate)
