### ISSUE TITLE
Unit in response time in analytics  view

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#654]
As a API owner I want to see response time unit in analytics page where it list the API uage details. Now it says just "response time" and I assume that it is milliseconds. 
![response-time](https://cloud.githubusercontent.com/assets/1927158/11393233/3394b46a-9367-11e5-8f13-5760136b5be0.png)

Definition of done
---
* [ ] Column header displays "Response time in ms"

**Comment by preriasusi** [comment]
Should not be huge work to fix this. Proposing to next sprint.

**Comment by kyyberi** [comment]
Even I should be able to fix that :) it takes more effort to follow contribution process than making fix :)

**Comment by bajiat** [comment]
@brylie Please check whether we can move the PR from master to develop.

**Comment by kyyberi** [comment]
I can do it again if needed

**Comment by elnzv** [comment]
@kyyberi, thanks.
We follow [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) guidelines.
In order PR to merged, name it as *hotfix/fix-name-here* and create it to be merged into develop.

**Comment by brylie** [comment]
The primary ideas is that the PR should be made against `develop` instead of `master` :-)

We also recognize the difficulty with contributing, and do not want the process to obstruct your contribution. Please let us know if you have any difficulties.

**Comment by kyyberi** [comment]
Referencing to generic processes page (some of which do not concern) is a good start. Next needed step is to make an example with the context in place. That lowers the barrier.

**Comment by brylie** [comment]
Alright. This  has been resolved. I accidentally committed directly to our `develop` branch, so yep... :-)

**Comment by kyyberi** [comment]
:) Nice.

**Comment by brylie** [comment]
Thanks for your feedback on our process. We will add brief instructions to our CONTRIBUTING.md, so that other contributors can quickly branch-commit-push-pr.

**Comment by brylie** [comment]
Closing this issue, since the unit time has been added to the table header.
