### ISSUE TITLE
Determine how to add color schemas for Boilerplate UI

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#66]
The Boilerplate currently ships with Light and Dark color schemes, which can be toggled in a configuration setting. Determine how to add custom color Schemes, and create a new one based on the Apinf Design Book.

User Stories
-------------
 ```
As an API Administrator (Harri)
I would like to change the colors of our API related page(s)
so they match our company branding and style
```

Deliverables
---------------
* [x] Document describing how to create new design scheme (file locations, syntax, etc.)
* [x] Example configuration of scheme containing color scheme and logo if possible

**Comment by JuusoV** [comment]
Created document in hackpad to save this information:
[The hackpad document](https://apinf.hackpad.com/How-to-add-color-schemas-to-boilerplate-UI-iuD3q5kDyVJ)

**Comment by JuusoV** [comment]
Related to #79 Will work with Illya next week on this.
