### ISSUE TITLE
Documentation page with search

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#663]
I took a look at the documentation viewer page. I have a gutt feeling dropdown will not work in the long run. Users will be lost in plethora of items in the future.

 Why not implement search in there too much like google? Make it interactive, so that close matches are listed below with short links as the user types text. The user can select the api from the list. User can select also from the more complite list if enter is pushed and search function return is rendered as pretty api listing (title, description, possible some other meta info) and link to docs.

**Comment by bajiat** [comment]
We are considering deprecating the separate Documentation viewer and adding the documentation to the tabbed API backend page as its own tab.

**Comment by bajiat** [comment]
We are deprecating the documentation section in favor of displaying documentation in the API backend tab view as its own tab. The issue can be closed when the PR for doc tab is closed.
