### ISSUE TITLE
Redesign View API Backend page/partials to use tabbed interface

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#664]
When viewing details for one api, it came to my mind that if adding api will utilize tabbed content, the same logic should be applied to api profile page as well. This would unify the UX if same logic is applied everywhere. 

# Definition of done
* [ ] Wireframe(s) provided for expected design outcome
* [ ] High priority information has been indicated on wireframe
* [ ] User story exists expressing end-user priorities
* [ ] UI semantics are chosen for tabbed interface and required DOM elements
* [ ] Use existing UI library if possible, namely Bootstrap 3
* [ ] HTML mockup exists demonstrating markup used for tabbed interface

**Comment by brylie** [comment]
It may not be safe to assume these pages will use the same logic, but we should certainly design them with each other in mind. E.g. the tabs may be used in both views, while the AutoForm and static view could be dynamically toggled based on whether the user is viewing or editing.

**Comment by brylie** [comment]
One example of how the logic will differ follows. 

* The *Add/Edit API Backend* form may contain the current step as a state variable related to form validation for each step -- allowing the user to proceed only with required fields are valid. 
* The *View API Backend* page would only need to track which tab is active and hide other tab content.
