### ISSUE TITLE
Research OpenID connect support for Apinf

### ISSUE THREAD

**Issue by preriasusi** [apinf/api-umbrella-dashboard#668]
Work estimation to add OIC (OpenID connect) support for Apinf (Meteor) requested by Apika.

**Comment by brylie** [comment]
There are two Meteor Accounts extension packages for OpenID Connect:

* https://atmospherejs.com/ddxdental/oidrc
* https://atmospherejs.com/ddxdental/accounts-oidrc

However, the sourcecode for the packages is not yet publicly available. I have contacted the package maintainers, asking for the sourcecode to be made available:

* https://github.com/DigitalDentalExchange/DigitalDentalExchange/issues/1

**Comment by preriasusi** [comment]
And the estimation was 20 hours for the developer familiar with Meteor. This is done.
