### ISSUE TITLE
Upgrade to API Umbrella 0.11 release

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#669]
Upgrade API Umbrella to latest version. Benefits include more performant gatekeeper and more organized code base. Several bug reports issued by Apinf team have been resolved in the latest version.

Definition of done
---
* [x] umbrella.apinf.io is running at 0.11 of Api Umbrella.

**Comment by brylie** [comment]
First attempt at upgrading failed after reboot. I opened an [issue with API Umbrella](https://github.com/NREL/api-umbrella/issues/200) describing the error message.

Chandra restored the server to a previous snapshot.

**Comment by brylie** [comment]
I have tried the upgrade process again, using the newly issued 0.10 package. The API Umbrella Web service fails to start, so the administrative interface is unavailable. I have followed up with Nick in the [same issue as above](https://github.com/NREL/api-umbrella/issues/200).

**Comment by elnzv** [comment]
@brylie, I was able to install version 0.8 and successfully upgrade to 0.10 locally.

**Comment by brylie** [comment]
@elnzv will you please try to reproduce the steps on a **clone** of the umbrella.apinf.io VM? 

@ccsr will you please re-clone the umbrella.apinf.io VM under the subdomain umbrella010.apinf.io and give @elnzv access?

**Comment by ccsr** [comment]
@brylie Can I destroy the umbrella010 server which we created yesterday?

**Comment by brylie** [comment]
@ccsr jep.

**Comment by ccsr** [comment]
@elnzv and @brylie this is done. There is umbrella010.apinf.io server cloned and it seems that Illya already has sudo access to it. So @elnzv please use your credentials which are same for umbrella.apinf.io and log in.

**Comment by bajiat** [comment]
@elnzv Would you be able to take this task?

**Comment by jykae** [comment]
@ccsr I need access to umbrella.apinf.io server to make the upgrade.

**Comment by jykae** [comment]
@elnzv Could you give me access to umbrella010.apinf.io ?

**Comment by brylie** [comment]
@jykae I have created a user for you. I can let you know the password in person.

**Comment by jykae** [comment]
Got access and located error from logs, started discussion here: https://github.com/NREL/api-umbrella/issues/200

**Comment by jykae** [comment]
I tried to follow up @ashakunt fix for this but "router" app didn't exist in "embedded/apps" folder. Also "embedded/bin" is significantly different and misses lots of binaries that exist in 0.8.

Changing "server_names_hash_bucket_size" in api-umbrella/etc/nginx/web.conf doesn't seem to be enough. It isn't changing, maybe overwritten somewhere. Restarted Umbrella couple of times.

**Comment by brylie** [comment]
Alright, good work here @jykae. Please open an upstream issue with API Umbrella, if the your comments on the previous issue are not resolved :-)

**Comment by jykae** [comment]
Opened a fresh issue: https://github.com/NREL/api-umbrella/issues/208

@brylie Should we put this to backlog?

**Comment by brylie** [comment]
@jykae yep. We will continue this another sprint.

**Comment by jykae** [comment]
Update:
@GUI has answered to the issue above, the place for quick fix is the same I traced, but didn't want to touch that before I verify that.

Fix for this will be included in the release 0.11

**Comment by jykae** [comment]
Umbrella  0.11 has been released. 
Trying again to umbrella010.apinf.io I purge the installation and try fresh.

**Comment by jykae** [comment]
Umbrella 0.11 installation went smoothly to umbrella010.apinf.io
Umbrella service starts much faster than 0.8 version.

**Comment by jykae** [comment]
@ccsr @brylie In order to upgrade umbrella.apinf.io to version 0.11, I would need access rights to the server.

**Comment by jykae** [comment]
Requested clone from @ccsr  of umbrella.apinf.io to try out upgrade from 0.8 to 0.11

**Comment by jykae** [comment]
Got clone of "umbrella.apinf.io" today, trying upgrade tomorrow. Removing "blocked" tag.

**Comment by jykae** [comment]
Got Umbrella successfully upgraded from 0.8 -> 0.11 to clone machine.

**Comment by jykae** [comment]
Issue with Umbrella REST API only when creating user, https://github.com/NREL/api-umbrella/issues/217 Noticed with nightly.umbrella.apinf.io in #864

**Comment by jykae** [comment]
API Key used in the frontend settings must have "api-umbrella-key-creator" role.

**Comment by jykae** [comment]
Requested access to umbrella.apinf.io yesterday from @ccsr to make upgrade there.

**Comment by ccsr** [comment]
@jykae you should have access to it now

**Comment by jykae** [comment]
Thanks @ccsr !

**Comment by jykae** [comment]
umbrella.apinf.io is now upgraded to v0.11 This has been a long and bumpy road :)
