### ISSUE TITLE
Create a catalogue view for APIs

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#67]
## Create a simple list of available API backends

User story: As Minh (API consumer), I want to find Apinf hosted APIs.

### Definition of done:
* [x] HTML Mockup
* [x]  Create template with embedded with datatable using actual database collection

**Comment by JuusoV** [comment]
Still to be decided: Where will be this Catalogue view presented?

###  What I did 


- Fixed branching issue with local and current branch.
-

**Comment by JuusoV** [comment]
Kept the time estimate at 13 hours. Id say realistical time estimate right now is 10-11 hours.
This depends on how easily I can get data from the database.

**Comment by JuusoV** [comment]
Done. Added task #95 to hook into the navigation
