### ISSUE TITLE
Deploy the 0.2.0 alpha 2 release

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#670]

**Comment by elnzv** [comment]
Getting this error:

```console
Uncaught ReferenceError: JsonRoutes is not defined jsonRoutes.js?c65d1af9d72651c014f2305140cc8d197ee112ec:1 
```
when deploying (same error starting locally). For now commented this file.

**Comment by frenchbread** [comment]
@elnzv Is this error shows up on a server-side or a client-side?

**Comment by elnzv** [comment]
Client, it doesn't crush app locally, but on remote.

On Thu, 3 Dec 2015, 14:26 Damir Mustafin <notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> Is this error shows up on a server-side
> or a client-side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apinf/api-umbrella-dashboard/issues/670#issuecomment-161619829>
> .
>
-- 

Illya Nizyev ~ www.nzv.nz

**Comment by frenchbread** [comment]
Well, try to check if JsonRoutes package is installed.. I had the same error in a browser, when testing it locally but later it just disappeared.

**Comment by elnzv** [comment]
Checked. Package is in place.

On Thu, 3 Dec 2015, 14:35 Damir Mustafin <notifications@github.com> wrote:

> Well, try to check if JsonRoutes package is installed.. I had the same
> error in a browser, when testing it locally but later it just disappeared.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apinf/api-umbrella-dashboard/issues/670#issuecomment-161621387>
> .
>
-- 

Illya Nizyev ~ www.nzv.nz

**Comment by elnzv** [comment]
Solution is might be in wrapping JsonRoute with 

```js
if (Meteor.isServer) {}
```
Based on this code: https://github.com/harryward/lystify/blob/93d81c0dfa3b109523c1190a14b079cb641286a2/morsList.js#L32-L39

**Comment by elnzv** [comment]
Deployed.
