### ISSUE TITLE
API status check error while editing API backend 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#671]
Steps:  

1.Open the Internet explorer and visit https://apinf.io  
2.Sign in   
3.Select 'API Backends' from menu  
4.Add API Backend  
5.Go to 'Manage API backends'   
6.Click on 'Edit' button   
7.Edit API backend  
8.Click on 'Submit' button

Result:  
- Status check takes indefinite time.
- Servers are not shown  

Screenshot:  

![edit_api_checking_status_indefiinite_time](https://cloud.githubusercontent.com/assets/13309358/11509650/f53ed1a4-9867-11e5-991b-13c3991f8ce7.png)

**Comment by brylie** [comment]
This may have been resolved when we merged the add/edit forms. I have not been able to reproduce this bug report on the `develop` branch, as of today.

**Comment by saralavanip** [comment]
Verified this issue.

**Comment by brylie** [comment]
Re-opening, as this issue still affects the `update` form. Closing with upcoming PR.

**Comment by saralavanip** [comment]
Verified.
