### ISSUE TITLE
Mouse point on labels make them disappear

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#673]
Steps:  

1.Visit https://apinf.io  
2.Sign in   
3.Select 'API Backends' from menu  
4.Click on 'Add API Backends'  
5.Go to 'Manage API backends'    
6.Click on 'View' button     
7.Click on 'View usage instructions'  
8.Click on the link for 'profile page'  and copy the API key  
9.Click on the link given for making API call  
10. Add the Frontend prefix and API key  
11.Select 'Analytics' from menu  

Result: Mouse point on labels in the table make them disappear.   

Screenshot:    

![table_not_responsive2](https://cloud.githubusercontent.com/assets/13309358/11510183/136e260e-986b-11e5-8f7d-cc9cc1944355.png)

**Comment by jykae** [comment]
This was fixed with this:

a.dynatable-sort-header:hover {
  color: darkblue;
  text-decoration: underline;
}
 I also added "display" class to table to fit it in the white area.

**Comment by jykae** [comment]
Check PR, https://github.com/apinf/api-umbrella-dashboard/pull/750

**Comment by saralavanip** [comment]
Verified on latest develop version.
