### ISSUE TITLE
'Reset all' in 'Filter' not working

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#676]
Steps:  

1.Visit https://apinf.io

2.Sign in

3.Select 'API Backends' from menu

4.Click on 'Add API Backends'

5.Go to 'Manage API backends'

6.Click on 'View' button

7.Click on 'View usage instructions'

8.Click on the link for 'profile page' and copy the API key

9.Click on the link given for making API call   

10.Add the Frontend prefix and API key

11.Select 'Analytics' from menu    
12.Go to Overview chart and select few records  
13. Click on 'Reset All'  

Result:  'Reset all'  is not working

Screenshot:  

![reset_all_not_working2](https://cloud.githubusercontent.com/assets/13309358/11527561/6b344470-98ea-11e5-9c2c-31fdada3c0bf.png)

**Comment by jykae** [comment]
This is quite challenging.
We would need to put all charts in chartsGroup or chartRegistry, to call filterAll/redrawAll functions. This is badly documented, and might be a bug in the library as well.

**Comment by frenchbread** [comment]
As an alternative, we can pass the "initial" analytics data (that is loaded when page loads for the first time) to the charts. Probably make another `Meteor.call('getChartData')` or `instance.getDashboardData()`

**Comment by jykae** [comment]
@frenchbread I looked that yesterday afternoon, but did not know what data I should pass to 'getDashboardData()' function. Thanks for good alternative :)

**Comment by jykae** [comment]
Hmm, do we need to do everything that is inside "Template.chartsLayout.rendered" in charts.js ? To reset map also.. I'll try first to reset the charts.

**Comment by frenchbread** [comment]
I've tried to make a custom reset button:
```javascript
Template.chartsLayout.helpers({
    'click #resetCharts': function () {
        var instance = Template.instance();
        var data = instance.dataToExport.get();
        instance.renderCharts(instance.parseChartData(data));
      }
});
```
All instance functions are available from `chats.js`. But I faced a problem here - `instance.renderCharts(data){ }` function is "hardcoded" for `data` object that comes almost directly from elastic search. That's why we probably need to refactor `charts.js` before working on this issue.

**Comment by frenchbread** [comment]
@jykae Did not see your update on this issue. Tested it, works for me. :+1:
