### ISSUE TITLE
Incorrect URL in usage instructions 

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#679]
Steps:  

1.Visit https://apinf.io  
2.Sign in   
3.Select 'API Backends' from menu  
4.Click on 'Add API Backend'  
5.Enter API name  
6.Select the Backend protocol from drop down menu  
7.Enter the details of servers: Host and Port  
8.Enter Frontend host and Backend host  
9.Enter URL matches: Frontend prefix and Backend prefix  
10.Click on 'Submit'  button  
11.Click on 'View usage instructions'  
12.Click on the link for 'profile page'  and copy the API key  
13.Click on the link given for making API call  
14. Add the Frontend prefix and API key  

Result: The URL https://umbrella.apinf.io/api-umbrella/[Frontend prefix] in usage instructions is incorrect. 
- Actual call happens at: https://umbrella.apinf.io/[frontend prefix]

Screenshot:  

![incorrect_url_instructions](https://cloud.githubusercontent.com/assets/13309358/11534863/b27b13a2-9919-11e5-91ea-eefa0c7caaf8.png)

**Comment by bajiat** [comment]
@frenchbread Would yo be interested in this task?

**Comment by frenchbread** [comment]
OK

**Comment by frenchbread** [comment]
Is this somehow connected to #694 ?

**Comment by saralavanip** [comment]
Verfiied
