### ISSUE TITLE
Design keyword based search for frontpage

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#684]
Related to issue #629.

# Definition of done

## Frontpage
* [x] There is a search field prominently visible on frontpage.
* [x] Search field contains meaningful helptext.
* [x] Search fields queries API backend collection.
  * [x] Query uses API backend `title` field.
  * [x] Query uses API backend `backend_host` field. - ?
* [x] All search query fields are indexed.
* [x] Search query is case insensitive.
* [x] Search query accepts arbitrary length string, which can contain spaces.

## Results page
* [x] Search results are displayed on a new page
* [x] Page has its own route.
  * [x] Page route contains the search keyword(s)
* [x] Page displays search query texts
* [x] Page displayes number of results
* [x] Page display search field (open items: does it contain the current search query)

## Search results
* [x] Individual results are listed separately.
* [x] Result contains title text.
  * [x] Title text displays prominently.
  * [x] Title text links to View API backend.

**Comment by bajiat** [comment]
@frenchbread Since you were interested in the implementation task, could you take the design as well? Refer to #629 for original idea.

**Comment by frenchbread** [comment]
Wireframe:

Search field is displayed on each page in the header.

![search](https://cloud.githubusercontent.com/assets/2122679/11739684/a14fd752-a030-11e5-895f-62264199d454.png)

**Comment by frenchbread** [comment]
There are going to be two scenarios how to make a search for API Backends:

1. Using search field on the home page - [wireframe](https://cloud.githubusercontent.com/assets/1927158/11168041/953b3e0c-8b86-11e5-858f-aab941fc1801.png).
2. Using search field in the header - [wiraframe](https://cloud.githubusercontent.com/assets/2122679/11739684/a14fd752-a030-11e5-895f-62264199d454.png).

-

**One** of the approaches is to follow [this guide](https://github.com/ideaq/meteor-search) provided in the README and use separate mongodb instance rather than build in meteor mongo. As mentioned in repo above:
> By default, Meteor starts up its own instance of MongoDB, this does not have full-text indexing/search

-

**Second** is to build own method with a complex query:
```javascript
return ApiBackends.find(<query_object>);
```

In example provided `query_object` takes `name` as a main key:
```javascript
return ApiBackends.find({ "name": /maps/ }); 

// Returns an array ob objects with a name that contains "maps" word in it
```

Example above is case sensitive though, for that reason could use extended approach, e.g.:
```javascript
return ApiBackends.find({ "name": /^maps$/i }); 
```

Or using RegEx by providing an object with a `$regex` operator:
```javascript
return ApiBackends.find({ "name": { $regex : '^maps$' } }); // case INSENSITIVE
```

[Source](http://stackoverflow.com/questions/8246019/case-insensitive-search-in-mongo)

**Comment by frenchbread** [comment]
#### One useful feature:

Once search is submitted, and if the search query 100% matches the apiBackend (or only one document was returned), we can redirect user directly to that `API Backend View` page.

**Comment by frenchbread** [comment]
Mongo query example that I came up with:
```javascript
// Construct query
var query = {
  $or: [
    {
      name: {
        $regex: searchPhrase,
        $options: 'i'
      }
    },
    {
      backend_host: {
        $regex: searchQuery,
        $options: 'i'
      }
    }
  ]
};

// Fetch apiBackends
var foundApiBackends = ApiBackends.find(query).fetch();
```

This example represents a search for `<searchPhrase>` in both `name` & `backend_host` fields. 

`$regex`'s `i` - option gives case-insensitivity (in Mongodb).

[MongoDB - `$regex` docs.](https://docs.mongodb.org/manual/reference/operator/query/regex/)

**Comment by frenchbread** [comment]
#### Search functionality is implemented and works nicely. 

Even though documents are returned, getting this error:
```
Exception from sub searchApiBackends id PR3nriYFkine3PFka Error: Publish function can only return a Cursor or an array of Cursors
```

I've been trying to fix it by adding `waitOn` for subscription function to a `/search` route but it did not fix the error.

@brylie Any thoughts?

[`working-branch`](https://github.com/apinf/api-umbrella-dashboard/compare/feature/search-apis)

**Comment by brylie** [comment]
@frenchbread it looks like [you return an empty object if there is not a search term](https://github.com/apinf/api-umbrella-dashboard/compare/feature/search-apis#diff-b7918c7dad6393e73ae3f4aa9237794eR3), which is not a cursor.

Check out the [Guide to Full Text Search in Meteor](https://www.okgrow.com/posts/guide-to-full-text-search-in-meteor) for a working implementation. 

Make sure you are also indexing the fields for searching, using `_ensureIndexed`, which is also demonstrated in the previously mentioned article.

**Comment by frenchbread** [comment]
@brylie Thanks! That helped to fix the issue.

**Comment by frenchbread** [comment]
PR #719 created. Currently having `WIP` label on it. 

I'm going to improve the visual design of search result returned on a page with @elnzv's help.

**Comment by frenchbread** [comment]
Removed `WIP` label. 

@apinf/developers please review.
