### ISSUE TITLE
Implement keyword based search for frontpage

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#685]
Related to #629 and #684.

**Comment by frenchbread** [comment]
Interested.

**Comment by frenchbread** [comment]
Definition of done as well as implementation updates are provided in issue #684.

[`working-branch`](https://github.com/apinf/api-umbrella-dashboard/compare/feature/search-apis)

**Comment by bajiat** [comment]
To be closed. As @frenchbread commented, all progress can be seen from #684.
