### ISSUE TITLE
Sprint 22 functional testing

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#688]
Test the improved View API backed, which now has a tabbed interface, on nightly.apinf.io. 

Definition of done
---
* [x] Go throught the different views: Details, Metadata, Feedback, Backlog, optionally also Export. (If possible, in more than one browser)
* [x] If there is an API you have added and hence you are the manager, add metadata for that API.
* [x] If there is an API you have added and are the manager addone  backlog item for that API.
* [x] Select another API (one which you are not manager for) and create one feedback item for it.

**Comment by bajiat** [comment]
@ashakunt Any updates on Apinf functional testing?

**Comment by bajiat** [comment]
Blocked by #836, i.e. nightly being down.

**Comment by jykae** [comment]
@bajiat @saralavanip nightly.apinf.io up again.

**Comment by bajiat** [comment]
@jykae Thanks for fixing the nightly!

**Comment by saralavanip** [comment]
Please find below issues reported:

https://github.com/apinf/api-umbrella-dashboard/issues/852
https://github.com/apinf/api-umbrella-dashboard/issues/851
https://github.com/apinf/api-umbrella-dashboard/issues/853
https://github.com/apinf/api-umbrella-dashboard/issues/854
https://github.com/apinf/api-umbrella-dashboard/issues/855
https://github.com/apinf/api-umbrella-dashboard/issues/856
https://github.com/apinf/api-umbrella-dashboard/issues/857
https://github.com/apinf/api-umbrella-dashboard/issues/865
https://github.com/apinf/api-umbrella-dashboard/issues/867
