### ISSUE TITLE
Add API key field to user profile

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#69]
Implement API key field to user profile.

User story: As Minh (API consumer), I want to retrieve my API key.

Definition of done:
* [x]  Add API key field to user schema
* [x]  Add key preview field to user schema
* [x]  Add API key  / preview field to profile page

**Comment by brylie** [comment]
We have at least two options for how to store the API Key data, in relation to the Meteor user.

1) We can store the API Umbrella User data within the Meteor user object (e.g. user.profile.apiUmbrellaUser..)
2) We can store the API Umbrella User data in a separate collection and have a 'foreign key' relationship in the Meteor user object (e.g. user.apiUmbrellaUser = key)

In the second case, we would write a collection helper to retrieve the correct API Umbrella User object from the ApiUmbrellaUsers collection, allowing traversal such as user.apiUmbrellaUser.apiKey.
