### ISSUE TITLE
Set up i18n translation interface

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#691]
How are we going to manage translations? I'm ready to do some translations to Finnish but not sure which way to proceed. Strings are at least planned if not all already to be in separate files for each lang. 

I see two options:
* take translation management to dedicated platform. 
* copy original en i18n file and rename it to target language and accept as pull request. 

The latter is taking the easy way for project, but probably not the best for community and for getting crowd of translators.

**Comment by kyyberi** [comment]
I tested OneSky service: 

* http://os7daht.oneskyapp.com/collaboration/

API Umbrella is using the same.

**Comment by kyyberi** [comment]
I could take this feature and keep on working with it given that this is the way to proceed.

**Comment by brylie** [comment]
Good suggestion, we just need to make sure the l10n strings are compatible with [tap:i18n](https://github.com/TAPevents/tap-i18n/).

**Comment by brylie** [comment]
Also, the tap:i18n package uses [i18next](http://i18next.com/), which has a [web translation interface](http://i18next.com/pages/ext_webtranslate.html).

**Comment by kyyberi** [comment]
Well either one looks good. Now we need decision.

**Comment by kyyberi** [comment]
@bajiat I believe this is PO decision at the end. Is there something, additional information, or else needed to make decision which way to go?

**Comment by bajiat** [comment]
@kyyberi I will look into this and see if I need more information.

**Comment by bajiat** [comment]
@kyyberi @brylie 
If we take OneSky into use, we would need to modify the i18n json file  as described in #692. Is there anything else that is required? 

I looked at Jarkko's experimentation and based on that the OneSky web interface looks easy to use and  it seems to allow easy crowdsouring (but only for up to 5 collaborators for free.) Also, looks likes it regularly updated (based on the Github repo).

**Comment by kyyberi** [comment]
Or then we could use transifex, which is also used a lot in open source community. https://www.transifex.com/apinfio/apinfio-api-management/dashboard/

**Comment by bajiat** [comment]
Let's continue using OneSky. The UI seems nice to use and easy to understand. Signup is not too complicated either (esp when compared to Transifex).
