### ISSUE TITLE
Change basePath in swagger.json to use apiBackend.frontendPrefix

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#694]
The `baseUrl` setting in `swagger.json` is currently [set to the value of Meteor.apiUmbrella.basePath](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/routes/jsonRoutes.js#L20). This will cause errors. Change the JsonRoute to use the [frontend prefix from the API Backend configuration](https://github.com/apinf/api-umbrella-dashboard/blob/develop/both/collections/backend.js#L91).

# Definition of done
* [x] [swagger.json is autogenerated from JsonRoute](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/routes/jsonRoutes.js#L1)
* [x] in autogenerated swagger.json
  * [x] [`basePath`](https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-simple.json#L16) is set to value of [`url_matches.frontend_prefix`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/both/collections/backend.js#L91)
  * [x] `basePath` value **does not include** `/api-umbrella/` prefix

**Comment by bajiat** [comment]
@frenchbread Would you want to make this small adjustment to your Swagger implementation?

**Comment by frenchbread** [comment]
@bajiat Sure!

**Comment by frenchbread** [comment]
@brylie What should happen if `apiBackend` contains couple of `url_matches`? Because they are anyways stored in an array e.g. `apiBackend.url_matches[0].frontend_prefix`..

**Comment by brylie** [comment]
Yep, for now we select the zeroth. I am not sure what scenarios might arise with sub-route custom settings, but we can cross that bridge when it arises.

**Comment by frenchbread** [comment]
PR #698.
