### ISSUE TITLE
Remove "android" from .meteor/platforms

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#696]
As we don't currently need to build ".apk" package for Android, this could be removed from [build platforms](https://github.com/apinf/api-umbrella-dashboard/blob/develop/.meteor/platforms#L1) as it causes error on building for production.

**Comment by brylie** [comment]
:+1:

**Comment by bajiat** [comment]
@jykae Would you be interested in this task?

**Comment by jykae** [comment]
Related and will be resolved here: https://github.com/apinf/api-umbrella-dashboard/pull/728
