### ISSUE TITLE
Implement communication channel between developers and API admins

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#70]
Using the wireframe and design document from the issue #149, implement communication channel feature.

User story: As Minh (API consumer), I want to be able to report API problems or bugs to API administrator

# Definition of done

## Research
* [x] Locate the wireframe and design document for task #149.
* [x] Check availability for discussion modules in Atmosphere or other Meteor projects.

## Install 
If an existing 'conversation' package exists for Meteor:

* [ ] Add the discussion module to project.
* [ ] Integrate discussion module
* [ ] Implement missing templates or other functionality

## Implement
If no, or few, existing conversation module(s) exist:

* [x]  Create template(s) to match wireframe document.
  * [x] Form to send message
  * [ ] Form to respond
  * [ ] Template(s) to display discussion thread
* [x] Create template logic
  * [ ] Display conversation
  * [x] Send message
* [ ] Create collection to store conversations between admins and developers.
* [x] Create publication(s)
* [x] Subscribe to publication(s) in relevant template(s)

**Comment by bajiat** [comment]
Related to

**Comment by bajiat** [comment]
@elnzv Could you take this task? It would be a continuation of your design task from last sprint. If yes, can you estimate the size.

**Comment by elnzv** [comment]
@bajiat, please, give me access to docs repo, I will upload design files there.

**Comment by bajiat** [comment]
@elnzv You should have Write permission to docs now. 

@brylie: for your information, I have added Write permission to design and research teams to docs repository, because Illya and Laura were not able to add documents.

**Comment by elnzv** [comment]
Here is exactly what we are looking for:
https://github.com/vivekvrao/user-feedback

It has all functionality I mentioned in design document.
There is basic and really poor UI, so this is something I will work on.

I will fork this project and make needed modifications.
Also it is a good opportunity to contribute to open source project.

**Comment by brylie** [comment]
@elnzv status report?

**Comment by elnzv** [comment]
Working on own solution for this feature.
Working branch - https://github.com/apinf/api-umbrella-dashboard/tree/feature/user-admin-communication-channel
