### ISSUE TITLE
Use actual frontend prefix when displaying usage instructions on API Backend page

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#707]
The usage instructions on the API Backend page currently display as such:

> https://umbrella.apinf.io[frontend-prefix]

This may be confusing, and omits the slash between the base url and path.

Consider how to fix this issue, possibly displaying the fully formatted URL with actual values foor base url and path.

# Reference
The 'host' setting (in  `both/collections/settings.js` ) does not enforce a trailing slash, either currently or in the upcoming settings feature:

```js
"apinf.host": {
    type: String,
    regEx: SimpleSchema.RegEx.Url,
...
```

**Comment by brylie** [comment]
@frenchbread, will you please check this issue? Your work in Sprint 18 (#679) is related to this task.

**Comment by frenchbread** [comment]
@brylie Ok, will look into that. Btw on my side the URL is displayed with a slash on place - `https://umbrella.apinf.io/[Frontend prefix]`.

Would the `[frontend-prefix]` change to a real `apiBackend.url_matches.frontend-prefix` solve the problem?

**Comment by brylie** [comment]
Yep. Did you complete this task? I cannot recall.

**Comment by frenchbread** [comment]
@brylie If i'm correct it has been fixed & merged to `develop` branch.

**Comment by frenchbread** [comment]
Created a PR #726. Please review
