### ISSUE TITLE
Make sure settings, including example.settings.json, are refactured to match settings page PR structure

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#709]
The Settings Page feature made changes to the way settings are handled. As a follow up to that task, we need to check that all settings are updated in throughout our app, including the example.settings.json, to match the new structure.

Specifically:

* apiUmbrella
* elasticSearch
* mail
* contactForm
* githubConfiguration

**Comment by brylie** [comment]
This issue is related to the review process for @elnzv issue #327

**Comment by bajiat** [comment]
@jykae Would you be interested in this task?

**Comment by bajiat** [comment]
@apinf/developers Who wants to volunteer for this task?

**Comment by elnzv** [comment]
Checked. That have already been done.
See this commit: 
https://github.com/apinf/api-umbrella-dashboard/commit/bd3e1e71e213186b4ec77ca937565694939a2269

@apinf/developers, please confirm and close this issue.

**Comment by brylie** [comment]
OK, go ahead and close.
