### ISSUE TITLE
Add API Backend form fields still wrong

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#712]
I added image from Apinf frontend and Umbrella, if this helps to understand issue on we have currently in the form. This should be fixed as soon as possible.

<img width="1036" alt="nayttokuva 2015-12-14 kello 12 46 58" src="https://cloud.githubusercontent.com/assets/293452/11779000/17100782-a261-11e5-8860-03abf568b12e.png">

<img width="1258" alt="nayttokuva 2015-12-14 kello 12 47 26" src="https://cloud.githubusercontent.com/assets/293452/11779001/1a069fc8-a261-11e5-9172-1d79bf7270a7.png">

**Comment by brylie** [comment]
@jykae this was fixed in a [PR merged 1 day ago](https://github.com/apinf/api-umbrella-dashboard/pull/710).
