### ISSUE TITLE
Update CONTRIBUTING.md with brief Gitflow instructions

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#720]
Add a brief introduction to the contribution process, so that new contributors can easily follow our process. Include at least the following steps:

* branch -- from `develop`
* commit -- into own `feature/` branch
* push -- to origin
* pull request -- for review, making sure to base your PR on the `develop` branch

**Comment by kyyberi** [comment]
Something like this would make it clear for all https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#submitting-a-pull-request
