### ISSUE TITLE
Force HTTP to HTTPS

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#729]
Find out how to force http traffic to https. How this is done in apinf.io?

My findings: https://www.ibm.com/developerworks/community/blogs/7cce3ca0-2e7b-4603-90c5-570b646f0dd7/entry/secure-meteor-production-environment-with-meteor-up?lang=en

Referring to the last section in the article: "If you want to enforce every request to be via HTTPS, simply add the Meteor package force-ssl​. With this package in your local development environment, you don't need https and the app can still be accessed via http. In production mode (which is the case with systems setup via MUP) every request via http is redirected to https."

**Comment by jykae** [comment]
Steps:
* Added "force-ssl" package to project
* Tested first on development
* mup deploy to apika-staging server

Does not require SSL on the development, on the production with MUP forces SSL if user tries to access http path. Works as it promises.

I will put this to APIKA, to fix #788
@brylie  can decide if we want this package to main product

**Comment by jykae** [comment]
apika.digipalvelutehdas.fi forces now HTTPS.

**Comment by jykae** [comment]
Couple of links for reminder how to setup SSL without extra step to configure nginx in the front of Meteor application: 
https://github.com/arunoda/meteor-up#ssl-support
http://alexnj.com/blog/configuring-a-positivessl-certificate-with-stud

**Comment by brylie** [comment]
@jykae lets use it in our project as well.

**Comment by jykae** [comment]
@brylie Ok, I put PR

**Comment by bajiat** [comment]
@jykae What is the number of the PR?
