### ISSUE TITLE
Create a form for API definition based on API Umbrella UI

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#73]
Design a form to configure new API endpoints based on API Umbrella UI. Use autoform and simple schema, if possible.

User story: As Harri (API administrator), I want to create API and its configurations

Definition of done:
* [x]  wireframe
* [x]  Template with autoform embedded (requires schema from #90)

**Comment by nizyev** [comment]
We have decided for now to mirror most of the structure of existing API Umbrella form configuration. There are going to be discussion on Tuesday (09.06) about UI elements and I have created an [issue](https://github.com/NREL/api-umbrella/issues/148) to clarify about one element of existing form. Final task (which is part of #79) is branding with material design.
