### ISSUE TITLE
Add 'Latest API Backends' view to front page

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#730]
Add the Latest API Backends template to the front page. 

See the picture for wireframe:
![ux2](https://cloud.githubusercontent.com/assets/1927158/11991569/8de56f58-aa24-11e5-88b7-52f06ea280e3.png)

Related issue: #629 

Definition of done
---
* [x] Landing page template includes the latest API backends template (refer to #687).
* [x] Latest API backends responsively adjusts to screen width.
* [x] Latest API backends display  in a grid of boxes.
* [x] Latest API backends template accepts parameter for number of backends shown.

**Comment by jykae** [comment]
@bajiat @brylie Should this replace the current front page in APIKA?

**Comment by kyyberi** [comment]
Not included in question, but in my world yes it should.

**Comment by jykae** [comment]
@kyyberi Ok, thanks :) there's lots of stuff.. I think viewing the middle section "Uusimmat rajapinnat" engl. "Latest API backends" is basically the thing in this task at first.

**Comment by brylie** [comment]
Not the whole front page. It is a partial template, so will be inserted into the existing front page. Specifically, you are working on the **Uusimmat rajapinnat** portion of a much larger rewrite task.

**Comment by brylie** [comment]
Here is a starter template: http://startbootstrap.com/template-overviews/heroic-features/

Basically, we can move towards the whole page rewrite by taking a small step, and using the starter template to  display the latest API Backends.

Later, we can add more features and replace the current frontpage with the new work-in-progress page.

**Comment by frenchbread** [comment]
You taking about the front page when user is not logged in, right? Otherwise user is redirected to the `/dashboard` page.

Also, would be good approach to have a `home page` for a logged in user with all the sweet templates like latest APIs,  search box, some other stuff (just like on the wireframe) which is kind of welcomes user. This way it is possible to have a bird-eye view on some of the content (APIs), links etc with no need to navigate somewhere else.

**Comment by jykae** [comment]
I started with something like this.

![latestapis_frontpage](https://cloud.githubusercontent.com/assets/293452/12093041/4eda2af4-b309-11e5-9de9-a2c5ad1c1b42.png)

**Comment by frenchbread** [comment]
Looks good. It is how it's supposed to be, I guess.

**Comment by kyyberi** [comment]
Looks like a good start!

**Comment by kyyberi** [comment]
Under APIKA you are supposed to follow style guide. Under apinf as @jykae's example.

**Comment by bajiat** [comment]
@kyyberi Can we discuss the style guide and front page for Apika on Friday?

**Comment by kyyberi** [comment]
@bajiat sure we can.

**Comment by jykae** [comment]
@brylie I think I have the requirements for this task now done. I will push the latest stuff to upstream in a moment. There's lot of "marketing speech" on this front page. Do I leave them after the latest Api listing or take away? Do we bring this to "apika_branding" branch OR take generic features to main development branch?

"apika_branding" is the branch where I will deploy to Apika.

@frenchbread your point there was good, if user is logged in it's now quite impossible to get in to frontpage. Good suggestions, that could be way to go.

**Comment by brylie** [comment]
@jykae you can make your pull request by comparing with the `develop` branch. We will have more work relating to the front page redesign, but for now lets just review your changes.

**Comment by jykae** [comment]
@brylie Ok, https://github.com/apinf/api-umbrella-dashboard/pull/749
