### ISSUE TITLE
Fix subscription for latestApiBackends template

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#742]
PR #727 was merged with a global subscription. Update the `latestApiBackends` template to use a template level subscription.

Subscriptions should happen in the `Template.created` callback, rather than within template helpers. They should be attached to the template instance, rather than globally.

```js
Template.latestApiBackends.created = function () {
  // Get named reference to Template instance
  let instance = this;
  
  // Subscribe to latest API Backends, template level
  instance.subscribe("latestApiBackends");
};
```

Please issue a hotfix pull-request for this subscription issue.

# References
* [Meteor Pattern: Template-Level Subscriptions](https://www.discovermeteor.com/blog/template-level-subscriptions/)
* [Using Template-Level Subscriptions with Blaze](https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management/with-blaze)

**Comment by brylie** [comment]
@frenchbread or @jykae would you please consider contributing this small hotfix?

**Comment by frenchbread** [comment]
I'll take this one.

**Comment by frenchbread** [comment]
Created PR #748. Please review.
