### ISSUE TITLE
Replace the apinf.host setting with a call to Meteor.absoluteUrl()

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#743]
Related to #709.
We currently have an unnecessary setting:

```js
apinf: {
  host: "--"
}
```

Remove this setting from the settings form, readme, and from within our code. 

Definition of done
---
* [x] Any usage of `apinf.host` setting is replaced with `Meteor.absoluteUrl()`.

**Comment by sebbel** [comment]
I replaced the unnecessary setting in this branch. 
https://github.com/apinf/api-umbrella-dashboard/tree/bugfix/743-apinf-host
