### ISSUE TITLE
Method for switching UI language

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#753]
When translations in any other language than the source (English) have been imported, there is a need to add a method (button, link, menu) for switching the UI language.

# Definition of done
* [x] Language bar appears along top of page (styled in black in front-page US redesign mockup)
* [ ] Language bar contains options for existing translations
  * [ ] Options are retrieved via [`TAPi18n.getLanguages()`](https://github.com/TAPevents/tap-i18n#tapi18n-api) in a template helper
* [x] Clicking an option in the language bar sets the language via [`TAPi18n.setLanguage(language_tag)`](https://github.com/TAPevents/tap-i18n#tapi18n-api)

# Resources
* tap:i18n [API Docs](https://github.com/TAPevents/tap-i18n#tapi18n-api)

**Comment by brylie** [comment]
@elnzv, will you please take this issue as part of your branding work? I have added a description of done and link to the tap:i18n API docs for reference.

**Comment by jykae** [comment]
Finnish translations added yesterday, switching language works, but when page is refreshed language is switched back to English. @brylie Maybe I need template helper to make it persist? I try to track this.

Note: This language switching was added yesterday only to "feature/apika-branding-front-page" branch. I think we should have it in "develop" as well.

**Comment by frenchbread** [comment]
@jykae What about keeping current language state in a session variable or cookies (local storage)?

**Comment by jykae** [comment]
@frenchbread Hmm, session variable might be a good idea.
Anyway, the current language must be saved somehow in the client to persist between the page refreshes.

**Comment by brylie** [comment]
@jykae [open a support request with tap:i18n](https://github.com/TAPevents/tap-i18n/issues). Page refresh is not common in our app, so this edge case need not block us from resolving this task.

**Comment by bajiat** [comment]
Partially blocked by #785.

**Comment by jykae** [comment]
We might need to use localStorage in Meteor, http://info.meteor.com/blog/session-cookies Meteor user session uses localStorage as well, which is kind of weird compared to other frameworks.

**Comment by sebbel** [comment]
what do you mean by 'weird'?

**Comment by brylie** [comment]
I think using localStorage allows for large session objects to be stored, perhaps compared with cookies.

**Comment by brylie** [comment]
See [Why Meteor doesn't use session cookies](http://info.meteor.com/blog/session-cookies) for further info.
