### ISSUE TITLE
Enhance usage instructions for API

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#758]
In the View API backend page, there is a "View usage instructions" button. Pressing the button opens the following instructions:

"Make API calls to: 
[automatically filled request URL]

Note: you may need to use your API Key, found on your profile page."

Based on feedback through the APIKA support channel, there is a need to enhance these instructions.

Optimally, the instructions should include the parameter of using API key (api_key) in the request coupled with the user's actual API key.
As a minimum, the instruction could include how to use API key in request (i.e. the parameter api_key).

Refer also to bug report #606.

**Comment by saralavanip** [comment]
Verified on latest develop version. 
Still have issue while calling API. Usage instructions could be more explanatory, providing URL that includes user API key.

Reported bugs:
https://github.com/apinf/api-umbrella-dashboard/issues/606
https://github.com/apinf/api-umbrella-dashboard/issues/758

**Comment by bajiat** [comment]
@frenchbread Will you take this task? Brylie can give you some guidance, if needed.

**Comment by frenchbread** [comment]
@bajiat Self-assigned

**Comment by frenchbread** [comment]
PR #801. 
Looks like:
<img width="1079" alt="screen shot 2016-01-27 at 10 27 25" src="https://cloud.githubusercontent.com/assets/2122679/12607836/99c234f6-c4e0-11e5-89be-114f6eac08ec.png">
