### ISSUE TITLE
Enable translation of SimpleSchema custom validation messages

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#759]
We are using SimpleSchema custom validation messages on our user profile form, and possibly other form(s). When trying to add i18n capabilities to the text strings, we get a server side error:

```
TypeError: Object #<Object> has no method 'en'
```

# Related issues
* There is an [issue filed with meteor SimpleSchema](https://github.com/aldeed/meteor-simple-schema/issues/534).
* tap:i18n has an [issue marked fixed](https://github.com/TAPevents/tap-i18n/issues/56)
* meteor-autoform-i18n has a [related issue](https://github.com/gwendall/meteor-autoform-i18n/issues/3)

**Comment by brylie** [comment]
Fixed with PR #760 (issue #472) by moving localization files into `/lib/i18n` to control load order.
