### ISSUE TITLE
Create API testing functionality in documentation browser

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#76]
We have integrated the Swagger UI, which includes sandbox functionality. The functionality should be improved in order to use the actual API key and the API Umbrella proxy.

The Swagger UI is embedded in the `/documentation` template and has two fields at the top:
![swaggerui-urlwithapi_key](https://cloud.githubusercontent.com/assets/17307/10306402/76ebcf82-6c2f-11e5-868d-e46a51a0916c.png)

In the Swagger UI, we want to populate the `api_key` field with the current user's API key.

# User Story
```
 As Minh (API consumer), I want to test API calls in a sandbox.
```

# Definition of done

* [x] Determine how to modify the [Swagger UI](http://swagger.io/swagger-ui/) API testing functionality.
  * [x] Modifications to Swagger UI may be unnecessary, if we can pass arguments in to the iframe
* [x] Pass the APInf user API key to Swagger UI sandbox. (e.g. via an iframe argument or some other method)
* [ ] If possible, ensure the Swagger UI uses API Umbrella proxy, e.g. umbrella.apinf.io, for requests.
  * The API Umbrella proxy URL can be found in [config.json](https://github.com/apinf/api-umbrella-dashboard#settingsjson) (as `api_umbrella.base_url`)

**Comment by ccsr** [comment]
@bajiat this need to be in MVP. Either we need to have flawless document or this. As you know that developers dont read instructions and want to try first. So this is really important for MVP

**Comment by ccsr** [comment]
I totally agree with @bajiat as sandbox needs to be there. Developers are our customers. We need to have a strong value proposition for Developers. I will assign this to Aseem if anything can be done in this regard.

**Comment by ccsr** [comment]
@ashakunt One idea is to use https://github.com/mmcnierney14/api-sandbox

**Comment by bajiat** [comment]
Does the sandbox need to be able to use consumer's API key?

**Comment by bajiat** [comment]
@frenchbread Would you be interested in this task?

**Comment by frenchbread** [comment]
@bajiat Not really, I addition I am not really experienced in Swagger UI.

**Comment by frenchbread** [comment]
@bajiat Ok. Would need to do some research on it..

**Comment by bajiat** [comment]
@frenchbread Thanks for taking this task. Note that this is the highest priority task of the ones you have selected.

**Comment by brylie** [comment]
@frenchbread what is the status of this task?

**Comment by frenchbread** [comment]
@brylie Have not really started  yet. Just did some research about swagger UI. Going to focus on it next week.

**Comment by frenchbread** [comment]
So far, I did some more research about Swagger UI. Created account at [swaggerhub](https://swaggerhub.com/) for testing, created API key as well. 

To be able to use custom API key as well as REST API, there is a need to set up a separate server instance. [Reference link.](http://swagger.io/swagger-codegen/) 

So the next step will probably a installation and launching this instance setup.

Does this sound like correct approach?

Also, what did you mean by `API Umbrella proxy`? Do we just refer to (apiUmbrella API)[http://apiumbrella.io/docs/admin-api/#/] and getting rid of swagger?

> The functionality should be improved in order to use the actual API key and the API Umbrella proxy.

@bajiat @brylie

**Comment by brylie** [comment]
> Also, what did you mean by API Umbrella proxy?

Basically, our apinf.io service is built around API Umbrella. When users are browsing documentation for a third party API, we may want to route their 'sandbox' calls through apinf.io (our API Umbrella proxy) as opposed to directly calling the remote API.

**Comment by brylie** [comment]
Also, the Swagger Codegen may not be relevant to this issue. As far as I understand, Swagger Codegen generates an API scaffold, such as in JavaScript. We are only focused on the documentation browser, Swagger UI, for this task.

**Comment by brylie** [comment]
@frenchbread I have updated this description with a picture. For the rest of this sprint, just focus on how to pass the user API Key into the Swagger UI `api_key` field.

We can look at the more difficult aspect of routing the API calls through `umbrella.apinf.io` in another spring.

**Comment by frenchbread** [comment]
@brylie Okay. 
Just one thing to clarify: `User API key`  is api key created at https://swaggerhub.com/ for a user OR user's api key at https://apinf.io ?

**Comment by frenchbread** [comment]
[`feature/pass-api-key-to-swagger`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/pass-api-key-to-swagger) - current branch I am working on. 

Basic functionality is done, User's API-Key now shows up within swagger UI. Testing..

**Comment by frenchbread** [comment]
>  If possible, ensure the Swagger UI uses API Umbrella proxy, e.g. umbrella.apinf.io, for requests.

This def. of done if attached to newly created issue #517.
