### ISSUE TITLE
Merge CoverPhoto and ProjectLogo to use shared collection

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#774]
Currently, we have separate collections for CoverPhoto and ProjectLogo. Determine how to merge the collections into a single collection, e.g. BrandingImages.

**Comment by jykae** [comment]
@brylie Putting this back to backlog, not that easy and important right now.

**Comment by bajiat** [comment]
@frenchbread Can you take this task, since you are familiar with FS collection?

**Comment by frenchbread** [comment]
@bajiat Ok.

**Comment by brylie** [comment]
Try storing a reference to the file ID in the relevant collections. E.gm Branding.logoId. Use a file upload widget that returns the File ID, so that it can be added as a foreign key reference to the relevant document

**Comment by brylie** [comment]
I.e.

Branding.logoId -》Files._id

**Comment by brylie** [comment]
I have opened a [support request](https://github.com/yogiben/meteor-autoform-file/issues/89) on the meteor-autoform-file repository, to see if we can get some example code demonstrating how to store the File ID in the Branding collection. If this approach does not work, I recommend deprecating the `meteor-autoform-file` package in favour of [aldeed:meteor-cfs-collection](https://github.com/aldeed/meteor-cfs-autoform)

**Comment by brylie** [comment]
If we use **aldeed:meteor-cfs-collection** package, the schema will be changed to look like this:

```js
 projectLogoId: {
    type: String,
    autoform: {
      afFieldInput: {
        type: "cfs-file",
        collection: "files"
      }
    }
  },
coverPhotoId: {
    type: String,
    autoform: {
      afFieldInput: {
        type: "cfs-file",
        collection: "files"
      }
    }
  },
...
```

**Comment by brylie** [comment]
One caveat with the **aldeed:meteor-cfs-collection** package is that we *may* need to figure out how to show a file upload progress indicator. We may be able to do so with the [cfs-ui](https://github.com/CollectionFS/Meteor-cfs-ui) package.

**Comment by brylie** [comment]
@frenchbread I was able to resolve this issue. I have opened a PR for review.

**Comment by frenchbread** [comment]
@brylie Thanks for help with this one. I'll review it tomorrow.

**Comment by brylie** [comment]
@frenchbread and @jykae this PR adds backwards incompatible changes to the codebase. I am not sure how we can enable a migration step for this code, as it removes the collection files altogether. I am open to suggestions.

**Comment by frenchbread** [comment]
@brylie How about dropping it? Since there are a lot of "sample" API backends, we can get rid of them and probably restore the rest.

**Comment by brylie** [comment]
@frenchbread this PR only includes Branding related files. Specifically, the cover photo and logo. It should not affect the API Catalogue or other API backend related features.

**Comment by frenchbread** [comment]
@brylie I see. Then I guess it should not be a problem to restore files manually, unless we want to write a script that will migrate binary data.

**Comment by nnn** [comment]
Closing this since we are in a process of deprecating cfs-collection.
