### ISSUE TITLE
Choose one charting option for our platform.

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#78]
Based on previous research, select chart package to carry project forward. Create a demonstration of chart package into current project.

Definition of done:
* [x] Charting package included in package
* [ ] Create basic views to demonstrate charting feature (e.g. barchart, linechart)

**Comment by brylie** [comment]
What is the status of this task? Did you choose one? What was your choice? Did you meet the definition of done in the task?

**Comment by frenchbread** [comment]
ChartJS - charting library that I've chosen. I am already familiar with it and it supports all needed features for out project such as a lot of different charting options(pie, bar ..) and popup labels when hovering over specific point on a graph.

There is available chartjs package for meteor and I added one. All the updates are in the [sample-chartUsage-demo branch](https://github.com/apinf/api-umbrella-dashboard/tree/feature/sample-chartUsage-demo) branch.

Here is the basic look:

![screen shot 2015-06-04 at 10 37 10](https://cloud.githubusercontent.com/assets/2122679/7979320/deceaa9c-0aa6-11e5-97da-20b945773382.png)
