### ISSUE TITLE
"Edit API Settings" button should not show for unauthorized users

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#781]
Steps to reproduce:
1) In the dashboard click sidebar "Catalogue"
2) Click any "View Details" -button
3) Click "Edit API Settings"

**Comment by jykae** [comment]
@brylie Are you able to fix this one?

**Comment by brylie** [comment]
That is behaving as expected. When the user is not authorized to edit the API Backend, they get that message.


We need to prevent the "Edit API Backend Settings" from showing to unauthorized users, similarly to the other tabs such as Metadata.
