### ISSUE TITLE
Data table headers on dashboard render two translations when changing language

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#785]
When viewing the dashboard (Analytics) and changing the language, the data table headers show translations for both languages. Determine why the initial language translation is not removed.

**Comment by brylie** [comment]
On a first glance at this task, the dashboard code may need significant refactoring in order to refresh the table when language changes. I.e. the TAPi18n.getLanguage() method is reactive, meaning that it can be used to trigger template autorun() events. However, the dashboard template only renders the charts on created(), and the chart rendering function is not designed to allow the table to be re-rendered separately.

**Comment by frenchbread** [comment]
After dyno-table initialisation the initial column header text gets wrapper around anchor link (to be able to trigger sorting events)

**Before init (page source):**
```html
 <th data-dynatable-column="time" >{{_ "dataTable_TimeStamp"}}</th>
```
**After init:**
```html
<th class="dynatable-head" data-dynatable-column="time">
    <a href="#" class="dynatable-sort-header">Time stamp</a>
</th>
```

For that reason, when `TAPi18n.setLanguage("fi")` is called, the initial `<th>`'s text is forced to be changed. However, since text value gets replaced, the translated text is appended to the "old" locatio

**Comment by brylie** [comment]
How can we re-render the dynatable?

**Comment by frenchbread** [comment]
Re-rendering dynatable is not a problem. The problem is to re-render the dynatable's header which is not re-rendered in any way unless we force it to (manually somehow). 

I think this is unneeded and for that reason it's better to reload the entire page with applied language setting.

Another solution is to replace text-headers with an icons. (Finally we can keep header text values in english)

**Comment by brylie** [comment]
@frenchbread how are you re-rendering the Dynatable? I.e. what function are you calling to re-render the Dynatable?

**Comment by frenchbread** [comment]
@brylie I've attached it to Template.instance()

**Comment by brylie** [comment]
Every other page element works properly when switching the language. The UI text changes reactively, without requiring a page refresh. While refreshing the page would work, it seems there should be a way to accomplish this reactively.

**Comment by brylie** [comment]
@frenchbread what function?

**Comment by frenchbread** [comment]
refreshTable()

**Comment by brylie** [comment]
OK, cool. So, it has been refactored into its own function, or was refreshTable() a separate function before this task?

**Comment by brylie** [comment]
@frenchbread within the `refreshTable()` function, would it be reasonable to remove the DOM element, re-insert, and re-render the table? This way all old language text is cleaned, without having to refresh the entire page.

**Comment by frenchbread** [comment]
It was a separate function, yes. E.g.:
```javascript
instance.renderCharts = function() {
    // ...
    function refreshTable() { 
        // ...
    }
}
```
Now:
```javascript
instance.renderCharts = function() {
    // ...
    instance.refreshTable = function () { 
        // ...
    }
}
```

**Comment by brylie** [comment]
OK, move the function definition outside of the `renderCharts` function.

**Comment by frenchbread** [comment]
> remove the DOM element, re-insert, and re-render the table
How can we do it? ("onclick" for example)
I though we need to listen for "languageOnChange" event or smth..

**Comment by brylie** [comment]
The `renderCharts` function will probably need to be broken into separate chunks, instance level functions as you demonstrate above. For the time being, lets just refactor the `refreshTable()` function by moving it outside of the `renderCharts()` function.

**Comment by frenchbread** [comment]
@brylie Ok, will try it.

**Comment by brylie** [comment]
The general pattern in reactive programming is to tell your function to depend on a reactive data source. In this case, the current language is a reactive data source. So, if you envoke `refreshTable()` your function within a reactive computation, such as `Template.autorun()` the function will automatically re-run without any manual event handling.

**Comment by frenchbread** [comment]
Moved `refreshTable()` out of `renderCharts()`.
Working branch: [`hotfix/datatable-headers-i18n`](https://github.com/apinf/api-umbrella-dashboard/tree/hotfix/datatable-headers-i18n)

**Comment by bajiat** [comment]
@frenchbread We are checking the tasks In progress. Do you have an idea of the status of this task?

**Comment by frenchbread** [comment]
@bajiat If i'm recalling correctly there were some issues this this task and it's not finished. It requires "DOM hack" just like @jykae did with medium-editor text duplication.

**Comment by bajiat** [comment]
@frenchbread Would you be able to continue and finalised the fix during this sprint?

**Comment by frenchbread** [comment]
@bajiat Yep. I will continue this one.

**Comment by bajiat** [comment]
@frenchbread What is the status of this task?

**Comment by bajiat** [comment]
@frenchbread Is this task in progress or should it be moved back to Ready column?

**Comment by frenchbread** [comment]
Formally it's in progress. I'll finish it this sprint. On Fri, May 27, 2016 at 11:35 AM, Taija Björklund < notifications@github.com [notifications@github.com] > wrote:
@frenchbread [https://github.com/frenchbread] Is this task in progress or should it be moved back to Ready column?
