### ISSUE TITLE
Github sign in freeze

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#788]
I tried to login with Github account after 0.2 release and it freezes after succesful auth from Github 
![screenshot from 2016-01-22 21 09 38](https://cloud.githubusercontent.com/assets/1927158/12520328/96e0d3b0-c14c-11e5-8fa2-8d7a60738003.png)

**Comment by jykae** [comment]
This relates to issue https://github.com/apinf/api-umbrella-dashboard/issues/729

@kyyberi Use "https://" in the front of URL for now, User session doesn't seem to be same between 80 and 443 ports. Forcing SSL would solve this. Github login expects "https". 
We are sorry for the inconvenience

@brylie Let's check this on Monday.

**Comment by kyyberi** [comment]
Ah. Fix might be that apika forces all http connections to use https. That way user does not get confused.

**Comment by jykae** [comment]
@kyyberi Now apika.digipalvelutehdas.fi forces HTTPS.

**Comment by kyyberi** [comment]
Great!
