### ISSUE TITLE
Text overflow in left menu

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#789]
After login, the texts in left side menu overflow

![screenshot from 2016-01-24 11 54 11](https://cloud.githubusercontent.com/assets/1927158/12535603/5a03abc0-c291-11e5-8651-ab6f501a47c5.png)

**Comment by bajiat** [comment]
Allowing word boundary wrapping would fix the issue.

**Comment by bajiat** [comment]
@elnzv Can you take this task?
