### ISSUE TITLE
Openstreetmap insecure content over HTTPS

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#791]
Openstreetmap loads content over http, as it would be nicer to control it to load over HTTPS when we are using HTTPS everywhere.

Reference: http://gis.stackexchange.com/questions/83953/openlayer-maps-issue-with-ssl

![mixedcontent_apika](https://cloud.githubusercontent.com/assets/293452/12549443/f5ee8dbe-c365-11e5-9256-b700e3ccbb17.png)

**Comment by elnzv** [comment]
I think that is closed by #859.  And already in develop. Need to be tested on remote.

**Comment by elnzv** [comment]
Just tested. No more warnings. Everything works fine.
@jykae, please confirm.

**Comment by jykae** [comment]
Verified, map https warnings are gone in nightly.apinf.io
