### ISSUE TITLE
Add apiDocumentationEditor.host setting to settings page

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#792]
The API Documentation Editor feature currently expects the host to be set via Meteor.settings. However, the host setting is not documented, nor is it displayed on the /settings page. Add the API Documentation Editor host setting to the documentation and settings UI.

# Definition of done
* [ ] example.settings.json contains an example of the `public.apiDocumentationEditor.host` setting
* [ ] The `/settings` route displays an option for API Documentation Editor host
* [ ] The `apiDocumentationEditor` field exists in settings schema (`type: Object`)
* [ ] The `apiDocumentationEditor.host` field exists in settings schema (`type: String`)
 * [ ] The `apiDocumentationEditor.host` field has regEx for URL (`SimpleSchema.RegEx.Url`)

* [ ] *optional* If no API Documentation Editor host setting has been defined, disable the "Documentation Editor" link in master layout sidebar

**Comment by sebbel** [comment]
I would like to take this task.

**Comment by bajiat** [comment]
@sebbel Thanks for volunteering! I will assign the task for you.

**Comment by sebbel** [comment]
Thanks  @bajiat :+1:

**Comment by bajiat** [comment]
@sebbel Thanks for the good work! If I understood correctly, your code can also be used as a template for other optional settings.
