### ISSUE TITLE
Generate documentation from Swagger 2.0 spec file

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#795]
# user story
As API admin I would like to provide API swagger 2.0 spec file (either upload or point file URL) and let service generate documentation in API -management. 

# tools available
https://github.com/swagger-api/swagger-codegen/blob/master/bin/html-petstore.sh

**Comment by kyyberi** [comment]
Add the link to Swagger spec in API metadata.

**Comment by bajiat** [comment]
Closing as duplicate. Covered partially in Documentation tab rewrite. Codegen also considered in research task #950.
