### ISSUE TITLE
Uncaught exception from Swagger viewer in APIKA

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#798]
* Uncaught exception from Swagger viewer in apika.digipalvelutehdas.fi 
![swagger-viewer](https://cloud.githubusercontent.com/assets/293452/12576767/a38bbc04-c41e-11e5-9c00-23163a7bf21c.png)

Exception comes from "both/collections/apiDocs.js" 
Maybe data context issue as we are using "this" quite confidently.

Definition of done
---
* [ ] Error handling exists in both/collections/apiDocs.js
* [ ] The existence of Meteor.User is checked by error handling

**Comment by jykae** [comment]
Exception comes from "both/collections/apiDocs.js" 
Maybe data context issue as we are using "this" quite confidently.

**Comment by jykae** [comment]
This is pretty hard to track because I cannot reproduce issue in local development.
Added checks though.

**Comment by brylie** [comment]
Where is the collection helper `getApiBackendName` used in our project?

**Comment by frenchbread** [comment]
@brylie [Here](https://github.com/apinf/api-umbrella-dashboard/blob/develop/both/collections/apiDocs.js#L13)

**Comment by frenchbread** [comment]
Issue #841 is related to this one

**Comment by brylie** [comment]
@frenchbread thanks. We were actually looking for where it was being used, not defined. That was the confusion.

**Comment by frenchbread** [comment]
@brylie Ah, it's used in template helper - select box on Swagger UI page ([here](https://github.com/apinf/api-umbrella-dashboard/blob/3a7a79686741d3ff68d9f3695e53a3cab1470b2a/client/views/documentation/select/select.html#L7))

**Comment by brylie** [comment]
The [template file select.html had a logical error](https://github.com/apinf/api-umbrella-dashboard/blob/feature/remove-default-language/client/views/documentation/select/select.html#L6-L7).  Even when no `apiDocumentation` is available it tries to call the `getApiBackendName` helper. So, we need a check around that code.
