### ISSUE TITLE
Swagger UI is using Apinf base url, but should be using API Umbrella base url

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#800]
When rendering a Swagger file in the Swagger UI, the host string is overridden. The value of the new host string is gathered from the Apinf absolute URL. However, the value should be set to the API Umbrella base URL, since API Umbrella is actually proxying the requests.

**Comment by frenchbread** [comment]
@brylie Well, actually Swagger UI does not use Apinf's base URL, instead it uses API Umbrella base URL:
```javascript
// Get basePath for apiUmbrella from Meteor settings file
var apiUmbrellaBaseUrl = Meteor.settings.apiUmbrella.baseUrl;
```
And seems that request is proxying through API Umbrella.

The only think that uses Apinf's absolute path is the input field inside Swagger UI iframe, that is used to grab the swagger `*.json` file.

**Comment by brylie** [comment]
OK. 

@bajiat do you recall the source of this bug report?

**Comment by preriasusi** [comment]
I wrote how Swagger calls goes wrong in APIKA into #842 (https://github.com/apinf/api-umbrella-dashboard/issues/842).

But according to @jykae this should be fixed already. @jykae could you confirm, and should that #842 be closed already?

**Comment by brylie** [comment]
If #842 fix works here, please close this issue.
