### ISSUE TITLE
Allow navigation from Add API Backend wizard header

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#803]
The Add API Backend wizard shows the steps in the header area of the template. Currently, the steps do not allow users to navigate backwards when clicking. Adding backward navigation capabilities to the steps in the header may improve usability.

![navigation wizard steps](https://cloud.githubusercontent.com/assets/4495160/12611998/7f96d6e4-c522-11e5-866e-3194906955b8.png)

**Comment by bajiat** [comment]
+1

**Comment by brylie** [comment]
This should be possible using the [`{{ pathForStep stepId }}` helper](https://github.com/forwarder/meteor-wizard/issues/62#issuecomment-175634836).

**Comment by jykae** [comment]
Issue using pathForStep helper, https://github.com/forwarder/meteor-wizard/issues/72

Did not work as expected.

**Comment by jykae** [comment]
Got useful link how to use Wizard with Iron Router, https://github.com/forwarder/meteor-wizard#using-routers-
