### ISSUE TITLE
Mixed content over SSL in general

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#813]
Browser Error: 

```
Mixed content over SSL http://petstore.swagger.io/
```

APIKA uses HTTPS everywhere.
Used site is not available HTTPS.

Suggestion:
* Provide example Swagger file within Apinf project by uploading Petstore file to public files folder.
* Tell Swagger UI to render local Swagger example file, so that it comes from same origin.

**Comment by jykae** [comment]
@elnzv How are you proceeding with this one?
The Swagger mixed content is closely related to #846 I could do that if you are figuring out the SSL mixed content in general. Just want to make sure that we are not conflicting.

**Comment by elnzv** [comment]
@jykae, I have also changed http to https in this commit - https://github.com/apinf/api-umbrella-dashboard/commit/f80df659c0d1ceb555b5320dc657c2d6499d9a84
