### ISSUE TITLE
Enhance API usage instructions

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#815]
Improve the API usage instructions on View API backend page.
* There should be two alternatives for instructions:
  * User is logged in: current instructions, but remove the last sentence "Note: you may need to use your API Key, found on your profile page."
  * User is not logged in: Have a call example without API key. Instruct the users to log in.
* Add error checking for user not logged in to show the latter version of instructions.
* Also, add i18n tags for both versions.

**Comment by frenchbread** [comment]
I'd like to take it.

**Comment by frenchbread** [comment]
PR #832.

**Comment by frenchbread** [comment]
Looks like:
 - User is not authorized 
<img width="1179" alt="screen shot 2016-02-02 at 01 22 18" src="https://cloud.githubusercontent.com/assets/2122679/12734831/a16951e8-c94b-11e5-83b6-308a437c54c9.png">
 - User is authorized 
<img width="1171" alt="screen shot 2016-02-02 at 01 23 03" src="https://cloud.githubusercontent.com/assets/2122679/12734836/a7cf6b1c-c94b-11e5-8a57-69302fdbdaa9.png">
