### ISSUE TITLE
Allow 'date format' to be defined from user locale

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#816]
Currently, the site default date format is stored in `/lib/_config/_config.js`. Enable the date format to be configured from the Settings page.

* [x] Ensure the [date format is set from the user locale within `/lib/utils.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/utils.js#L5). 
* [x] Remove the [`defaultLanguage` key from `/lib/_config/_config.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/_config.js#L23)
* [x] If user locale is none of the locales defined in project translations, English (en) is used as default locale.

# Reference
* Moment.js [i18n documentation](http://momentjs.com/docs/#/i18n/)

**Comment by bajiat** [comment]
Suggestion from @brylie, @jykae, @bajiat: Deprecate the entire config gile. Remove all code that uses anything in config.

**Comment by frenchbread** [comment]
Closing this since #970 is merged.
