### ISSUE TITLE
Determine how to schedule actions in Meteor, e.g. simple cron

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#82]
Determine what options are available for scheduling functions in Meteor. Schedule data synchronization between Apinf and API Umbrella, via REST API, using scheduling method.

Definition of done
* [x] Choose method for scheduling tasks in Meteor
* [ ] Use scheduling method to poll API Umbrella REST API at a given interval

**Comment by frenchbread** [comment]
I found a simple [cron system](https://github.com/percolatestudio/meteor-synced-cron) that supports supports syncronizing jobs between multiple processes.

Here is basic use example:
```javascript
SyncedCron.add({
  name: 'Crunch some important numbers for the marketing department',
  schedule: function(parser) {
    // parser is a later.parse object
    return parser.text('every 2 hours');
  },
  job: function() {
    var numbersCrunched = CrushSomeNumbers();
    return numbersCrunched;
  }
});
```

The time interval is actually set as a plain text which is later being parsed. The best tool that I found so far. 

Any suggestions?

**Comment by brylie** [comment]
Looks good. Do you recommend we go forward with that option?

**Comment by frenchbread** [comment]
Since we needed good library/package for scheduling tasks with specific frequency - I think yes, I do recommend this one.
