### ISSUE TITLE
Latest APIs row renders wrong with title that has more than one line

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#824]
Find out way to fix this with CSS if possible.

![latestapis](https://cloud.githubusercontent.com/assets/293452/12716170/4d924a16-c8e7-11e5-814c-0edf50b266e4.png)

**Comment by brylie** [comment]
Possible approaches:
* [Bootstrap equal height panels with flexbox](http://www.bootply.com/7UhIWMK808)
