### ISSUE TITLE
Update nightly.apinf.io configurations to use SSL

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#836]
### Problem 
"force-ssl" package now forces to https, and mup configuration was not updated after that. 

### Solution
"nightly.apinf.io" TravisCI mup deployment needs configuration update to use SSL.
SSL Certificate needed.
* Let's Encrypt would be good option for nightly: https://letsencrypt.readthedocs.org/en/latest/using.html

### Required information
* What kind of certificate we have in "apinf.io"? If wildcard, we could use the same.

**Comment by jykae** [comment]
@bajiat If it's ok I could take this one to get nightly up again.

**Comment by jykae** [comment]
Trying SSL certificate generation for nightly with Mozilla's Let's Encrypt

**Comment by ashakunt** [comment]
(y) 
Getting this up and running will support latest testing as well.

**Comment by ashakunt** [comment]
@saralavanip you might want to get updated with progress here so that you know when nightly is up and running back again.

**Comment by jykae** [comment]
Wow, pretty awesome for generating and authenticating SSL certificate.
Just generated signed SSL certificate with Let's Encrypt first time :)

Command used:
```
./letsencrypt-auto certonly --standalone --email {myemail} -d nightly.apinf.io
```

**Comment by ashakunt** [comment]
and @jykae that is a green certificate?

**Comment by jykae** [comment]
@ashakunt What you mean with green? Standalone option uses simple webserver for authenticating certificate with CA. Hopefully it works, configuring mup to use this new certificate.

**Comment by ashakunt** [comment]
I meant, a green padlock; and not the error messages that the certificate is a self signed + other bs.. I just now looked into its website and its sounds wonderful

**Comment by jykae** [comment]
@ashakunt ok. Yep, a bit too good to be true :D

**Comment by jykae** [comment]
nightly.apinf.io up again using new SSL certificate. Build successful with TravisCI.

![nightlycert](https://cloud.githubusercontent.com/assets/293452/12784839/36e27258-ca92-11e5-80dd-c4efcc45abae.png)

**Comment by jykae** [comment]
Configurations updated with PR https://github.com/apinf/api-umbrella-dashboard/pull/843
