### ISSUE TITLE
Use 'manager' role to toggle visibility of 'My Managed APIs' link in sidebar; cleanup subscription

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#849]
Currently, we are using a [`userHasApis`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/layouts/master_layout/sidebar/sidebar.js#L2) template helper to toggle visibility of the 'My Managed APIs' link in the master layout sidebar. The helper [performs a database query](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/layouts/master_layout/sidebar/sidebar.js#L6) and [returns true if there are any query results](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/layouts/master_layout/sidebar/sidebar.js#L8). This has required a [subscription](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/layouts/master_layout/sidebar/sidebar.js#L24), which is 'polluting' other features and leading to some false assumptions about data availability.

# Task
* Use the `{{#if isInRole 'manager'}}` helper to toggle visibility of `My Managed APIs` navigation menu link
* Remove the [`userHasApis`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/layouts/master_layout/sidebar/sidebar.js#L2) helper
* Remove the [`myManagedApis` subscription](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/layouts/master_layout/sidebar/sidebar.js#L24)

**Comment by jykae** [comment]
@brylie I cannot find a way how we could do this without making query to ApiBackends.

**Comment by brylie** [comment]
@jykae when the user adds an API Backend, use the autoform `onSuccess` hook to also add the user to the `manager` role.

In the migration script, get a list of all user IDs stored in `apiBackend.managerIds` arrays and add the users to the `manager` role.

**Comment by brylie** [comment]
See the [alanning:roles documentation](https://github.com/alanning/meteor-roles/blob/master/README.md).

**Comment by brylie** [comment]
E.g.

```js
Roles.addUsersToRoles(userId, ['manager'])
```

**Comment by jykae** [comment]
Ok, thanks. I will try this approach.

**Comment by jykae** [comment]
Otherwise ok, will try to provide migration script.
