### ISSUE TITLE
Demonstrate progress in a JavaScript learning framework

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#86]
Start working though an interactive JavaScript course. 

Definition of done
* [ ] Demonstrate progress towards completion of the JavaScript learning resources.

**Comment by JuusoV** [comment]
Khan Academy course: HTML/JS: Making webpages interactive 
https://www.khanacademy.org/computing/computer-programming/html-css-js

**Comment by JuusoV** [comment]
The course im doing:
https://www.khanacademy.org/computing/computer-programming/html-css-js

**Comment by JuusoV** [comment]
40% Into the course. Reduced time estimate from 8 hours to 5.

**Comment by JuusoV** [comment]
Watched almost entire series of LevelUpTuts Meteor for Everyone. Really good stuff, highly recommended.
