### ISSUE TITLE
nightly.apinf.io should use own instance (nightly.umbrella.apinf.io)

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#864]
* [x] Configure nightly.apinf.io to use nightly.umbrella.apinf.io
* [x] Create & use Let's Encrypt SSL certificates for Umbrella

**Comment by ashakunt** [comment]
+ 100 for this.. (count 100 votes from my side)

**Comment by jykae** [comment]
I am having issue with Umbrella REST API when using nightly.umbrella.apinf.io that uses Umbrella v0.11. Opened issue: https://github.com/NREL/api-umbrella/issues/217

**Comment by jykae** [comment]
API Key that is used in our frontend settings must have "api-umbrella-key-creator" role.

**Comment by jykae** [comment]
@apinf/developers consider using nightly.umbrella.apinf.io from now on as development & testing Umbrella, so we could keep umbrella.apinf.io professional looking.
