### ISSUE TITLE
Error message while editing  API-Backend not explanatory

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#865]
Operating Systems:

1. Linux : Ubuntu 14.04.03 LTS (Trusty)
2. Windows 10

Browsers: 
1. Mozilla Firefox 44.0 
2. Google Chrome 48.0.2564.103
3. Microsoft Edge 25.10586.0.0

Steps:
1.Visit https://apinf.io
2. Sign in
3. Go to 'API Backends' 
4. Add API Backend
5. Go to 'Manage API backends'
6. Click on 'View' 
7. Go to 'Details' and click on 'Edit API Settings'
8. Edit API name (eg: add more characters to existing API name)
9. Click on 'Submit' button

Result: Error message “ Cannot read property 'length' of null “    

Screenshot:  

![edit_api_error_message_firefox](https://cloud.githubusercontent.com/assets/13309358/12914736/dd14047a-cf2e-11e5-8076-4878829524ca.png)

**Comment by jykae** [comment]
Could not find this API backend from umbrella.apinf.io Did you @saralavanip create this before editing? umbrella.apinf.io  has been upgraded and cleanup for old API backends has been done.

I followed the steps and added "New Test API backend" and edited the name "New Test API backend edited". Works fine.

**Comment by saralavanip** [comment]
@jykae , this API backend is from nightly.apinf.io. Yes, I added it before editing.

**Comment by jykae** [comment]
That backend doesn't exist on nightly.umbrella.apinf.io we should do cleanup on the Apinf front. nightly.umbrella.apinf.io is a fresh Umbrella install and misses all previously added backends. I think you were testing at that time when I was working with new Umbrella installation for nightly.

**Comment by saralavanip** [comment]
@jykae , Thanks for the info.

Verfied on https://apinf.io : Adding and editing  a new API backend was successful . I'll also test on nightly.apinf.io once the issue #893 is resolved.

**Comment by jykae** [comment]
I will cleanup not existing API backends on the nightly  and this can be closed after that.

**Comment by jykae** [comment]
Cleanup done for API backends on nightly and ApiDocs, server rebooted and synced with nightly Umbrella. Closing this.
