### ISSUE TITLE
Swagger viewer still tries to load example swagger.json over http

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#871]
Mixed Content: The page at 'https://nightly.apinf.io/swagger/index.html?url=' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://petstore.swagger.io/v2/swagger.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by bajiat** [comment]
@elnzv Your PR will probably close this issue as well
