### ISSUE TITLE
Edit API backend view testing

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#877]
The functional testing task is the following:
* Testing the Edit API backend form, which has undergone some quite substantial reorganization and re-writing. 
 * Select and API backend and edit it using the form.
* Localisation testing.
  * Go through the different views and check that the UI texts are visible and no text has been replaced e.g. with i18n tag (= text id)
  * Switch the language on every view and see that the texts get updated to the other UI language.

**Comment by saralavanip** [comment]
Completed this task and please find below issues reported:

https://github.com/apinf/api-umbrella-dashboard/issues/880  
https://github.com/apinf/api-umbrella-dashboard/issues/881  
https://github.com/apinf/api-umbrella-dashboard/issues/882
https://github.com/apinf/api-umbrella-dashboard/issues/883 
https://github.com/apinf/api-umbrella-dashboard/issues/884 
https://github.com/apinf/api-umbrella-dashboard/issues/885 
https://github.com/apinf/api-umbrella-dashboard/issues/886  
https://github.com/apinf/api-umbrella-dashboard/issues/887   
https://github.com/apinf/api-umbrella-dashboard/issues/888    
  https://github.com/apinf/api-umbrella-dashboard/issues/895
https://github.com/apinf/api-umbrella-dashboard/issues/894
https://github.com/apinf/api-umbrella-dashboard/issues/893   
https://github.com/apinf/api-umbrella-dashboard/issues/897  
https://github.com/apinf/api-umbrella-dashboard/issues/898
