### ISSUE TITLE
Change locals settings file to use nightly

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#879]
All Apinf developers need to update their local deployment settings to use nightly.umbrella.apinf.io. Ville to help and to make sure that all developers have the correct access rights.

* [x] Brylie
* [x] Damir
* [x] Illya

**Comment by brylie** [comment]
@apinf/developers please sign off here when you have updated your development settings.json to use nightly.umbrella.apinf.io

**Comment by sebbel** [comment]
updated my dev settings.json

**Comment by brylie** [comment]
@sebbel what email do you want to use to access nightly.umbrella.apinf.io?

**Comment by sebbel** [comment]
the same I had in umbrella.apinf.io

2016-02-17 11:15 GMT+01:00 Brylie Christopher Oxley <
notifications@github.com>:

**Comment by brylie** [comment]
@jykae will you please verify that @sebbel has an admin user in nightly.umbrella.apinf.io, with the same username he used in umbrella.apinf.io?

**Comment by brylie** [comment]
@jykae please add my brylie@samposoftware.com email to the nightly.umbrella.apinf.io admin users.

**Comment by frenchbread** [comment]
Please add [damir.mustafin@samposoftware.com](mailto:damir.mustafin@samposoftware.com) to admin users too. @jykae 

Also, does elasticsearch instance remain on a old host?

**Comment by brylie** [comment]
@frenchbread use Elastic on the new server.

**Comment by jykae** [comment]
@brylie you can take this, if everyone has to have access before next week.

**Comment by brylie** [comment]
@frenchbread, you should now be able to log in to https://nightly.umbrella.apinf.io/admin

Once logged in, you can access your private keys for your local development config:
* API Key
* Admin Auth Token

Remember to change all URLs in your config.json to match the new server.

**Comment by brylie** [comment]
@sebbel I have also added you to the server. Please follow the instructions in the previous message to set up your development environment.

**Comment by brylie** [comment]
I am closing this issue, since the core development team have been added to the new platform. If you have any errors when using your API credentials locally, please open an issue with details.
