### ISSUE TITLE
Upload document and submit error

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#885]
Steps:  

1. Visit https://nightly.apinf.io  
2. Login  
3. Go to dashboard  
4. Add API Backend  
5. Go to Manage API Backends  
6. Click on 'Edit'
7. Go to 'Documentation'
8. Click on 'Browse' to upload 'documentation'  file
9. Click on 'Submit' button

Findings:  

- Notifies user if file uploaded is not a .yaml or .json file and shows error “Cannot read 'property' length of null “ after clicking on 'submit' button.

- Also shows the same error for the correct file type .yaml or .json  uploaded  

![edit_api_upload_doc_config_file_msg](https://cloud.githubusercontent.com/assets/13309358/13176822/9ad344ee-d71d-11e5-8262-1fd3ec0de399.png)

![upload_any_file_type_error_msg](https://cloud.githubusercontent.com/assets/13309358/13176795/725d177e-d71d-11e5-808a-f46ac7154180.png)

![upload_config-yaml_file_error](https://cloud.githubusercontent.com/assets/13309358/13176797/786b4b04-d71d-11e5-91dc-846837ff9f96.png)

**Comment by bajiat** [comment]
To be resolved by #938: the upload functionality from the form will be replaced.
