### ISSUE TITLE
'Edit API backend' view in 'Suomi' language with partly translated text strings

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#887]
Steps:  

1. Visit https://nightly.apinf.io  
2. Change language to 'Suomi'  
3. Login  
4. Go to dashboard  
5. Add API Backend  
6. Go to Manage API Backends  
7. Click on 'Edit'
8. Go to 'Documentation'

Findings:  

- Title text strings for input fields shown in English language
- Title text for 'Browse' and 'Create API documentation' buttons in 'Suomi' view shown in English language
- User information text strings are shown in English language

Screenshots: 

![suomi_view_documentation](https://cloud.githubusercontent.com/assets/13309358/13177236/7354bb48-d720-11e5-8279-776fd01ecdaa.png)

![suomi_view_global_req_settings](https://cloud.githubusercontent.com/assets/13309358/13177247/7d1574e2-d720-11e5-90e2-da61b6594ba9.png)

![suomi_view_advanced_req_rewriting](https://cloud.githubusercontent.com/assets/13309358/13177253/8612f2e0-d720-11e5-8037-f8cfb0a7c97f.png)
  
![suomi_view_advanced_settings](https://cloud.githubusercontent.com/assets/13309358/13177260/90a57692-d720-11e5-8a01-ddee18048374.png)  

![edit_suomi_view_info_text_english1](https://cloud.githubusercontent.com/assets/13309358/13217158/282457fa-d969-11e5-88b2-1e8fd53b631f.png)

![edit_suomi_page_info_english_text2](https://cloud.githubusercontent.com/assets/13309358/13217156/1f0752ee-d969-11e5-9185-92528c7b025a.png)

**Comment by bajiat** [comment]
@elnzv Your PR probably closes this, since the documentation section has been removed from the API settings form
