### ISSUE TITLE
Create a recipe for unit testing

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#889]
Create a model or recipe for a unit test case.

**Comment by bajiat** [comment]
@ashakunt Can you assign this to Alapan? To be completed by 4 March

**Comment by ashakunt** [comment]
@Alapan is working on it already.

**Comment by ashakunt** [comment]
First recipe for unit testing was pushed to "tests" branch. @Alapan  can provide more details about how to run and its dependencies.

**Comment by Alapan** [comment]
I wrote the tests with Jasmine and Velocity. The commands I used to install them were:

meteor add sanjo:jasmine
meteor add velocity:html-reporter

When starting the localhost application by 'meteor --settings PATH-TO-apinf.config.json', the Velocity UI should show the test results.

**Comment by Alapan** [comment]
For testing the template events I added a new package:

meteor add xolvio:template-isolator

**Comment by bajiat** [comment]
@Alapan Will you open a PR on this task?

**Comment by Alapan** [comment]
@bajiat A pull request was created.

**Comment by Alapan** [comment]
I created a new pull request with branch 'test-recipes' and deleted the 'tests' branch. This was because the earlier branch had conflicts since it was mistakenly created on top of the 'master' branch, and not 'develop'. The commits from 'tests' were cherry-picked to 'test-recipes', and the earlier pull request referencing this issue was closed.

**Comment by ashakunt** [comment]
@bajiat @brylie should this be closed now? 

cc: @Alapan

**Comment by brylie** [comment]
Jep.

**Comment by brylie** [comment]
In the future, include the following text in PR descriptions:

* Closes #[issue number]

Github will then automatically close the issue when the PR is merged.
