### ISSUE TITLE
Create an automated functional test recipe

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#890]
Create one automated functional test to server as a recipe for creating automated test cases.

**Comment by bajiat** [comment]
@ashakunt Can you assign this to Alapan? To be completed by 4 March

**Comment by ashakunt** [comment]
@Alapan is already working on this now.

**Comment by Alapan** [comment]
A couple of test cases were written with Selenium (using Eclipse, as the available documentation is better), and the corresponding tests with Robot will be finished tomorrow.

**Comment by Alapan** [comment]
The tests have been written with Robot as well. More tests were written with Robot than Selenium.

**Comment by bajiat** [comment]
@Alapan Will you open a PR on this task? This enables us to review your work / code.

**Comment by Alapan** [comment]
@bajiat A pull request was created.

**Comment by Alapan** [comment]
To install Robot framework, I executed the following commands:

1) sudo apt-get update
2) sudo apt-get install python-pip python-dev build-essential
3) pip install robotframework
4)  sudo pip install robotframework-selenium2library
Verify installation went OK:
1) pybot –version
2) python
in interpreter, type “import Selenium2Library”
(if OK, no errors will be shown, press ctrl+D to exit)

To run the tests, in the folder having tests.txt, the command to be executed is : 
pybot tests.txt

**Comment by Alapan** [comment]
I created a new pull request with branch 'test-recipes' and deleted the 'tests' branch. This was because the earlier branch had conflicts since it was mistakenly created on top of the 'master' branch, and not 'develop'. The commits from 'tests' were cherry-picked to 'test-recipes', and the earlier pull request referencing this issue was closed.

**Comment by Alapan** [comment]
I removed the workspace folder with Selenium tests. The plan is to stick to JavaScript as much as possible and instead use the text-based Robot scripts for UI automation.
