### ISSUE TITLE
User profile testing

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#891]
1) Create a user profile and edit it.
2) Create a dummy user profile and assign this dummy user profile admin privileges. Finally, delete the dummy profile.
(For the second part, you will need admin privileges. Let us know, what is the profile you are using and we will assign you the privileges.)

**Comment by saralavanip** [comment]
@bajiat : I am currently working on issue #877, Settings and localisation testing, I'll continue working on this issue#891 soon.

**Comment by saralavanip** [comment]
@bajiat , @brylie  @jykae :  Signing up on nightly.apinf.io is giving error "internal server error". Could you please check with this issue.  

Also, please let me know if the latest version deployed, so that I can proceed working on this task. 

Screenshot:  

![sign-up-apinf-error](https://cloud.githubusercontent.com/assets/13309358/13244996/98bfaa06-da12-11e5-9d9f-2de4012b3180.png)

**Comment by bajiat** [comment]
I got the same error, when trying to sign up / register as a new user.

**Comment by brylie** [comment]
Yes, this is probably related to a bug we are experiencing since the Umbrella 0.11 upgrade. We need to follow up with @GUI on the API Umbrella tracker to determine whether the problem may be with our integration package or with the API Umbrella Admin API.

**Comment by bajiat** [comment]
Defect #893 created.

**Comment by jykae** [comment]
Nightly settings fixed, verify that registration works now, and close if successful.

**Comment by saralavanip** [comment]
@jykae , Sign up /register a new account on nightly.apinf.io was successful. 
This is my user id: newtest_api1 .

**Comment by saralavanip** [comment]
@bajiat , I have signed up on nightly.apinf.io, could you please give me admin rights. Here is my username: newtest_api1

**Comment by saralavanip** [comment]
@jykae , Thanks for providing profile admin privileges.

**Comment by saralavanip** [comment]
This task has been completed and please find the below issues reported:

https://github.com/apinf/api-umbrella-dashboard/issues/902
https://github.com/apinf/api-umbrella-dashboard/issues/904 
https://github.com/apinf/api-umbrella-dashboard/issues/909  
https://github.com/apinf/api-umbrella-dashboard/issues/903
