### ISSUE TITLE
Signing up on nightly.apinf.io is giving error "internal server error"

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#893]
![screenshot of defect](https://cloud.githubusercontent.com/assets/13309358/13244996/98bfaa06-da12-11e5-9d9f-2de4012b3180.png)

# Steps to reproduce
1. Log in to API Umbrella (0.11 @ nightly.umbrella.apinf.io)
2. Go to Users -> Admin Accounts
3. Create a new admin user
  * check 'superuser' box
4. Go to Users -> API Users
5. Click 'Add New API User'
6. Create new API user with same email as admin user
  * Under Permissions -> Roles, add `api-umbrella-key-creator`
7. Sign-in with new Admin user
8. Get `API Key` and `Admin API Token` for new user
9. Add API Key and Admin API Token to settings.json
10. Launch Apinf
11. Register a new user

# Observed behavior
When registering a new user, the screen displays an **Internal server error** message. In the server console, the following error appears:

```sh
Exception while invoking method 'ATCreateUserServer' Error
     at new ApiUmbrellaError (packages/brylie_api-umbrella/server/apiUmbrellaError.js:33:1)
     at Object.self.adminApi.v1.apiUsers.createUser (packages/brylie_api-umbrella/server/apiUmbrellaWeb.js:275:1)
   ...
```

The main issue is related to the following line `Object.self.adminApi.v1.apiUsers.createUser (packages/brylie_api-umbrella/server/apiUmbrellaWeb.js:275:1`, where we are trying to create an user on API Umbrella.

Related issue: https://github.com/NREL/api-umbrella/issues/217

**Comment by jykae** [comment]
The main issue for this is #899 Close this when it is verified to work.

**Comment by jykae** [comment]
@Alapan and @brylie verified that nightly sign up works now. Closing.
