### ISSUE TITLE
Clean all test APIs from production version

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#905]
Make sure all test APIs are cleaned from both apinf.io / production. They must be removed from both Apinf API backend collection and Api Umbrella. This is particularly important because they show up in latest APIs on frontpage.

Definition of done
---
* [x] apinf.io front page shows no test / testing / test123 APIs
* [x] Api catalogue does not contain any testing APIs
* [x] All test APIs have been removed from production Api Umbrella
Note: if there any backlog items, metadata or such for the test APIs, remove them as well.

**Comment by bajiat** [comment]
Three options to do this:
1. Wait for delete functionality to be completed and delete from UI
2. Delete from console -> manually going through 30 apis
3. Re-set the project -> requires recreating users, settings

@ccsr What is the urgency? Should we go with option 2 rather than waiting for 1? (See task #616)

**Comment by ccsr** [comment]
@bajiat I vote for option 1, but what is the time line for option 1 to be implemented.

**Comment by jykae** [comment]
Option 2 selected and done.
