### ISSUE TITLE
Sign up / sign in with Github not working in apinf.io

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#906]
It is not possible to sign up or sign in with Github in apinf.io. This seems to happen regardless of user being signed into Github or not.

**Comment by jykae** [comment]
Verified. Waiting rights from @ccsr to apinf.io server to work on this issue.

**Comment by jykae** [comment]
Got access to server, waiting @elnzv to share mup.json & settings.json for deployment. Also admin rights to apinf.io UI would help to check Settings, maybe able to fix without running new deployment.

**Comment by jykae** [comment]
Github OAuth config is fine. I found out that apinf.io deployment has env variable ROOT_URL=http://apinf.io set which should point to https. Same kind of case here, https://github.com/meteor/meteor/issues/4550

I would not need mup.json & settings.json from @elnzv to reconfig that.

**Comment by jykae** [comment]
mup logs:

stdout: 
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: redirect_uri_mismatch","time":{"$date":1457342615471},"level":"warn"}
[apinf.io] {"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: redirect_uri_mismatch","time":{"$date":1457342629822},"level":"warn"}
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: redirect_uri_mismatch","time":{"$date":1457342856733},"level":"warn"}
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: redirect_uri_mismatch","time":{"$date":1457342876613},"level":"warn"}
[apinf.io] spiderable: phantomjs failed at http://apinf.io/: { [Error: Command failed: Can't open '/dev/stdin'
] killed: false, code: 255, signal: null } 
stderr: Can't open '/dev/stdin'

**Comment by jykae** [comment]
I also updated the server software, fixed NTP clock that made deployment freeze in invoking state and removed old kernels.

Github registration and login should work now, waiting that someone from @apinf/developers verifies and closing after that.

**Comment by bajiat** [comment]
@jykae Sign in works at apinf.io (with Chrome).
