### ISSUE TITLE
API status check giving false error message

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#918]
## Behaviour
After adding API that requires authorization, API status shows: 
"API backend is down for some reason. Please contact support." 

Example: 
"Yle API uses app_id and app_key URL parameters for authentication, Apinf should be flexible for different kind of API authorizations. It's not good to show "API backend is down for some reason. Please contact support.", if we are getting 401 not authorized."

Above comment from issue: https://github.com/apinf/api-umbrella-dashboard/issues/917

## Expected
When getting 401, show info "API requires authentication" or allow 401 to be successful status.

**Comment by brylie** [comment]
@frenchbread will you take this task? It may be that we need to pass the HTTP response code to the user, and allow other status codes than 200.
