### ISSUE TITLE
Add initial setup wizard for new deployments

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#922]
When setting up a new Apinf instance, present the first administrator with a set-up wizard. This wizard should help the Admin complete any required, or optional, settings. It can optionally include a branding step.

# Suggested solution
One [suggested solution](https://forums.meteor.com/t/first-time-setup-wizard-recipe/22057/2?u=brylie) would be the following:
* [x] Create a *[server method](https://github.com/meteor/guide/blob/master/content/methods.md)* to check for required settings. 
  - E.g. `checkRequiredSettings`
* [x] Add a [global router hook](http://iron-meteor.github.io/iron-router/#hooks), via `Router.onBeforeAction()` or `Router.onRun()`, that calls the *server* method on every route
  - E.g. `Router.onBeforeAction(function () {  Meteor.call('checkRequiredSettings', ... ) });`
* [x] If the server method returns `false` the router should re-direct the user to the configuration screen
* [ ] Project starts successfully by calling only `meteor`. I.e. the `--settings` flag is no longer required.

  - Note: the configuration wizard should make sure an administrator is logged in, to prevent abuse

**Warning**: Avoid publishing the settings to the client, as not all settings should be publicly known. E.g. we have private keys stored in our settings, so the `checkRequiredSettings` function should only run on the server.

# Resources
- See the [discussion thread in Meteor forums](https://forums.meteor.com/t/first-time-startup-wizard-recipe/22057) related to this task.
- See the Meteor Guide [Methods](https://github.com/meteor/guide/blob/master/content/methods.md) article for details about Meteor Methods
- See the Iron Router Guide [Hooks](http://iron-meteor.github.io/iron-router/#hooks) article for details about router hooks

**Comment by brylie** [comment]
In order to ensure that required settings have been provided, we can add a global router rule. This rule should check for any required settings, and show the user a configuration wizard with required settings are not present.

**Comment by ashakunt** [comment]
@ccsr you were talking about this issue yesterday, right? @brylie would you need some help about this? I and @Alapan can try to propose a working solution.

**Comment by brylie** [comment]
@ashakunt thanks for your help here. We are hoping for a code contribution for this task. E.g. can you take this task?

**Comment by brylie** [comment]
@ashakunt, @Alapan, @ccsr, and @shaliko, I have updated the task description with a possible solution as well as resources related to the solution. The proposal comes from the Meteor Forums.

**Comment by ashakunt** [comment]
@brylie given my current schedule, i am not sure how much I will be able to code myself, but i can assure of help from both, me and @Alapan to get this done asap.

**Comment by ccsr** [comment]
@ashakunt please prioritize this. One customer is waiting to try this and I cannot send it without this done.

**Comment by ashakunt** [comment]
@ccsr I and @Alapan are getting this done asap.

**Comment by ashakunt** [comment]
Thanks @brylie fr the suggestion. Based on our current discussions, that is how we will proceed. In a nutshell, here is a checklist of small tasks on how this should be implemented: 

**Step 1:**
* [ ] Add a new flag in settings.json `(e.g. additionalConfigurationRequired)`
* [ ] Write a server method `(e.g. checkRequiredSettings)`
* [ ] Make a call to this server method at `Router.onBeforeAction` or anything similar.
* [ ] Based on the return value of `checkRequiredSettings`; show an alert on all the pages (routes); which says: "Hello World".

**Step 2:**
* [ ] Define the list of all mandatory settings required, e.g. `brandName`, `brandLogoURL`, `brandFacebookURL`, `mailgunSettings` to name a few.
* [ ] Extend the function `checkRequiredSettings` to check for all these setting values and return true if any one of the settings is missing from settings.json
* [ ] Update the "Hello World" implementation to show something like: "Hey there! This installation of apinf requires additional configuration failing which, some of its features might not work as expected. Please click here to configure this instance."

**Step 3:**
* [ ] Please click here to configure button or link takes user to "Login page"
* [ ] User logs in with his/her credentials
* [ ] If user is not in list of Admins, he is given a message: "You are not authorized to view this page"
* [ ] If user is an admin, then we show the wizard.

**Comment by ashakunt** [comment]
Immediate next steps (and action items): 

* [ ] @brylie, @ccsr  : please define the mandatory settings
* [ ] @brylie, @ccsr : do we get the design of wizard from somewhere?
* [ ] @Alapan : start to work on **Step 1** followed by 2 and 3.

**Comment by brylie** [comment]
Ah, please do not rely on settings.json. We are in the process of deprecating the usage of settings.json.

**Comment by brylie** [comment]
The `checkRequiredSettings` method should suffice, so long as it is run in the `Router.onBeforeAction`.

**Comment by ashakunt** [comment]
@brylie : in that case, where do you plan to define mailGunSettings, and other relevant items that would be different for different instances?

**Comment by Alapan** [comment]
Right now, I have defined a flag `additionalConfigurationRequired` in my settings file `apinf.config.json`.

**Comment by ashakunt** [comment]
@Alapan : its ok for now to get it done through apinf.config.json. If (and when) it is deprecated, the relevant update will be made.

**Comment by brylie** [comment]
Alright, but the `additionalConfigurationRequired` value in settings.json flag is not necessary for this task at all.

**Comment by ashakunt** [comment]
@brylie : Yes. It is not required and I hope, you have also checked that I have added the task in three steps, where this `additionalCon....` is replaced by actual settings and the `checkRequired..` is replaced by actual function. Also, check the previous comment, where I have asked to define the mandatory settings!!

**Comment by brylie** [comment]
Please do not yell.

**Comment by brylie** [comment]
When Meteor is running, there is a global `Meteor.settings` object. This settings object can be pre-populated from a `settings.json`. However, it can also be used here to bypass the need for a `settings.json`:

# Example
When starting, the `Meteor.settings` object looks like this:

```js
{
public: {}
}
```

We can attach arbitrary key/value pairs to Meteor.settings.

**Comment by ccsr** [comment]
@brylie @ashakunt @Alapan guys please try to have a call if possible

**Comment by brylie** [comment]
Further, when completing the initial settings wizard, we can define a key/value pair within `Meteor.settings` to the following effect:

```js
{
  public: {}
  initialSetupComplete: true
}
```

**Comment by brylie** [comment]
Then, `checkRequiredSettings` method (or equivalent), can look for the flag in `Meteor.settings`:

```js
const setupComplete = Meteor.settings.initialSetupComplete;

if (setupComplete) {
 ...
}
```

**Comment by ccsr** [comment]
@ashakunt @Alapan @brylie @shaliko we agreed yesterday that settings.json needs to go, because of issues with dockerizing. @brylie has suggested above and lets try that first and if it still can be worked at.

**Comment by brylie** [comment]
One other key aspect is to set `Meteor.initialSetupComplete = true;` when the setup wizard has finished.

**Comment by ashakunt** [comment]
@ccsr @brylie : are we going to deprecate settings.json right away? Is there a pull request where this work is in progress? If not, I would suggest to continue this work with settings.json and then, we can port this work as well. I agree with @brylie about `Meteor.initialSetu... = true`.

**Comment by ashakunt** [comment]
and @brylie : i do not think I was yelling at you!

**Comment by ashakunt** [comment]
just had a discussion with @ccsr and we can continue this work in parallel. When settings.json is deprtecated, we just have to re-write (or adapt) `checkRequirements...` to meet the new scheme. Rest all can continue. @Alapan please continue working on this.

**Comment by brylie** [comment]
Thanks @ashakunt. Please consider the `settings.json` as deprecated now.

**Comment by ccsr** [comment]
@ashakunt please no rework. Please proceed with the assumption that settings.json is not there @shaliko can you please help here?

**Comment by shaliko** [comment]
@ashakunt @ccsr In my branch I dropped code that insert settings.json to MongoDB on startup. So now user after registration fill settings on settings page instead of load it from settings.json. That simplify Docker config and decouple app startup from api-umbrella.

I dropped this code https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/startup.js#L3-L15

Code was not on review yet, so maybe will have changes.

**Comment by ashakunt** [comment]
Thanks, @shaliko we are not using settings.json for this purpose and hence, this task is now independent of your work. Further,

**Comment by ashakunt** [comment]
So, the alert should look something like the highlighted part in this image: 

![selection_259](https://cloud.githubusercontent.com/assets/5460151/14852219/b853596e-0c8d-11e6-94fe-704cf31b4807.png)

but a bit bigger and has the message like: 

**Additional configuration required!**
Hey there, this instance of __APINF__ needs additional configuration. Click here to continue. You must be an admin to do this!

**Comment by ashakunt** [comment]
@ccsr @brylie : do we now have a defined set of settings that must be checked? Also, do we get a design for this wizard? Or its ok to go ahead with what I have in my mind?

**Comment by Alapan** [comment]
I don't know how to add a value in Meteor.settings object programmatically.

**Comment by brylie** [comment]
In general, `Meteor.settings` is just an object. So, you can add a value like you would with any other object:

```js
Meteor.settings.newKey = "value";
```

We can also test for the presence or absence of a value like so:

```js
> let test = {};
undefined
> test
{}
> test.newKey
undefined
> test.newKey = "value";
'value'
> test.newKey
'value'
if (test.newKey) {console.log("New key exists"); }
New key exists
```


Now that we see how to add the value, we can look at when to add the value. In g
