### ISSUE TITLE
Design and implement tab for API Documentation viewer in API backend view

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#929]
When a user is viewing an API backend, they should be able to see the related documentation as well. The suggestion is to create a new tab for viewing the relevant Swagger file, if it has been uploaded.
If the owner has added a link to external documentation, show that as well. If there is no Swagger available, show only the link.

# User stories:
As an API consumer, I want to easily access API documentation so that I can understand what I can use the API for
As an API consumer, I want to make API calls directly from the documentation browser so that I can have interact directly with the API without the need of another UI.
As an Apinf administrator I want to warn Apinf users that API calls from documentation console are real calls.

Follow-up to issue #624

Co-pilot: @Nazarah

Definition of done
---
* [ ] Create a wireframe for Documentation viewer tab.
* [ ] Implement the tab
* [ ] Integrate the [ReDoc viewer](https://github.com/Rebilly/ReDoc) into the project
* [ ] Create publication and subscription for single API document
* [ ] Conduct a usability test for the working prototype.

**Comment by Nazarah** [comment]
The usability test would be performed on the APINF system after ReDOC viewer is incorporated.

**Comment by Nazarah** [comment]
View ReDoc for designing purpose

**Comment by bajiat** [comment]
@elnzv Would you be interested with this task?

**Comment by elnzv** [comment]
Adding wireframes

![tab-api-docs_1](https://cloud.githubusercontent.com/assets/7489044/15536553/7b407054-227a-11e6-998c-9eb1b1936bfa.png)

![tab-api-docs_2](https://cloud.githubusercontent.com/assets/7489044/15536555/7fb13380-227a-11e6-8cc2-4fef90d5467f.png)

**Comment by Nazarah** [comment]
In the edit option, would there be option for changing the URL/ uploading a new file?

**Comment by Nazarah** [comment]
Suggestion of keeping info icon to describe about the functionali
![7b407054-227a-11e6-998c-9eb1b1936bfa](https://cloud.githubusercontent.com/assets/17976243/15565665/d18bf6d6-2324-11e6-9fec-6d6a769bf501.png)

**Comment by Nazarah** [comment]
As people always looks to functionality visible to them without any click, i suggest keep the tab in front view.
You can make the entire left menu hidden with a expand collapse button indicating about additional functionalities in the left.
This gives flexibility to users.
