### ISSUE TITLE
Plan meeting for API service level quality feature(s)

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#932]
coming to the catalog sometimes feels like a'sandbox'. Come up with ideas about how users can annotate, rate, and filter out API backends.'

#Definition of done
* [x] Organize a brainstorming session.
* [ ] Store the meeting minutes and ideas.

**Comment by bajiat** [comment]
Vesa organised and facilitated the meeting. Taija will write the ideas down and incorporate them in backlog work.

**Comment by bajiat** [comment]
Document created and pull request assigned to Vesa.

**Comment by bajiat** [comment]
Document available in documentation repository (develop branch): https://github.com/apinf/docs/tree/develop/docs/ideas
