### ISSUE TITLE
Create a Node-RED demonstration of real-time data from HSL

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#933]
Based on the demonstration at API Days Suomi, set up Node-RED and demonstrate the real-time map flow for HSL data. 

As a follow up, determine how to proxy the HSL data to a second Node-RED instance, through the first Node-RED instance.

**Comment by bajiat** [comment]
@brylie Interested in this one?

**Comment by brylie** [comment]
Initial testing was a success. I was able to create a custom proxy for the HSL data, and rate limit the messages to one per second. There is a lot of room for experimentation/improvement.

**Comment by brylie** [comment]
I have improved on the above flow by adding a rate limiting module. The 'HSL real-time proxy' flow is available in the [Node-RED Flows catalog](http://flows.nodered.org/flow/5d2c9fa71b249b21d3c377087dd5b395)
