### ISSUE TITLE
Design and implement upload documentation functionality to Documentation tab

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#938]
Api owners must be able to upload a Swagger for an API backend. Alternatively, they can provide a link to external documentation.

# User stories
As an API owner, I want to upload a Swagger document into Apinf so that I can help API consumers understand API structure.
As an API owner, I want to add a link to my existing API documentation so that I can reuse the existing documentation.

# Definition of done

## Design
* [ ] Wireframe for adding/uploading Swagger documentation and providing link.
  * [ ] Revise the wireframe working with the developer.

## Collection
* [ ] Define a schema for storing the documentation. It must contain at least file id and URL fields.
* [ ] Create a publication and subscription.

## UI
* [ ] Create view for uploading the file and adding the link. 
* [ ] Create functionality to delete an uploaded file.
* [ ] Consider how to handle a pre-existing Swagger file if a new file is added.
* [ ] Remove the document upload functionality from the Edit API backend form

## Usability test
* [ ] Conduct a usability test for the working prototype.

**Comment by Nazarah** [comment]
Usability test is conducted on working prototype after the implementation is done.

**Comment by bajiat** [comment]
@brylie @illya @frenchbread Who would be interested in this task?

**Comment by bajiat** [comment]
This also needs to be done in co-operation / discussion with the other developers

**Comment by jykae** [comment]
@elnzv @brylie Did you have packages or ideas for file upload or do I conduct search for that?

**Comment by jykae** [comment]
I found this in first results: https://github.com/tomitrescak/meteor-uploads

**Comment by jykae** [comment]
I will go with that package, there are not much good alternatives for the deprecated collectionFS package. @elnzv would you be able to work as a co-pilot for wireframes on this one?

**Comment by jykae** [comment]
API documentation & API Metadata, in my opinion are a bit overlapping features, what you think should we integrate these, Swagger file has metadata descriptions for API. Or documentation would be extension for our metadata collection?

**Comment by jykae** [comment]
I am getting this error https://github.com/tomitrescak/meteor-uploads/issues/224 and trying to figure out, what is the proper solution, would be good to have Meteor 1.3 update done pretty soon for Apinf.

**Comment by jykae** [comment]
No official recommendations at the moment, but sounds like this package would be good to go for 1.3 https://forums.meteor.com/t/meteor-guide-for-upload-store-files-in-meteor-1-3/21836

**Comment by jykae** [comment]
Mandatory versions: https://github.com/blueimp/jQuery-File-Upload#mandatory-requirements, currently we have too old jquery version, https://github.com/apinf/api-umbrella-dashboard/blob/develop/.meteor/versions#L106

**Comment by jykae** [comment]
File upload jquery seemed to require Meteor 1.3 update to get rid of the jquery-upload package error on startup.

**Comment by jykae** [comment]
Another option mentioned here https://forums.meteor.com/t/deprecating-collectionfs/16921 would be https://github.com/vsivsi/meteor-file-collection
Depends would we like to use MongoDB GridFS or simpler on disk file upload that meteor-uploads provides.

**Comment by Nazarah** [comment]
Info Icon message: "You can update the documentation by uploading the latest Swagger file or providing an URL for the document. Currently only Swagger format is supported for upload."
