### ISSUE TITLE
Resolve Elastic-REST error after Meteor 1.3 upgrade

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#949]
> TypeError: Object [object Object] has no method 'npmRequire'
>    at new ElasticRest (packages/frenchbread_elastic-rest/server/elastic-rest.js

OK, our NPM dependency handling has changed, so we probably need to use the ES2015 import syntax in that file.

Suggestion: while solving this, add the package under Apinf organization.

Co-pilot: @brylie

**Comment by bajiat** [comment]
@frenchbread Interested?

**Comment by frenchbread** [comment]
I'll look into that

**Comment by brylie** [comment]
@frenchbread we are deprecating the elastic-rest package, and moving the code into our core.

**Comment by brylie** [comment]
What are your thoughts on this approach? We have a working solution as of yesterday.

**Comment by frenchbread** [comment]
@brylie Yep. I've been trying to set up elastic-rest package the whole day now and it turns out that we do not actually need it. `elasticsearch` - original npm package has a good API in verison 12. I've also written a test app for it and will try to implement it on a dashboard.

**Comment by brylie** [comment]
@jykae resolved this task with a commit to the Meteor 1.3 upgrade branch.

**Comment by frenchbread** [comment]
Same as #927. Closing this issue..
