### ISSUE TITLE
Determine how boilerplate dashboard menus work

### ISSUE THREAD

**Issue by JuusoV** [apinf/api-umbrella-dashboard#95]
Determine how the admin dashboard menus work. Where are they created? How can we extend them? Can we override them easily? What other functionality do they have?

### Definition of done
* [x] Show an example configuration of changed top and side menu layout
* [ ] Make sure boilerplate project contains documentation about menu customization

**Comment by JuusoV** [comment]
Posted [issue] (https://github.com/yogiben/meteor-admin/issues/201)

**Comment by JuusoV** [comment]
Reduced time estimate from 13 to 8 hours.
Waiting reply to the issue.

**Comment by brylie** [comment]
We can use the [addSidebarItem](https://github.com/yogiben/meteor-admin#add-sidebar-item-with-single-link) method to add sidebar menu links.

**Comment by brylie** [comment]
@JuusoV when will you be able to demonstrate an example of a sidebar with added link? Try using the `addSidebarItem` function mentioned in the previos comment.
