### ISSUE TITLE
Hierarchy and prioritization for project planning

### ISSUE THREAD

**Issue by philippeluickx** [apinf/api-umbrella-dashboard#962]
In order to communicate better about the roadmap, it would be a good idea to go from high-level epic to user stories to tasks.

Prioritization would happen on epics and user stories. Development on task level.

We will investigate a few alternatives and define a way of working.

**Comment by philippeluickx** [comment]
Current implementation: Github and waffle.io

Challenge is that all issues from Github are treated all the same. This results in +200 tickets that can not be managed.

**Comment by philippeluickx** [comment]
Not all user stories are captured in documentation.

Should all user stories be in the docs, even if no decision is made to implement them?

**Comment by philippeluickx** [comment]
Idea:
Define user stories into the docs repository and create Github issues linked to the docs.

**Comment by philippeluickx** [comment]
Idea:
Impact mapping - @brylie could you add some more info on this?

**Comment by philippeluickx** [comment]
Idea:
Open discussion on Discourse for user stories

**Comment by philippeluickx** [comment]
Idea:
Use other tools as https://taiga.io/ or https://www.zenhub.io/

**Comment by elnzv** [comment]
We were thinking about moving to Zenhub or at least talking.
I tried it myself and I like it. It integrates with Github website so I have one place to control it all.
So if we were voting, I would vote for Zenhub.

**Comment by philippeluickx** [comment]
I have the impression that a combination of zenhub and Github docs for user stories would work as well. They both serve different purposes.

**Comment by frenchbread** [comment]
+1 for Zenhub. Tried it myself, worked pretty good. Seems like Zenhub uses different labeling approach compare to waffle.io, that's why it's not possible to use them both at the same time.

**Comment by brylie** [comment]
Cool. I was thinking about several parts of this picture, and suggest we consider the following incremental improvements to our existing process/tooling:

# Use Kanban only to vizualize work-in-progress
We have tried managing our backlog, e.g. prioritizing issues, from waffle.io. Kanban is not suited for this sort of task. 

Lets use Kanban for what it is good at: **visualize work in progress*

## Use github milestones to track 'epics'
We are currently using Milestones to track sprints. This may not be necessary any longer, and the milestone might serve a different purpose. Milestones allow us to group tasks together in a way that transcends our sprint cycle.

Epics, according to Atlassian are:

> Epics are feature-level work that encompasses many user stories... Epics are almost always delivered over a set of sprints.

The Github milestone is designed to track work towards a set goal, which may take place over a timespan greater than two weeks. They also have a simple progress indicator, and can be used to filter/ issues.

# Keep linking user-stories to issues via labels
We are currently linking user stories to issues via labels. Lets continue this process, and just shorten the labels.

We can continue developing our user stories document in a structured format, which has proven successful for prioritization.

# Explore visual techniques for stakeholder communication
One of our high level goals is to communicate with stakeholders, such as @ccsr, where we are in the development process. Previously, we have used diagrams to communicate development status and roadmap. Some examples include:

- 'epic floorplan' - a box diagram showing all project components that can help clarify team progress and plans. We used this in Dipor.
- mind map overview - we can use a visual tree structure to communicate our user story and epic (a.k.a. feature) priorities, as well as showing links between the two. A mind map can be provided as an image with accompanying source file

# Manage the backlog with tags and bulk actions
We can add just a couple of labels to our project that would help us plan/prioritize better. The tags, for instance, could be:

- high priority
- urgent

This would allow us to filter issues by epic/feature and priority status. We can use the filtered tags to make a selection and apply a bulk action, such as moving 10 issues into our planning column simultaneously.

# Process review meetings (a.k.a. sprint retrospectives)
We used to hold process review meetings, that were used to explore how to improve our working process. Around 6 months ago, we stopped holding the process. Part of the controversy surrounding this discussion may stem from the lack of process review. In other words, we have not been reflecting on and improving our working process. Lets try to hold a team process review at least once a month.

# Summary
While discussing improving our process, it is important to look at what we have already done well and see if incremental changes can serve our higher goals.

**Comment by philippeluickx** [comment]
@brylie Thanks for the write-up!
