### ISSUE TITLE
Study what monitoring service to be used

### ISSUE THREAD

**Issue by ccsr** [apinf/api-umbrella-dashboard#966]
Evaluate monitoring module to monitor APInf service. Which means monitoring servers status part of APInf service. We used Zabbix in past but any suggestion would be welcome. We would like to use this monitoring service for monitoring individual APIs in future. This monitoring service should be able to send alarms if opted for.

# User stories
> As an Apinf administrator I want to be notified if any of the Apinf platform services are down

@ccsr shall be deploying a VM for this purpose and give details to @shaliko.

# Definition of done
- [x] Research potential monitoring services
- [x] Determine primary use cases and goals of monitoring
- [x] Prioritize features based on the use cases and goals
- [x] Document the findings of the evaluation: e.g. comparison of monitoring module features. Make sure that the comparison is objective and equal weight is given to proposed options
- [x] Store the document in the Apinf docs repository.

**Comment by shaliko** [comment]
https://github.com/apinf/docs/pull/7

**Comment by shaliko** [comment]
![metric_tools_-_google_sheets](https://cloud.githubusercontent.com/assets/36139/15724473/da39e132-284f-11e6-8038-7afd792e70dc.jpg)

**Comment by bajiat** [comment]
@shaliko Please add additional details for the following:
- Setup complexity: more explicit details about the setup, how to do the setup
- Resource: what does "not requires much resources" and "resource hungry" mean in practise, where do these conclusions stem from
- What is the criteria for considering RDBMS negative compared to own database?
- Communication protocol: can you give a reference or details?
- Why is Prometheus UI green, but Zabbix neutral? What is the difference?
- Other pros: what is the difference between "modular and composable" versus "have plugins"?
- Provide links to query language documentation or further details
- Plugins for metrics: can you either provide a link for Zabbix as well or explain what "A lot of monitoring scripts" means

**Comment by bajiat** [comment]
See also the user story in #1022 

> As an API consumer I want to see the API "uptime" in the catalog so that I can discard "unreliable" APIs without going into details view.

**Comment by shaliko** [comment]
@bajiat Updated, but because we decide use Prometheus for internal monitoring, looks like we no need store that research in Apinf docs repository ?

**Comment by bajiat** [comment]
@shaliko But doesn't it still monitor Apinf services / modules (like Umbrella)?

**Comment by philippeluickx** [comment]
I have the feeling we have made a decision to go with Prometheus, right? If so, let's close this ticket, feel happy about it and move on!

**Comment by brylie** [comment]
Based on discussion with @shaliko, Prometheus seems like a good candidate for monitoring our internal services. I.e. those managed by our staff.

> As an Apinf administrator I want to be notified if any of the Apinf platform services are down

It is not as clear whether Prometheus could be used as a general purpose monitoring solution for the Apinf platform, e.g. monitoring third-party servers where we do not have administrative privileges.

> As an API owner I want to be notified if my API is down so that I can take corrective action

> As an Apinf user I want to see the percentage of failures/uptime (timeout, bad gateway, internal server error) for a given API so that I can determine the reliability of a given API backend

**Comment by brylie** [comment]
As pointed out by @shaliko, we agreed to split this task into two components:

- Prometheus for internal service monitoring (assigned to @shaliko)
- Determine how to provide API health-check monitoring from Apinf code (under consideration)

**Comment by brylie** [comment]
I just double-checked, and issue #956 describes the remaining questions very well.
