### ISSUE TITLE
Documentation viewer 1.0

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#979]
This is an EPIC for issues related to Documentation viewer: uploading files, validating files, viewing documentation and making calls from documentation viewer

**Comment by philippeluickx** [comment]
All tickets for this epic are Done, can we close this one too?

**Comment by bajiat** [comment]
One thing is missing in my opinion: we have a validation method for Swagger file validation, but it is not used at the moment. The validation needs to be moved from backend to client side. This needs one more ticket.

**Comment by bajiat** [comment]
Actually, I'm taking my comment back. File validation can be an enhancement since Swagger UI is capable of handling Swagger validation. It would be better for the user to know it already when uploading the file, but we can include that task in Documentation viewer 2.0. Closing the EPIC.
