### ISSUE TITLE
Create smart container for catalog views

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#989]
# User story
As an Apinf user I want to sort the view of catalog based on popularity ( = bookmarking), recency, alphabetical order so that it is easier to find interesting APIs.

# Definition of done
## Sorting
* [ ] User can sort the catalog based on popularity: how many users have bookmarked the API
* [ ] User can sort the catalog based on recency: most recently created API backend first or last
* [ ] User can sort the catalog based on alphabetical order: API name, backend host
* [ ] Optionally, user can also sort by highest/lowest average rating

## Filtering
* [ ] User can filter by owner (user name of the user who has added the API)
* [ ] User can filter by category

## UI component 
* [ ] bar for managing filtering, sorting and view toggling exists
* [ ] when the view is toggled, view mode (card or table) is switched
  
## Data subscription
* [ ] Prepopulate / manage the data for the different views (card and table) 
  * [ ] entire catalog
  * [ ] sorted catalog
  * [ ] filtered catalog
  * [ ] Optionally, filtered and sorted catalog

## Pagination
* [ ] Data is either paginated or has infinite scroll or shows everything

**Comment by Nazarah** [comment]
I will work on the wireframes.

**Comment by bajiat** [comment]
Reliability needs to move to another issue since we don't have API monitoring analytics yet. So it will be completed later.

**Comment by Nazarah** [comment]
Currently considering Most Recent, Most Popular, Most Consumed and Highest Uptime.

**Comment by philippeluickx** [comment]
I would simplify and only keep Most Popular. Most Consumed is very similar and provides the same information more or less.

Also, what use case is there behind "Most Recent". An API that has not changed in 2 years time might be still very much up-to-date. Just someone has done a good design and you try to keep developers happy by not changing too much. So what is the value of most-recent?

**Comment by brylie** [comment]
@bajiat we should include a definition of done in this task.
