### ISSUE TITLE
Create RAML and/or Swagger file describing Admin API

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#99]
Create an [Admin API](http://apiumbrella.io/docs/admin-api/) description file in either Swagger or RAML format. [Restlet Studio](https://studio.restlet.com/) can be used to visually design this file.

Definition of done
---
* [ ] Demonstrate comprehension of existing Admin API structure
* [ ] Create Swagger or RAML file describing all Admin API endpoints, methods, parameters, etc

**Comment by brylie** [comment]
There is a [related issue](https://github.com/NREL/api-umbrella/issues/129) on the API Umbrella issue queue.

**Comment by ccsr** [comment]
@brylie I am bit confused with this. Why are we spending time on creating Swagger or RAML for Admin API? I understood that we need to have mechanism to create Swagger and or RAML for the APIs which are hosted on APInf. May be I dont understand the whole context here. Please help me understand.

**Comment by brylie** [comment]
The API Umbrella Admin API lacks documentation. When this task was created, we were trying to figure out how to understand all available Admin API methods. Nick has responded to the previously mentioned issue regarding API Umbrella Admin API documentation in a [related issue](https://github.com/NREL/api-umbrella/issues/129), and seems willing to document the endpoints himself.
