### ISSUE TITLE
Create functionality for uploading an API logo

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#996]
# User story
As an API owner I want to be able to add a logo for my API so that it is easy to visually distinguish it from others in the catalog

(To be shown in card view only?)

**Comment by Nazarah** [comment]
Can be shown in tabular view as well to give user familiarity.
But not needed as essential.

**Comment by Nazarah** [comment]
I will work on the wireframes.

**Comment by Nazarah** [comment]
Logo uploader at API Main page (Logo place holder and button)

![apilogoupload1](https://cloud.githubusercontent.com/assets/17976243/15960904/b5993a5a-2f0a-11e6-9bd8-9cfa98d585a8.png)

Clicking button activates the logo uploader. File can be selected by browsing or drag-n-drop. File size and format restriction is given at the bottom. Help text explains the upload process

![apilogouploader](https://cloud.githubusercontent.com/assets/17976243/15960937/dad378a8-2f0a-11e6-89ef-f618c59c9d36.png)

Drag and Drop: Upload button is active when file is succesfully selected.
It is inactive when upload is in process or error occurs.
Upload completion status can be seen.

![apilogouploaderdragdrop](https://cloud.githubusercontent.com/assets/17976243/15961117/babefb40-2f0b-11e6-970b-8d116c240745.png)

![apilogouploaderdragdropuploadcomplete](https://cloud.githubusercontent.com/assets/17976243/15961124/c11f7ab4-2f0b-11e6-9337-855fdba8ca36.png)

![apilogouploaderdragdropuploadunsuccessful](https://cloud.githubusercontent.com/assets/17976243/15961130/c86c2f74-2f0b-11e6-9fcb-2ba016588fd7.png)
