### ISSUE TITLE
Allow owner to select the API they are viewing the analytics for

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#999]
The main user of the dashboard is an API owner who checks the dashboard for performance and to get insight into API usage.  When API owner is viewing the dashboard, they should also be able to define or select an API they see analytics for (from their APIs)

# User story
> As an API owner
I want to determine which API I want to see the analytics for 
so that I can gain insight on single API usage

# Design

* Selected API
![apinfanalyticsselectedapi](https://cloud.githubusercontent.com/assets/17976243/16450563/5f509d40-3e06-11e6-9365-caa6edcf3c66.png)

* API selection
![apinfanalyticsapiselection](https://cloud.githubusercontent.com/assets/17976243/16450599/8cedcf8e-3e06-11e6-9dd2-0278db4e867f.png)

# Definition of done
* [x] User has a method for selecting a single API on dashboard page
* [x] Based on the user selection, dashboard charts (and table) get updated
* [x] User can easily select another API for viewing the analytics
* [x] User interface clearly indicates what API you are looking at (vs. looking at all APIs)
* [x] Optionally, user can switch back to all APIs owned by this particular owner

# Resources
- Upstream support request: https://github.com/NREL/api-umbrella/issues/252

**Comment by Nazarah** [comment]
Is there any case that user wants to see multiple APIs? for comparison purpose?

**Comment by bajiat** [comment]
See Brylie's support request and Nick's answer to it: https://github.com/NREL/api-umbrella/issues/252

**Comment by brylie** [comment]
@frenchbread will you be taking this task forward?

**Comment by frenchbread** [comment]
Yes, self-assigned.

**Comment by brylie** [comment]
This is number one priority. High priority and urgent. It blocks several other tasks.

**Comment by frenchbread** [comment]
Got it.

**Comment by brylie** [comment]
Generally, an API owner will need to see the API Name. However you link the API Name to the filter is up to you. E.g. if API ID is easiest, go with it, but make sure the end-user has an intuitive way to filter the dashboard.

**Comment by frenchbread** [comment]
Actually now, when sending custom requests (with api backend id in the URL) there are only 404 responses. I'm not sure how did we manage to add API Id to the request URL but it won't work that way I thing because now API Id is represented as a separate page - not as a parameter.

**Comment by frenchbread** [comment]
One more question: If there is no API selected, should we show anything?
Possible scenarios:
- Showing "Select API to view analytics for" message with no data
- Showing analyrics data for all APIs managed by current user
- Something else (like the entire analytics in ES) - maybe for admin view

**Comment by brylie** [comment]
I like the second option. We can also consider having a multi-select box, so that an administrator or API Owner can select multiple API Backends. I have added [Bootstrap Select](https://silviomoreto.github.io/bootstrap-select/examples/) to a project recently, and it is easy to use.

**Comment by brylie** [comment]
One goal here is to try and share most of the Dashboard code/functionality between Administrators and API Owners.

**Comment by frenchbread** [comment]
Cool. Yea, that is possible. What about using API Id in the URL then?
> Actually now, when sending custom requests (with api backend id in the URL) there are only 404 responses. I'm not sure how did we manage to add API Id to the request URL but it won't work that way I thing because now API Id is represented in URL as a separate page - not as a parameter

**Comment by brylie** [comment]
If API ID works, go for it. We just need to show the end-user the API Name, so they understand what they are seeing.

**Comment by frenchbread** [comment]
It works but response is 404, because API ID is provided not as a parameter

**Comment by frenchbread** [comment]
That's what I mean.

#### No API selected:
<img width="612" alt="screen shot 2016-07-04 at 16 38 40" src="https://cloud.githubusercontent.com/assets/2122679/16562476/e670efac-4205-11e6-9754-caa3bd281f68.png">

#### API selected:
<img width="593" alt="screen shot 2016-07-04 at 16 38 55" src="https://cloud.githubusercontent.com/assets/2122679/16562475/e66dfefa-4205-11e6-9338-0271913da0d3.png">

In scope of this issue it works though.

**Comment by brylie** [comment]
As per the [discussion with Nick (@GUI)](https://github.com/NREL/api-umbrella/issues/252), and your observations, using the the API ID won't work for analytics queries. It was suggested that we filter by the 'path' or 'frontend_prefix'.

How are you filtering the API?

**Comment by brylie** [comment]
The UI looks good by the way.

**Comment by Nazarah** [comment]
I have a suggestion. Can we only show the 3XX, 4XX and 5XX requests in the  HTTP status code chart with bigger bars. Currently they look small. Also I was thinking that is it necessary to keep the 2XX status bar there? because we are already will be showing success rate if API calls in overview information. SO the HTTP Status code chart should focus on issues other than 2XX.
If you wish to keep interactiveness of all the chart with each other, I'd suggest to increase the unit size for measuring 3XX, 4XX and 4XX so their corresponding bars appear bigger.

**Comment by brylie** [comment]
One challenge about making the 3, 4, and 5xx bars larger with respect to the 2xx bars, is that there are sometimes an 'order of magnitude' fewer requests with 3xx, 4xx, or 5xx codes. E.g. there may be:


- 1,000 requests with 2xx status code 
- 100 requests with 4xx status codes
- 10 requests with 5xx status code
- 1 request with 3xx status code

This type of situation is where a logarithmic scale becomes useful.

![Picture of a logarithmic scale](https://commons.wikimedia.org/wiki/Category:Logarithmic_scale#/media/File:Graphic--y-x-to-4--log_log.png)

 @frenchbread can we configure the HTTP Status Codes chart to use a logarithmic axis for the *request counts*?

**Comment by frenchbread** [comment]
I'm filtering charts by API Id now. It works, but I can switch to `frontend_prefix` if needed.

**Comment by frenchbread** [comment]
I think we can configure the HTTP Status Codes chart to use a logarithmic scale but is separate issue.

**Comment by brylie** [comment]
@Nazarah would you please open an enhancement for the HTTP Status Codes chart? I can add details about the logarithmic axis, if you will add your initial reasoning.

**Comment by brylie** [comment]
@frenchbread how difficult would it be to use frontend_prefix?

**Comment by frenchbread** [comment]
@brylie It you look at the screenshots above, in the table there is a row with `request_path` value. It won't be more difficult to use `frontend_prefix` for filtering.

**Comment by brylie** [comment]
OK, so does the API ID in the screenshot (`/soundcloud/{{ API ID ]]/` ) come from the Apinf database or API Umbrella?

**Comment by frenchbread** [comment]
Yes, and that's why when I send sample requests they return 404.

**Comment by brylie** [comment]
What is the source of the API ID?

**Comment by brylie** [comment]
OK, just use the `frontend_prefix`. Lets forget about the API ID for now.

**Comment by frenchbread** [comment]
Updated filtering to use front-end prefix instead of API id.

**Comment by brylie** [comment]
Cool beans. Let me know when this is ready for review.

**Comment by frenchbread** [comment]
OK, I'm now going to add filtering for "default selection" - combined analytics for all APIs owned by a user.

**Comment by brylie** [comment]
@frenchbread good idea :smile:
